### ISSUE TITLE
MacVim sometimes crashing under Yosemite

### ISSUE THREAD

**Issue by douglasdrumond** [macvim-dev/macvim#10]
_From @GoogleCodeExporter on March 16, 2015 9:25_

```
I apologize for the sparseness of this report, but I hope you'll find it useful 
nonetheless. I'm running a pre-release of Yosemite, so I don't know if this is 
an issue with the OS or MacVim, but it's happened a few times now, so I thought 
you might be interested in the stack trace that is provided. This is what the 
latest crash resulted in. If this isn't useful, just let me know. If you have 
questions that I can answer to assist you, email me at chivalry@mac.com.

Thanks,
Chuck
```

Original issue reported on code.google.com by `chivalry...@gmail.com` on 27 Jul 2014 at 9:53

Attachments:
* [crash_log.txt](https://storage.googleapis.com/google-code-attachments/macvim/issue-509/comment-0/crash_log.txt)

_Copied from original issue: douglasdrumond/macvim#509_

**Comment by douglasdrumond** [comment]
_From @GoogleCodeExporter on March 16, 2015 9:25_

```
I'm having similar issues.
```

Original comment by `sea...@gmail.com` on 20 Sep 2014 at 4:51

**Comment by douglasdrumond** [comment]
_From @GoogleCodeExporter on March 16, 2015 9:25_

```
I think it was related to a gvim update that for some reason needed to be 
performed on the command line. Each time this issue has arisen (which has been 
at least twice), when I launched Terminal I got an alert that gvim needed to be 
updated. I performed the update and this appeared to fix whatever was going on 
with MacVim.
```

Original comment by `chivalry...@gmail.com` on 20 Sep 2014 at 8:08

**Comment by douglasdrumond** [comment]
_From @GoogleCodeExporter on March 16, 2015 9:25_

```
I continue to have these isuses
```

Original comment by `phi...@staffjoy.com` on 26 Dec 2014 at 11:11

**Comment by jpetrie** [comment]
Has anybody seen this recently? The original crash report suggests something wrong with the window's document icon cell (which appears next to the window title). There's not a lot to go on there as the stack is mostly Cocoa infrastructure. Further crash reports or reproduction scenarios would be helpful.

**Comment by splhack** [comment]
please feel free to create a new issue if we still have the issue with Snapshot 81.
