### ISSUE TITLE
Question: custom icons

### ISSUE THREAD

**Issue by chdiza** [macvim-dev/macvim#100]
@douglasdrumond @splhack @jpetrie It seems to me that we no longer generate those custom icons, at least not unless the user takes a special step.  And when I do manually take that special step, nothing happens except `make: `MacVim-generic.icns' is up to date.`.  The many `icns` files are already built and there.

I want to simplify the Macvim Homebrew formula to remove its custom-icon code, so I'm just checking here that we in fact don't build custom icons anymore.

I think it's good that the icons are prebuilt, and we should think about removing the icon-generation stuff from our main repo.  We have a github org now, so we can make a separate, icon-related repo under our umbrella to preserve the icon-generating scripts for posterity.

**Comment by jpetrie** [comment]
Is this related to #99? I don't think I even realized there was icon generation going on, I thought we always had all of them pre-generated and checked in.

If the scripts in question are just for taking a big source icon and generating all the smaller permutations, and there's no existing common tool for doing so or something built-in to the Xcode tools suite, then moving it to it's own repository under macvim-dev so we can use it the next time the OS X icon style changes seems reasonable to me.

I guess this means MacVim will always have the new-style icon even on old OS X versions for which the style doesn't match? I don't know how much that matters; I certainly don't care as I don't use anything but the most-current OS X version. Do others?

That's my take on it.

**Comment by chdiza** [comment]
No, it's not related to #99.  That is, nothing regarding our generation scripts is responsible for the problem in #99.  The problem there is about the app icon, not the document icons.  It's only the latter that used to be script-generated on every build.  If we can "fix" the app icon, #99 is done.

**Comment by chdiza** [comment]
The icon-generating scripts are mainly for putting filetype-extension text on the document icons.  There is no reason to do this on every build, which is why I'm glad it hasn't been happening on every build.  I can't remember when it stopped, because I always just immediately overwrite our icons with my own custom ones.

**Comment by splhack** [comment]
@chdiza you want to remove src/MacVim/icons/Makefile and icon generating code from this repository, because you just want to simplify the Macvim Homebrew formula to remove its custom-icon code? that's all?

**Comment by splhack** [comment]
move to #176
