### ISSUE TITLE
How to keep window size fixed when zooming font?

### ISSUE THREAD

**Issue by johnnyutahh** [macvim-dev/macvim#1006]
How can one keep the window size fixed when zooming font?

This is growing to be a critical feature for me. Managing a multiple-display-monitor without this becomes quite tedious. [VimR](http://vimr.org) and [iTerm2](https://apple.stackexchange.com/questions/92173/how-to-prevent-terminal-from-resizing-when-font-size-is-changed/222329#222329) can do this.

From 2014, 2015:
https://superuser.com/questions/797827/keep-window-size-when-resizing-font-in-macvim

**Comment by ychin** [comment]
Use `set guioptions+=k`. I have contemplated making this the default, but generally followed the conservative "don't change defaults" Vim mentality though I'm still back-and-forth on this.

**Comment by rwmitchell** [comment]
Just found this and am loving 'k' option!    almost.

I'm using a function to cycle thru a font list.  After changing fonts, it displays the font name as a mode msg.
With 'k', the window gets cleared after a brief flash of the font name.

Here's the function:
```function! FontCycle(dir)
    " Increment circular list.  See :help expr-%
    let g:fc_current = (g:fc_current + a:dir) % len(g:fc_list)
    if g:fc_current < 0
      let g:fc_current = len(g:fc_list) - 1
    endif
    let &guifont = g:fc_list[g:fc_current]
    redraw
    echohl ModeMsg
    echo g:fc_current ": " &gfn
    echohl NONE
  endfunction```

Is there a way to have 'k' set and keep the message from clearing?

**Comment by ychin** [comment]
I missed this comment @rwmitchell but in case you still have this issue today, the reason why it flashes is that the different fonts have different font sizes and it causes Vim to resize. Any time Vim is resized, it clears the message (I don't think there's an option to configure this but I could be wrong).

To solve this, you could either turn off the option by doing `set guioptions-=k` when using your font toggling function. Alternatively, you can use a timer to print the text just a split second later, and this would allow it to be printed right after the resize:

```vim
function! DisplayFont(timer)
    echohl ModeMsg
    echo g:fc_current ": " &gfn
    echohl NONE
endfunc

function! FontCycle(dir)
    " Increment circular list.  See :help expr-%
    let g:fc_current = (g:fc_current + a:dir) % len(g:fc_list)
    if g:fc_current < 0
      let g:fc_current = len(g:fc_list) - 1
    endif
    let &guifont = g:fc_list[g:fc_current]
    redraw
    let g:fc_timer = timer_start(10, 'DisplayFont')
endfunction
```

**Comment by rwmitchell** [comment]
Thanks!

I had ultimately solved it by adding a function to call ShowFont(), written exatctly as yours, but without the timer arg.  I then used a hotkey to call it.

I added your timer line, but 10 didn't work - changed to 50 and it worked perfectly!

Thanks again!!
