### ISSUE TITLE
Release a new snapshot for Vim 8.2

### ISSUE THREAD

**Issue by numbcoder** [macvim-dev/macvim#1007]
The latest snapshot is outdated，could you make a new release?

Thanks for your work. It would be better to make a new release with new Vim features automatic by the CI once a month.

**Comment by pechorin** [comment]
Yeah, waiting for macvim 8.2 with popup windows support.

**Comment by treaves** [comment]
> The latest snapshot is outdated，could you make a new release?
> 
> Thanks for your work. It would be better to make a new release with new Vim features automatic by the CI once a month.

A lot of OSS have a 'nightly' feed that is the last successful build of the day.  In the 'Check for Updates' feature, 'Nightly' can be enabled to pull this.  Otherwise it's the semvar releases.  This would be good to implement.

**Comment by numbcoder** [comment]
@treaves Yes，add a 'Nightly' build would be more suitable.

**Comment by ychin** [comment]
A release will be made today or tomorrow.

I do want to apologize for the long period of inactivity in this repo / releases. It's been difficult to juggle professional responsibilities and dedicating time to MacVim development.

As for the suggestion to add Nightly build, a complication is the issue with code signing and notarization and I haven't been able to find an easy way to deploy this in a way that I trust. Apple has made running unsigned downloaded apps pretty painful for a regular user so if you jump through the hoops to enable that, may as well just build the code yourself. I do think I could potentially add an additional channel for less tested changes that I release frequently. This would only be necessary if there is a potential for bugs that I don't feel comfortable with releasing to the general userbase while cutting edge users may not mind.

**Comment by pechorin** [comment]
Thanks for this project and response, hope one day this automation problems will be possible to solve.

**Comment by numbcoder** [comment]
@ychin You needn't to apologize to anyone. 
As we all know, maintain a large open source project is extremely complicated and difficult. I'm sorry for my unreasonable request.

Thanks for your great work!

**Comment by treaves** [comment]
> As for the suggestion to add Nightly build, a complication is the issue with code signing and notarization and I haven't been able to find an easy way to deploy this in a way that I trust. Apple has made running unsigned downloaded apps pretty painful for a regular user so if you jump through the hoops to enable that, may as well just build the code yourself. I do think I could potentially add an additional channel for less tested changes that I release frequently. This would only be necessary if there is a potential for bugs that I don't feel comfortable with releasing to the general userbase while cutting edge users may not mind.

Have a look at how VimR does nightly releases perhaps. 

https://github.com/qvacua/vimr
