### ISSUE TITLE
Cannot import python 3 (python 3 -) for Python 3.7.3

### ISSUE THREAD

**Issue by BaksiLi** [macvim-dev/macvim#1009]
**Describe the bug**
After I updated system python to 3.7.3 stable from 3.7.1, macvim failed to import python 3.

So I typed `brew reinstall macvim` to recompile vim so that the new library could be loaded correctly. But it didn't work since macvim has not supported 3.7.3.

Please update this.

**Expected behavior**

```
E319: Sorry, the command is not available in this version: py3 import vim
```

**Environment (please complete the following information):**
 - Vim: latest macvim
 - OS: macOS 
 - Terminal: Both iTerm 2 and GUI.

**Comment by BaksiLi** [comment]
I solved this problem temporarily by modifying `~/Library/Caches/Homebrew/macvim--git/src/if_python3.c` as shown in [MacVIM - Python 3 Error](https://stackoverflow.com/a/48043037/8780437).

Also, I believe if you install an older version of python 3, say [python 3.7.3](https://www.python.org/downloads/release/python-373/), the problem can also be solved.

**Comment by eirnym** [comment]
**My environment:** I have MacVim from Github (official build) and Python3.7.6 from MacPorts (from `Homebrew` and `python.org` will work as well). 
(in a little while will be with the latest git version - b93473f2e)

I have `:py3 1+2` at the beginning of my `.vimrc`, so I disable `py` command entirely. 
I've tried `:py3 import sys; print(sys.version)` and it shows `3.7.6 …` as it should be
I've tried `:py3 import vim; print(dir(vim))` and it shows all names defined in this module with no problems.

So I guess it's a problem in formula and you should drop an issue to maintainers, and they're different from authors and maintainers of this repository. But it helps to compare with other versions

**Comment by eirnym** [comment]
And if it's really a problem in `if_python`, they you need to address it to the [upstream](https://github.com/vim/vim)

**Comment by eirnym** [comment]
I've tested with the latest commit I've mentioned, with MacVim and tests were the same as above. Everything worked as usual, nothing was broken. 
Commands I use to build locally were these:

```zsh
$ git clean -fdx
$ make clean
$./configure --enable-python3interp=dynamic
$ make
$ cd src/MacVim/build/Release/MacVim.app
$ open .
```

**Comment by eirnym** [comment]
@BaksiLi My opinion is maintainers of `Homebrew`'s formula have changed something or added some restrictions and so you can't use normally `py3` command. Please, contact them and ask to fix the issue. As it was mentioned before in this repo, they fix it in a short period of time.
