### ISSUE TITLE
version numbers is snapshot 162 broken

### ISSUE THREAD

**Issue by core-code** [macvim-dev/macvim#1011]
the version number in snapshot 162 is broken. this is a regression from snapshot 161

<img width="236" alt="Screenshot 2020-03-03 at 17 05 25" src="https://user-images.githubusercontent.com/1261954/75794694-72630100-5d71-11ea-826a-bb07d020e56d.png">
<img width="258" alt="Screenshot 2020-03-03 at 17 05 21" src="https://user-images.githubusercontent.com/1261954/75794701-74c55b00-5d71-11ea-99d1-d3fd6f723bff.png">

specifically the CFBundleShortVersionString in your Info.plist file is set to '.'

it should probably be set to '162' or '8.2.319' instead. in the previous release is was set to '8.1.2234

**Comment by ychin** [comment]
Yes this is a mistake in the parsing code. Will be fixed in next version.

**Comment by core-code** [comment]
awesome, thanks!

**Comment by eirnym** [comment]
as well it was said in Sparkle, that it was a 8.**3**.319 instead of 8.2.319
