### ISSUE TITLE
umask (forwarded from vim)

### ISSUE THREAD

**Issue by hdatma** [macvim-dev/macvim#1013]
## umask test from the command line:

    umask 0022
    /Applications/MacVim.app/Contents/MacOS/Vim --clean testfile_umask -c ':wq'
    ls -l testfile_umask
    -rw-r--r-- 1 me staff 0 Mar 3 20:34 testfile_umask

## same test from the GUI:

    new tab
    i
    sample text
    esc
    File > Save As > Desktop > Untitled.txt

    ls -l ~/Desktop/Untitled.txt
    -r--r--rw- 1 me staff 5 Mar 3 20:37 /Users/me/Desktop/Untitled.txt

## Reference

https://github.com/vim/vim/issues/5725

**Comment by eirnym** [comment]
@hdatma I appreciate that you've forwarded an issue here. Could you add a description to make it easier to discuss the issue?

**Comment by eirnym** [comment]
`umask` is a shell command to a system call which sets `umask` to a process tree, no environment variables and settings involved. If you create a process from another one which is not in this tree, it won't inherit a umask.

It's an intended behaviour between `umask`. If you need very special `umask` controlled by your `vim` session, please ask them to expose `umask`.

**Long story short** 
If you open MacVim from a terminal after setting `umask` in this terminal, GUI will inherit `umask` and subsequent `Vim` sessions run from it will inherit it as well. However, if you open MacVim first and then open `Vim` from a terminal where you set an `umask`, only this `Vim` session will inherit it.

**Detailed explanation with command sequence**

`vim` is an alias to `/Applications/MacVim.app/Contents/MacOS/MacVim`, so `vim -f` runs `vim` in terminal, not in GUI.

```sh
$ umask 0777
$ # command that 100% works
$ touch testfile_umask 
$ ls -l testfile_umask | awk '{print $1}'
---------- 
$ rm testfile_umask
$ # vim in terminal
$ vim -f --clean testfile_umask -c ':wq'
$ ls -l testfile_umask  | awk '{print $1}'
---------- 
$ rm testfile_umask
$ # MacVim is not open, so it should inherit the umask
$ vim --clean testfile_umask -c ':wq'
$ ls -l testfile_umask | awk '{print $1}'
---------- 
$ rm testfile_umask
$ # open MacVim with inherited umask was open, but not edit a file
$ vim
$ # :e testfile_umask | wq
$ ls -l testfile_umask | awk '{print $1}'
---------- 
$ rm testfile_umask
$ # Close MacVm, open it fresh from GUI, not from this terminal session
$ # :e testfile_umask | wq
$ ls -l testfile_umask | awk '{print $1}'
-rw-r--r--
$ rm testfile_umask
$ # Close MacVm, open it fresh from GUI, not from this terminal session
$ # In this test vim session should be opened with given umask
$ vim --clean testfile_umask -c ':wq'
$ ls -l testfile_umask | awk '{print $1}'
----------
$ rm testfile_umask
```

**Comment by hdatma** [comment]
My test: a fresh login, without Terminal, a fresh MacVim launched from /Applications, a fresh text inside of it, and a "save as" action to the Desktop. The permissions of the resulting file are "-r--r--rw-". 

MacVim is the only app doing this crazyness. 

To trace back the problem, I tried /Applications/MacVim.app/Contents/MacOS/Vim from the Terminal, and the permissions are correct. 

The problem, therefore, must be in /Applications/MacVim.app/Contents/MacOS/MacVim.  

You say that Vim and MacVim respect umask. I see that MacVim has a head of its own.

**Comment by eirnym** [comment]
MacVim has been started with your default `umask` specified by a system administrator (default is `022` as per documentation). You can try to change it in your global account settings (probably you should go deeper than default UI to do this). 

after GUI app has been started, every next window is a separate process. This made by MacVim to make it's easier to control. So if you run another MacVim from the command line, the head process won't be changed 

This is confirmed by my tests and is an intended behavior.

**Comment by eirnym** [comment]
I suppose you have set `umask` in your `profile` scripts and you want to propagate it to MacVim as well. These files are not read by GUI environment in macOS and any GUI apps automatically as far as I know if it's not said explictely. Under `Linux`, you have startup scripts where you can set environment for the whole GUI, I don't know if there _any_ similar options for current versions of macOS. there were some for older ones

Nevertheless, I haven't found `umask` or similar option in `vim` (as well as `MacVim`) to set automatically even if you really want it.
