### ISSUE TITLE
Build script error due to space in "Macintosh HD"

### ISSUE THREAD

**Issue by AKielhorn** [macvim-dev/macvim#1014]
**Describe the bug**

I am currently moving from System 10.1 to System 10.3 (yes, I'm late).
I have all my sources on my primary disk, known as "Macintosh HD".

I'm building on System 10.3. 
This results in the following error:
`
PhaseScriptExecution Copy\ mvim\ scripts /Volumes/Macintosh\ HD/Users/axel/src/macvim_10.13/src/MacVim/build/MacVim.build/Release/MacVim.build/Script-52283AB71EBA200C00A6F6B9.sh (in target: MacVim)
    cd /Volumes/Macintosh\ HD/Users/axel/src/macvim_10.13/src/MacVim
    /bin/sh -c /Volumes/Macintosh\\\ HD/Users/axel/src/macvim_10.13/src/MacVim/build/MacVim.build/Release/MacVim.build/Script-52283AB71EBA200C00A6F6B9.sh
mkdir: /Volumes/Macintosh: Permission denied
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
chmod: /Volumes/Macintosh: No such file or directory
chmod: HD/Users/axel/src/macvim_10.13/src/MacVim/build/Release/MacVim.app/Contents/bin/mvim: No such file or directory
/Volumes/Macintosh HD/Users/axel/src/macvim_10.13/src/MacVim/build/MacVim.build/Release/MacVim.build/Script-52283AB71EBA200C00A6F6B9.sh: line 6: cd: /Volumes/Macintosh: No such file or directory
`

The resulting Vim works fine.
The `mvim` script and the symbolic links are missing.

**To Reproduce**
Put the source on an external volume with a space in the volume name.
(Having a space in the path to the source may be sufficient.)

./configure
make

**Expected behavior**

BINPATH needs some quoting to accept a path with a space.

**Environment (please complete the following information):**
 - Vim version 8.2.319
 - OS: macOS 10.13.6
 - Terminal: Terminal

**Comment by ychin** [comment]
This should be fixed! Re-open the issue and let me know if it doesn't work.
