### ISSUE TITLE
The new commit to fix version parsing is broken

### ISSUE THREAD

**Issue by chdiza** [macvim-dev/macvim#1017]
Here's what I see at the end of a configure run:
```
configure: error: could not parse Vim version: 8.2.319
```

**Comment by ychin** [comment]
What macOS version or environment are you running? It worked on my machine and in CI.

**Comment by eirnym** [comment]
I confirm that it works well for my env too. (Catalina)

**Comment by chdiza** [comment]
Mojave.  Even if I clone the repo afresh, I still get it.

**Comment by chdiza** [comment]
My `./configure` flags: 
```
    --disable-netbeans
    --disable-nls
    --disable-sparkle
    --with-compiledby=chdiza
```

These flags have worked for years.

**Comment by chdiza** [comment]
Found the problem: you should change the `grep` invocation to use the full path of the macOS system `grep`.  I have a custom `grep` (GNU), and it was being called by the configure script.  Apparently some difference between BSD grep and GNU grep is popping out in the new commit.

**Comment by chdiza** [comment]
Alternatively, perhaps putting back the double-quotation marks that the commit removed would do the trick.

**Comment by chdiza** [comment]
I've isolated it further.  The problem is the regexp in line 14911.  GNU grep doesn't accept the "\d", only "[[:digit:]]".  The macOS (BSD) grep will also accept "[[:digit:]]".

The fix, both versions of which I've tested locally, is thus to either:

(a) In line 14911 replace all three instances of "\d" with "[[:digit:]]", or

(b) In line 14911 change "grep" to "/usr/bin/grep".

@ychin If you let me know which you prefer I can make the PR myself.

**Comment by ychin** [comment]
@chdiza thanks for isolating the problem. It's a small change so I can just fix it. I will probably do both (a) and (b), since I don't like having different potential grep programs interfering with the script anyway.
