### ISSUE TITLE
macvim installed with brew cask doesn't work anymore

### ISSUE THREAD

**Issue by MartinDelille** [macvim-dev/macvim#1022]
**Describe the bug**

*macvim* crash at startup.

**To Reproduce**

```
$ vi                                                                                                                                                                      935ms
dyld: Library not loaded: /usr/local/opt/ruby/lib/libruby.2.6.dylib
  Referenced from: /usr/local/Cellar/macvim/8.1-161/MacVim.app/Contents/MacOS/Vim
  Reason: image not found
fish: 'vi' terminated by signal SIGABRT (Abort)

**Expected behavior**

It should launch properly

**Environment:**

```
$ vim --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar  3 2020 12:05:00)
macOS version
Included patches: 1-319
Compiled by travis@Traviss-Mac.local
```
 - macOS 10.14.6
 - iTerm2

**Additional context**

I installled *macvim* with `brew cask install macvim`.

**Comment by eirnym** [comment]
Hi @MartinDelille 

MacVim 161 is an outdated version and may not work well enough.Current version is 162

Please, drop an issue to maintainers of MacVim cask in Homebrew. They are different people than MacVim's developers.

Meanwhile you may try to check it manually, update/install/reinstall ruby 2.6 or build from source.

**Comment by ychin** [comment]
As @eirnym said, please update to the latest version.

This seems to be happening because you have some plugins that depends on Ruby, however, it shouldn't crash like that (it should just complain Ruby cannot be found). Just to sanity check can you try `vi --clean` and see what happens?

**Comment by MartinDelille** [comment]
I fixed it: instead of installing macvim with `brew cask install macvim`, I installed it with `brew install macvim`!

**Comment by ychin** [comment]
Hmm, `brew install` and `brew cask install` does different things. If you want a binary built by us and updates managed by MacVim, `brew cask install` is the option you want as it just downloads the binary from our releases. `brew install` will build things locally etc.

If you just want a binary you could go to https://github.com/macvim-dev/macvim/releases and find the latest MacVim.dmg to install it. I'm still curious why you were seeing the crash but I guess if switching to `brew install` worked for you maybe it's not worth probing further.

**Comment by MartinDelille** [comment]
I know. I trust more `brew install` than `brew cask install` since binary are build from a third party (homebrew azure pipelines)

**Comment by eirnym** [comment]
@MartinDelille it's not true, I use the official release from GitHub for many years without a problem. This release is downloaded by cask, which is a bit outdated

**Comment by MartinDelille** [comment]
@eirnym I mean in a general way. Homebrew cask binaries are less secure than classic homebrew binaries. For macvim, I agreed that the build process is clear and totally trustable! 😄

**Comment by ychin** [comment]
Just to be pedantic. Technically as the maintainer I can upload a build that I claim to be built by Travis (in fact I have to do something similar by taking a Travis-built binary and sign it under by Apple Developer ID). Travis doesn't sign their generated binary so the release process does require trust in me, so it's correct that `brew install` does remove that (if you trust the code).
