### ISSUE TITLE
Blank newlines inject in command output

### ISSUE THREAD

**Issue by amadeus** [macvim-dev/macvim#1026]
Newlines get generated when the command output updates the current line. This bug is most easily explained by watching this video:

[example video](https://cdn.discordapp.com/attachments/365662117191352320/690281428855947274/example.mp4)

**Expected behavior**
There should be no new lines generated between command output updates.

**Environment (please complete the following information):**
In the video I run the version command - it's the current latest release, 8.2 with patches 1-319 - the GUI client.

**Comment by eirnym** [comment]
@amadeus Thank you for an issue,

1) Please, provide information about macOs version you using
2) Please, try to run with `mvim --clean` to eliminate any settings and personal configuration from the issue
3) Please, run this command in Terminal.app from Vim (if you use release version the app is located in `/Applications/MacVim.app/Contents/MacOS/Vim`) to check if the issue is reproducible there as well.

**Comment by amadeus** [comment]
* I am running macOS 10.15.3
* It reproduces with `mvim --clean`
  * `mvim` launches the gui client
* Running macvim in terminal does a completely different thing, it completely hides macvim and shows the command executing normally, before switching back to macvim, so in that case it does not exist there:
![image](https://user-images.githubusercontent.com/83376/77123046-53fd3680-69fc-11ea-844d-a86d5da59a3a.png)

**Comment by eirnym** [comment]
Could you provide a command with reproducible output as `git prune` is very specific to local repository?
Could you also try the same command in `gvim` (as in Linux or Windows) **without** `!` option enabled in `guioptions`?

My bet that `git` sees that it's a terminal (even a dumb one as `:!` uses in GUI mode) and tries to output a nice progress which this terminal implementation is processing badly. Both `:terminal` and `dumb` implementation are based on [vim/vim](https://github.com/vim/vim) code with only visual output implementation.

**Comment by amadeus** [comment]
So I upgraded git (`2.23.0_1 -> 2.25.2`), and it seems to have fixed the issues! Thanks for the tip about it being an issue from git

**Comment by eirnym** [comment]
Stay safe :)
