### ISSUE TITLE
Go to line parameter in URL Handler 

### ISSUE THREAD

**Issue by borissov** [macvim-dev/macvim#1028]
Hello,
I have problem with go to line parameter in URL Handler. Stop working after update OSX and MacVim. 

I use this syntax and work normally on old version: 
mvim://open?url=file:///....myfile.php&line=248

Environment:
OSX 10.15.4 
MacVim 162
Vim 8.2.319

**Comment by ychin** [comment]
This is a duplicate of #1020. It was fixed and will be deployed in the next update (https://github.com/macvim-dev/macvim/milestone/11).
