### ISSUE TITLE
Highlight feature "gui=strikethrough" does not display strikethrough text.

### ISSUE THREAD

**Issue by jtvoorhies** [macvim-dev/macvim#1034]
Highlight feature "gui=strikethrough" does not display strikethrough text.

**To Reproduce**
1. Run `mvim --clean`
2. Create or edit an html file
3. Type `<strike>some text</strike>` or `:highlight htmlStrike`
4. Observe "gui=strikethrough" yet the strike mark is not on the text.

**Expected behavior**
The highlight feature "gui=strikethrough" should show a strikethrough

**Screenshots**
Screenshot attached.

**Environment (please complete the following information):**
 - Vim version:
  VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar  3 2020 12:05:00)
  macOS version
  Included patches: 1-319
  Compiled by travis@Traviss-Mac.local
  Huge version with MacVim GUI. 
 - OS: macOS 10.15.4
 - Terminal: MacVim GUI
<img width="760" alt="mvim --clean no strikethrough" src="https://user-images.githubusercontent.com/33003771/78416681-2b765e80-75f0-11ea-8a3d-e087958eaa48.png">

**Comment by ychin** [comment]
Yeah we should add this. Maybe next release where we look at getting the renderer fix in.

**Comment by qiqiboy** [comment]
Hi, is there any update on this? Thanks.

**Comment by ychin** [comment]
I forgot about this, that's all. I'm preparing a release right now, but let me see if it's easy to squeeze this in before the release.

**Comment by ychin** [comment]
Actually, sorry, but I think I'll push this till r175 (the one after the coming release) since I kind of want to push it out soon, and I want to make sure I get the rendering to look correct, plus support the new Vim text styles in one go (double underline, dashed / dotted underlines).

**Comment by ychin** [comment]
Nevermind what I said. I'm waiting to see if Vim will stabilize a bit before I pick a good version to release on, so we are going to squeeze it in (#1287).
