### ISSUE TITLE
Why have patches 481 through 525 not appeared in the commit list?

### ISSUE THREAD

**Issue by chdiza** [macvim-dev/macvim#1035]
ac23466693b Merged in upstream patchers 480 through 525.

But those commits don't individually appear in the `git log` like they usually do when upstream is merged in.

Is this on purpose?  I like it better when I can see all the little Vim patches.

**Comment by ychin** [comment]
I screwed up and accidentally cherry-picked my merge commit. Will fix.

**Comment by ychin** [comment]
Fixed.

**Comment by amadeus** [comment]
Doesn't appear to be?

**Comment by chdiza** [comment]
I don't see it fixed either.

**Comment by ychin** [comment]
It's in now. I forgot to push
