### ISSUE TITLE
App version of Snapshot 162 release is "."

### ISSUE THREAD

**Issue by steakknife** [macvim-dev/macvim#1037]
Version is reported as '.' from notarized & non-notarized .app within .dmg's.

This may also break Sparkle's self-update ability if that's in-use.

**Comment by ychin** [comment]
This was fixed in release snapshot-163 (#1011). Also, this won't affect Sparkle, so you don't need to worry about it (the 8.2.1234 type versioning is mostly just for human-readable displays)

**Comment by steakknife** [comment]
@ychin Actually, that's completely untrue. I use a defunct hybrid app called Bodega to scan all Sparkle apps for version updates and it showed up as "." too. The version is stored in the `/Applications/MacVim.app/Contents/Info.plist` as `CFBundleShortVersionString` which is where macOS and Sparkle get the current version from.

**Comment by ychin** [comment]
Why do you think `CFBundleShortVersionString` is what Sparkle uses? It uses `CFBundleVersion` (https://sparkle-project.org/documentation/). MacVim publishes an incremental snapshot number (currently at 163) which is actually what Sparkle understands as the version number. The new version is already out so you just need to press the "Check for Updates…" item and it should update itself to latest.
