### ISSUE TITLE
Question: Can we open a new empty file in a folder from Finder in OSX

### ISSUE THREAD

**Issue by mgw-sbic** [macvim-dev/macvim#1042]
Hi, We often want to create a new, empty file in a specific folder when we are using Finder. Can we two finger click / right click within the folder in Finder and open MacVim so its current directory is that folder? Or is there another way to achieve this?

**Comment by eirnym** [comment]
You can use a service called `New MacVim buffer here…` when you press context menu on a folder. If it's not enough, you can create your own using `Automator.app`

**Comment by mgw-sbic** [comment]
HI Eirnym, thank you for the answer. I Googled for that phrase, but couldn't find how to enable the Services menu and how to add MacVim to that menu. On Mojave I do not see the Services-> menu in the FInder context menu. Thank you for your help!

**Comment by eirnym** [comment]
You can find it in context menu for a folder, not for Finder

**Comment by mgw-sbic** [comment]
Hey again Eirnym,

So, the Folder is part of the finder, and I found it thank you! It is fine for me.

**Comment by ychin** [comment]
Glad you found it! But yes you should be able to open a menu on either the folder, empty space in Finder, or just Finder -> Services to locate the Services. You can also do `:help macvim-services` for more info:

```
10. System services					*macvim-services*

MacVim supports two system services.  These can be accessed from the MacVim
submenu in the Services menu or by right-clicking a selection.  For services
to work, MacVim.app should be located in the /Applications folder.  (You might
have to logout and then login again before macOS detects the MacVim services.)

These are the currently supported services:
	* New MacVim Buffer With Selection: Create a new buffer and paste the
	  currently selected text.
	* New MacVim Buffer Here: Create a new buffer and set the current
	  directory to the file or folder that is selected in the Finder.

The services respect the "Open files from applications" setting in the general
preferences.
```
