### ISSUE TITLE
Invalid argument when setting spellfile, but works in regular vim

### ISSUE THREAD

**Issue by davetron5000** [macvim-dev/macvim#1044]
**Describe the bug**

When setting `spellfile`, if `isfname` does not contain a period (`.`), I get `E474: Invalid argument: spf=/Users/davec/Projects/Personal/sustainable-rails/spellfile.en.utf-8.add`

This does not happen in the terminal-based vim I have installed via homebrew.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `vim --clean` (or `gvim --clean`, etc.)
1. `:set isfname-=.`
1. `:set spf=~/.vim/spell/en.utf-8.add` (or to any valid spellfile)
1. E474: Invalid argument: spf=~/.vim/spell/en.utf-8.add

**Expected behavior**
I don't believe the contents of `isfname` should affect the spellfile.

**Environment (please complete the following information):**

<details>
  <summary>VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 12 2020 00:47:07)</summary>

      macOS version
      Included patches: 1-539
      Compiled by travis@Traviss-Mac.local
      Huge version with MacVim GUI.  Features included (+) or not (-):
      +acl               +file_in_path      +mouse_urxvt       -tag_any_white
      +arabic            +find_in_path      +mouse_xterm       -tcl
      +autocmd           +float             +multi_byte        +termguicolors
      +autochdir         +folding           +multi_lang        +terminal
      -autoservername    -footer            -mzscheme          +terminfo
      +balloon_eval      +fork()            +netbeans_intg     +termresponse
      +balloon_eval_term +fullscreen        +num64             +textobjects
      +browse            -gettext           +odbeditor         +textprop
      ++builtin_terms    -hangul_input      +packages          +timers
      +byte_offset       +iconv             +path_extra        +title
      +channel           +insert_expand     +perl/dyn          +toolbar
      +cindent           +job               +persistent_undo   +transparency
      +clientserver      +jumplist          +popupwin          +user_commands
      +clipboard         +keymap            +postscript        +vartabs
      +cmdline_compl     +lambda            +printer           +vertsplit
      +cmdline_hist      +langmap           +profile           +virtualedit
      +cmdline_info      +libcall           +python/dyn        +visual
      +comments          +linebreak         +python3/dyn       +visualextra
      +conceal           +lispindent        +quickfix          +viminfo
      +cryptv            +listcmds          +reltime           +vreplace
      +cscope            +localmap          +rightleft         +wildignore
      +cursorbind        +lua/dyn           +ruby/dyn          +wildmenu
      +cursorshape       +menu              +scrollbind        +windows
      +dialog_con_gui    +mksession         +signs             +writebackup
      +diff              +modify_fname      +smartindent       -X11
      +digraphs          +mouse             -sound             -xfontset
      +dnd               +mouseshape        +spell             +xim
      -ebcdic            +mouse_dec         +startuptime       -xpm
      +emacs_tags        -mouse_gpm         +statusline        -xsmp
      +eval              -mouse_jsbterm     -sun_workshop      -xterm_clipboard
      +ex_extra          +mouse_netterm     +syntax            -xterm_save
      +extra_search      +mouse_sgr         +tag_binary        
      -farsi             -mouse_sysmouse    -tag_old_static    
         system vimrc file: "$VIM/vimrc"
           user vimrc file: "$HOME/.vimrc"
       2nd user vimrc file: "~/.vim/vimrc"
            user exrc file: "$HOME/.exrc"
        system gvimrc file: "$VIM/gvimrc"
          user gvimrc file: "$HOME/.gvimrc"
      2nd user gvimrc file: "~/.vim/gvimrc"
             defaults file: "$VIMRUNTIME/defaults.vim"
          system menu file: "$VIMRUNTIME/menu.vim"
        fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
      Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
      Linking: clang   -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/readline/lib -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o Vim -framework Cocoa -framework Carbon       -lm  -lncurses -liconv -framework AppKit   -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE
</details>

* OS: macOS 10.15.4 19E287
* Terminal: GUI

**Additional context**

This problem does not happen on the terminal vim installed with Homebrew.  That version is (but note that this has not happened on any version released in the last several years):

<details>
  <summary>VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 19 2020 22:40:28)</summary>

      macOS version
      Included patches: 1-600
      Compiled by Homebrew
      Huge version without GUI.  Features included (+) or not (-):
      +acl               -farsi             +mouse_sgr         +tag_binary
      +arabic            +file_in_path      -mouse_sysmouse    -tag_old_static
      +autocmd           +find_in_path      +mouse_urxvt       -tag_any_white
      +autochdir         +float             +mouse_xterm       -tcl
      -autoservername    +folding           +multi_byte        +termguicolors
      -balloon_eval      -footer            +multi_lang        +terminal
      +balloon_eval_term +fork()            -mzscheme          +terminfo
      -browse            +gettext           +netbeans_intg     +termresponse
      ++builtin_terms    -hangul_input      +num64             +textobjects
      +byte_offset       +iconv             +packages          +textprop
      +channel           +insert_expand     +path_extra        +timers
      +cindent           +ipv6              +perl              +title
      -clientserver      +job               +persistent_undo   -toolbar
      +clipboard         +jumplist          +popupwin          +user_commands
      +cmdline_compl     +keymap            +postscript        +vartabs
      +cmdline_hist      +lambda            +printer           +vertsplit
      +cmdline_info      +langmap           +profile           +virtualedit
      +comments          +libcall           -python            +visual
      +conceal           +linebreak         +python3           +visualextra
      +cryptv            +lispindent        +quickfix          +viminfo
      +cscope            +listcmds          +reltime           +vreplace
      +cursorbind        +localmap          +rightleft         +wildignore
      +cursorshape       +lua               +ruby              +wildmenu
      +dialog_con        +menu              +scrollbind        +windows
      +diff              +mksession         +signs             +writebackup
      +digraphs          +modify_fname      +smartindent       -X11
      -dnd               +mouse             -sound             -xfontset
      -ebcdic            -mouseshape        +spell             -xim
      +emacs_tags        +mouse_dec         +startuptime       -xpm
      +eval              -mouse_gpm         +statusline        -xsmp
      +ex_extra          -mouse_jsbterm     -sun_workshop      -xterm_clipboard
      +extra_search      +mouse_netterm     +syntax            -xterm_save
         system vimrc file: "$VIM/vimrc"
           user vimrc file: "$HOME/.vimrc"
       2nd user vimrc file: "~/.vim/vimrc"
            user exrc file: "$HOME/.exrc"
             defaults file: "$VIMRUNTIME/defaults.vim"
        fall-back for $VIM: "/usr/local/share/vim"
      Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
      Linking: clang   -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -lintl -framework AppKit  -L/usr/local/opt/lua/lib -llua5.3 -mmacosx-version-min=10.15 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.30.2_1/lib/perl5/5.30.2/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc  -L/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/config-3.7m-darwin -lpython3.7m -framework CoreFoundation  -lruby.2.7
</details>

**Comment by ychin** [comment]
I checked upstream Vim and this seems to happen as well, and I'm not sure if this is a bug. @davetron5000 since it's been a while, can you just try Homebrew Vim again and post the version? It's likely you see this in MacVim and not Homebrew Vim just because of different versions.

But since this seems to happen in latest Terminal Vim as well I think you may want to file this with Vim.

**Comment by davetron5000** [comment]
Confirmed that with terminal vim 8.2.1700 this is happening there, too.  So it seems this is not a MacVim-specific bug.  I will try to open an issue on actual vim.  Wish me luck :)
