### ISSUE TITLE
Snapshot 78

### ISSUE THREAD

**Issue by splhack** [macvim-dev/macvim#105]
It's ready to deploy Snapshot 78.
https://github.com/macvim-dev/macvim/wiki/Deployment

**Comment by splhack** [comment]
- Vim patch 7.4.902
- Add basic support for CoreText ligatures
- Add optional blur to transparent windows
- Allow to open directory in Open dialog
- Fix rendering and resizing issues on El Capitan Split View
- Fix Deployment Target for Yosemite with Xcode 7.1

any other updates?

**Comment by chdiza** [comment]
Wasn't there already a Snapshot 78?

**Comment by chdiza** [comment]
Yes, there was: https://github.com/macvim-dev/macvim/commit/c45736ab2b3dec5297be3049cfe0edd4ef55416c

**Comment by splhack** [comment]
78 is already reverted. never mind.

**Comment by splhack** [comment]
Snapshot 78 will be built with dynamic linking to Lua, Perl, Python 2, Python 3, and Ruby.
https://github.com/macvim-dev/macvim/blob/77b7042855becd832fe3c03ae1af4e6db5985e57/.travis.yml#L17

However the runtime depends on Homebrew path hierarchy. To adopt the other package system or self built for loading script binding shared libraries, I'll release another snapshot after my patch is applied.
https://github.com/vim/vim/commit/a0f849ee40cbea3c889345256786b640b0becca2#diff-38d7929bd26d74d92ceddf984bbfc8dbR125

**Comment by chdiza** [comment]
There shouldn't be a snapshot 78, as it already exists (not on the releases page, but at the link I gave above).  There should be a snapshot 79.

**Comment by splhack** [comment]
ok, It doesn't matter it's up to you

**Comment by chdiza** [comment]
> ok, It doesn't matter it's up to you

It does matter, which is why I tried to prevent the existence of two distinct things named "Snapshot 78".  If someone creates an issue and we ask what version of MacVim she is using, and she says "Snapshot 78", we won't know which version she is using.  She could be using the thing we just built and released today, or she could be using `c45736a`.

**Comment by splhack** [comment]
https://github.com/macvim-dev/macvim/releases/tag/snapshot-79

**Comment by eirnym** [comment]
Honestly to say, there was snapshot 78 build. But it had been removed very soon after released.

**Comment by eirnym** [comment]
By the way, good job, guys!

**Comment by chdiza** [comment]
> Honestly to say, there was snapshot 78 build. But it had been removed very soon after released.

That's not the point, though.  The point is that a user could have checked out commit c45736a, which is titled "Snapshot 78", and completely reasonably have told us she is using Snapshot 78.

**Comment by splhack** [comment]
yeah. but it's rare case, no one cares.
