### ISSUE TITLE
Editing multiple files from command line opens in multiple windows

### ISSUE THREAD

**Issue by eirnym** [macvim-dev/macvim#1059]
**Describe the bug**
MacVim 163 (8.2.539) shows behaviour where all files will be opened in the same window and this is an expected workflow for me
MacVim (latest master, commit d552421a21b24493ed0745980cf0bb267b021289): 
1) opens all files in separate windows 
2) terminal stays in the front (MacVim won't take focus)
3) `--clear` seems to take an argument for MacVim.app (issue #1058) but doesn't change any behaviour of this.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Build MacVim in directory `/Users/eirnym/dev/macvim` using `git clean -fdx && make clean && ./configure --enable-python3interp=dynamic && make`
1. Create test files with `cd /Users/eirnym/test && rm -rf *txt && touch {1,2,3}.txt`
1. Open Vim with command `src/MacVim/build/Release/MacVim.app/Contents/MacOS/Vim *txt`
1. When Vim (terminal) opens, execute `:ls` to make sure that all 3 **buffers** on the list, exit Vim. (it's correct behaviour)
1. Open MacVim with command `src/MacVim/build/Release/MacVim.app/Contents/MacOS/MacVim *txt` (or by listing them separately)
1. 3 (three) windows in background will be opened
1. `--clear` seems to take an argument for MacVim.app (issue #1058) but doesn't change any behaviour of steps to reproduce

**Expected behavior**
Will be opened 1 (one) with 3 buffers as Vim (from the same build) does and how MacVim 163 and past versions do.

**Screenshots**
If applicable, copy/paste the text or add screenshots to help explain your problem.

**Environment:**
 - Vim version commit **d552421a21b24493ed0745980cf0bb267b021289** (currently the latest)
 - OS: macOS 10.15.6 (19G60d)
 - Terminal: Terminal.app

**Comment by ychin** [comment]
As discussed in #1058, `Contents/MacOS/MacVim` is not a valid entry point for MacVim for command-line usage, and no documentation points to it. This behavior also hasn't changed.

The proper way is really to use  scripts like `Contents/bin/vim` to mimic a Vim-like command-line behavior (although directly invoking `Contents/MacOS/Vim` would work as well, even though that's not the "official" way).
