### ISSUE TITLE
Universal Sparkle Framework required for Apple Silicon

### ISSUE THREAD

**Issue by stack** [macvim-dev/macvim#1060]
I have successful compiled and have been using MacVim on Apple Silicon. Everything is working properly at this point. The only change I had to make was to replace the existing Sparkle.framework with a hand compiled version that is universal.

I imagine once we get closer to release, an actual release of the Sparkle.framework will exist that is universal.

**Comment by ychin** [comment]
Yeah I will release an Apple Silicon compatible version of MacVim in the next release. Only annoyance with Sparkle is that they don't have an official Apple Silicon compatible version right now so I will need to build it myself, which is not a big deal.

**Comment by stack** [comment]
MacVim has been working great on the DTK I have. I am having an issue with importing python modules, but this issues is also present on Intel, so it might be more of a Big Sur bug.

**Comment by robjperez** [comment]
I'm also using MacVim in the DTK built in the machine itself. The x86 running in Rosseta2 lagged from time to time, so I decided to build it myself. As a side note, instead of replacing Sparkle with an Universal binary I just removed it from the build and everything works ok.

**Comment by ychin** [comment]
This was done in #1118.
