### ISSUE TITLE
Fails to start language server

### ISSUE THREAD

**Issue by Chris-Leeworthy** [macvim-dev/macvim#1061]
I installed the terraform-lsp language server combined with the COC plugin.  This works fine when I am using Vim in the terminal, but gives an error when I open a terraform file from the MacVim gui.

![Screenshot 2020-07-16 at 19 06 39](https://user-images.githubusercontent.com/13499355/87706869-1b961b00-c798-11ea-9ee6-d1e842e7cdc3.png)

It feels like a file path or security context issue, but that's just speculation on my part.  Maybe there's something I need to do in the config to have this work in MacVim as well as terminal Vim?

I am running 
Vim 8.2
Mac OS: Catalina 10.15.6
MacVim: Custom Version 8.2.539 (163)

**Comment by eirnym** [comment]
@Chris-Leeworthy, Thank you for an issue

Could you check if this language server is compatible with Vim (base) and report an issue there. MacVim is only a GUI for a base Vim. 

Also when you report an issue to the [upstream](https://github.com/vim/vim), please link it here to track the progress.

**Comment by Chris-Leeworthy** [comment]
it's working just fine with Vim in the terminal,  wouldn't that indicate that the GUI is the issue rather than vim itself?

**Comment by ychin** [comment]
Are you using the binary released under https://github.com/macvim-dev/macvim/releases? Or manually built or Homebrew?

**Comment by Chris-Leeworthy** [comment]
I'm using the binary from  https://github.com/macvim-dev/macvim/releases

**Comment by eirnym** [comment]
COC server support was developed for NeoVim, not Vim

**Comment by ichizok** [comment]
Please check `:echo executable('terraform-lsp')` and `:echo $PATH` in GUI MacVim.

**Comment by ychin** [comment]
Brief glance does seem like it's a permission issue, but I will need to try this out and install it locally to be able to tell. If you want to debug it, you could always build MacVim GUI locally and try running or running the "MacVim_non_notarized.dmg" version from the releases page which doesn't have app hardening turned on.

**Comment by Chris-Leeworthy** [comment]
@ichizok Thank you, this has tracked down the source of the differing behaviour.

Running `:echo executable('terraform-lsp')` in the GUI reports a `0` and when run from the terminal reports `1`

 `:echo $PATH` also reports different results depending on whether I'm in the terminal version or the GUI version.  Unsurprisingly, the path for the GUI version doesn't include the path to the terraform-lsp command.

I guess I now have to figure out why path is so different!

**Comment by Chris-Leeworthy** [comment]
Got it.

The instructions at this page explain how to fix the differing path values.  The only downside is I will have remember to manually apply the fix if I make any other changes to PATH that would affect Vim/MacVim, but I can probably write something to automate that.

https://github.com/b4winckler/macvim/wiki/Troubleshooting#for-zsh-users

Thanks to everyone for your time and attention on this. :-)
