### ISSUE TITLE
gx stop open link in browser (bug return in Version 8.2.539 (163))

### ISSUE THREAD

**Issue by ApolloTang** [macvim-dev/macvim#1067]
**Describe the bug**
This bug is returning to current version  8.2.539 (163)
https://github.com/macvim-dev/macvim/issues/935

**To Reproduce**
Detailed steps to reproduce the behavior:
1.  place cursol on a url
2. type gx in normal mode
3. html content is open in a new buffer instead of web browser

**Expected behavior**
html content should be opened in a web browser

**Screenshots**
see: https://github.com/macvim-dev/macvim/issues/935

**Environment (please complete the following information):**
![Screen Shot 2020-08-02 at 12 36 32](https://user-images.githubusercontent.com/1150961/89127618-d7f02080-d4bc-11ea-83f7-e287a1f8cd9a.png)

**Comment by eirnym** [comment]
@ApolloTang thank you for an issue,

Please, refer to #925 and https://github.com/vim/vim/issues/4738 because this one is a full duplicate of these both

**Comment by eirnym** [comment]
Basically, plugin author changed it's behaviour a year ago and many people have problem with it since then. On one hand it's his plugin on the other hand it's bundled to vim itself, so there's no reason to open too many issues for the single problem. This won't help to solve it.

**Comment by ApolloTang** [comment]
close due to duplication
