### ISSUE TITLE
MacVim stopped working after update to v. 8.2.1424 (gettext)

### ISSUE THREAD

**Issue by ekortright** [macvim-dev/macvim#1073]
After updating to 8.2.1424 (164), MacVim stopped working.  The program runs, but no window is displayed.

When trying to run from the command line, this is what I see:

<pre>$ mvim
dyld: Library not loaded: /usr/local/opt/gettext/lib/libintl.8.dylib
  Referenced from: /Users/me/Applications/MacVim.app/Contents/MacOS/Vim
  Reason: image not found
Abort trap: 6</pre>

Until now, I have been using MacVim with the gettext that comes with homebrew:

<pre>$ gettext --version
gettext (GNU gettext-runtime) 0.21
Copyright (C) 1995-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Written by Ulrich Drepper.</pre>

**Comment by mvilain** [comment]
I'm seeing different error on 10.13.6:

$ mvim
dyld: Library not loaded: /usr/local/opt/gettext/lib/libintl.8.dylib
  Referenced from: /Applications/MacVim.app/Contents/MacOS/Vim
  Reason: Incompatible library version: Vim requires version 11.0.0 or later, but libintl.8.dylib provides version 10.0.0
Abort trap: 6

**Comment by ychin** [comment]
There was an issue with the latest release with how the linkage is done and I’ll work to fix it in the next couple days. For now please use 163. I believe I should have reverted the updater to point to 163. Is that not the case?

**Comment by ekortright** [comment]
I just followed the prompts from MacVim and it installed 164.

**Comment by ychin** [comment]
Right. I think there was roughly 2-3 hours where this slipped through before someone filed the issue and I reverted the version bump so I would need to confirm that’s the case. Sorry about that.

**Comment by ychin** [comment]
This should be fixed. Snapshot 165 should be out soon, and i added a check to make sure a similar problem (external library linkage) won't show up again.

**Comment by ychin** [comment]
The release should now be out. Please re-open the issue if it still doesn't work.

https://github.com/macvim-dev/macvim/releases/tag/snapshot-165

**Comment by ekortright** [comment]
Works!  Thanks.
