### ISSUE TITLE
Switching to fullscreen looses window focus, if title bar "hidden"

### ISSUE THREAD

**Issue by krishan** [macvim-dev/macvim#1078]
**Describe the bug**
Switching to fullscreen looses the window focus, if the title bar is set to "hidden".

**To Reproduce**
1) In preferences, set the titlebar appearance to "hidden"
2) Switch to fullscreen, e.g. using the key shortcut

**Expected behavior**
Vim goes fullscreen and should have focus, e.g. it should react to me typing.

**Actual behavior**
Vim goes fullscreen, but no longer has focus. Typing results in a "beep" from the OS and no reaction from Vim.

**Environment (please complete the following information):**
 - Vim version 8.2.1456 (165)
 - OS: MacOS 10.15.5
- Terminal: GUI

**Comment by ychin** [comment]
Reproduced the bug. Will try to get it fixed by next release. The feature was mostly a hidden half-supported feature before, so testing done on it was a little less than the other normal modes.
