### ISSUE TITLE
python3 fatal error after recent update of Macvim

### ISSUE THREAD

**Issue by gaofn** [macvim-dev/macvim#1079]
**Describe the bug**
After the most recent update of MacVim, it stops working with tex files. 

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Upgrade to the most recent MacVim release (165)
2. type "mvim foo.tex"

**Expected behavior**
MacVim starts with foo.tex being edited.  Instead, MacVim does not start with the following error message 
```
Fatal Python error: config_get_locale_encoding: failed to get the locale encoding: nl_langinfo(CODESET) failed
Python runtime state: preinitialized
```
Everything was fine until MacVim was upgraded today.  Also type "vim foo.tex" starts a cli vim with foo.tex opened without any problem

**Screenshots**

**Environment (please complete the following information):**
 - MacVim version 165
 - OS: [macOS 10.15.6]
 - Terminal: [iTerm2] 
 - I have vim latex suite installed

**Additional context**

**Comment by ychin** [comment]
Seems like a Python 3.8 issue. Is vim latex suite a Python-based plugin?

Can you type `locale` in terminal and see what it shows? Ideally it should say UTF-8 in it. For example, it should say "en_US.UTF-8" instead of "en_US". You can always set `LANG=en_US.UTF-8` before launching `mvim` from terminal.

Also, you said if you do `vim foo.tex`, it works. This is just the system-provided Vim right?

**Comment by gaofn** [comment]
> Seems like a Python 3.8 issue. Is vim latex suite a Python-based plugin?
Yes, vim latex suite is python-based.

> 
> Can you type `locale` in terminal and see what it shows? Ideally it should say UTF-8 in it. For example, it should say "en_US.UTF-8" instead of "en_US". You can always set `LANG=en_US.UTF-8` before launching `mvim` from terminal.
My locale is correct. 
```
➜  ~ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
```

> 
> Also, you said if you do `vim foo.tex`, it works. This is just the system-provided Vim right?
Yes.
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun  5 2020 21:30:37)
macOS version
Included patches: 1-503, 505-680, 682-2292
```

**Comment by ychin** [comment]
Hm, I still think this is probably some Python locale configuration issue that you could fix on your end. I don't think system Vim is built with Python3, so it's likely that if you used system Vim you wouldn't even run into the code path as MacVim (which is built with Python2/3). Here are some suggestions:

1. Launch `mvim` and type `:language` and see what it says.
2. See what `:set pythonthreedll` says in MacVim.
3. Load the terminal version of MacVim by running `/Applications/MacVim.app/Contents/bin/vim foobar.tex` and see if it works. Alternatively, load MacVim directly from the doc (don't use the terminal) and load the same tex file.

**Comment by gaofn** [comment]
> Hm, I still think this is probably some Python locale configuration issue that you could fix on your end. I don't think system Vim is built with Python3, so it's likely that if you used system Vim you wouldn't even run into the code path as MacVim (which is built with Python2/3). Here are some suggestions:
> 
> 1. Launch `mvim` and type `:language` and see what it says.

It says
`Current language: "en_US/en_US/en_US/C/en_US/en_US"`
This is the same as in my system vim. 

> 2. See what `:set pythonthreedll` says in MacVim.

` pythonthreedll=/usr/local/Frameworks/Python.framework/Versions/3.7/Python`

> 3. Load the terminal version of MacVim by running `/Applications/MacVim.app/Contents/bin/vim foobar.tex` and see if it works. Alternatively, load MacVim directly from the doc (don't use the terminal) and load the same tex file.

No, neither works.  Same error message as before.

**Comment by ychin** [comment]
Yeah this makes sense. `lang` needs to say `en_US.UTF-8`, not just `en_US`. If you search for the error message you will see the relevant discussions. I think it's a Python 3.8 thing.

Given that your local locale is current in the terminal (when you typed `locale`), I think some of your configs is setting `lang` to the non-UTF-8 version. When you launch Vim from terminal (`mvim` or `vim`) it's supposed to take on the locale environment that you see by typing `locale`. You could try `mvim --clean` to see if `:lang` in Vim shows the correct one, or just manually set it in Vim `:lang en_US.UTF-8` for testing or just put that in your vimrc (although you shouldn't really need to).

**Comment by gaofn** [comment]
> Yeah this makes sense. `lang` needs to say `en_US.UTF-8`, not just `en_US`. If you search for the error message you will see the relevant discussions. I think it's a Python 3.8 thing.
> 
> Given that your local locale is current in the terminal (when you typed `locale`), I think some of your configs is setting `lang` to the non-UTF-8 version. When you launch Vim from terminal (`mvim` or `vim`) it's supposed to take on the locale environment that you see by typing `locale`. You could try `mvim --clean` to see if `:lang` in Vim shows the correct one, or just manually set it in Vim `:lang en_US.UTF-8` for testing or just put that in your vimrc (although you shouldn't really need to).

Yes, you are right.  I did find that in my `.vimrc` file, a line sets the `lang` to en_US.  Removing the line gives the correct `lang`.

**Comment by ychin** [comment]
I think the reason is that Python 3.8 introduced the behavior changes, which MacVim has upgrade to. Does seem suboptimal to me to have a breaking behavior like that but probably should take it up to Python dev.

**Comment by eirnym** [comment]
Python uses `nl_langinfo` from `glibc` library which returns nothing in this case. The problem was introduced 2 years ago in https://github.com/python/cpython/commit/dfe0dc74536dfb6f331131d9b2b49557675bb6b7 I think it's worth a while to raise a ticket there.
