### ISSUE TITLE
Wont update with `brew upgrade`

### ISSUE THREAD

**Issue by cwahlfeldt** [macvim-dev/macvim#108]
Hi, 

Im attempting to upgrade macvim to the most recent version using brew upgrade. 

Im getting the errors:

    ==> Upgrading 1 outdated package, with result:
    macvim 7.4-79
    ==> Upgrading macvim
    ==> Downloading https://github.com/macvim-dev/macvim/archive/snapshot-79.tar.gz
    Already downloaded: /Library/Caches/Homebrew/macvim-7.4-79.tar.gz
    ==> ./configure --with-features=huge --enable-multibyte --with-macarchs=x86_64 --enable-pe
    ==> make
    Last 15 lines from /Users/cwahlfeldt/Library/Logs/Homebrew/macvim/02.make:
          _perl_init in if_perl.o
      "_perl_construct", referenced from:
          _perl_init in if_perl.o
      "_perl_destruct", referenced from:
          _perl_end in if_perl.o
      "_perl_free", referenced from:
          _perl_end in if_perl.o
      "_perl_parse", referenced from:
      _perl_init in if_perl.o
      "_perl_run", referenced from:
          _perl_end in if_perl.o
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make[1]: *** [Vim] Error 1
    make: *** [first] Error 2

Heres the logs:
https://gist.github.com/2a707b357a6be6b8f453 

Thanks!

**Comment by splhack** [comment]
The reason is obvious. No '-lperl' link option here.
https://gist.github.com/anonymous/2a707b357a6be6b8f453#file-02-make-L81
https://gist.github.com/anonymous/2a707b357a6be6b8f453#file-01-configure-L105

**Comment by cwahlfeldt** [comment]
Thanks for the reply. How would I go about fixing the issue? You told me what the problem was, which was not obvious to me as Im not a brew/macvim guru, but not a solution. So instead of closing the issue, maybe wait until it has actually been solved.

**Comment by splhack** [comment]
I'm sorry but it is not MacVim issue nor Homebrew issue. If you're not sure the solution that I mentioned, just uninstall MAMP, brew upgrade, and install MAMP.

**Comment by cwahlfeldt** [comment]
Alright thanks.
