### ISSUE TITLE
8.2.1456 - shift+o broken when used on top line that wraps to multiple screen lines

### ISSUE THREAD

**Issue by AbePralle** [macvim-dev/macvim#1083]
**Describe the bug**
SHIFT+O does not work properly when used on the top line of the buffer and the top line wraps to occupy two or more screen lines. It clears the top screen line instead of shifting it down. Undo does not work properly after that command.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `mvim --clean`
2. Type in any placeholder text to make the top line occupy multiple screen lines. Add one or two more logical lines as well to see the Undo corruption in steps 5 & 6.
3. Escape to command mode. With the cursor on the top line, press SHIFT+O.
4. The top screen line will clear instead of shifting down.
5. Press `ESCAPE` and then `u` to undo. 
6. The top line is restored but one or more lines under it disappears. The number of following lines that disappear is equal to the number of screen lines that the top line occupies, minus one.

**Expected behavior**
SHIFT+O should work a long top line the same as on any other line. Note: this bug does not occur on the previous release, 8.2.539.

**Environment**
- Vim 8.2.1456
- macOS 10.15.5

**Comment by ychin** [comment]
I think this is fixed upstream in v8.2.1488 (9dc1917f42b23277e143fc58bbe27482b0b76bad). Will be fixed next release in release 166.
