### ISSUE TITLE
Xcode version change?

### ISSUE THREAD

**Issue by sfsam** [macvim-dev/macvim#1100]
The Xcode project can no longer be opened by older versions of Xcode including Xcode 10.3. Is there a reason to require a new Xcode? Looking at the source, the `objectVersion` key in `project.pbxproj` was recently changed from 46 to 54. I'm not terribly proficient with Xcode, but I wonder can this be changed back?

**Comment by sfsam** [comment]
Ah, nice one, Xcode. Thanks, @ychin.

**Comment by ychin** [comment]
I filed a PR to fix this. Feel free to grab the dev branch or master after I merge it and let me know if it worked. #1099 just did a bunch of changes to the Xcode project so it could have broken other things as well and of course Catalina makes it hard (impossible) to run older Xcode versions to test this.

**Comment by sfsam** [comment]
Looks good. I can open it now with Xcode 10.3 on macOS Mojave.
