### ISSUE TITLE
Unicode characters clipped

### ISSUE THREAD

**Issue by postylem** [macvim-dev/macvim#1110]
Unicode characters display as clipped in MacVim, which doesn't happen in terminal Vim.

**Bug description**
In MacVim unicode characters such as 𝒜𝒞𝒫𝑸𝒁 are clipped off (the first lines have these characters being rendered by [tex-conceal](https://github.com/KeitaNakamura/tex-conceal.vim)), the last few lines are just unicode in the textfile, if this matters.
<img width="507" alt="macvim" src="https://user-images.githubusercontent.com/5202957/96348494-3ae26400-1077-11eb-8db2-feaa74ee22be.png">

This is how it looks in terminal Vim, not perfect (these characters overlap their neighbours... see the "𝒫(Ω)" for instance), but much preferred to the clipping
<img width="514" alt="terminalvim" src="https://user-images.githubusercontent.com/5202957/96348495-3ae26400-1077-11eb-8ab2-4731a72e3642.png">

If I turn off the "Preferences > Advanced > Use Core Text Renderer" option, then this particular issue goes away, but I know this is deprecated, and it has lots of other problems, like introducing weird line-spacing issues.

Is there a solution for this?

**Environment:**
 - Vim version 8.2 [MacVim 8.2.1719 (166)], Included patches: 1-1719, Compiled by Homebrew
 - macOS Catalina 10.15.6 (19G2021)
 - Terminal iTerm2

**Comment by ychin** [comment]
Please don't turn off Core Text Renderer. As you said it's deprecated and doesn't work properly and the option will be removed soon.

#858 should fix this but we are still ironing some issues with it.

**Comment by ychin** [comment]
Alternatively, you can use the new-ish feature and do `call setcellwidths([[0x1d4ab, 0x1d4ab, 2]])`.

`0x1d4ab` is the unicode number for "𝒫", and doing this allows you to make it take up two columns instead of one to reduce any clipping and make it look nicer as well. You can use Vim command `ga` when cursor is on a character to see what the code is.

**Comment by postylem** [comment]
I see, thanks for the response!  For now, is there a way to get macvim to just show the characters overlapping, rather than clip them (that is, to get the same behaviour as in terminal vim, in my second screenshot)?  

Custom-adjusting the width with `setcellwidths()` for each glyph I want to use for my primary use-case it isn't useful, because it doesn't work for the glyphs which are put there by tex-conceal (it seems it only works for glyphs that are typed in as unicode characters, not ones that are displayed to 'conceal' tex code... I don't know enough about that to understand why).

**Comment by ychin** [comment]
> I see, thanks for the response! For now, is there a way to get macvim to just show the characters overlapping, rather than clip them (that is, to get the same behaviour as in terminal vim, in my second screenshot)?

No, not for now until the pull request I mentioned above gets merged.

> because it doesn't work for the glyphs which are put there by tex-conceal (it seems it only works for glyphs that are typed in as unicode characters, not ones that are displayed to 'conceal' tex code... I don't know enough about that to understand why).

Examples? I think it should work regardless how the text gets there. If you are using Terminal Vim for example, you can shift-select to select the raw text and paste it here.

**Comment by postylem** [comment]
Ah it does work, I was messing up the syntax. Thanks! 
There's still a small difference betwen the characters that show up because of tex-conceal, and the characters that are entered directly, when there is a newline after (see below).
I'll continue to work with this for now, setting a list of characters to display as double width as I need.

---

For reference: 
To make both 𝓟 (0x1d4d0) and 𝓐 (0x1d4df) be double-wide, I call
`:call setcellwidths([[0x1d4d0, 0x1d4d0, 2], [0x1d4df, 0x1d4df, 2]])`

This is before: 
<img width="359" alt="Screen Shot 2020-10-19 at 10 32 02" src="https://user-images.githubusercontent.com/5202957/96465647-30e76f00-11f7-11eb-92bc-ee93354107c7.png">
As you can see,
- glyphs displayed by tex-conceal show clipping if followed by a ascii character or newline, and overlap if followed by another conceal-replaced glyph
- glyphs which were directly entered to the file are only clipped by newline

and this is after calling setcellwidths for those two unicode codepoints
<img width="364" alt="Screen Shot 2020-10-19 at 10 31 33" src="https://user-images.githubusercontent.com/5202957/96465656-347af600-11f7-11eb-9d5b-2ab583e04623.png">

---

For comparison, this is what it looks like in terminal Vim (iTerm2).  No clipping ever, just overlap.
<img width="356" alt="Screen Shot 2020-10-19 at 10 18 10" src="https://user-images.githubusercontent.com/5202957/96466642-09dd6d00-11f8-11eb-8403-8b364a5dc335.png">

Note: if I call `:call setcellwidths([[0x1d4d0, 0x1d4d0, 2], [0x1d4df, 0x1d4df, 2]])` in terminal vim I get some odd things:
<img width="361" alt="Screen Shot 2020-10-19 at 10 48 34" src="https://user-images.githubusercontent.com/5202957/96467254-b9b2da80-11f8-11eb-8b26-1f4e7c7ae43b.png">
It seems not to be playing very well with

**Comment by ychin** [comment]
First, none of this has to do with conceal as I mentioned already, so just wanted to get this out of the way so we don't keep getting distracted with the red herring.

I think the terminal rendering with respect to `setcellwidths` seems a little buggy. Not sure if the bug is in Vim upstream or Terminal though. I am guessing upstream Vim because it's a new feature. It's not really MacVim-related so we should probably just discuss this in Vim's own issue tracker itself. Let's just use this issue to track clipping.

**Comment by postylem** [comment]
Sorry to be confusing. To clarify: the first two screenshots in my previous post were with macvim, and the second two were with terminal vim (iTerm2).  

The setcellwidth solution works for me.  But just to document clearly the behaviour I was decribing, for the benefit of anyone reading this later, here goes:

Here is a .tex document:
```latex
\documentclass[11pt]{standalone}
\usepackage{fontspec,mathrsfs}
\setmainfont{STIXGeneral-Regular}
\begin{document}
Unicode characters: 𝓟(Ω) 
                    𝓟₂ and 𝓟𝓐
                    𝓟 and 𝓐

Concealed latex   : $\mathscr{P}(\Omega)$
                    $\mathscr{P}_2$ and $\mathscr{P}\mathscr{A}$
		    $\mathscr{P}$ and $\mathscr{A}$
\end{document}
```
When I use macvim to edit this file, I see the following (with tex-conceal), where 
- underlying unicode wide characters overlap the next character unless it is a newline
- tex-conceal rendered wide characters are clipped when followed by an asci character or a newline, but not if followed by another non-ascii char (like ₂ or 𝓐).
 <img width="273" alt="Screen Shot 2020-10-22 at 12 45 31" src="https://user-images.githubusercontent.com/5202957/96903959-7b215800-1464-11eb-8164-fbc3aa0741ae.png">
and after running my cursor across the text:
<img width="279" alt="Screen Shot 2020-10-22 at 12 42 58" src="https://user-images.githubusercontent.com/5202957/96903706-2d0c5480-1464-11eb-935a-cebd9118499a.png">

Now, if I run `:call setcellwidths([[0x1d4d0, 0x1d4d0, 2], [0x1d4df, 0x1d4df, 2]])` to set the cellwidths to double for the two offending characters (U+1D4DF: MATHEMATICAL BOLD SCRIPT CAPITAL P, and U+1D4D0: MATHEMATICAL BOLD SCRIPT CAPITAL A), then I see
<img width="308" alt="Screen Shot 2020-10-22 at 12 30 00" src="https://user-images.githubusercontent.com/5202957/96903004-3a750f00-1463-11eb-8c8a-a403e9ff3076.png">
This is a workable fix for me.  I'll close the issue. Thank you.

There is still a question about why the unicode characters rendered from tex-conceal show a slightly different behaviour than the plain unicode characters, but I suppose that's due to something related to the fact that when I pass my cursor over the text the clipping shows up (I can't pass the cursor over the concealed text, because it becomes un-concealed when the cursor is on that line).
