### ISSUE TITLE
Support Python 3.9 (macOS + Homebrew)

### ISSUE THREAD

**Issue by itsayellow** [macvim-dev/macvim#1116]
**Describe the bug**
Homebrew has changed its default python3 to Python 3.9.  As such, on my system Macvim cannot find the Python3.8 library and python3 support is nonfunctional.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run macvim
2. execute `:py3 import os`
4. Macvim error is reported: 
```
E370: Could not load library /usr/local/Frameworks/Python.framework/Versions/3.8/Python
E263: Sorry, this command is disabled, the Python library could not be loaded.
```

In my shell, the only similar path that exists is for Python 3.9:
```
> ls /usr/local/Frameworks/Python.framework/Versions/          
3.9@     Current@
> ls /usr/local/Frameworks/Python.framework/Versions/3.9/Python
/usr/local/Frameworks/Python.framework/Versions/3.9/Python*
```
**Expected behavior**
Macvim is able to use Python 3.*

**Environment (please complete the following information):**
 - MacVim version 8.2.1719
 - OS: macOS 10.15.7

**Comment by cridemichel** [comment]
a temporary workaround is to install python@3.8 with homebrew and 
create a symbolic link as follows:
```bash
> cd /usr/local/Frameworks/Python.framework/Versions/
> ln -sf ../../../Cellar/python@3.8/3.8.6_1/Frameworks/Python.framework/Versions/3.8 3.8
> cd -
```
best C.

**Comment by radome** [comment]
> a temporary workaround is to install python@3.8 with homebrew and
> create a symbolic link as follows:
> 
> ```shell
> > cd /usr/local/Frameworks/Python.framework/Versions/
> > ln -sf ../../../Cellar/python@3.8/3.8.6_1/Frameworks/Python.framework/Versions/3.8 3.8
> > cd -
> ```
> 
> best C.

Nice, thanks. Small update: latest version on homebrew is `3.8.6_2`

**Comment by ychin** [comment]
CI was already updated to use 3.9 so the next release will look for the correct python libs. For now, you can manually do `set pythonthreedll=/usr/local/Frameworks/Python.framework/Versions/3.9/Python` to get it to work.

**Comment by ychin** [comment]
This should be fixed with the new release.
