### ISSUE TITLE
Initialisation exception while loading python3

### ISSUE THREAD

**Issue by eirnym** [macvim-dev/macvim#112]
I've tried to use official build `MacVim#80` (it includes https://github.com/vim/vim/commit/d94464ee294a351ce7b6ba18e8bd3f24f1bef920) with python3dll set like this in `~/.vimrc` file:

```
set pythondll=/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib
set python3dll=/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/libpython3.4.dylib
```
now command `python import sys` works well and loads correct dylib.
and command `python3 import sys` kills vim with exception:
```
Fatal Python error: Py_Initialize: unable to load the file system codec
ImportError: No module named 'encodings'
Vim: Caught deadly signal ABRT
Vim: Finished.
```

The most voted suggestion is unset or try to set correctly `PYTHONPATH` variable.

I've tried to set `PYTHONPATH` with no luck

**Comment by splhack** [comment]
Right. Snapshot 80 is binary compatible with these version only.

 - Lua 5.2
 - Perl 5.16
 - Python2 2.7
 - Python3 3.5
 - Ruby 2.0

You need to install Python 3.5.x, or you need to build MacVim by yourself.

**Comment by eirnym** [comment]
It doesn't work with 3.5 as well

**Comment by eirnym** [comment]
Output is same.

```
Fatal Python error: Py_Initialize: unable to load the file system codec
ImportError: No module named 'encodings'

Current thread 0x00007fff7b0c7000 (most recent call first):
Vim: Caught deadly signal ABRT
Vim: Finished.
```
