### ISSUE TITLE
New icon to match Big Sur's HIG

### ISSUE THREAD

**Issue by Ecco** [macvim-dev/macvim#1124]
**Describe the bug**
MacVim's icon doesn't comply with Big Sur's [new guidelines](https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/) regarding app icons.

**Expected behavior**
Comply with the guidelines. This way the app will fit better within macOS.

**Comment by ychin** [comment]
Did you mean the app icon for launching the app? It was recently added in #1054 already.

**Comment by Ecco** [comment]
Oh, yes indeed! Sweet!
