### ISSUE TITLE
Build fails on Tiger

### ISSUE THREAD

**Issue by chdiza** [macvim-dev/macvim#113]
Building has broken on Tiger.  I suspect that the recent change to `configure` that sets the Deployment Target based on what `uname` outputs has caused it.  I'll work on a firmer diagnosis.  Here's the error message:
```
ProcessPCH /Library/Caches/com.apple.Xcode.501/SharedPrecompiledHeaders/AppKit-cmkgzoukjtlmgkguorfuorbvxcpw/AppKit.h.gch /System/Library/Frameworks/AppKit.framework/Headers/AppKit.h normal ppc objective-c com.apple.compilers.gcc.4_0
    cd /bld/macvim/src/MacVim/PSMTabBarControl
    /Developer/usr/bin/gcc-4.0 -x objective-c-header -arch ppc -pipe -Wno-trigraphs -fpascal-strings -fasm-blocks -Os -Wreturn-type -Wunused-variable -fmessage-length=0 -mtune=G5 -mmacosx-version-min=10.4.11 -I/bld/macvim/src/MacVim/PSMTabBarControl/../build/PSMTabBarControl.build/Release/PSMTabBarControlFramework.build/PSMTabBarControl.hmap -F/bld/macvim/src/MacVim/PSMTabBarControl/../build/Release -I/bld/macvim/src/MacVim/PSMTabBarControl/../build/Release/include -I/bld/macvim/src/MacVim/PSMTabBarControl/../build/PSMTabBarControl.build/Release/PSMTabBarControlFramework.build/DerivedSources -c /System/Library/Frameworks/AppKit.framework/Headers/AppKit.h -o /Library/Caches/com.apple.Xcode.501/SharedPrecompiledHeaders/AppKit-cmkgzoukjtlmgkguorfuorbvxcpw/AppKit.h.gch
<built-in>:1: error: Unknown value ‘10.4.11’ of -mmacosx-version-min
** BUILD FAILED **
Makefile:2937: recipe for target 'macvim' failed
make[1]: *** [macvim] Error 1
make[1]: Leaving directory '/bld/macvim/src'
Makefile:26: recipe for target 'first' failed
make: *** [first] Error 2
```

I suspect that it should be either "10.4" or "10.4u", but am not sure which.

**Comment by chdiza** [comment]
Sorry, not `uname`, but `sw_vers`

**Comment by chdiza** [comment]
The `sw_vers` call includes the micro version number in the Deployment Target.  I suspect we need to trim it off.

**Comment by chdiza** [comment]
I've manually (in src/auto/configure) set it to "10.4u".  If that works, I'll work on `sed`-ing the micro version out and appending "u", like we already do in lines 4272-4274.

**Comment by splhack** [comment]
weird. anyway it should be "10.4" not "10.4u".
https://developer.apple.com/library/mac/documentation/DeveloperTools/Reference/XcodeBuildSettingRef/1-Build_Setting_Reference/build_setting_ref.html#//apple_ref/doc/uid/TP40003931-CH3-SW129

**Comment by chdiza** [comment]
Yeah, I discovered that after "10.4u" bombed.

OK, time to work on a sed script.  It may be tricky, because the very first release of every version of OS X is such that `sw_vers` returns "10.X" and not "10.X.0".  So I can't merely chop off the trailing ".X[X]"
