### ISSUE TITLE
Cannot use Chinese input method when I work under Rosetta

### ISSUE THREAD

**Issue by owner888** [macvim-dev/macvim#1142]
_Instructions: Replace the template text and remove irrelevant text (including this line)_

**Describe the bug**
(Issues related to the runtime files should be reported to their maintainer, check the file header.)

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `vim --clean` (or `gvim --clean`, etc.)
2. Edit `filename`
3. Type '....'
4. No error

**Expected behavior**

**Screenshots**
If applicable, copy/paste the text or add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/4317332/102232656-fa418280-3f21-11eb-948e-c2221236334a.png)

**Environment (please complete the following information):**
 - Vim version 8.2
 - OS: macOS 11.0
 - Terminal: GNU screen

**Additional context**

**Comment by ychin** [comment]
Hmm, what did you mean by "under Rosetta"? You are using the terminal right? Can you type Chinese when just typing in Terminal? What about using the system Vim (`/usr/bin/vim`)? What about in the GUI mode? Also, what input method and terminal are you using?

I just played around with it, and seems like I could enter Chinese when using MacVim in Terminal using Pinyin:

<img width="517" alt="image" src="https://user-images.githubusercontent.com/1217449/102316406-b606b000-3f2a-11eb-8df0-66e36c82eecb.png">

Wonder if it's a configuration problem.

**Comment by owner888** [comment]
thanks，when I reboot system, bug is fix

**Comment by ychin** [comment]
Oh cool. Glad to see it's fixed.
