### ISSUE TITLE
Problem Inserting Curly Quotes

### ISSUE THREAD

**Issue by firexcy** [macvim-dev/macvim#1151]
_Instructions: Replace the template text and remove irrelevant text (including this line)_

**Describe the bug**
macOS’s default key bindings for inserting curly quotes `“`, `”`, `‘`, and `’` (Option + (Shift + )`[`/`]`) is not working correctly.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Enter Insert Mode;
2. Press macOS’s default key binding for the left curly double quote `“` (Option + `[`);
3. The character `Û` is inserted instead of the expected `“`.

**Expected behavior**
The left curly double quote `“` is expected to be inserted as in other GUI macOS apps.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - Vim version 8.2
 - OS: macOS 11.1
 - Terminal: GUI

**Comment by ychin** [comment]
Do you have `set macmeta` on? If you do, the Option-<key> combo is not going to work and you have to turn it off.

I do want to fix this and deprecate `macmeta` in the future (probably part of #1052) but the work has not started yet.

**Comment by firexcy** [comment]
I do have `set macmeta` in my gvimrc. However, removing it and restarting MacVim doesn’t seem helpful.

**Comment by ychin** [comment]
Are you sure? Have you tried running MacVim with the `--clean` flag, or double check that `macmeta` is not set? You can do `:set macmeta?` to see the value.

**Comment by firexcy** [comment]
My bad, I forgot to remove `set macmeta` from a separate rc file sourced. Fixing that enables curly quotes input as expected. Thanks a lot for your patience.
