### ISSUE TITLE
How to change font size using the default font on macvim?

### ISSUE THREAD

**Issue by angarc** [macvim-dev/macvim#1160]
I really like the default font, but I don't like the default font size. However, I don't think i can change the font size without knowing the font

this code snippet does NOT work for me. I tried placing it in my .vimrc, but it didn't work
```
set guifont=:h18
```

I also tried placing that file in a .gvimrc, and that didn't work either.

lastly, I thought macvim used the same font as the terminal but that's not true because I compared the same file on two editors, one on the terminal and one on macvim, and the fonts are indeed different. 

How can I change the font size without changing the font? 

Thanks so much!

**Comment by ychin** [comment]
The default font is `Menlo-Regular`. Since by default MacVim sets the guifont to be empty, one easy trick to find out the font name is to use Cmd-= / Cmd-- to change the font size and then do `set guifont?` and it should show something like `guifont=Menlo-Regular:h12`.
