### ISSUE TITLE
macvim popup paste "+

### ISSUE THREAD

**Issue by cdddg** [macvim-dev/macvim#1161]
I use fzf, try to copy and paste in the vim popup window, In general terminals, as well as iterm2 work normally.
Only macvim I press `cmd+v` and only get "+

The following are my .vimrc
```
call plug#begin('~/.vim/plugged')
  Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
  Plug 'junegunn/fzf.vim'
call plug#end()
```

mac normal terminal
<img width="1440" alt="terminal" src="https://user-images.githubusercontent.com/39718445/103545700-e368cd00-4edc-11eb-968b-113c5dca2e07.png">

mac iterm2
<img width="1440" alt="iterm2" src="https://user-images.githubusercontent.com/39718445/103545663-d77d0b00-4edc-11eb-8fc5-0bdd62b25d57.png">

macvim
<img width="1440" alt="macvim" src="https://user-images.githubusercontent.com/39718445/103545676-dc41bf00-4edc-11eb-9c39-e4d19ac75b4c.png">

---

macvim: Custom Version 8.2.2164 (169)
macbook:  macOS Big Sur 11.1（20C69）

**Comment by cdddg** [comment]
This problem has been troubled for a long time, please help me

**Comment by cdddg** [comment]
I misunderstood, I think the problem should be in fzf [issue](https://github.com/junegunn/fzf.vim/issues/1176).

**Comment by ychin** [comment]
Yeah it's kind of an fzf issue. I do think MacVim could potentially provide a "paste literally" feature to paste in from the clipboard and apply it directly as the key input (this is basically what the terminal does), but I kind of hesitate to do it as it should only be useful in edge cases like this.
