### ISSUE TITLE
MacVim only renders text for short time when the Core Text renderer enabled

### ISSUE THREAD

**Issue by shenzhuxi** [macvim-dev/macvim#1174]
Since 169, MacVim on my MacBook Air (11-inch, Mid 2011) High Sierra only displayed text for a while then all the text disappeared when the Core Text renderer enabled. 

my MacBook Air (11-inch, Mid 2011) High Sierra
![GitHub Logo](https://user-images.githubusercontent.com/585720/104241005-e58ad880-5454-11eb-979c-2a3f27a687e0.png)

**Comment by ychin** [comment]
This is the same issue as #1164. Whenever you see this problem, can you follow instructions at https://github.com/macvim-dev/macvim/issues/1164#issuecomment-781639527 to capture logs and upload here? Make sure you have the latest version r170 first.

**Comment by ychin** [comment]
Also, what font do you use?

**Comment by ychin** [comment]
Closing as a dup of #1164. Please use that issue for tracking.
