### ISSUE TITLE
cannot type "ý" (czech keyboard)

### ISSUE THREAD

**Issue by Duuuscha** [macvim-dev/macvim#1180]
**Describe the bug**
I have a problem with typing character `ý` on czech keyboard. **It does work in nvim**, but **not in macvim** (neither **vim**). [This](https://stackoverflow.com/questions/48895362/the-ý-character-in-insert-mode-isnt-printed) is only discussion that I have found about this problem.  It works when loading clean vim (`vim --clean` (or `gvim --clean`), `[g]vim -u NONE`), but how can I make it work with my config. 

**To Reproduce**
Detailed steps to reproduce the behavior:
1. set czech keaboard QWERTZ macintosh
2. open vim/mvim at new file
3. Type "ý" in insert mode (at key number 7)

**Expected behavior**
When I press "ý", it should also be written in text.

**Screenshots**
![Keyboard_layout_Czech](http://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Keyboard_layout_Czech.svg/420px-Keyboard_layout_Czech.svg.png)

**Environment (please complete the following information):**
 - VIM - Vi IMproved 8.2
 - OS: [ macOS 10.15.7]
 - Terminal: [iTerm2]

**Additional context**
.vimrc
```
set nocompatible             " be iMproved, required
filetype plugin on             " required

call plug#begin('~/.vim/plugged')

Plug 'sirver/ultisnips' | Plug 'honza/vim-snippets'
    let g:UltiSnipsExpandTrigger = '<tab>'
    let g:UltiSnipsJumpForwardTrigger = '<tab>'
    let g:UltiSnipsJumpBackwardTrigger = '<s-tab>'
Plug 'lervag/vimtex'
    let g:tex_flavor='latex'
    let g:vimtex_view_method='skim'
    let g:vimtex_quickfix_mode=0
Plug 'KeitaNakamura/tex-conceal.vim'
    set conceallevel=1
    let g:tex_conceal='abdmg'
    "hi Conceal ctermbg=none

Plug 'vimwiki/vimwiki'
	let g:vimwiki_list = [{'path': '~/vimwiki/',
                      \ 'syntax': 'markdown', 'ext': '.md'}]

Plug 'itchyny/lightline.vim'

Plug 'altercation/vim-colors-solarized'

Plug 'plasticboy/vim-markdown'
    let g:vim_markdown_folding_disabled = 1

Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app && yarn install'  }

Plug 'vim-pandoc/vim-pandoc'
Plug 'vim-pandoc/vim-pandoc-syntax'
Plug 'vim-pandoc/vim-pandoc-after'

Plug 'sheerun/vim-polyglot'

Plug 'jiangmiao/auto-pairs'

Plug 'tpope/vim-surround'

Plug 'mhinz/vim-startify'
	let g:startify_custom_header = []
	
call plug#end()

if has("gui_running")
    colo solarized
	"highlight Normal guibg=#2E3440 guifg=#E5E9F0  
    set guicursor=n-v-c:block-Cursor/lCursor,ve:ver35-Cursor,o:hor50-Cursor,i-ci:ver25-Cursor/lCursor,r-cr:hor20-Cursor/lCursor,sm:block-Cursor-blinkwait175-blinkoff150-blinkon175
else
    colo solarized
endif
set background=dark

inoremap <C-f> <Esc>: silent exec '.!inkscape-figures create "'.getline('.').'" "'.b:vimtex.root.'/figures/"'<CR><CR>:w<CR>
nnoremap <C-f> : silent exec '!inkscape-figures edit "'.b:vimtex.root.'/figures/" > /dev/null 2>&1 &'<CR><CR>:redraw!<CR>
nnoremap <C-s>:   ! for FILE in ./figures/*.svg; do inkscape -D $FILE  -o .pdf --export-latex; done

hi clear Coceal

set guifont=Menlo-Regular:h18
set hlsearch
set incsearch
set ignorecase
set smartcase
set number
set relativenumber
"set wrap
set linebreak 
set nolist
set laststatus=2
set cmdheight=2
set noet ci pi sts=0 sw=4 ts=4
set nofoldenable
set mouse=a


augroup pandoc_syntax
  autocmd! FileType vimwiki set syntax=vimwiki.pandoc
augroup END

```

**Comment by eirnym** [comment]
actually both Czech keyboard layouts don't work with exactly this key

This letter can't be inserted with Polish keyboard as well, but can be pasted in

**Comment by eirnym** [comment]
@Duuuscha I've done some testing on my side for my list of plugins, and found that `jiangmiao/auto-pairs` blocks this letter completely to be inputted.

Could you write to them and link back to this issue if someone be interested in?

**Comment by eirnym** [comment]
and yes, they have already this issue: https://github.com/jiangmiao/auto-pairs/issues/317

**Comment by Duuuscha** [comment]
Thank you for mentioning the other issue at `auto-pairs` will follow it there.

**Comment by ychin** [comment]
Thanks for debugging this @eirnym!
