### ISSUE TITLE
brew install conflict

### ISSUE THREAD

**Issue by Amparose** [macvim-dev/macvim#1185]
**Describe the bug**
`brew` installing MacVim when Vim has been previously installed by `brew` results in a conflict:

```bash
Error: Cannot install macvim because conflicting formulae are installed.
  vim: because vim and macvim both install vi* binaries

Please `brew unlink vim` before continuing.
```

Unlinking and installing MacVim reverts Vim back to system version. Forcing the link back to Vim makes MacVim use the system version not the updated `brew` version.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. `brew install vim`
2. `brew install MacVim`

**Expected behavior**
Latest Vim is installed and MacVim using it.

**Environment (please complete the following information):**
 - Vim version (brew) 8.2.2725 and system Vim 8.2.2681
 - MacOS 11.2.3
 - Terminal: iTerm2

**Comment by ychin** [comment]
This is not a bug. As above comment mentioned, the `macvim` formula provides a Vim binary as well. It allows you to do something like `:gui` to go from terminal to GUI Vim. You really just need `brew install macvim` and that should be enough. If you do want the vanilla Vim, you can just use `brew unlink` as Homebrew instructs.
