### ISSUE TITLE
Keyboard navigation with tab key broken in Big Sur?

### ISSUE THREAD

**Issue by andrewplummer** [macvim-dev/macvim#1186]
After upgrading to Big Sur, keyboard navigation of native dialogs appears to be broken as far as I can tell. An example of these dialogs appears if you edit a file in another editor while open in MacVim:

<img width="280" alt="Screen Shot 2021-04-14 at 4 48 57 PM" src="https://user-images.githubusercontent.com/74646/114674156-e841e600-9d41-11eb-862e-6c311b383d80.png">

I have confirmed that `Preferences > Keyboard > Shortcuts > Use Keyboard Navigation` is enabled
I haven't seen this happen in any other app after updating.

OSX Version: 11.2.3
MacVim Version: 8.2.2681 (171)

**Comment by ychin** [comment]
It seems to work for me. (I could press "Tab", and then space bar to confirm) What doesn't work for you? As in, what key sequences are you expecting to work but doesn't?

**Comment by andrewplummer** [comment]
Very interesting. The tab key wasn't working at all (no blue outline focus change). However turning the setting off and on and doing a full restart seemed to fix the issue. Also note that I had Karabiner installed but disabled it to debug. Not impossible it was causing interference.. At any rate hopefully this can at least be useful to someone experiencing the same issue.
