### ISSUE TITLE
Pseudocrashes

### ISSUE THREAD

**Issue by chdiza** [macvim-dev/macvim#119]
To reproduce:  Open a new MacVim window.  Hit `ione two three`.  Hit Cmd-S.  Type "foo" to name the file.  Hit "return".

Observe that MacVim pseudocrashes immediately.  There is no crash report, but the Console says:
```
Nov  6 03:45:11 diza MacVim[17338]: Metadata.framework [Error]: void _MDItemMarkAsUsedForPath(CFStringRef): was called with a NULL path
Nov  6 03:45:11 diza Vim[27638]: -[MMBackend(Private) connectionDidDie:]@2329: Main connection was lost before process had a chance to terminate; preserving swap files.
```

I keep getting things like that in all kinds of context that all seem to revolve around non-existent files or unreadable files.

For example, at the terminal, `mvim foo` where "foo" is not the name of any file in the current working dir, will produce a pseudocrash like this.

**Comment by splhack** [comment]
why did you create the new issue?? It seems the exactly same as https://github.com/macvim-dev/macvim/issues/61. could you merge this issue to #61 and close this issue?

**Comment by chdiza** [comment]
I made a new one because there is a new element, namely, the save dialog.  But you're right, I should've added it to #61.
