### ISSUE TITLE
Fails to run and install under Big Sur 11.4

### ISSUE THREAD

**Issue by ssdowd** [macvim-dev/macvim#1196]
**Describe the bug**
Macvim fails to run after updating M1 mac to 11.4.

**To Reproduce**
1. Update to 11.4
2. Attempt run vim
3. dyld: Library not loaded: /System/Library/Perl/5.28/darwin-thread-multi-2level/CORE/libperl.dylib
  Referenced from: /usr/local/Cellar/macvim/8.2-171/MacVim.app/Contents/MacOS/Vim
  Reason: image not found

**Expected behavior**
I expected vim to run.

**Screenshots**
See step 3 above.

**Environment (please complete the following information):**
 - Vim version 8.2-171
 - OS: macOS 11.4
 - Terminal: iTerm2

**Additional context**
installed via brew.  attempted to reinstall, which fails.  Note: 11.4 does not contain a /System/Library/Perl/5.28.  It appears to have been replaced by 5.30.  After reinstalling Xcode, a `brew reinstall ruby` results in this:

`MacVim.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 11.4, but the range of supported deployment target versions is 10.9 to 11.3.99. (in target 'MacVim' from project 'MacVim')`

**Comment by juicejuice** [comment]
Exactly the same here, on an Intel Macbook 16" (2019) with Big Sur 11.4 using system-provided Perl. Due to MacOS [protections](https://support.apple.com/en-us/HT204899) you can't just symlink system Perl 5.30->5.28 either.

**Comment by ichizok** [comment]
There are several solutions;

* Replace brew's macvim by [GitHub release](https://github.com/macvim-dev/macvim/releases/download/snapshot-171/MacVim.dmg)
* Reinstall with `--build-from-source` (or `-s`) option: `brew reinstall -s macvim`
* Wait for the brew bottle rebuilt, and then upgrade

**Comment by juicejuice** [comment]
Thanks! I would note that the -s option (build from source) requires full Xcode installation too.

**Comment by ssdowd** [comment]
Thanks - that works. (Still has security warning: "MacVim" was blocked from use because it is not from an identified developer.)

**Comment by ReekyStive** [comment]
Thanks! Fixed with `brew reinstall -s macvim`
