### ISSUE TITLE
OS X 10.10 (Yosemite) + MacVim + vim-airline + fullscreen = blank space where airline should be

### ISSUE THREAD

**Issue by douglasdrumond** [macvim-dev/macvim#12]
_From @GoogleCodeExporter on March 16, 2015 9:25_

```
What steps will reproduce the problem?
Under OS X 10.10:

1. Build MacVim with homebrew
2. Install vundler and use vunder to install vim-airline.
3. Now when you run MacVim, you should see the airline header just fine until 
you go into fullscreen mode with the MacVim window, at which point the header 
line is blacked out.


What is the expected output? What do you see instead?
Expected: Airline header should be visible in fullscreen mode (this worked 
correctly in Mavericks)
Instead: see attached screen shot

What version of MacVim and OS X are you using (see "MacVim->About MacVim"
and  "Apple Menu->About This Mac" menu items, e.g. "Snapshot 40, 10.5.6
Intel")?

MacVim: Custom Version 7.4 (73)
OS X: Yosemite Beta 10.10, version 3

```

Original issue reported on code.google.com by `n.harris...@gmail.com` on 22 Sep 2014 at 1:47

Attachments:
* [macvim_bug.png](https://storage.googleapis.com/google-code-attachments/macvim/issue-512/comment-0/macvim_bug.png)

_Copied from original issue: douglasdrumond/macvim#512_

**Comment by douglasdrumond** [comment]
_From @GoogleCodeExporter on March 16, 2015 9:25_

```
Following up with some more info:

If I open a new tab with :tabnew, this forces airline to redraw and suddenly it 
appears again. I still think this is a MacVim / Yosemite issue (since this 
didn't happen with Mavericks), but there is a workaround.
```

Original comment by `n.harris...@gmail.com` on 24 Sep 2014 at 6:04

**Comment by douglasdrumond** [comment]
_From @GoogleCodeExporter on March 16, 2015 9:25_

```
This happens without airline, too. The first line of the file is missing, which 
makes editing pretty annoying. Same diagnostics as n.harris. Willing to do any 
texting/experimenting for more information.

Thanks!
```

Original comment by `jax...@gmail.com` on 3 Oct 2014 at 9:14

**Comment by douglasdrumond** [comment]
_From @GoogleCodeExporter on March 16, 2015 9:25_

```
Yes I noticed this in each public beta of Yosemite (10.10). The problem repros 
with a vanilla vim config. FWIW, VimR -- if I understand correctly, it uses 
some kind of macvim framework -- doesn't have this problem.
```

Original comment by `matt.saw...@gmail.com` on 7 Oct 2014 at 6:56

**Comment by douglasdrumond** [comment]
_From @GoogleCodeExporter on March 16, 2015 9:25_

```
any solution in view? 
```

Original comment by `bchesn...@gmail.com` on 18 Oct 2014 at 6:34

**Comment by douglasdrumond** [comment]
_From @GoogleCodeExporter on March 16, 2015 9:25_

```
:tabnew does not work for me unfortunately. I can however temporarily fix the 
issue by changing 'lines' to 999. From the manual:

    You can use this command to get the tallest window possible:
       :set lines=999

Note that you will have to enter that every time you switch between windowed 
and fullscreen mode. Unfortunately it does not seem possible to really automate 
this.

```

Original comment by `florian....@gmail.com` on 18 Oct 2014 at 11:53

**Comment by douglasdrumond** [comment]
_From @GoogleCodeExporter on March 16, 2015 9:25_

```
I have same problem on Yosemite, both :tabnew or :set lines=999 work as 
workaround, but have to do it on every switch
```

Original comment by `danijel....@gmail.com` on 18 Oct 2014 at 1:45

**Comment by douglasdrumond** [comment]
_From @GoogleCodeExporter on March 16, 2015 9:25_

```
Is anyone going to fix this issue. This is very annoying!
```

Original comment by `vinit.ku...@changer.nl` on 27 Oct 2014 at 6:15

**Comment by douglasdrumond** [comment]
_From @GoogleCodeExporter on March 16, 2015 9:25_

```
As a workaround you can decrease/increase the font size and the bar will appear.
```

Original comment by `agonzale...@gmail.com` on 2 Nov 2014 at 11:47

**Comment by douglasdrumond** [comment]
_From @GoogleCodeExporter on March 16, 2015 9:25_

```
This is very annoying. Every time I start vim and i have to increase or 
decrease the font size.
Kindly fix this issue asap (Macvim + yosemite)
```

Original comment by `abhinand...@gmail.com` on 6 Nov 2014 at 5:42

**Comment by douglasdrumond** [comment]
_From @GoogleCodeExporter on March 16, 2015 9:25_

```
I'm experiencing the problems mentioned above, and in addition to that, I also 
get the same line rendered numerous times (see attachment)

This only happens in fullscreen mode, windowed mode works fine.
```

Original comment by `alexge...@hotmail.com` on 9 Nov 2014 at 11:14

Attachments:
* [Screen Shot 2014-11-09 at 23.11.43.png](https://storage.googleapis.com/google-code-attachments/macvim/issue-512/comment-10/Screen Shot 2014-11-09 at 23.11.43.png)

**Comment by douglasdrumond** [comment]
_From @GoogleCodeExporter on March 16, 2015 9:25_

```
+1 here.. for both the missing line at the top and the multiple repeated lines 
on the body when I scroll
```

Original comment by `apierre....@gmail.com` on 12 Nov 2014 at 2:06

**Comment by douglasdrumond** [comment]
_From @GoogleCodeExporter on March 16, 2015 9:25_

```
I have this problem too in Yosemite,
```

Original comment by `michael....@googlemail.com` on 12 Nov 2014 at 12:49

**Comment by douglasdrumond** [comment]
_From @GoogleCodeExporter on March 16, 2015 9:25_

```
I have the missing line problem. Using a config from skwp's dotfile repo 
"yadr".  Thanks "agonzale...@gmail.com" for the font size workaround, saved me 
hours of switching to a new editor. Still annoying to have an extra step after 
fullscreen, but usable until we get a real fix.

Current Process (workaround):
[Command] + [Control] + [F]
[Command] + [-]
[Command] + [=]

Desired Process:
[Command] + [Control] + [F]

```

Original comment by `tekempe...@gmail.com` on 16 Nov 2014 at 7:30

**Comment by douglasdrumond** [comment]
_From @GoogleCodeExporter on March 16, 2015 9:25_

```
#13

This is a good way.
```

Original comment by `hkf...@gmail.com` on 30 Dec 2014 at 7:25

**Comment by douglasdrumond** [comment]
_From @GoogleCodeExporter on March 16, 2015 9:25_

```
This mapping works well for me.

nnoremap <silent> <F5> :set lines=999 columns=999<CR>
```

Original comment by `E.C.Bald...@gmail.com` on 9 Jan 2015 at 5:12

**Comment by douglasdrumond** [comment]
_From @GoogleCodeExporter on March 16, 2015 9:25_

```
Also experienced this, but an easy quickfix is to simply turn of the native 
fullscreen support (cmd+, for preferences and then remove the checkmark under 
advanced). 

It does mean that macvim will occupy the active space instead of creating a new 
fullscreen one, but i find that a minor problem
```

Original comment by `a...@jillion.dk` on 10 Feb 2015 at 8:24

**Comment by douglasdrumond** [comment]
_From @GoogleCodeExporter on March 16, 2015 9:25_

```
I found a fix from 
http://shorts.jeffkreeftmeijer.com/2014/full-screen-macvim-on-yosemite/
It works with me.
```

Original comment by `ddu...@gmail.com` on 16 Feb 2015 at 10:45

**Comment by jpetrie** [comment]
This appears to be the same issue as reported in PR #8, which has a proposed fix.

**Comment by douglasdrumond** [comment]
Closing as duplicate of #8
