### ISSUE TITLE
Strange character visible in a term session

### ISSUE THREAD

**Issue by amadeus** [macvim-dev/macvim#1203]
**Describe the bug**
![CleanShot 2021-08-03 at 18 00 37](https://user-images.githubusercontent.com/83376/128105287-10b0a2dc-5327-4cee-a983-cd576e47fd5c.png)

The best way to describe this bug is using the screenshot above - I am comparing terminal sessions between iTerm and a terminal buffer in MacVim - and I am noticing MacVim display a sort of odd V like character

I am unsure if this is a MacVim bug, a Vim bug, or something with regards to my terminal settings?

**Expected behavior**
My expected behavior is that my MacVim terminal session would look identical to an iTerm session

**Environment (please complete the following information):**
 - MacVim version 8.2 patches 1-3273
 - OS: macOS 11.5

**Additional context**
This is not a new issue, I think it's been around since terminal sessions were introduced, just never got around to reporting it.

**Comment by eirnym** [comment]
Hey, Thank you for an issue

Could you please check in a clean MacVim and Vim provided by a MacVim package just to make sure where the issue is. 

Also I'm not sure what is a term session you're referring to.

**Comment by amadeus** [comment]
I’ll double check a clean macvim shortly, but when I say terminal session - I mean just launching a new window in terminal or running `:term` in macvim

**Comment by amadeus** [comment]
I can confirm - using MacVim downloaded from releases, along with out any vimrc/plugins/configuration, does the same thing: 

<img width="862" alt="CleanShot 2021-08-04 at 12 45 29" src="https://user-images.githubusercontent.com/83376/128245196-84fbb5af-c34d-4725-b7f7-530f6f4f8d0a.png">

**Comment by eirnym** [comment]
So both in-term Vim and :term are affected, yes?

Could you check "pure" vim from Homebrew/MacPorts/macOS? Apple Terminal.app?

Could you also share your shell config?

**Comment by amadeus** [comment]
My shell config is: https://github.com/amadeus/prezto

In normal terminal - I do not get a V character with my shell config.

If I launch vim in terminal, then start a term session, I see the V character there as well

**Comment by amadeus** [comment]
I'm guessing, it's some sort of layout character that in Vim, isn't processed properly by the terminal code, so may not be something macvim can fix?

**Comment by eirnym** [comment]
Hi, 

I'm sorry for a delay response

I've played a bit with your ZSH configuration and I see this **V**-like symbol in many cases and it's even featured in a screenshot of the configuration 

I personally prefer self-made configuration as it does load only what I really want and don't spam with aliases and it is relatively fast. I can share if you'd like to.

**Comment by amadeus** [comment]
Gonna close this for now - it's a character that apparently has some meaning with my terminal, so probs just need to figure out what that is.
