### ISSUE TITLE
Interesting Cursor Position Bug

### ISSUE THREAD

**Issue by amadeus** [macvim-dev/macvim#1207]
**Describe the bug**
When using vim fugitive to make commits or push, the cursor seems to jump around - it's almost like a strange rendering artifact. I've attached a video:

**To Reproduce**
Detailed steps to reproduce the behavior:
It is the result of a plugin [vim fugitive](https://github.com/tpope/vim-fugitive) - but not sure how to replicate without it, I imagine this shouldn't be related to the plugin itself, but perhaps an issue with echon or something?

**Expected behavior**
I expect the cursor to not move around and end up not where it should be? You'll notice it's as if it's position is lost. Once I try to move the cursor, it returns to it's original position

**Screenshots**

https://user-images.githubusercontent.com/83376/133538735-19fee545-500e-463d-addd-3d13df98904c.mp4

**Environment (please complete the following information):**
 - Vim version 8.2, patches: 1-3423
 - OS: macOS 11.6

**Comment by amadeus** [comment]
shoot, forgot to fill this out correctly, continuing to edit, sorry

**Comment by eirnym** [comment]
I found it a bit laggy lately on my arch Linux box.  I'll test it tomorrow again

**Comment by amadeus** [comment]
Did a bit more digging, looks like it also can re-pro in normal Vim https://github.com/matsui54/ddc-buffer/issues/8

I think overall, there is probably some deeper vim bug around reacting to BufReadPost, but it seems like too much work for me to try and find a repro case for, so I did figure out a workaround within that plugin
