### ISSUE TITLE
Initialisation exception while loading python3.5

### ISSUE THREAD

**Issue by eirnym** [macvim-dev/macvim#121]
I've tried to use official build `MacVim#81` with python3dll set like this in `~/.vimrc` file:

```
set pythondll=/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib
set python3dll=/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/libpython3.5.dylib
```
now command `python import sys` works well and loads correct dylib.
and command `python3 import sys` kills current `Vim` with exception:
```
Fatal Python error: Py_Initialize: unable to load the file system codec
ImportError: No module named 'encodings'

Current thread 0x00007fff7b0c7000 (most recent call first):
Vim: Caught deadly signal ABRT
Vim: Finished.```

The most voted suggestion is unset or try to set correctly `PYTHONPATH` variable.

I've tried to set `PYTHONPATH` with no luck

**Comment by splhack** [comment]
For example, the Python 3.5.0 binary distribution https://www.python.org/downloads/, you should set the environment variable like this. The path is vary by Python environment.

    let $PYTHONPATH='/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5'

**Comment by eirnym** [comment]
It doesn't work. And you better close issue than discuss it. it's bad sign

**Comment by splhack** [comment]
Well, MacVim binary snapshot can't support each single unique Python environment. So, If still no luck, you should install https://www.python.org/downloads/, or use Homebrew to install python3, or build MacVim by yourself.
