### ISSUE TITLE
Dropping multiple files into MacVim causes it to crash

### ISSUE THREAD

**Issue by limintang** [macvim-dev/macvim#1227]
### Steps to reproduce

1. Pull the source repo from patch 8.2.4040 or later
2. Build MacVim
3. Open MacVim
4. Select multiple files and drop them together into MacVim
5. MacVim window disappears (crashes)

### Expected behaviour

MacVim opened all dropped files.

Issue can be fixed with the following patch:
[patch.txt](https://github.com/macvim-dev/macvim/files/7902583/patch.txt)
 

### Version of Vim

8.2.4040

### Environment

MacOS Catalina 10.15.7

**Comment by eirnym** [comment]
@limintang thank you for an issue. Can you open PR instead?

**Comment by limintang** [comment]
> @limintang thank you for an issue. Can you open PR instead?

Just opened a PR.
