### ISSUE TITLE
Error trying to build (missing terminal library?)

### ISSUE THREAD

**Issue by jordwalke** [macvim-dev/macvim#123]
Why do I get this error on Yosemite? I followed the compilation instructions.

```
no terminal library found
checking for tgetent()... configure: error: NOT FOUND!
      You need to install a terminal library; for example ncurses.
      Or specify the name of the library with --with-tlib.
```

**Comment by jordwalke** [comment]
The solution, as someone reported here, is to run in a clean bash environment - I have no idea what could be interfering:

https://github.com/qvacua/vimr/issues/13

**Comment by jordwalke** [comment]
So I discovered what was causing this. Building Webkit tells you to add this to your bashrc:

```
export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
```

But this causes the terminal library to not be found. Why is this?

**Comment by splhack** [comment]
turned out it's the configure script issue.
https://github.com/vim/vim/pull/482

**Comment by splhack** [comment]
Fixed in https://github.com/macvim-dev/macvim/commit/32d03b34ac8a34a962f57847fc431a2b4e14efea.
