### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by leungbk** [macvim-dev/macvim#1235]
It's been some months since the last release, and some nice commits have been made since then. It would be great if we could get an updated snapshot.

**Comment by halostatue** [comment]
A release would be very useful, as sheerun/vim-polyglot#779 points out. It imported new mainline vim files (specifically ft.vim at vim/vim@a2baa73d1d33014adea0fd9567949089ca21a782) and it fails to run in the currently released version of MacVim 8.2 (patch 3455). I have a fix in at sheerun/vim-polyglot#780, but it is not clear to me whether this will be accepted as it is changing an upstream file.

**Comment by ychin** [comment]
Sorry I have been away from MacVim development for a while which is not great. Let me catch up to see if there are glaring issues, and if not, make a release soon.

**Comment by lifepillar** [comment]
As I have started to use Vim9 scripts, MacVim has started to crash because of some bugs in Vim that have been fixed only recently. So, I am stuck using Vim in the terminal. I would really appreciate if a new MacVim release could be pushed forward!

**Comment by sigzero** [comment]
It was supposed to happen over the weekend. Maybe there were issues.

**Comment by eirnym** [comment]
@ychin is there anything we can help you with?

**Comment by sigzero** [comment]
A bunch of runtime files were merged so maybe that is an indication a new version will drop "soon".

**Comment by sigzero** [comment]
Vim9 is now out. Will MacVim update to it anytime soon?

**Comment by halostatue** [comment]
I would hope that a final release of MacVim with 8.2 would come out, and then work start on Vim 9 support.

**Comment by ychin** [comment]
Hi, I'm so sorry for the radio silence in recent months. life has been catching up to me and I was struggling to find time for MacVim, which is something I'm trying to correct and doesn't excuse the hold on the release.

One thing I'm trying to do is to do a more thorough validation of making sure one year's worth of Vim updates didn't break anything, but that's probably misguided compared to just pushing out a release. Can people who have been syncing and building MacVim give me a basic thumbs up/down on whether they see any glaring bugs that need to be addressed before I push out a Vi 9 release?

**Comment by denisw** [comment]
Thanks you @ychin! I built the latest `master` and gave it a spin. I noticed no issues. 👍

**Comment by stack** [comment]
I did a manual compile as of `286bd68d59d940dab45dbe9afe4dd77fa8810973` and so far so good. No glaring issues that I can see.

**Comment by eirnym** [comment]
@ychin we'd be happy to test! 

Manual tests seems to be working fine ;) push the pre-release if you worry about any additional issues

**Comment by sigzero** [comment]
Compiled it. I haven't found any issues so far for my normal usage.

**Comment by lifepillar** [comment]
Built the current master. I confirm that I don't get the crashes I used to get with Vim 9 script. Thanks!

**Comment by fs111** [comment]
@ychin I know this is probably annoying, but is there any ETA on when the vim9 release will be out?

Is there anything we can help with?

**Comment by ychin** [comment]
Sorry I got distracted a little trying to figure out why the colors looked so weird, and turned out Vim just had a large colorscheme update a couple months ago where they changed the default colorschemes which sidetracked me a little, as I thought there was some rendering issue. One of those things where a regular cadence would have really helped identify where these issues come in instead of having to bisect around.

I just pushed a tag to https://github.com/macvim-dev/macvim/releases/tag/snapshot-173, doing some final touches and then should be able to release it in a couple hours. Don't want to beat a dead horse but I know this infrequent release cadence and lack of activity is not ideal at all. I'm trying to catch up to the other stuff like outstanding bugs and PRs after the release.

**Comment by lifepillar** [comment]
>I got distracted a little trying to figure out why the colors looked so weird

In principle, the built-in color schemes should look better, especially in the GUI. If you think that they have some issue, could you please [provide some feedback](https://github.com/vim/colorschemes/issues)?

Btw, thanks for the huge effort you put in this project!

**Comment by RichardDooling** [comment]
Thank you so much. I'm just a writer, not a programmer, but I live in this program all day every day. THANKS

I'll wait for the brew version.

**Comment by nico** [comment]
Thank you for your work shipping new MacVim releases. Very appreciated :)
