### ISSUE TITLE
Build of main ae7aaf146 fails

### ISSUE THREAD

**Issue by al3xandru** [macvim-dev/macvim#1236]
### Steps to reproduce

```        
make clean
make distclean
rm -vf src/auto/config.cache
./configure --with-features=huge --enable-multibyte --enable-terminal --enable-cscope --enable-python3interp=dynamic  --enable-perlinterp=dynamic --enable-rubyinterp=dynamic --enable-luainterp=dynamic --with-lua-prefix=/opt/homebrew --with-macarchs=arm64 --disable-sparkle --with-compiledby="alex@$(date +%Y%m%d%H%M)/$(git rev-parse --short HEAD)" 
```

### Expected behaviour

Compilation to succeed.

### Version of Vim and architecture

Main branch ae7aaf146 on arm64

### Environment

macOS 12.2.1
arm64

### Logs and stack traces

```shell
gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -I/opt/homebrew/opt/ruby/include -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -arch arm64 -I/opt/homebrew/Cellar/libsodium/1.0.18_1/include -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/ex_cmds2.o ex_cmds2.c
ex_cmds.c:3742:10: error: use of undeclared identifier 'e_cannot_use_s_backslash_in_vim9_script'
                emsg(_(e_cannot_use_s_backslash_in_vim9_script));
                       ^
ex_cmds.c:5011:15: error: use of undeclared identifier 'e_pattern_found_in_every_line_str'
                    semsg(_(e_pattern_found_in_every_line_str), pat);
                            ^
2 errors generated.
```

### Issue has been tested with given configuration

- [ ] by running MacVim.app from GUI macOS interface
- [ ] by running vim/gvim/etc installed by MacVim
- [ ] by running other versions of vim (e.g. /usr/bin/vim)

### Issue has been tested with no configuration

- [ ] by running `mvim --clean` (or `gvim`, supplied by MacVim distribution)
- [ ] by running `vim --clean` (in terminal, supplied by MacVim distribution)
- [ ] by running `vim --clean` (in terminal, other suppliers, e.g. /usr/bin/vim)

### Other conditions

- [ ] The both Homebrew packages "vim" and "macvim" are installed

**Comment by eirnym** [comment]
This is a part of upstream code. If fix is already in the upstream, it needs to be merged

**Comment by al3xandru** [comment]
Upstream vim compiles successfully in the same env.

**Comment by ichizok** [comment]
Maybe the state of your repository is incorrect, please try `git reset --hard` and rebuild.

**Comment by al3xandru** [comment]
After pulling 656f26b5a, main build again.

**Comment by eirnym** [comment]
By the way, it always needs to be verified which exact commit has been merged into upstream. It's never "the latest commit". 

Merges are done manually as MacVim has numerous changes to the core to make some commands to work properly.
