### ISSUE TITLE
mistake in wiki page 'Building'

### ISSUE THREAD

**Issue by mzlogin** [macvim-dev/macvim#1239]
In section 'How to get the MacVim source code': https://github.com/macvim-dev/macvim/wiki/Building#how-to-get-the-macvim-source-code

```sh
$ git clone git://github.com/macvim-dev/macvim.git
```

should be

```sh
$ git clone git@github.com:macvim-dev/macvim.git
```

or some error may occurs:

> The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.

**Comment by eirnym** [comment]
Hi @mzlogin

Nice catch! Could you make a PR to fix this issue?

**Comment by mzlogin** [comment]
Hi @eirnym 

I'd like to make a PR, but as I know, GitHub [doesn't support pull requests for the wiki repository](https://github.com/gollum/gollum/issues/265), only the main repository.

ref <https://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github> and <https://github.com/isaacs/github/issues/333>

**Comment by eirnym** [comment]
It's a shame that GitHub still not allow to fix wikis via PRs

**Comment by mzlogin** [comment]
I agree 😢 

So would you please fix it?

**Comment by ichizok** [comment]
Thank you, fixed it.
