### ISSUE TITLE
Getting warning 'You are opening the application “MacVim” for the first time' every time opening MacVim

### ISSUE THREAD

**Issue by Naitreey** [macvim-dev/macvim#1240]
### Steps to reproduce

I'm getting the warning dialogue every time opening a text file in Finder into MacVim app:
![CleanShot 2022-04-11 at 17 23 52](https://user-images.githubusercontent.com/10528297/162708733-d626d951-674f-4df1-9949-c5ab6a14c320.png)

Steps to reproduce:
1. Open Finder, find a text file.
2. Right click it and open it with MacVim.
3. macOS warning dialogue shows up.
4. Click "Open" the file will open in MacVim.
5. Quit MacVim completely with <kbd>cmd</kbd>+<kbd>q</kbd>.
6. Repeat, the warning dialogue shows up again.
 
But I won't get the warning if I open the file in terminal with `gvim` command.

### Expected behaviour

The warning dialogue should show up only for the first time launching MacVim, not every time.

### Version of Vim and architecture

8.2.3455, GUI, x86_64

### Environment

Monterey, x86_64, iTerm2, xterm-256color, bash 5.1.16(1)-release

### How MacVim was installed

Homebrew

### Issue has been tested with given configuration

- [X] by running MacVim.app from GUI macOS interface
- [X] by running vim/gvim/etc installed by MacVim
- [ ] by running other versions of vim (e.g. /usr/bin/vim)

### Issue has been tested with no configuration

- [ ] by running `mvim --clean` (or `gvim`, supplied by MacVim distribution)
- [ ] by running `vim --clean` (in terminal, supplied by MacVim distribution)
- [ ] by running `vim --clean` (in terminal, other suppliers, e.g. /usr/bin/vim)

### Other conditions

- [ ] The both Homebrew packages "vim" and "macvim" are installed

**Comment by ychin** [comment]
Closing issue. As the above comment said, I don't think MacVim is doing anything weird here. Can reopen if that doesn't fix the issue.
