### ISSUE TITLE
Feature Request: Enable Quicklook for MacVim filetypes

### ISSUE THREAD

**Issue by themightyoarfish** [macvim-dev/macvim#126]
When MacVim is configured as the `Open With`-App for a text file (e.g. `.h` or `.cpp`), quicklooking at the files will not work. I don't know much about it, but from what I've read this is because MacVim does not have the appropriate qlGenerator plugins and OSX does not fall back to the default ones. This is quite annoying. Is there a way to make this work? For me it is somewhat essential for a seamless integration with OSX.

See also: https://apple.stackexchange.com/questions/206905/quicklook-does-not-preview-txt-files

**Comment by eshansingh** [comment]
+1. It's really bad when the Quick look doesn't appear. When it does, it's without any synatx highlighting.

**Comment by eshansingh** [comment]
+1

**Comment by gavocanov** [comment]
+1

**Comment by elsonwu** [comment]
+1

**Comment by chdiza** [comment]
> When MacVim is configures as the Open With-App for a text file (e.g. .h or .cpp), quicklooking at the files will not work.

I don't see this.  I can quicklook all the filetypes I typically open with MacVim.

**Comment by splhack** [comment]
have you tried http://whomwah.github.io/qlstephen/ ? I'm thinking to add it into MacVim for quicklook of MacVim filetypes.

**Comment by splhack** [comment]
could you guys try #172?

**Comment by themightyoarfish** [comment]
@splhack I compiled the `features/quicklook` branch and it appears to work.

**Comment by splhack** [comment]
thank you for testing.
