### ISSUE TITLE
Checkbox for Smooth Scrolling doesn't completely show in Preferences

### ISSUE THREAD

**Issue by wbpayne22902** [macvim-dev/macvim#1281]
### Steps to reproduce

1. Clone the `macvim` repository and compile and run
2. Open the Preferences window
3. You will see that the sizing of the window is off and the checkbox is cut off at the bottom of the dialog.
<img width="595" alt="Screen Shot 2022-09-11 at 1 29 05 PM" src="https://user-images.githubusercontent.com/107161609/189541213-f72930fd-f565-440f-8ea3-76a7432ea46e.png">

### Expected behaviour

The checkbox should be completely visible

### Version of Vim and architecture

Macvim HEAD commit fcd7bd4 Vim version 9.0.420, GUI, arm64

### Environment

Mac OS Monterey 12.5.1 arm64
Terminal not relevant as issue is with GUI mode.
zsh 5.8.1

### How MacVim was installed

Clone of repository from GitHub and manual build.

### Issue has been tested with given configuration

- [X] by running MacVim.app from GUI macOS interface
- [x] by running vim/gvim/etc installed by MacVim
- [x] by running other versions of vim (e.g. /usr/bin/vim)

### Issue has been tested with no configuration

- [x] by running `mvim --clean` (or `gvim`, supplied by MacVim distribution)
- [x] by running `vim --clean` (in terminal, supplied by MacVim distribution)
- [x] by running `vim --clean` (in terminal, other suppliers, e.g. /usr/bin/vim)

### Other conditions

- [ ] The both Homebrew packages "vim" and "macvim" are installed

**Comment by ychin** [comment]
Oh yeah I didn't test for the case where sparkle is disabled and the preference pane gets resized to adjust. Will fix.

**Comment by ychin** [comment]
Also, not to disappoint you this is "smooth resizing" , not "smooth scrolling". Smooth scrolling is not going to come for a while, and only if I could find a good way to do it in a stable fashion.

**Comment by wbpayne22902** [comment]
Sorry about that, I meant smooth resizing.  For some reason my brain thinks one thing and writes another. Also, sorry for neglecting to mention that I had Sparkle disabled.  Thanks for the fix, I've tested it and it works great.
