### ISSUE TITLE
Coarse MacVim version reporting in about, update checks and github releases

### ISSUE THREAD

**Issue by eirnym** [macvim-dev/macvim#1293]
### Steps to reproduce

1. Look on the about dialog box and it shows "Custom version 9.0.472 (174)`. close it
2. Open `Check for updates` menu. it shows "MacVim 9.0.472 is the newest version"
3. Check GitHub releases page, it shows "MacVim Release 174"

### Expected behaviour

I expect all sources show more or less the same text, e.g. "MacVim Release 9.0.472 (174)". This is required for a user to have a strong visual connection between versions seen in all of these sources

I do NOT expect that `:version` command is touched in any way.
I do NOT expect that HomeBrew/MacPorts versioning is touched in any way.

### Version of Vim and architecture

arm64

### Environment

Operating system: macOS Monterey 12.6
Terminal: GUI only

### How MacVim was installed

from GitHub releases to the default location

### Issue has been tested with given configuration

- [X] by running MacVim.app from GUI macOS interface
- [ ] by running vim/gvim/etc installed by MacVim
- [ ] by running other versions of vim (e.g. /usr/bin/vim)

### Issue has been tested with no configuration

- [X] by running `mvim --clean` (or `gvim`, supplied by MacVim distribution)
- [ ] by running `vim --clean` (in terminal, supplied by MacVim distribution)
- [ ] by running `vim --clean` (in terminal, other suppliers, e.g. /usr/bin/vim)

### Other conditions

- [ ] The both Homebrew packages "vim" and "macvim" are installed

**Comment by ychin** [comment]
Yeah this is a good point. We do see people getting confused about version numbers from time to time. For (2), the “check for updates” dialog box is controlled by Sparkle. I filed an issue to see if we can customize the display of it (https://github.com/sparkle-project/Sparkle/issues/2267), but in other places too we should be a little more consistent in how we present Vim version and MacVim release number.

**Comment by eirnym** [comment]
Thank you @ychin for the fast response to it, I'll monitor that issue as well
