### ISSUE TITLE
Option for disabling window shadows

### ISSUE THREAD

**Issue by VonbatenBach** [macvim-dev/macvim#1301]
Hi, I've been wondering if it would be possible to add an option in Preferences tab to additionally tweak appearance of the macvim windows. We already have options for transparent titlebars and removing them. It would be nice to have an option to disable default macOS shadows around edges of an active window. I don't know whether it is even possible, but these shadows are often irritating when we place a macvim window near a pdf viewer for instance. Sometimes it would be much better to have a "cleaner", more minimalistic appearance.

**Comment by eirnym** [comment]
StackOverflow recommends WinBuddy macforge plugin for removing shadows from windows

**Comment by VonbatenBach** [comment]
Yeah, the problem is that these projects (basically relying on MacForge) seem to be not developed anymore and they rely on changing parameters "externally". I've been wondering whether it is possible to change such properties of windows from the level of source code of a given app.

**Comment by eirnym** [comment]
The mentioned comment shows, that it set in iTerm2, but doesn't work

**Comment by eirnym** [comment]
Tested the latest iTerm2 on Monterey (12.6) and I see shadows having any option set.

**Comment by eirnym** [comment]
I'm not against the option, just I prefer not to have this option if it won't work.

**Comment by ychin** [comment]
Wow I have to say eventually for every single flag on an NSWindow there will be someone filing an issue requesting for it to be configurable haha.

> Tested the latest iTerm2 on Monterey (12.6) and I see shadows having any option set.
> I'm not against the option, just I prefer not to have this option if it won't work.

There is clearly a supported option to do this (https://developer.apple.com/documentation/appkit/nswindow/1419234-hasshadow?language=objc).

Those threads talking about using MacForge etc are talking about how to do this globally and disabling other apps' shadows. If the app voluntarily do this there shouldn't be an issue.

Let me think more about this but I don't see any reason why I wouldn't add it, as its impact is small. If nothing goes wrong this will probably go into the next release.

**Comment by VonbatenBach** [comment]
This would be great! :)

**Comment by eirnym** [comment]
@ychin Nevertheless, I'm unable do disable shadows on my macOS instance

**Comment by ychin** [comment]
> Nevertheless, I was unable do disable shadows on my macOS instance

Sure, but I think that's because you are trying to change another app's shadows, not an app voluntarily doing so. The OS is blocking the ability to modify another app's behavior, for bitter or worse. In this case we are voluntarily saying we don't want drop shadows which is fine and supported by the API. I just committed the option to do this, feel free to try it out.
