### ISSUE TITLE
Undercurl Appears As Dotted Line Instead of a Squiggle Line

### ISSUE THREAD

**Issue by tchau-mdsol** [macvim-dev/macvim#1309]
### Steps to reproduce

- install macvim from Homebrew `brew install --cask macvim`
- start macvim `mvim --clean`
- type `:hi spellbad` or `:hi spellcap`

![image](https://user-images.githubusercontent.com/91994213/194730627-f71a24c5-57aa-47f6-a058-314fc12d1f32.png)

### Expected behaviour

The undercurl beneath XXX should appear as a squiggle instead of a dotted line.  See the squiggling line underneath "mispelled" in the image below as an example.

![image](https://user-images.githubusercontent.com/91994213/194730567-10c69d01-cea1-4ced-89c3-aa0ed43e30de.png)

### Version of Vim and architecture

vim --version VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep 24 2021 14:13:28) macOS version - x86_64 Included patches: 1-3455 Compiled by GitHub Actions Huge version with MacVim GUI.

### Environment

$ sw_vers
ProductName:	macOS
ProductVersion:	12.6
BuildVersion:	21G115

### How MacVim was installed

brew install macvim

### Issue has been tested with given configuration

- [ ] by running MacVim.app from GUI macOS interface
- [ ] by running vim/gvim/etc installed by MacVim
- [ ] by running other versions of vim (e.g. /usr/bin/vim)

### Issue has been tested with no configuration

- [X] by running `mvim --clean` (or `gvim`, supplied by MacVim distribution)
- [ ] by running `vim --clean` (in terminal, supplied by MacVim distribution)
- [ ] by running `vim --clean` (in terminal, other suppliers, e.g. /usr/bin/vim)

### Other conditions

- [ ] The both Homebrew packages "vim" and "macvim" are installed

**Comment by tchau-mdsol** [comment]
Changing undercurls to
```
let &t_Cs="\e[4:3m"
let &t_Ce="\e[4:0m"
```
has no effect on mvim

**Comment by ychin** [comment]
The info you provided don’t seem to make sense to me. Your version info says it’s Vim 8.2 compiled in 2021, which is old. Also, it says that it’s compiled by GitHub Actions which means it’s the binary release we do. Meanwhile your description says you installed MacVim via Homebrew. Are you sure you don’t have two versions of MacVim running concurrently?

If you are, I personally recommend just using the binary release from us since it’s what I spend most of the time testing, but either one would use. I’m just suspecting you are using a stale version of MacVim.

**Comment by ychin** [comment]
Do you have the "Core Text renderer" set to off in the Advanced Preference? If so, was there a reason you set it? It pretty much has to be on to get the latest feature as setting it off is deprecated as the description suggests. It will be mandatory to be on in the next release.

> So, I originally installed the --cask version on HomeBrew, which pulled from this github repo, and it was outdated. Therefore, I retested the undercurl issue by installing with both `brew install --cask macvim` and `brew install macvim`.

On this part, just curious, why was it outdated? Did you turn off the updater?

**Comment by tchau-mdsol** [comment]
```Do you have the "Core Text renderer" set to off in the Advanced Preference? ```

That is a bingo!  Thank you so much.

```On this part, just curious, why was it outdated? Did you turn off the updater? ```

I don't upgrade my casks or shutdown my computer as often as I should.  😞

**Comment by ychin** [comment]
Cool, good to see it resolved.

> I don't upgrade my casks or shutdown my computer as often as I should. 😞

The cask version is just the binary release from https://github.com/macvim-dev/macvim/releases. It should check for new releases when you start MacVim, or manually check it in MacVim -> Check for Updates. I guess you may have turned auto-update off in Preferences in the app. In general Homebrew casks are designed to not require you to update it through Homebrew.
