### ISSUE TITLE
"After last window closes" setting ignored

### ISSUE THREAD

**Issue by GT-GH** [macvim-dev/macvim#1338]
The current version of MacVim (9.0.472) seems to be ignoring the setting for "After last window closes" when set to "Quit MacVim". After I quit all editor windows, MacVim remains open. I'm on a Mac M1 Max running Monterey 12.5.1, if it helps.

**Comment by ychin** [comment]
What are you other settings? In particular, what's your setting on "Open untitled window"? #1257 made a change so that you cannot have both "Open untitled window" = "never", and "After last window closes" = "Quit MacVim". If you think about these two settings they kind of don't make any sense.

**Comment by GT-GH** [comment]
You're right, that was the issue. Thank you!

Still, I don't think that change makes sense and I hope you consider rolling it back. These settings DO make sense together. The "Open untitled window" setting should only be checked on launch (and a new window opened if needed). The "After last window closes" setting should only be checked after at least one window had been actively closed by the user (i.e., not on launch).

I practically never need a new/blank document to open on launch, it only adds an unnecessary step to my process. On the other hand, I don't want a zombie process lingering after I'm done editing my last file.

**Comment by ychin** [comment]
Hmm, I see. I didn't think this was actually a real use case, but I can consider addressing it. It likely won't be a direct rollback since the previous implementation was buggy but I can try to make it only start to activate the "After last window closes" after the first window has showed up.

**Comment by GT-GH** [comment]
I appreciate it very much, and thank you also for providing this excellent editor on the Mac platform!

**Comment by ychin** [comment]
Ok #1339 will address. This should be part of the next release (r175) which I hope would be out soon-ish but some other issues are preventing it so working on those.
