### ISSUE TITLE
Clicking on "Download MacVim" button on website causes my browser to raise "This site can't be reached" error

### ISSUE THREAD

**Issue by todd-demone** [macvim-dev/macvim#1344]
### Steps to reproduce

1. Visit https://macvim-dev.github.io/macvim/
2. Click "Download MacVim"

### Expected behaviour

I expect  MacVim.dmg file to be downloaded to my computer

### Version of Vim and architecture

MacVim release = 174, architecture = arm64 (M1 Mac)

### Environment

macOS Ventura 13.0.1 
Brave browser

### How MacVim was installed

It hasn't been installed because I can't download it.

### Logs and stack traces

```shell
Browser output:

This site can’t be reachedobjects.githubusercontent.com’s DNS address could not be found. Diagnosing the problem.
DNS_PROBE_POSSIBLE
```

### Issue has been tested with given configuration

- [ ] by running MacVim.app from GUI macOS interface
- [ ] by running vim/gvim/etc installed by MacVim
- [ ] by running other versions of vim (e.g. /usr/bin/vim)

### Issue has been tested with no configuration

- [ ] by running `mvim --clean` (or `gvim`, supplied by MacVim distribution)
- [ ] by running `vim --clean` (in terminal, supplied by MacVim distribution)
- [ ] by running `vim --clean` (in terminal, other suppliers, e.g. /usr/bin/vim)

### Other conditions

- [ ] The both Homebrew packages "vim" and "macvim" are installed

**Comment by todd-demone** [comment]
The website download button seems to be working again. Thanks!

**Comment by ychin** [comment]
Yeah not sure what happened. Probably just a temporary GitHub DNS issue or something.
