### ISSUE TITLE
Printing problem with Custom Version 9.0.472 (174) on MacOS Ventura 13.0.1

### ISSUE THREAD

**Issue by MichaelHendry** [macvim-dev/macvim#1347]
### Steps to reproduce

Open a text file in MacVim
Print the file (using command-P or File->Print)

MacVim reports "Print job sent" and opens the Preview App, but the file is not opened in Preview. Clicking on the Preview icon in the Dock brings up an open file window.

### Expected behaviour

Up until the most recent Ventura update, the file would be opened in Preview. and could be printed with Command-P.

I suspect this may be the result of a tightening of security features in Mac OS, which may be preventing the creation of an intermediate file, or preventing its being opened by Preview.

### Version of Vim and architecture

Version 9.0.472 (174) 

### Environment

MacOS Ventura 13.0.1 Intel Processor on iMac Retina 5K 27 Inch 2020

### How MacVim was installed

MacVim updated via MacVim->Check for updates

### Issue has been tested with given configuration

- [X] by running MacVim.app from GUI macOS interface
- [ ] by running vim/gvim/etc installed by MacVim
- [ ] by running other versions of vim (e.g. /usr/bin/vim)

### Issue has been tested with no configuration

- [ ] by running `mvim --clean` (or `gvim`, supplied by MacVim distribution)
- [ ] by running `vim --clean` (in terminal, supplied by MacVim distribution)
- [ ] by running `vim --clean` (in terminal, other suppliers, e.g. /usr/bin/vim)

### Other conditions

- [ ] The both Homebrew packages "vim" and "macvim" are installed

**Comment by ychin** [comment]
I can reproduce. Looking into it.

**Comment by MichaelHendry** [comment]
Thanks, ychin.

I'll stop the (now proved futile) sequence of uninstallation, re-installation, rebooting etc!

I'd tried the :hardcopy command, but got the same result as Cmd-P.

Michael

**Comment by ychin** [comment]
For hardcopy you should be able to save it out to a dedicated file (or you can just modify `printexpr`). Then you can manually open that in Preview.

**Comment by MichaelHendry** [comment]
The problem seems to be that Preview no longer opens .ps files - they're ghosted when I try a File-Open in Preview.

I've worked around the problem using the following:

:hardcopy > 0.ps | !ps2pdf 0.ps && open -a preview 0.pdf

0.pdf is then opened in Preview and can be printed in the usual way.

**Comment by MichaelHendry** [comment]
Preview on Ventura no longer supports .PS files, see:

https://support.apple.com/en-us/HT213250

"...The Preview app included with your Mac supports PostScript (.ps) and Encapsulated PostScript (.eps) files in macOS Monterey or earlier. Starting with macOS Ventura, Preview no longer supports these files. Other apps that can view or convert .ps and .eps files are available from the App Store and elsewhere..."

**Comment by ychin** [comment]
Oh crap yeah you are right, now I vaguely remember reading about the drop of PostScript support and was thinking "who still uses PostScript" lol. Famous last words…

I guess we could either bundle `ps2pdf` or find another alternative. I will need to think about it a little.

**Comment by ychin** [comment]
Btw, @MichaelHendry , I'm wondering if you have tried the `:TOhtml` command before and see if that solves your issue? It's another way to tackle the issue but it generates an HTML page that you can then print in a browser. I'm just trying to gather how important it is to fix this issue.

Also, if you want a shorter term fix, I believe you can set printexpr to be `system(['lpr'] + (empty(&printdevice)?[]:['-P', &printdevice]) + [v:fname_in]). delete(v:fname_in)+ v:shell_error`. Only issue with using `lpr` is that it directly sends the doc to the printer, without a way to preview it which is kind of sucky.

**Comment by jubilatious1** [comment]
https://github.com/macvim-dev/macvim/pull/1390#issuecomment-1499536278

**Comment by jubilatious1** [comment]
> hardcopy > 0.ps | !ps2pdf 0.ps && open -a preview 0.pdf

This works in `MacOS Ventura 13.3` with `MacVim: Vim 9.0.1276 (MacVim r176)`.

@MichaelHendry

**Comment by MichaelHendry** [comment]
Now that I've upgraded to Sonoma, I'm having a problem with printing from Adobe Acrobat, which fails to print with the following explanation::

Stopped. Michael Hendry, "Filter" failed. 0 pages, 1 copy

The hardcopy method above works, but I'd prefer not to have to remember these magic spells.

My .gvimrc file now reads as follows:

set tabstop=4
set shiftwidth=4
"se printexpr=system('ps2pdf\ '.v:fname_in.'\ '.v:fname_in.'.pdf\ &&\ open\ '.v:fname_in.'.pdf')\ +\ v:shell_error
 se printexpr=system('ps2pdf\ '.v:fname_in.'\ '.v:fname_in.'.pdf\ &&\ open\ -a\ Preview\ '.v:fname_in.'.pdf')\ +\ v:shell_error

Having completed this comment, I realise that the problem probably lies with Acrobat, not MacVim, but it may help another Mac User who has recently upgraded to Sonoma.

which works around the problem by directing the output specifically to Preview instead of the default application for .PDF files.

**Comment by ychin** [comment]
Huh, I didn't consider the possibility that someone may have assigned another application to open PDFs by default. Let me play around with Acrobat a little first before I decide how to resolve this. I wonder if the issue is since we delete the PDF after a timeout.

**Comment by ychin** [comment]
Actually @MichaelHendry , why do you still have an explicit `printexpr` set? You know that the recent MacVim release (r178) already fixed this problem right? It will automatically use Preview to open it. You should remove the line that sets `printexpr` in your vimrc.

**Comment by MichaelHendry** [comment]
You're absolutely right - I don't need the printexpr line for MacVim.

I've been grappling with the use of a non-graphical version of vim which is called by "LifeLines" - a curses-based genealogy program which calls an external editor to edit information in its GEDCOM database. I can't use MacVim for this because Mac OS doesn't use the same calling convention for "open file X in application Y".

I can work around this by copying-and-pasting into an opened copy of MacVim.

**Comment by ychin** [comment]
Ok, actually… Sonoma broke printing, again, sigh. The fix we did last time used `pstopdf` which was an Apple bundled tool, but macOS 14 Sonoma has completely removed Postscript support so that tool got nuked as well. Currently investigating options, but maybe I'll just force users to install `ps2pdf` instead. Printing is a niche enough thing.
