### ISSUE TITLE
NERDTreeMapOpenInTab crashes MacVim

### ISSUE THREAD

**Issue by jacobespersen** [macvim-dev/macvim#1349]
### Steps to reproduce

- Having NerdTree installed
- Then trying to open a new tab pressing `t`

### Expected behaviour

The given file should be opened in a new tab.

### Version of Vim and architecture

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Sep 15 2022 18:56:17) macOS version - x86_64 Included patches: 1-472 

### Environment

[Ventura 13.0.1 (22A400), 2,4 GHz 8-Core Intel Core i9]
[iTerm2]
[fish, version 3.3.1]

### How MacVim was installed

Homebrew

### Issue has been tested with given configuration

- [ ] by running MacVim.app from GUI macOS interface
- [X] by running vim/gvim/etc installed by MacVim
- [ ] by running other versions of vim (e.g. /usr/bin/vim)

### Issue has been tested with no configuration

- [ ] by running `mvim --clean` (or `gvim`, supplied by MacVim distribution)
- [ ] by running `vim --clean` (in terminal, supplied by MacVim distribution)
- [ ] by running `vim --clean` (in terminal, other suppliers, e.g. /usr/bin/vim)

### Other conditions

- [X] The both Homebrew packages "vim" and "macvim" are installed

**Comment by eirnym** [comment]
Hi, I have a few questions about the issue

Could you please share the trace log as it's a crash

How MacVim has been installed?

Have you tried in the GUI version? If not, please try. 

Could you share minimal vimrc configuration with which another person can reproduce the issue. Please, have no assumptions how plugins are installed as I'd like to have exact machine-repeatable test to find out the problem

**Comment by ychin** [comment]
I think this is a dup of #1333. @jacobespersen you can try to follow https://github.com/macvim-dev/macvim/issues/1333#issuecomment-1303248931 to use non-GUI tabs for now until the next release which will have the fix.

**Comment by jacobespersen** [comment]
@ychin It indeed looks like a duplicate!
Thanks a lot for the help
