### ISSUE TITLE
MacVim crashes when opening a new tab if started from terminal (homebrew installation)

### ISSUE THREAD

**Issue by DrTobe** [macvim-dev/macvim#1350]
### Steps to reproduce

1. `mvim`
2. `:tabe<RETURN>`
3. MacVim crashes (relatively silently)

Alternatively:
1. `mvim`
2. Ctrl + P (with CtrlP plugin installed)
3. Ctrl + T (to open whatever file in a new tab)
4. MacVim crashes with a stack trace

### Expected behaviour

It should open a new tab and not crash.

### Version of Vim and architecture

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Sep 15 2022 18:56:17) macOS version - arm64 Included patches: 1-472 Compiled by Homebrew

### Environment

OS: Ventura 13.1
Terminal: iTerm2
$TERM: xterm-256color
Shell: zsh

This can also be reproduced with the stock Terminal.app. It does not happen when MacVim is started via Spotlight. It also happens when MacVim is started with `mvim --clean`.

### How MacVim was installed

Installed via Homebrew

### Logs and stack traces

```shell
Please let me know which further info / logs / stack traces are helpful to debug the problem.
```

### Issue has been tested with given configuration

- [ ] by running MacVim.app from GUI macOS interface
- [ ] by running vim/gvim/etc installed by MacVim
- [ ] by running other versions of vim (e.g. /usr/bin/vim)

### Issue has been tested with no configuration

- [X] by running `mvim --clean` (or `gvim`, supplied by MacVim distribution)
- [ ] by running `vim --clean` (in terminal, supplied by MacVim distribution)
- [ ] by running `vim --clean` (in terminal, other suppliers, e.g. /usr/bin/vim)

### Other conditions

- [ ] The both Homebrew packages "vim" and "macvim" are installed

**Comment by charlax** [comment]
Same issue with the following specs:

- Ventura 13.1
- Starting from kitty terminal
- zsh

Installed via Homebrew:

```
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Sep 15 2022 18:XX:XX)
macOS version - arm64
Included patches: 1-472
Compiled by Homebrew
Huge version with MacVim GUI.
```

Happens with `mvim --clean` too.

**Comment by charlax** [comment]
Actually, you get the behavior even if you open the app from Finder.

**Comment by dlejay** [comment]
Same issue with the following specs:

Ventura 13.1
Starting by clicking the icon
Installed via Macports:
```

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Dec 25 2022 22:32:35)
macOS version - arm64
Included patches: 1-472
Compiled by MacPorts
Huge version with MacVim GUI.

```
Happens with `mvim --clean` too.

**Comment by phongphan** [comment]
I could confirmed that it happen on the `Release 174` but not on master. It seems to fixed by cd4bd98304dbfba38b3e089f406b59f218d6ec4a

**Comment by ychin** [comment]
Sorry, I have been slow in making a release. I'm trying to fix up the stragglers so we can get a stable build with fully-fleshed out features but it was taking long than I thought. I think we are getting close though. Having an outstanding crash is def not great.

**Comment by ychin** [comment]
But this is basically a dup of #1333. I'm closing as a dup for now. It will be in the next release.
