### ISSUE TITLE
included Sparkle in latest DMG has broken symlink

### ISSUE THREAD

**Issue by andlabs** [macvim-dev/macvim#1366]
The latest version of MacVim includes a file `Contents/Frameworks/Sparkle.framework/XPCServices`, which is a symlink to `Contents/Frameworks/Sparkle.framework/Versions/Current/XPCServices`, but that file does not exist. (Since `Current` is technically a symlink to `B`, the equivalent file in `B` is also missing.)

This doesn't appear to be a problem in the normal user workflow of using Finder to install the package, but does break on unattended automated installation using a package manager we deploy internally to our fleet of Macs. (A recursive `chmod` chokes on the broken symlink.)

**Comment by ychin** [comment]
Right. We upgraded to Sparkle 2, and the framework contains XPCServices that [Sparkle's documentation](https://sparkle-project.org/documentation/sandboxing/#removing-xpc-services) suggests that we can remove, which we do so in [a script](https://github.com/macvim-dev/macvim/blob/master/src/MacVim/scripts/cleanup-after-build). I missed the top-level symlink as you pointed out though.

I can fix that. Just curious though, what exactly is the automated installation doing and why does it need to recursively go inside an .app bundle to chmod them? Wouldn't the .app "just work"?

Also, is this blocking the workflow for you guys then?

**Comment by andlabs** [comment]
We can work around this for now, yes.

The package manager copies the app bundle to a temporary directory, changes the owner from `root` to the user owner, restores the original permissions (overriding /tmp's umask), and then atomically moves the app bundle into `/Applications`, so that failed installs don't leave the machine in a broken state.

**Comment by ychin** [comment]
I see, that's interesting to know. I didn't know MacVim is installed this way since I always assumed people mostly just grab a binary release or install via Homebrew.

If it's not blocking you for now, I'll just merge the PR that fixes it and it will be out in the next release, which should be 1.5-2 months from now (there may be pre-release builds in between as well).

**Comment by andlabs** [comment]
Thanks! Things get weird in enterprise settings compared to individual users, yes =P

**Comment by ychin** [comment]
This should be fixed for the latest release.
