### ISSUE TITLE
Regex isn't working properly

### ISSUE THREAD

**Issue by frankjonen** [macvim-dev/macvim#1368]
### Steps to reproduce

Example1: https://vim.fandom.com/wiki/Regex_lookahead_and_lookbehind

1. Put: `The quick fox jumps over the lazy brown dog.` in an empty buffer.
2. Search with `/brown\( fox\)\e=`

Brings up an error message instead of the word `brown`.

You can try the rest on that page. None work. Syntax files using `/zs` also have issues not selecting.

### Expected behaviour

Should select the word `brown` in provided example.

### Version of Vim and architecture

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Sep 15 2022 18:56:17) macOS version - x86_64 Included patches: 1-472 Compiled by Homebrew   

### Environment

macOS Monterey
GUI

### How MacVim was installed

Homebrew

### Issue has been tested with given configuration

- [X] by running MacVim.app from GUI macOS interface
- [ ] by running vim/gvim/etc installed by MacVim
- [ ] by running other versions of vim (e.g. /usr/bin/vim)

### Issue has been tested with no configuration

- [ ] by running `mvim --clean` (or `gvim`, supplied by MacVim distribution)
- [ ] by running `vim --clean` (in terminal, supplied by MacVim distribution)
- [ ] by running `vim --clean` (in terminal, other suppliers, e.g. /usr/bin/vim)

### Other conditions

- [ ] The both Homebrew packages "vim" and "macvim" are installed

**Comment by ychin** [comment]
Seems to work just fine for me? You didn't copy the example verbatim. It should be "quick **brown** fox" in the text, and you need to use `\@=`, or `\ze`, *not* `\e` or `/ze`. These details matter a lot.

**Comment by frankjonen** [comment]
You can close it. I've been looking at it too long to see the issue. Turns out it wasn't Vim but some override that blocked the `/zs` `/ze` selections I needed. Took me some hours to find the lead.

**Comment by ychin** [comment]
Ah ok. Yeah we have all done that 😅.
