### ISSUE TITLE
Ligatures cause characters to be cut off at certain font sizes?

### ISSUE THREAD

**Issue by prurph** [macvim-dev/macvim#137]
When I enable ligatures, certain characters are cut off, both for the current line and other lines, as seen here:

![default vimrc - vim 2015-11-14 17-39-14](https://cloud.githubusercontent.com/assets/6109531/11166154/d68c1c36-8af6-11e5-801e-a75835ef2b24.png)

This is shown with font Hasklig, but happens for monospaced fonts even without ligatures, with and without Powerline glyphs, etc. It only happens at certain font sizes (above is 12). For example, 13, 16 and 17pt are fine, but 14, 15, 18, etc. show the issue. Disabling ligatures removes the problem for all fonts at all sizes.

Could this be something on my end or is it an issue with MacVim?

**Comment by splhack** [comment]
Can you provide a minimum way to reproduce the issue from here?

    $ defaults delete org.vim.MacVim
    $ /Applications/MacVim.app/Contents/MacOS/Vim -g -u NONE -U NONE

**Comment by prurph** [comment]
Sure--after launching MacVim as above:

1. Preferences > check "Enable support for ligatures"
2. Quit and relaunch MacVim using `-g -u NONE -U NONE` as above
3. Type some sample text on different lines.
4. Press `CMD+` to increase the font to size 12. The text becomes cut off like this:

![no name - vim 2015-11-23 01-23-18](https://cloud.githubusercontent.com/assets/6109531/11330883/cc2a5632-9180-11e5-806b-0776e2ccb002.png)

Moving the cursor over the affected text causes it to "fix" itself, until that text is no longer selected or otherwise "active", at which point it again appears as above. This seems to affect most, but not all, monospaced fonts, including:

DejaVu Sans Mono, Inconsolata for Powerline, Liberation Mono for Powerline, Source Code Pro (the original, the Powerline version, and Hasklig, which is based on Source Code Pro) and Envy R.

I am on El Capitan. Thanks!

**Comment by splhack** [comment]
> 1. Preferences > check "Enable support for ligatures"

MacVim doesn't have the setting any more. Please use the latest snapshot and complete the procedure?

**Comment by prurph** [comment]
My bad--I was using the version from Homebrew. I have built from the latest snapshot, used `set macligatures` and all is well. Here is a screenshot showing the difference:

![default vimrc - vim 2015-11-24 19-40-46](https://cloud.githubusercontent.com/assets/6109531/11385099/92f13b7e-92e3-11e5-99c8-f6b25d42b612.png)

Many thanks for your patience.

**Comment by splhack** [comment]
good to know!
