### ISSUE TITLE
<C-H> Mapping has stopped working in MacVim GUI, but still works in TUI

### ISSUE THREAD

**Issue by SirVer** [macvim-dev/macvim#1370]
### Steps to reproduce

1. Open a file in TUI mode `vim /tmp/blub.txt`
2. Ensure something is imapped to `<c-h>`. 
3. Typing `<c-h>` actually triggers this trigger
4. :gui
5. Now `<c-h>` is deleting the last character.

### Expected behaviour

`<c-h>` should not be the same as `<backspace>`. I am aware that in traditional terminal emulators, there is no difference between `<c-h>` and `<backspace>`, however on another computer with an older mac VIM, this behaved differently: both the TUI and the GUI accept `<c-h>` as a mapping that is not interpreted as backspace. On my new computer (with Vim 9) and a recent macvim from homebrew, the TUI still accepts it, but not the GUI. Of note is that this happens *most of the time*, but sometimes the GUI also accepts `<c-h>`. 

[I made a screen capture to show the behavior](https://youtu.be/wA25CzmHToc), here `<c-h>` is mapped to https://github.com/SirVer/ultisnips expand command. You can see that it expands `lorem<c-h>` always in TUI mode, but only sometimes in GUI mode. 

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 01 2021 08:32:44)
macOS version - x86_64
Included patches: 1-2681

### Version of Vim and architecture

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Feb 07 2023 11:35:56) macOS version - arm64 Included patches: 1-1276 Compiled by Homebrew Huge version with MacVim GUI. 

### Environment

OS: Ventura, arm64
terminal:  same behavior for iTerm2 & Terminal.app
TERM: xterm-256color
SHELL: zsh 5.8.1 (x86_64-apple-darwin22.0)

### How MacVim was installed

homebrew

### Logs and stack traces

```shell
-
```

### Issue has been tested with given configuration

- [ ] by running MacVim.app from GUI macOS interface
- [X] by running vim/gvim/etc installed by MacVim
- [ ] by running other versions of vim (e.g. /usr/bin/vim)

### Issue has been tested with no configuration

- [ ] by running `mvim --clean` (or `gvim`, supplied by MacVim distribution)
- [ ] by running `vim --clean` (in terminal, supplied by MacVim distribution)
- [ ] by running `vim --clean` (in terminal, other suppliers, e.g. /usr/bin/vim)

### Other conditions

- [ ] The both Homebrew packages "vim" and "macvim" are installed

**Comment by ychin** [comment]
I'm also having some issues reproducing this. @SirVer here are some suggestions:

1. Can you try to launch MacVim without the terminal by directly clicking on the app or something like `open /Applications/MacVim.app`? When you do `:gui` sometimes it can bring in some of the terminal emulator environment so it's useful to launch the GUI fresh to see if it reproduces.
2. When the issue happens, you can do `<C-V><Backspace>` and `<C-V><C-H>` to see if Vim is indeed interpreting those keys as `<BS>` and `^H` correctly.
3. Launch Vim in `--clean` as @eirnym suggested for testing.

Some questions:

1. What does `set t_kb?` in your terminal Vim report?

**Comment by SirVer** [comment]
I am very impressed with this very fast turnaround of replies. However, after a(nother) reboot, the problem seems to have disappeared. This is frustrating, since I spent at least a few hours trying to get to the bottom of it myself, but as long as its gone I should be satisfied.

I am going to close this, should it reappear I will post more information on this ticket. Thank you both again for your quick reaction looking into this!

**Comment by ychin** [comment]
FWIW I found some weirdness with MacVim after updating my stable build right after installation as well. The scrolling was quite stuttery and I thought I introduced a bug. But for some reason it went away, and I'm still not sure if it's a bug somewhere or an OS thing or whatnot. Oh well I can't reproduce now anyway.
