### ISSUE TITLE
Welcome message's `:` are not aligned

### ISSUE THREAD

**Issue by dantezhu** [macvim-dev/macvim#1380]
### Steps to reproduce

1. open macvim
2. show the welcome msg, but `:` are not aligned  
    <img width="528" alt="image" src="https://user-images.githubusercontent.com/1105212/223365749-92f96e54-1fac-44c9-b058-c8312649fcc1.png">

### Expected behaviour

`:` should be aligned
like this:
<img width="430" alt="image" src="https://user-images.githubusercontent.com/1105212/223373990-92695d54-dd04-486e-8907-f0475df4348a.png">

### Version of Vim and architecture

9.0.1276

### Environment

OS: macos 13.2.1 (22D68)

### How MacVim was installed

brew

### Issue has been tested with given configuration

- [x] by running MacVim.app from GUI macOS interface
- [x] by running vim/gvim/etc installed by MacVim
- [ ] by running other versions of vim (e.g. /usr/bin/vim)

### Issue has been tested with no configuration

- [ ] by running `mvim --clean` (or `gvim`, supplied by MacVim distribution)
- [ ] by running `vim --clean` (in terminal, supplied by MacVim distribution)
- [ ] by running `vim --clean` (in terminal, other suppliers, e.g. /usr/bin/vim)

### Other conditions

- [ ] The both Homebrew packages "vim" and "macvim" are installed

**Comment by ychin** [comment]
Huh, this only seems to happen when `columns` is even. If it's odd numbered it will work. I will fix it up.

Just curious, do you use MacVim with locale set to Chinese? MacVim still has quite a few unlocalized pieces (the settings dialog, random texts) so I'm curious how the user experience is.

**Comment by dantezhu** [comment]
Thanks ychin.
MacVim works very well in Chinese environment.

The only thing that makes me uncomfortable is that when using LeaderF to input Chinese, it will look like this:

<img width="927" alt="image" src="https://user-images.githubusercontent.com/1105212/223606030-7bb7cbb6-ba5d-4313-971c-b1efa04f1d16.png">

I know it can be solved by canceling `Draw marked text inline`, but this will cause the original input characters to be hidden, so it is not a perfect solution.

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/1105212/223606166-30d473da-e7f7-4f1b-a719-78832954632c.png">

I have seen similar issues mentioning this problem, and it seems that the bottom layer needs to be modified to solve it, it may be difficult to solve.

Everything else works fine, thanks a lot for your contribution!

**Comment by ychin** [comment]
Ah yes, getting input to work better is actually quite high on my list to do next, so this will be tackled soon. In particular you should not need to disable "draw marked text inline" if everything worked and we shouldn't have two settings that are both broken a little bit in their own ways. Getting input methods to work better in non-insert mode situations (including your use case, or just using `r`) is on my list but I need to think a little about the best way to tackle them first, but I don't think there's anything in Vim that's particularly problematic. It's mostly a MacVim-layer issue. So there should be a fix in the future soon (disclaimer: "soon" has a flexible definition…) !

**Comment by dantezhu** [comment]
Haha, thank you very much! looking forward to the fix~ 😁
