### ISSUE TITLE
Completion introduces incorrect entries (version 922

### ISSUE THREAD

**Issue by AmaruCoder** [macvim-dev/macvim#142]
I upgraded my MacVim version 712 to 922. Now, when I use the keyword completion when writing prose, the list included incorrect entries. See below:

## MacVim version 712
![Version 712](https://dl.dropboxusercontent.com/u/301329/MacVim/MacVim-712.png)

## MacVim version 922
![Version 922](https://dl.dropboxusercontent.com/u/301329/MacVim/MacVim-922.png)

**Comment by chdiza** [comment]
This is probably an issue with regular Vim.  Does it happen when running github.com/vim/vim 7.4.922 in the console?

**Comment by AmaruCoder** [comment]
Yes, it happens. When running version 922 from the console, I see exactly the same issue. See below:

## Running from Mac OS's console

![MacVim version 922 from the console](https://dl.dropboxusercontent.com/u/301329/MacVim/MacVim-console-922.png)

**Comment by chdiza** [comment]
Did you run https://github.com/vim/vim from the console, or did you merely run `/applications/MacVim.app/contents/MacOS/Vim` from the console?  If the first one, then this is not a MacVim issue, but a Vim issue.  You can report it at https://github.com/vim/vim.  If the latter, then it is a MacVim issue.

**Comment by AmaruCoder** [comment]
The latter. I run `/applications/MacVim.app/contents/MacOS/Vim` from the console. So, it seems to be a MacVim issue.

**Comment by splhack** [comment]
Could you try https://github.com/vim/vim ? You can use [Homebrew](http://brew.sh/) like this.

    $ brew install vim

Then try to use `/usr/local/bin/vim`.

**Comment by chdiza** [comment]
@splhack is right.  What I meant to be asking is whether or not "real" Vim has this problem.  If it doesn't, then it's a MacVim issue.

**Comment by AmaruCoder** [comment]
I installed vim using Homebrew, and run it from `usr/local/bin`, but I get the same results. See below:

## Vim 903
![MacVim version 922 from the console](https://dl.dropboxusercontent.com/u/301329/MacVim/MacVim-brew-902.png)

**Comment by chdiza** [comment]
What does the "903" mean?  Vim, in Homebrew, should be at 7.4.922.  If it's not for you, then do `brew update`, `brew rm vim`, `brew install vim`.

**Comment by chdiza** [comment]
Also, the screenshot is unavailable.

**Comment by AmaruCoder** [comment]
I installed Vim with:

`$ brew install vim`

And then run it from `/usr/local/bin/`

**Comment by chdiza** [comment]
You told us that already :)

What does the "903" mean? Vim, in Homebrew, should be at 7.4.922.  Does `/usr/local/vim --version` say `7.4.922`?

**Comment by AmaruCoder** [comment]
The command `homebew install vim` installs version 7.4.903.

**Comment by chdiza** [comment]
You didn't read my prior instructions.  Do `brew update`, then do `brew remove vim`, then do `brew install vim`.

**Comment by AmaruCoder** [comment]
Following the instructions, `brew install vim` has installed the version 7.4.922, and it shows the same issue.

**Comment by chdiza** [comment]
OK, this means the problem is with Vim.  This issue should be reported to the github/vim/vim repo, complete with your screenshot using Vim (not MacVim).
