### ISSUE TITLE
No rendering in New tab in MacVim built from source 57b0bab10

### ISSUE THREAD

**Issue by al3xandru** [macvim-dev/macvim#1439]
### Steps to reproduce

1. Open a file in a new buffer: `tabe [file]`
2. Get an empty window
<img width="983" alt="image" src="https://github.com/macvim-dev/macvim/assets/290841/89b3d50f-d951-4fc6-92af-01596bb8281f">
3. Switching between tabs makes them all "empty"

### Expected behaviour

Normal vim behavior

### Version of Vim and architecture

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Oct 11 2023 13:00:16) macOS version - arm64 Included patches: 1-1994 Compiled by 5098093a6@202310111259

### Environment

macOS 14.0
MacBook Pro M1

Huge version with MacVim GUI.  Features included (+) or not (-):
+acl               +cscope            -gettext           +mouseshape        +postscript        -tag_old_static    +visualextra
+arabic            +cursorbind        -hangul_input      +mouse_dec         +printer           -tag_any_white     +vreplace
+autocmd           +cursorshape       +iconv             -mouse_gpm         +profile           -tcl               +wildignore
+autochdir         +dialog_con_gui    +insert_expand     -mouse_jsbterm     +python/dyn        +termguicolors     +wildmenu
-autoservername    +diff              +ipv6              +mouse_netterm     +python3/dyn       +terminal          +windows
+balloon_eval      +digraphs          +job               +mouse_sgr         +quickfix          +terminfo          +writebackup
+balloon_eval_term +dnd               +jumplist          -mouse_sysmouse    +reltime           +termresponse      -X11
+browse            -ebcdic            +keymap            +mouse_urxvt       +rightleft         +textobjects       -xattr
++builtin_terms    +emacs_tags        +lambda            +mouse_xterm       +ruby/dyn          +textprop          -xfontset
+byte_offset       +eval              +langmap           +multi_byte        +scrollbind        +timers            +xim
+channel           +ex_extra          +libcall           +multi_lang        +signs             +title             -xpm
+cindent           +extra_search      +linebreak         -mzscheme          +smartindent       +toolbar           -xsmp
+clientserver      -farsi             +lispindent        +netbeans_intg     +sodium            +transparency      -xterm_clipboard
+clipboard         +file_in_path      +listcmds          +num64             +sound             +user_commands     -xterm_save
+cmdline_compl     +find_in_path      +localmap          +odbeditor         +spell             +vartabs
+cmdline_hist      +float             +lua/dyn           +packages          +startuptime       +vertsplit
+cmdline_info      +folding           +menu              +path_extra        +statusline        +vim9script
+comments          -footer            +mksession         +perl/dyn          -sun_workshop      +viminfo
+conceal           +fork()            +modify_fname      +persistent_undo   +syntax            +virtualedit
+cryptv            +fullscreen        +mouse             +popupwin          +tag_binary        +visual
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/opt/homebrew/MacVim.app/Contents/Resources/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe -DMACOS_X -DMACOS_X_DARWIN -g -O2 -I/opt/
homebrew/Cellar/libsodium/1.0.18_1/include -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc -L/usr/local/lib -o Vim -lm -lncurses -L/opt/homebrew/Cellar/libsodium/1.0.18_1/lib -lsodium -liconv -framework AppKit

### How MacVim was installed

built from source

### Issue has been tested with given configuration

- [X] by running MacVim.app from GUI macOS interface
- [ ] by running vim/gvim/etc installed by MacVim
- [ ] by running other versions of vim (e.g. /usr/bin/vim)

### Issue has been tested with no configuration

- [ ] by running `mvim --clean` (or `gvim`, supplied by MacVim distribution)
- [ ] by running `vim --clean` (in terminal, supplied by MacVim distribution)
- [ ] by running `vim --clean` (in terminal, other suppliers, e.g. /usr/bin/vim)

### Other conditions

- [ ] The both Homebrew packages "vim" and "macvim" are installed

**Comment by ychin** [comment]
Thanks for reporting. From playing with it I think this has to do with Xcode 15 / macOS 14 SDK. I just updated my software and I knew it was too bugfree / seamless to be true :/. I'll take a look.

If you want to build from source, you could use the older SDK / Xcode.

**Comment by al3xandru** [comment]
I’m not really an Xcode user and don’t know how to make these changes. I have a Makefile that configures the build and runs it from the terminal. 

As a side note I did notice though, that I can’t build anymore on a macOS 13.5.2. Maybe I need to upgrade Xcode but I have no clue yet.

**Comment by ychin** [comment]
Sure feel free to make an issue

**Comment by al3xandru** [comment]
I can confirm latest build doesn't show this issue anymore. Thank you
