### ISSUE TITLE
Reported Vim version is null when MacVim is run via GUI

### ISSUE THREAD

**Issue by dlejay** [macvim-dev/macvim#1449]
### Steps to reproduce

1. Open MacVim via GUI
2. Click `about`
3.  See the null version
<img width="233" alt="Capture d’écran 2023-10-20 à 16 27 57" src="https://github.com/macvim-dev/macvim/assets/39823850/26027a56-0847-48bb-a86f-6755a44bbc1d">

### Expected behaviour

Show the actual Vim version.

When running `mvim` from the command line the issue disappears.

### Version of Vim and architecture

Good question

### Environment

macOS Sonoma

### How MacVim was installed

Homebrew

### Issue has been tested with given configuration

- [ ] by running MacVim.app from GUI macOS interface
- [ ] by running vim/gvim/etc installed by MacVim
- [ ] by running other versions of vim (e.g. /usr/bin/vim)

### Issue has been tested with no configuration

- [X] by running `mvim --clean` (or `gvim`, supplied by MacVim distribution)
- [ ] by running `vim --clean` (in terminal, supplied by MacVim distribution)
- [ ] by running `vim --clean` (in terminal, other suppliers, e.g. /usr/bin/vim)

### Other conditions

- [ ] The both Homebrew packages "vim" and "macvim" are installed

**Comment by dlejay** [comment]
Upgrading Macvim solved the issue.

**Comment by ychin** [comment]
We you building MacVim yourself in Xcode? The fact that you saw "null" in the version implies to me that you were building MacVim yourself instead of building MacVim using the Makefile. I don't think anything between r177 and r178 would have fixed any issue on this.
