### ISSUE TITLE
Opening macvim on sudo mode makes menu bar color change to default

### ISSUE THREAD

**Issue by hansol-shin** [macvim-dev/macvim#145]
I set my menu bar color to be dark mode.
When I open macvim via terminal using mvim, it opens with dark menu bar.
However when I do sudo mvim filename it somehow overrides the dark menu bar and opens with a white menu bar (default).
Is this bug due to my settings or a known issue?

**Comment by splhack** [comment]
It's not a bug or issue.

Your `/etc/sudoers` `env_keep` doesn't include `HOME` if you are using OS X's sudo. Take a look at `man sudo`. You can use `-e` option.

    $ sudo -e FILE

Or `-E` option.

    $ sudo -E mvim FILE
