### ISSUE TITLE
Dragging MacVim tab overlapping the title bar results in a crash [UI]

### ISSUE THREAD

**Issue by salvosq** [macvim-dev/macvim#1473]
### Steps to reproduce

1. Create multiple editor tabs (cmd+t)
2. Drag one of them overlapping the title bar.

### Expected behaviour

I need to move tabs for reordering purposes.

### Version of Vim and architecture

9.1.0 (179)

### Environment

Process:               MacVim [28974]
Path:                  /Applications/MacVim.app/Contents/MacOS/MacVim
Identifier:            org.vim.MacVim
Version:               9.1.0 (179)
Code Type:             X86-64 (Native)
Parent Process:        Vim [28973]
Date/Time:             2024-01-08 14:55:40.3414 +0100
OS Version:            macOS 14.2.1 (23C71)
Report Version:        12

### How MacVim was installed

From https://macvim.org/

### Logs and stack traces

```shell
Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x000042f2965f177e
Exception Codes:       0x0000000000000001, 0x000042f2965f177e
Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [28974]
```

### Issue has been tested with given configuration

- [X] by running MacVim.app from GUI macOS interface
- [ ] by running vim/gvim/etc installed by MacVim
- [ ] by running other versions of vim (e.g. /usr/bin/vim)

### Issue has been tested with no configuration

- [X] by running `mvim --clean` (or `gvim`, supplied by MacVim distribution)
- [ ] by running `vim --clean` (in terminal, supplied by MacVim distribution)
- [ ] by running `vim --clean` (in terminal, other suppliers, e.g. /usr/bin/vim)

### Other conditions

- [ ] The both Homebrew packages "vim" and "macvim" are installed

**Comment by ychin** [comment]
I could reproduce this issue. Looking into it. Will try to push out an update soon after investigation and fix.

**Comment by dennisjbell** [comment]
Any update on this?

**Comment by ychin** [comment]
Sorry I have not been able to spend enough time on MacVim last few months due to travels and whatnot. Currently trying to go through backlog and merge from Vim upstream and then fix issues like this. Sorry for the delay.

**Comment by felix021** [comment]
Been experiencing similar issue: dragging a tab results in weird UI responses, and even freezes MacOS's Dock which can only be solved by killing the MacVim process manually.

- MacVim r179 (Vim 9.1.0), downloaded from github
- Apple M3 Pro
- MacOS 14.3 (23D56)

**Comment by ychin** [comment]
Finally fixed this. Sorry this took a while.
