### ISSUE TITLE
unable to adjust font size in macvim

### ISSUE THREAD

**Issue by slferris** [macvim-dev/macvim#1476]
### Steps to reproduce

set guifont=Monaco:h20 in .gvimrc; saved (size 14 is too small for me to read comfortably)

### Expected behaviour

increased font size

### Version of Vim and architecture

VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Jan  4 2024 03:08:50) macOS version - arm64

### Environment

macOS Sonoma 14.2.1
zsh 5.9 (arm-apple-darwin22.1.0)

### How MacVim was installed

downloaded from macvim website; installed from package

### Issue has been tested with given configuration

- [X] by running MacVim.app from GUI macOS interface
- [ ] by running vim/gvim/etc installed by MacVim
- [ ] by running other versions of vim (e.g. /usr/bin/vim)

### Issue has been tested with no configuration

- [ ] by running `mvim --clean` (or `gvim`, supplied by MacVim distribution)
- [ ] by running `vim --clean` (in terminal, supplied by MacVim distribution)
- [ ] by running `vim --clean` (in terminal, other suppliers, e.g. /usr/bin/vim)

### Other conditions

- [ ] The both Homebrew packages "vim" and "macvim" are installed

**Comment by ychin** [comment]
Seems to work for me? How does it not work for you exactly? What does `set guifont?` show?

What do you mean by "unable to adjust font size" anyway? You mean not able to set font at all right?

**Comment by slferris** [comment]
Thanks for your quick response. 

When I change set guifont=Monaco:h14 in ~/.gvimrc to a larger number, it reads, for example, set guifont=Monaco:h24, but the size of the font does not get any bigger. Is there somewhere else I need to change the font?

**Comment by slferris** [comment]
Sorry, ignore my last email. It tried it again, and now the font size seems to be working OK. Thanks again for responding.

**Comment by ychin** [comment]
Good to know. I'll just close the issue then. One reason that might have happened is you have "Quickstart" enabled in the Advanced setting, which would mean it has an old version of your vimrc preloaded.
