### ISSUE TITLE
unable to enter directories in ~/library

### ISSUE THREAD

**Issue by EricEWeir** [macvim-dev/macvim#1481]
I just posted this to Mac_Vim:

I’m a non-coding, non-developer coming back to vim primarily as a writer after several years away. I once had a comfortable configuration developed with a lot of help from people at mac-vim and at vim_use.

I would like to create and edit files in directories in ~/library/mobile documents. I get a listing of directories in ~/library but am unable to enter any of them. Wondering if I’d even be able to open files if I could. 

When I run vim in terminal I do not have this problem.

I'm not competent to diagnose this problem and fix it. I sought help with it on the vim subreddit. Users there in a similar Mac environments reported they don't have the problem. 

Help greatly appreciated.

**Comment by ychin** [comment]
I believe this was resolved on the mailing list: https://groups.google.com/g/vim_mac/c/n8vvN8X3T-U/m/6OLCE26PAAAJ
