### ISSUE TITLE
Upstream Merge?

### ISSUE THREAD

**Issue by ir0nh34d** [macvim-dev/macvim#1486]
Any chance we can get an upstream merge?  I looked at https://github.com/macvim-dev/macvim/wiki/Merging-from-upstream-Vim - is it still significant effort to merge upstream into MacVim?

**Comment by ychin** [comment]
Yeah sorry I have been a little behind on this. Will get on it this week. Been a little occupied with other things.

For context, it's still a little bit of work to merge. A lot of it isn't just the technical aspect of handling merge conflicts etc but also reviewing the changes upstream to make sure there aren't new features or changes that may change what MacVim needs to do downstream etc. From experience, a lot of times bugs sneak in even if there aren't any obvious merge conflicts so I just like to be thorough. It's not a significant amount of effort though.

**Comment by ychin** [comment]
Merged in de3b3657623c4002a72b6d3d9e556f42cc7f7274
