### ISSUE TITLE
Touchbar esc not working anymore.

### ISSUE THREAD

**Issue by k-h** [macvim-dev/macvim#1490]
I never had an issue with the touchbar escape working but recently I updated to ventura and now it does nothing.  I have to use ctl-[ which is really annoying. How do I make the touchbar esc work again?

13" MBP 13.6.7 (22G720)
MacVim r179 (Vim 9.1.0)

**Comment by ychin** [comment]
Hmm, how does it not work? It still shows up but when you press it it doesn't do anything?

Just to confirm, what year is your MBP?

**Comment by k-h** [comment]
The esc button/area appears but it doesn't do anything.

Also yesterday the touchbar went dark and I had to restart it.  It's never done that before.  I have had MacVim running for several days, while doing some work. 

MacBook Pro 13-inch, 2017, Four Thunderbolt 3 Ports

**Comment by ychin** [comment]
@k-h Did you ever figure it out? I can't quite seem to reproduce it. Judging from what you described it seems more like a global OS issue where your TouchBar is seeing issues. Does this issue not happen for other apps?

**Comment by k-h** [comment]
No, never did.  I use macvim and vim in Terminal but my touchbar has got flakey so it could be an OS issue.  Once the touchbar turns off it stays off for all apps.

**Comment by ychin** [comment]
Right. I'll just close the issue for now. This really sounds more like a combination of issues from hardware/OS rather than a MacVim issue to me, especially if the Touch Bar is just flaky in general. Apple support may be able to help you more.
