### ISSUE TITLE
Open in Terminal Option of Finder Pathbar: selected folder opens in MacVim

### ISSUE THREAD

**Issue by DogmaF** [macvim-dev/macvim#1496]
### Steps to reproduce

1. open a finder window with the Pathbar enabled
2. select a folder (i.e. click once to highlight folder)
3. right-click on the folder name in the Pathbar
4. choose 'open in terminal'

Instead of opening a terminal at the selected directory, MacVim executes and opens the directory as a text file.

### Expected behaviour

A terminal opens at the directory indicated by the folder.

### Version of Vim and architecture

9.1, GUI, Intel i9, 64 Gb, AMD Radeon Pro 5500M 8 Gb

### Environment

OS: 14.6.1
$TERM: xterm-256color
shell: bash

### How MacVim was installed

downloaded installer from macvim

### Vim configuration where issue is reproducable

https://drive.google.com/file/d/1R_h8poaPPzuo4oo9yHWz7jh0BbIIT649/view?usp=drive_link

### Issue has been tested with given configuration

- [X] by running MacVim.app from GUI macOS interface
- [ ] by running vim/gvim/etc installed by MacVim
- [ ] by running other versions of vim (e.g. /usr/bin/vim)

### Issue has been tested with no configuration

- [ ] by running `mvim --clean` (or `gvim`, supplied by MacVim distribution)
- [ ] by running `vim --clean` (in terminal, supplied by MacVim distribution)
- [ ] by running `vim --clean` (in terminal, other suppliers, e.g. /usr/bin/vim)

### Other conditions

- [ ] The both Homebrew packages "vim" and "macvim" are installed

**Comment by DogmaF** [comment]
Solution: choose a file that the system sees as "Unix Executable File" (such as a shell script that does not have an extension), open "Get Info" on such a file, change the "Open with:" selection to "Terminal.app", and finally click "Change All..

**Comment by ychin** [comment]
Hmm I never knew about this behavior. I am guessing you assigned Unix Executable File to MacVim? Or was that done automatically?

**Comment by DogmaF** [comment]
I actually don't recall how my Unix executables got assigned to MacVim. But the solution was not obvious. Hopefully by raising this issue I can help others that run into the problem.
