### ISSUE TITLE
Randomly creates "Enter Full Screen" entries in window menu

### ISSUE THREAD

**Issue by TheDudeWithTheThing** [macvim-dev/macvim#150]
This might not be so random but here are the details.  As you can see in the screenshot I have reclaimed <D-f> from the normal Find menu to be used with CtrlP.  What happens sometimes is <D-f> will magically remap to be Enter Full Screen.  It may or may not be related to me closing my laptop and opening it or just the laptop going to sleep.  I never use full screen mode for MacVim and having 8 tabs or so open only to have to restart MacVim to get my <D-f> functionality back is not good.  I haven't tried to dig into the source yet and figured I'd post an issue for it in case anyone else is experiencing this.  I just recently installed macvim via homebrew and that's when it started. Previously with the binary from github I never hit this problem. I'm happy to help diagnose with any info.

![](https://www.evernote.com/l/AFuMx6LU_ehBFI1tEy70oyPpTSr5QLgCaDEB/image.png)

**Comment by chdiza** [comment]
1. Just FYI, `:set [no]fu` can get you out of fullscreen if you accidentally wind up there.

2. If I recall correctly, macmenu key mappings *must* be done in `gvimrc`, not a separate file.  Put that part in your `gvimrc` and see if it keeps happening.

**Comment by TheDudeWithTheThing** [comment]
Hey @chdiza thanks for the quick reply. I've moved all command key binds to my gvimrc and will see if that fixes, will close this out if it does.

**Comment by chdiza** [comment]
Yeah, my memory was right.  `:help macmenu`, first paragraph.

But you don't need to move ALL bindings to `.gvimrc`.  Just the `macmenu` ones.

**Comment by TheDudeWithTheThing** [comment]
You'll notice in my screenshot that the gui_macvim lines are already in my gvimrc, seems like moving the command key binds there didn't fix it either.

What I find really baffling is that by default command f is find, not full screen.

**Comment by chdiza** [comment]
In the only screen shot on this page, the lines are in a file called `mappings.vim`.

**Comment by chdiza** [comment]
Ah, no, I see now.  The statusline was very faint!

**Comment by chdiza** [comment]
Which gets loaded first, `gvimrc` or `mappings.vim`?  If it's `mappings.vim`, that's likely the problem.

**Comment by chdiza** [comment]
The next time it gets "remapped" to fullscreen, try doing `:verbose map` to see if `<D-f>` or `<D-F>` appear anywhere, and what file they're being sourced from.

**Comment by eirnym** [comment]
Menu key bindings you can change in `System Preferences -> Keyboard -> Shortcuts -> App Shortcuts` and no need to modify `gvimrc`

**Comment by TheDudeWithTheThing** [comment]
@chdiza mappings is sourced in the last line of my vimrc, so if vimrc is loaded before gvimrc (I forget the load order) then that could be it.

@eirnym thanks! I'll give that a go too.

**Comment by chdiza** [comment]
Vimrc is loaded before gvimrc.  This is almost surely the prob.  I hope!

**Comment by chdiza** [comment]
FWIW, I see the proliferation of entries in the drop-down menu too.  However in my case it isn't Cmd-F, rather it's Shift-Cmd-F. (MacVim shows the Shift as an up-arrow picture.) It happens that in System Preferences I have set as a keyboard shortcut for all apps "Shift-Cmd-F" for "Enter Full Screen".  Do you have "Cmd-F" bound to all apps (or even some apps) in System Preferences?

**Comment by chdiza** [comment]
I should add that in my case this causes no problems other than ugliness, because in my gvimrc I map what is in effect Shift-Cmd-F to "Toggle Full Screen Mode".  So it may well be that on my machine "Enter Full Screen" is being commandeered, but I never noticed it because the hijacker installs the same keyboard chord as I do.

**Comment by TheDudeWithTheThing** [comment]
I think I'm all set. It still happened even after swapping the mapping to be after gvimrc. What fixed it is binding an absurd key combo (all meta keys plus F) to enter full screen and now it stopped the high jacking I believe.

**Comment by TheDudeWithTheThing** [comment]
Thanks for the help everyone, going to consider this particular case resolved though it does sound like a bug exists that creates menu items repeatedly.

**Comment by chdiza** [comment]
@TheDudeWithTheThing Nevertheless, did you have any keyboard mappings set in System Preferences that apply to "Enter Full Screen" in all apps, or even just for MacVim?  This might help us diagnose what's going on.

**Comment by TheDudeWithTheThing** [comment]
Nope, just the default help one and now the "dummy" macvim one

![](https://www.evernote.com/l/AFtqSRqDuqFGOY6dYPTuehqmjiMUfNSpn5cB/image.png)

**Comment by chdiza** [comment]
So is that huge keychord showing up multiple times in the Window menu of MacVim?  You said the hijacking stopped, but I'm not sure if you mean the unexpected entries into fullscreen mode, or the existence of the many entries in the dropdown menu, or both.

**Comment by TheDudeWithTheThing** [comment]
It does still show up but at least now it's with the giant keychord and not my CtrlP bind.  I'm convinced it has to do with the window being redrawn on desktop switch / laptop close / open, laptop sleep / wake but haven't been able to prove it.  Here's what I'm currently looking at.

![](https://www.evernote.com/l/AFtoPFIarz9IHq5aYoBR3ogDkAQBnuf7_qUB/image.png)

**Comment by chdiza** [comment]
OK, so we've got a problem with the interaction between MacVim and custom keyboard shortcuts made in the official Apple way, and we've got two examples (yours and mine).  Your version is where the custom chord is just for MacVim, and my version is when it's for "All Applications".  Your version was created with the Keyboard PreferencePane, and mine was created with the CLI via `defaults`.

On the one hand, one suspects the flaw is on our end since I've never seen anything like this before.  On the other hand, the keyboard shortcut part of the Keyboard PreferencePane and the shortcuts created have been buggy with weird side-effects since---I kid you not---Panther :smile:

**Comment by chdiza** [comment]
@douglasdrumond @jpetrie @splhack I think maybe this issue should be reopened, or better,  a new one created describing the problem and referencing the current issue.  We can give it a special label to keep it separate from the "usual" issues.

Regardless of what we four think about this particular issue, I think we should decide on our general policies for issue management.

**Comment by TheDudeWithTheThing** [comment]
I'm happy to help with testing / troubleshooting as well so keep me in the loop if you like.

**Comment by zhm** [comment]
Is this resolved? It's marked closed but I see this after using MacVim for a while:

![Enter Full Screen](https://cldup.com/whRjkO0LN7.png)
