### ISSUE TITLE
Non Native Full Screen :q bug

### ISSUE THREAD

**Issue by amadeus** [macvim-dev/macvim#1515]
### Steps to reproduce

Ensure you have `non-native` full screen enabled

1. `set fu`
2. `:q`
3. Notice black screen 

https://github.com/user-attachments/assets/a68f33dc-13d8-4a07-b068-33efd66066a2

### Expected behaviour

Window should be closed

### Version of Vim and architecture

9.1.873

### Environment

macOS: 14.7.2 (23H311)

### How MacVim was installed

Built from source

### Issue has been tested with given configuration

- [X] by running MacVim.app from GUI macOS interface
- [ ] by running vim/gvim/etc installed by MacVim
- [ ] by running other versions of vim (e.g. /usr/bin/vim)

### Issue has been tested with no configuration

- [ ] by running `mvim --clean` (or `gvim`, supplied by MacVim distribution)
- [ ] by running `vim --clean` (in terminal, supplied by MacVim distribution)
- [ ] by running `vim --clean` (in terminal, other suppliers, e.g. /usr/bin/vim)

### Other conditions

- [ ] The both Homebrew packages "vim" and "macvim" are installed

**Comment by ychin** [comment]
That's weird. Seems to be a new bug (doesn't happen in the official r180). Thanks for reporting. Let me look into it. I'll make sure it's fixed before r181 and regression tested

**Comment by ychin** [comment]
Caused by #1510

**Comment by amadeus** [comment]
Thanks for the quick fix! 🙏
