### ISSUE TITLE
inputdialog broken in snapshot 81 82

### ISSUE THREAD

**Issue by chemzqm** [macvim-dev/macvim#152]
![macvim](https://cloud.githubusercontent.com/assets/251450/11296768/1c324640-8faf-11e5-8ca3-292a41bef8bd.jpeg)

I'm using https://github.com/othree/xml.vim. When using the latest version of macvim, there's no input field, it works fine when I use snapshot 77.
MacOS version is El Capitan.

**Comment by splhack** [comment]
How to reproduce

    :let a = inputdialog('test')

**Comment by splhack** [comment]
thank you for the report
