### ISSUE TITLE
Window focus loss problems

### ISSUE THREAD

**Issue by chdiza** [macvim-dev/macvim#156]
On El Capitan, make sure the preferences are set to use the old style ("non-native") fullscreen support.

Start MacVim fresh so that a window appears.  Then do Cmd-N to raise another MacVim window.  Now put that window into fullscreen.  Now do Cmd-W to close that window.

Expected behavior (and also the actual behavior on Yosemite and below): Focus goes to the the window that was opened first.

Actual behavior: While MacVim remains the active app, no MacVim window has "focus".  The titlebar and buttons are greyed out.  Cmd-`won't return focus.  Cmd-Tab-` won't return focus.  The only things that return focus are: mouse click, Cmd-Tab-release then Cmd-Tab-release.

This doesn't happen with "native" fullscreen, but I suspect that's only a side-effect of the fact that "native" fullscreen puts one on a different space, so the return to the original space rescues MacVim from this problem.

I have a hunch that this is related to the fact that on El Capitan, `:maca performClose:` doesn't perform a close.  It won't do it in a fullscreen window (of either style, native or non-native), and it won't do it in a non-fullscreen window.  (Given this, I have no idea how Cmd-W, which is mapped in menu.vim to do a `performClose:`, manages to work.)

In an effort to see if a particular commit created the focus problem, I tested some older ones.  I couldn't get one to exhibit expected behavior, and as I went back, eventually I hit a commit that wouldn't build on El Capitan.  So there's something funny about El Capitan.

I ruled out my `~/.vim` and `~/[g]vimrc` being the problem.  I can reproduce even with `mvim -u NONE -U NONE -N`.  It's not an `mvim` issue, since I can reproduce it whether MacVim is started from `mvim` or from double clicking on the app.

**Comment by chdiza** [comment]
I forgot to mention that there is no issue if before closing the fullscreen window, one exits fullscreen.  So there is something funny about how El Capitan is playing with closing the last window of a Vim instance while in fullscreen.

**Comment by ychin** [comment]
I can't seem to repro this on latest OS versions. Closing non-native fullscreen window seem to just return focus back to the other window. Closing this issue for now as it's very old, but feel free to re-open @chdiza  if you still encounter this issue.
