### ISSUE TITLE
Recent files list in app exposé broken in El Capitan

### ISSUE THREAD

**Issue by brnt** [macvim-dev/macvim#160]
Prior to elcap, using app exposé revealed live-ish, selectable images of currently open windows and also a list of recent file thumbnails along the bottom of the screen. With the update to elcap, the list of files across the bottom doesn't change after you open (and close) files. The list of files is still present, but it shows a non-changing, increasingly stale list of files. It appears to occasionally update, like if you reboot or if Finder crashes.

**Comment by windwiny** [comment]
`killall Dock` restart Dock, will refresh the recent files list.

And , `TextMate` has this problem too ,  

But, the pdf reader  `skim ` http://skim-app.sourceforge.net ,  this program will refresh recent files list on close a file, not need quit program. 

Anybody can find which API call will solve this problem?

**Comment by kodabb** [comment]
So, I haven't been dreaming, there really is a bug!

I think MacVim should be doing something like this after opening a file

``` 
[[NSDocumentController sharedDocumentController] noteNewRecentDocumentURL:[NSURL fileURLWithPath:####]];
```

This should populate the "Open Recent" and conversely the Mission Control files.

Further resources
 - http://stackoverflow.com/questions/3236529/add-to-the-open-recent-menu-an-item-that-doesnt-point-to-a-file
 - https://lists.apple.com/archives/cocoa-dev/2004/Jul/msg01168.html
 - https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSDocumentController_Class/#//apple_ref/occ/instm/NSDocumentController/noteNewRecentDocumentURL:

**Comment by splhack** [comment]
@kodabb :+1:

**Comment by windwiny** [comment]
No good.
It is  OS X 10.11.3/4 bug https://discussions.apple.com/thread/7328388?start=0&tstart=0

Anybody who can email or twitter a apple's programmer or CEO? let he fix this bug.

**Comment by jpetrie** [comment]
This doesn't appear to be a MacVim bug; MacVim updates its recent documents list correctly (as can be seen in the Open Recent menu), it's looks like the App Exposé process just doesn't refresh until the Dock reboots. 

It appears to happen with every application, including built-in Apple ones.
