### ISSUE TITLE
Problem Compiling the source code

### ISSUE THREAD

**Issue by lvcargnini** [macvim-dev/macvim#167]
Hi,

I just tried to compile the MacVim from github and using Macports, in both cases I had the same problem, the following message is log output from macports (log attached):
> ... -lpthread -framework CoreFoundation -lruby -lpthread -ldl -lobjc  -L/opt/local/lib    
>:info:build Undefined symbols for architecture x86_64:
>:info:build   "_rb_float_new_in_heap", referenced from:
>:info:build       _vim_to_ruby in if_ruby.o
>:info:build   "_rb_str_new_cstr", referenced from:
>:info:build       _ex_rubydo in if_ruby.o
>:info:build       _ex_rubyfile in if_ruby.o
>:info:build       _buffer_name in if_ruby.o
>:info:build       _vim_to_ruby in if_ruby.o
>:info:build       _get_buffer_line in if_ruby.o
>:info:build ld: symbol(s) not found for architecture x86_64
>:info:build clang: error: linker command failed with exit code 1 (use -v to see invocation)
>:info:build make[1]: *** [Vim] Error 1
>:info:build make[1]: Leaving directory >`/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_>ports_editors_MacVim/MacVim/work/macvim-snapshot-85/src'
>:info:build make: *** [all] Error 2
>:info:build make: Leaving directory >`/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_>ports_editors_MacVim/MacVim/work/macvim-snapshot-85'
>:info:build Command failed:  cd >"/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_>ports_editors_MacVim/MacVim/work/macvim-snapshot-85" && /usr/bin/make -j8 -w all >XCODEFLAGS="CACHE_ROOT=/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_editors_MacVim/MacVim/work/caches" >PYTHON=/opt/local/bin/python2.7 
>:info:build Exit code: 2
>:error:build org.macports.build for port MacVim returned: command execution failed
>:debug:build Error code: CHILDSTATUS 53871 2
>:debug:build Backtrace: command execution failed

There is any workaround or solution for this problem ?

[macports_main.log.txt](https://github.com/macvim-dev/macvim/files/57232/macports_main.log.txt)

**Comment by splhack** [comment]
The problem is inconsistency of Ruby header at compiling time and library at linking time in your system.

For MacPorts, I think you should ask the maintainer of MacVim MacPorts.

For your own build, the easiest way is just use the binary release https://github.com/macvim-dev/macvim/releases.

The second one is uninstalling all Ruby environments from your system except the system Ruby environment.

If you still want to use your time, you can set `vi_cv_path_ruby` environment variable and investigate `src/auto/config.mk` to check header include path and linker library path after configure script.

**Comment by lvcargnini** [comment]
Thanks Kazuki,
I’ll follow your advice.

Best Regards

Luis Vitorio Cargnini, Ph.D.
Research Technologist Engineer
HGST, a Western Digital Company
<luis.cargnini@hgst.com<mailto:luis.cargnini@hgst.com>>
o: 408-717-5513
[cid:A1F5F1E9-17C6-41C8-958C-18A999300485]
3403 Yerba Buena Road
San Jose, CA 95135
www.hgst.com
#LongLiveData



From: Kazuki Sakamoto <notifications@github.com<mailto:notifications@github.com>>—

Reply to this email directly or view it on GitHub<https://github.com/macvim-dev/macvim/issues/167#issuecomment-163378419>.
HGST E-mail Confidentiality Notice & Disclaimer:
This e-mail and any files transmitted with it may contain confidential or legally privileged information of HGST and are intended solely for the use of the individual or entity to which they are addressed. If you are not the intended recipient, any disclosure, copying, distribution or any action taken or omitted to be taken in reliance on it, is prohibited.  If you have received this e-mail in error, please notify the sender immediately and delete the e-mail in its entirety from your system.
