### ISSUE TITLE
Scrambled text, possibly during presence of Emoji on the same line

### ISSUE THREAD

**Issue by kgrz** [macvim-dev/macvim#169]
In the attached gif, I'm moving the cursor from the beginning of the line to the end that has an Emoji character. The scrambled text can be noticed. Although not evident in the GIF, the text scrambling can be seen if I have emoji characters in the status line (using airline plugin).

![macvim](https://cloud.githubusercontent.com/assets/400299/11709651/2c70dd56-9f3f-11e5-95fd-f4d60ae0daa3.gif)

I've opened macvim in terminal mode with the following command:

    mvim -v -N -u NONE ~/.tmux.conf

The terminal emulator used for the video recording is iTerm2 running tmux, but this also happens on OSX's Terminal.app without tmux.

OSX version: El Capitan 10.11.2
iTerm2 version: 2.9.20151117-nightly
MacVim version: Github `master` branch compiled today using Homebrew

**Comment by splhack** [comment]
MacVim can't handle the terminal rendering. You should ask it in iTerm2 community.

If MacVim GUI doesn't render the emoji properly, please let me know the UCS-2 code.

**Comment by kgrz** [comment]
Thanks for the pointer. I forgot to test it in MacVim GUI before opening this issue :facepalm: Checking on Terminal.app and seeing the issue there too suggested that it was independent of the terminal emulator. But I was wrong.
