### ISSUE TITLE
Cursor disappears on window resize/fullscreen in Yosemite

### ISSUE THREAD

**Issue by douglasdrumond** [macvim-dev/macvim#17]
_From @GoogleCodeExporter on March 16, 2015 9:25_

```
I'm using snapshot 73 in Yosemite. Whenever I resize a window or enter native 
fullscreen mode, my cursor disappears for all modes and does not reappear. 
Switching modes, entering text, etc. does not bring it back. Thanks!
```

Original issue reported on code.google.com by `dmg...@gmail.com` on 29 Oct 2014 at 5:21

_Copied from original issue: douglasdrumond/macvim#518_

**Comment by splhack** [comment]
please feel free to create a new issue if we still have the issue with Snapshot 81.
