### ISSUE TITLE
redraw/redrawstatus does not flush window.

### ISSUE THREAD

**Issue by lambdalisue** [macvim-dev/macvim#174]
`redraw` or `redrawstatus` does not flush window in MacVim so users cannot recognize the current status by indicators like "Downloading [2/5]..." or whatever. Try https://gist.github.com/lambdalisue/94d14ff706a5627d64f5 

So I add `gui_macvim_flush()` after `ex_redraw` and `ex_redrawstatus` in [this commit](https://github.com/lambdalisue/macvim/commit/701397ef18bd13f83fec37fc420a5646f4e228b9).
It seems that the issue no longer exists with that commit but I am not familiar with Vim/MacVim source code so could anyone check the side-effect and fix this problem?

Thanks :-)

**Comment by splhack** [comment]
Could you test https://github.com/macvim-dev/macvim/pull/175?

**Comment by lambdalisue** [comment]
Perfect. Thanks. I'm looking forward it to be merged ;-)

**Comment by lambdalisue** [comment]
:confetti_ball:

**Comment by chdiza** [comment]
Shouldn't this have been solved by using `:redraw!` instead of `:redraw`, rather than chaning MacVim source?

Plain Vim doesn't behave in the way that this commit (and #182) make MacVim behave.

**Comment by lambdalisue** [comment]
> Shouldn't this have been solved by using :redraw! instead of :redraw, rather than chaning MacVim source?

I don't think so. I tried `redraw!` but using `redraw!` in for loop makes screen blinking.

[Vim help](http://vimdoc.sourceforge.net/htmldoc/various.html#:redraw) said.

```
							*:redr* *:redraw*
:redr[aw][!]		Redraw the screen right now.  When ! is included it is
			cleared first.
			Useful to update the screen halfway executing a script
			or function.  Also when halfway a mapping and
			'lazyredraw' is set.
```

So `redraw` and `redraw!` is a bit different.
I tinkg calling `gui_macvim_flush_force` after `redraw` or `redrawstatus` is a correct behavior.

**Comment by chdiza** [comment]
>  but using redraw! in for loop makes screen blinking

But that's how plain Vim works.

Also, the flush_force version of this repair makes for a blinking cursor upon `:redraw`, when it didn't previously blink.

**Comment by chdiza** [comment]
The docs show that `:redraw` isn't *supposed* to completely clear and then redraw the screen.  That's what `:redraw!` is for.

**Comment by lambdalisue** [comment]
> But that's how plain Vim works.

No. At least in Vim on Ubuntu, GVim on Ubuntu, or Vim on Mac, the screen does not blink when I call `:redraw` but `redraw!`. So you cannot use `redraw!` instead of `redraw`. It's different.

https://gist.github.com/lambdalisue/94d14ff706a5627d64f5

> The docs show that :redraw isn't supposed to completely clear and then redraw the screen. That's what :redraw! is for.

No. `:redraw!` stands for to **clear first**. `redraw` should **also redraw the screen whenever called** as well but without clearing (thus the screen won't blink).

I'm not sure if calling `gui_macvim_flush_force` is a correct way but I'm sure that the previous behavior is way different from other Vim.

**Comment by lambdalisue** [comment]
And actually I noticed that `redraw!` did not work as well in revision ddc5c14 the one before the fix.

**Comment by chdiza** [comment]
> No. :redraw! stands for to clear first. redraw should also redraw the screen whenever called as well but without clearing (thus the screen won't blink).

That's what I said.  `:redraw` is not for clearing first, `:redraw!` is for clearing first.

**Comment by splhack** [comment]
@chdiza your comment "Plain Vim doesn't behave in the way that this commit (and #182) make MacVim behave. " is useless. Please provide a concrete reproduction scenario like https://gist.github.com/lambdalisue/94d14ff706a5627d64f5.

**Comment by chdiza** [comment]
At the very least, if I take that gist and :source it and run `Test2`, the behavor is different in MacVim and plain Vim.  In plain Vim (i.e., from github.com/vim/vim, `/usr/local/bin -u NONE -N`), I see the countdown from 99 echoed by single digits.  In MacVim (`mvim -u NONE -U NONE -N`) I see nothing at all echoed.  It should work in both MacVim and plain Vim.  If I run MacVim in the console, it behaves like plain Vim.

**Comment by lambdalisue** [comment]
Now I got. Yes it seems an issue on `redraw!` but `redraw`.

**Comment by chdiza** [comment]
It didn't do that prior to the flush tweaks.  I don't have time right now to see whether it was introduced in the flush or the force_flush change.

**Comment by lambdalisue** [comment]
### Expected behavior
Of https://gist.github.com/lambdalisue/94d14ff706a5627d64f5

Indicator is increasing 1 by 1 (E.g. Test: 1 -> Test: 2 -> ...) **without** blinking screen when `Test 1 (redraw)` is called.
Indicator is increasing 1 by 1 (E.g. Test: 1 -> Test: 2 -> ...) **with** blinking screen** when `Test 2 (redraw!)` is called.

### Actual behavior

##### Just before the redraw fix
revision: ddc5c148e848ca3b6113af0f994678caeb3da0dd

Both `Test1` and `Test2` hung a bit and `Test 99` is suddenly shown.

##### After the 1st redraw fix
revision: 2d3163f649caec70afcea3df950ba40eb40af568

Indicator is increasing 2 by 2 (Test: 1 -> Test: 3 -> ...) **without** blinking screen when `Test 1` is called (almost correct behavior).
Nothing is shown when `Test 2` is called.

##### After the 2nd redraw fix
revision: 05e488d36905b719a9f24a3047e511fec13b658e

Indicator is increasing 1 by 1 (Test: 1 -> Test: 2 -> ...) **without** blinking screen when `Test 1` is called (**correct behavior**).
Nothing is shown when `Test 2` is called.

### My conclusion
Both `redraw` and `redraw!` were broken and only `redraw` was fixed with recent commits. So reverting the commits won't fix the problem and further workarounds are required I guess. But I'm not really familiar with the code of Vim nor MacVim so I have no idea how :-p

### How did I change the revision (in case)

I add `:revision => "xxx"` to `brew edit macvim` and re-installed.

```ruby
head "https://github.com/macvim-dev/macvim.git", :revision => "ddc5c14"
```

**Comment by chdiza** [comment]
> with blinking screen (because of screen flush) when Test 2 (redraw!) is called.

Why is a blinking screen expected in this case?  It doesn't blink in plain Vim when I call Test2.

**Comment by lambdalisue** [comment]
because it clear the screen. try with fullscreen mode and/or a slow machine. prob your GPU is too fast to recognise i guess.
