### ISSUE TITLE
Use gui_macvim_flush_force instead of gui_macvim_flush in redraw/redrawstatus

### ISSUE THREAD

**Issue by lambdalisue** [macvim-dev/macvim#182]
It is strongly related to https://github.com/macvim-dev/macvim/issues/174

I noticed that `redraw` only affect when I call `redraw` at least twice. While I use `redraw` to update the indicator, this behavior is not expected.

While the comment of [`gui_macvim_flush`](https://github.com/b4winckler/macvim/blob/fd916f58a3723000b9d7b2e0d5657d050e4af962/src/MacVim/gui_macvim.m#L331-L339) said

    // This function counts how many times it is called and only flushes the
    // draw queue if called sufficiently often.  The first few times it is
    // called it will flush often, but the more it is called the less likely is
    // it that anything will be flushed.  (The counter resets itself if the
    // function isn't called for a second.)
    //
    // NOTE: Should only be used in loops where it is impossible to know how
    // often Vim needs to flush.  It was written to handle output from external
    // commands (see mch_call_shell() in os_unix.c).

I guess [`gui_macvim_flush_force`](https://github.com/b4winckler/macvim/blob/fd916f58a3723000b9d7b2e0d5657d050e4af962/src/MacVim/gui_macvim.m#L373) should be called istead of `gui_macvim_flush` when `redraw` or `redrawstatus` is called **while these commands stand for to update MacVim manually**.

**Comment by splhack** [comment]
#183 merged, thanks

**Comment by lambdalisue** [comment]
Thanks a lot ;-)
