### ISSUE TITLE
81a64f introduced double width for some single width characters

### ISSUE THREAD

**Issue by Shirk** [macvim-dev/macvim#184]
I recently became aware of [this thread](https://groups.google.com/d/msg/vim_mac/GIRB202h5h8/g8PK-Uj7CwAJ) in the mac_vim list.

In summary a user is complaining that suddenly his supplementary characters are rendered double width but should in fact be rendered single width.

I noticed the same for status characters used by a plugin in my setup.
Here's a screenshot of the issue:

![double width bug](https://cloud.githubusercontent.com/assets/304352/11956501/f9637038-a8ba-11e5-92e7-463acfe6e63e.png)

After some bisecting I discovered the issue was introduced in 81a64f5848676778cd76d1291a8af1fe562b556f which implemented Emoji support.
The problem seems to be a result of a few new and changed, but now too generous, character ranges in `src/mbyte.c`.

Reverting only the changes to that file I get this:

![correct rendering](https://cloud.githubusercontent.com/assets/304352/11956553/6480b434-a8bb-11e5-8666-24c1b0f1daac.png)

I had a look at the unicode ranges for Emoji and - apart for the big Emoji block `U+1F300`+ - they are scattered across blocks in `U+2300`/`U+2500`/`U+2600` und `U+2700`.

A proposed fix might be to check the output of `runtime/unicode.vim` and add the Emoji code points to the resulting `doublewidth`-table replacing the catch-all blocks that we have now.

**Comment by splhack** [comment]
I'll change mbyte.c.

**Comment by Shirk** [comment]
Anything I can give you a hand with? 

I tried it myself but for some reason my test builds would sometimes stop displaying multibyte characters correctly at all..

**Comment by splhack** [comment]
https://github.com/macvim-dev/macvim/pull/187

**Comment by splhack** [comment]
You can install the latest MacVim using https://github.com/macvim-dev/homebrew-macvim
