### ISSUE TITLE
netrw split-view focus problem

### ISSUE THREAD

**Issue by silent-e** [macvim-dev/macvim#185]
I'm having trouble with split pane focus when already having a file open and opening netrw in a newly opened split pane.  The first split pane is given focus and won't let me switch to the other pane.  Orientation of the panes doesn't matter.

I've narrowed it down to it breaking in 7.4 snapshot 79 while snapshot 77 works just fine.  I am using the binaries, not compiling from source.

### Steps to recreate

* Open a file
* Create a new split using `ctrl-w, v`, `:vsp`, `:sp`.  Whatever pleases you.  :smile: 
* use `:Explore` to open a netrw view in the new split pane
* Focus should now be in the split pane containing the file you originally opened.  switching to the new pane will not accept focus.  Clicking in the pane, keyboard commands, nothing works.

I've been able to recreate this in a brand-spanking-new install of MacVim 7.4 (79).  No customizations, nothing in a .vimrc, etc.  Snapshot #77 uses netrw v153 while #79 is using netrw v154.

I found [this stackoverflow post](https://stackoverflow.com/questions/17989747/vim-netrw-explore-window-focus-issue) that sounds a _little_ like the issue but they're able to open a file in the new Explore pane while I can't even switch focus.  The solution in there was to download a more recent version of netrw from Dr. Chip but that didn't solve it for me.  I tried Dr. Chip's v155f from November 23, 2015.

Thoughts?

(e)

**Comment by splhack** [comment]
Have you tried Vim in Terminal.app?
https://github.com/macvim-dev/macvim/wiki/Troubleshooting#test-the-original-vim

**Comment by aisapatino** [comment]
I'm having the same problem. Seems to be an issue with vim (not macvim specifically), and hasn't been fixed there as far as I can tell. See https://github.com/vim/vim/issues/484

**Comment by splhack** [comment]
ok, I close it because it is Vim issue.

**Comment by silent-e** [comment]
Yeah, confirmed.  brew-installed vim v7.4 with patches 1-963 has the same issue.  So uninstalling that and sticking with MacVim 7.4 (77) is the solution for now I guess.

(e)
