### ISSUE TITLE
opening html files gives Unknown function: htmlcomplete#DetectOmniFlavor

### ISSUE THREAD

**Issue by douglasdrumond** [macvim-dev/macvim#19]
_From @GoogleCodeExporter on March 16, 2015 9:25_

```
With the latest version pulled from GitHub I get the following error when I 
open html/erb/php file with html tags inside:

Error detected while processing 
/Applications/MacVim.app/Contents/Resources/vim/runtime/ftplugin/html.vim:
line   25:
E117: Unknown function: htmlcomplete#DetectOmniFlavor

Commenting out the line seems to fix the issue, but anyway what's the proper 
solution? 
```

Original issue reported on code.google.com by `vesti...@gmail.com` on 21 Nov 2014 at 10:48

_Copied from original issue: douglasdrumond/macvim#520_

**Comment by douglasdrumond** [comment]
_From @GoogleCodeExporter on March 16, 2015 9:25_

```
I'm also getting this error while opening html files with vim
```

Original comment by `rob.ahlb...@gmail.com` on 6 Jan 2015 at 12:04

**Comment by splhack** [comment]
please feel free to create a new issue if we still have the issue with Snapshot 81.
