### ISSUE TITLE
Tab bar graphics too large on 10.6

### ISSUE THREAD

**Issue by rhendric** [macvim-dev/macvim#191]
Just noticed this while testing the latest build:

![](https://cloud.githubusercontent.com/assets/1570964/12012559/41ae2d94-acc9-11e5-99d4-3111170ced6b.png)

Bisected down to bc134ed; looks like [Snow Leopard may not do well with COMBINE_HIDPI_IMAGES](http://stackoverflow.com/questions/12786733/retina-2x-graphics-incorrectly-being-used-on-standard-def-display-using-snow).

**Comment by splhack** [comment]
Deleting these two lines solves the issue?

- https://github.com/macvim-dev/macvim/blob/0bf0f54d5915fedeadf75b3a06d6b8e66ed53a36/src/MacVim/MacVim.xcodeproj/project.pbxproj#L662
- https://github.com/macvim-dev/macvim/blob/0bf0f54d5915fedeadf75b3a06d6b8e66ed53a36/src/MacVim/MacVim.xcodeproj/project.pbxproj#L693

**Comment by rhendric** [comment]
I also had to get the two in src/MacVim/PSMTabBarControl/PSMTabBarControl.xcodeproj/project.pbxproj.

**Comment by splhack** [comment]
#192 fixed the issue?

**Comment by rhendric** [comment]
:+1:
