### ISSUE TITLE
"E595: contains unprintable or wide character" in snapshot 88

### ISSUE THREAD

**Issue by sscherfke** [macvim-dev/macvim#197]
Since Snapshot 88, the config line `showbreak=↪` results in the error `E595: contains unprintable or wide character: showbreak=↪`. It worked in previous releases.

**Comment by junkblocker** [comment]
:+1:

**Comment by splhack** [comment]
could you try #200?

**Comment by junkblocker** [comment]
:+1: The proposed fix works for me.

**Comment by junkblocker** [comment]
There are more issues in the emoji range. See https://github.com/macvim-dev/macvim/issues/128#issuecomment-168539067 .

**Comment by splhack** [comment]
updated #200
