### ISSUE TITLE
Invalid fall-back for $VIM with custom prefix

### ISSUE THREAD

**Issue by junkblocker** [macvim-dev/macvim#198]
If I configure MacVim using 

```
/usr/bin/env CC=clang ./configure \
--with-features=huge \
--enable-gui=macvim \
--enable-fail-if-missing \
--enable-pythoninterp=dynamic \
--enable-perlinterp=dynamic \
--enable-rubyinterp=dynamic \
--enable-luainterp=dynamic \
--with-lua-prefix=/opt/brew \
--enable-cscope \
--enable-multibyte \
--with-compiledby=xxxxxx@xxxx.xxx
```

`vim --version` gives me

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  1 2016 16:58:46)
MacOS X (unix) version
Included patches: 1-1004
...
...
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
...
...
```

If I try to change it because I install MacVim in ``~/Applications`` by specifying prefix

```
/usr/bin/env CC=clang ./configure \
--prefix=/Users/abcd/Applications \    
--with-features=huge \
--enable-gui=macvim \
--enable-fail-if-missing \
--enable-pythoninterp=dynamic \
--enable-perlinterp=dynamic \
--enable-rubyinterp=dynamic \
--enable-luainterp=dynamic \
--with-lua-prefix=/opt/brew \
--enable-cscope \
--enable-multibyte \
--prefix=/Users/abcd/Applications \
--with-compiledby=xxxxxx@xxxx.xxx
```

I get

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  1 2016 16:58:46)
MacOS X (unix) version
Included patches: 1-1004
...
...
  fall-back for $VIM: "
/Users/abcd/Applications/MacVim.app/Contents/Resources/vim"
...
...
```

with an extra newline at the beginning of the `fall-back for $VIM` value.

**Comment by splhack** [comment]
It is not MacVim issue. I recommend you to ask it in Vim issues.

**Comment by splhack** [comment]
btw what is the problem? It seems it's just Vim auto line break.

**Comment by junkblocker** [comment]
It's not just inside vim via `:version`. It's showing up in `% vim --version` output, so not line break. The problem is that it looks wrong giving the impression that there is a newline prefix in the value.

**Comment by splhack** [comment]
`:version` and `--version` both uses `list_version` to output the lines https://github.com/macvim-dev/macvim/blob/master/src/version.c#L2917 , it's just line break. Anyway, you should go Vim issues if you still think it is a problem.

**Comment by junkblocker** [comment]
I will at some point.

```C
    if (*default_vim_dir != NUL)
    {
	version_msg(_("  fall-back for $VIM: \""));
	version_msg((char *)default_vim_dir);
	version_msg("\"\n");
    }
```

doesn't seem to indicate a newline should be printed. It means `default_vim_dir` has a newline before it.

**Comment by junkblocker** [comment]
Ah, never mind. I see that `version_msg` is inserting a new line if the message is longer than Columns..whatever that got calculated as. It's a cosmetic issues then. I'll skip followup.
