### ISSUE TITLE
Menlo font renders wide in MacVim GUI after recent changes

### ISSUE THREAD

**Issue by junkblocker** [macvim-dev/macvim#199]
Menlo font seems to be taking up more width than it used to. Compare rendering of any source in Textedit or Terminal with MacVim on Menlo 12 Regular.

**Comment by junkblocker** [comment]
Before EMOJI changes:

<img width="220" alt="befor emoji" src="https://cloud.githubusercontent.com/assets/20190/12076647/b8accd58-b168-11e5-801b-e9527de2b350.png">

After EMOJI changes:

<img width="250" alt="after emoji" src="https://cloud.githubusercontent.com/assets/20190/12076646/b8a6fa68-b168-11e5-9bd6-0d9c3bdddbe0.png">

**Comment by splhack** [comment]
I can't reproduce the issue.

<img width="271" alt="screen shot 2016-01-03 at 3 44 20 pm" src="https://cloud.githubusercontent.com/assets/81904/12081556/db53cb12-b231-11e5-8817-2f279b206f9f.png">

Did you follow the troubleshooting instruction? https://github.com/macvim-dev/macvim/wiki/Troubleshooting

$ killall MacVim
$ killall Vim
$ defaults delete org.vim.MacVim
$ /Applications/MacVim.app/Contents/MacOS/Vim -g -u NONE -U NONE

Then `set guifont=Menlo\ Regular:h12`.

**Comment by junkblocker** [comment]
That seems to work. MacVim preferences were the culprit.
