### ISSUE TITLE
Unable to install on 10.10.4

### ISSUE THREAD

**Issue by themightyoarfish** [macvim-dev/macvim#201]
A couple of weeks ago I successfully compiled the `features/quicklook` branch (see #126), but now when I try it, the install leaves an incomplete `.app` in my `/Applications` folder. I do it like this.

```
git clone https://github.com/macvim-dev/macvim.git
cd macvim/src
CC="xcrun clang" ./configure --with-features=Huge --enable-pythoninterp=yes --enable-multibyte --enable-rubyinterp=yes
```
I need to do the configuring like this because otherwise compilation fails, and somehow I don't get `make` to use clang otherwise.
Then
```
sudo make install
```

The result can be seen here.
![screen shot 2016-01-04 at 16 54 40](https://cloud.githubusercontent.com/assets/11613312/12093559/f324aaa4-b303-11e5-94e9-3fc8547fefae.png)

Can somebody reproduce this?

**Comment by themightyoarfish** [comment]
When I check out the linked commit, I get the same result, strangely, but I am not sure what could cause this at my end.

**Comment by splhack** [comment]
How about the official MacVim Homebrew formula https://github.com/macvim-dev/homebrew-macvim ?

**Comment by themightyoarfish** [comment]
I don't use homebrew and that also would not be educational.

**Comment by splhack** [comment]
It is not MacVim issue as you know. I recommend you to ask it in vim-mac mailing list http://www.vim.org/maillist.php .

**Comment by themightyoarfish** [comment]
> It is not MacVim issue as you know.
How can you be sure? I assume you don not reproduce this?

I installed snapshot 88 as a test and it crashes on startup (something wrong with python). Not sure if connected.

**Comment by splhack** [comment]
I'm pretty sure because MacVim uses Travis-CI for tracking regression.
- https://travis-ci.org/macvim-dev/macvim
- https://travis-ci.org/macvim-dev/homebrew-macvim

> I installed snapshot 88 as a test and it crashes on startup

why don't you create an issue with the complete crash log?

**Comment by themightyoarfish** [comment]
Hm, I rebooted, recloned and used `CC=clang` and compiled again. The `install` and `uninstall` targets still leave garbage in my `/Applications`, but in `macvim/src/MacVim/build/Release`  there is a functional `.app` now. I don't understand this.
