### ISSUE TITLE
Snapshot 89 changes spell underlining?

### ISSUE THREAD

**Issue by RichardDooling** [macvim-dev/macvim#202]
I'm used to the subtle wavy lines under spelling errors: red, green, blue. But snapshot 89 has changed them to brighter square dots?

<img width="341" alt="screen shot 2016-01-08 at 5 38 36 am" src="https://cloud.githubusercontent.com/assets/1476034/12197152/2d0fd072-b5ca-11e5-8eb2-32ca1ee188f0.png">

**Comment by splhack** [comment]
git bisect will help to blame the change.

**Comment by splhack** [comment]
how to repro it after the following?

    $ killall -9 MacVim
    $ killall -9 Vim
    $ defaults delete org.vim.MacVim
    $ /Applications/MacVim.app/Contents/MacOS/Vim -g -u NONE -U NONE

**Comment by splhack** [comment]
any update?

**Comment by RichardDooling** [comment]
As of snapshot 91 the wavy lines are back and all is well. I don't know what caused it. 

Thanks

Rick

**Comment by splhack** [comment]
ah, the reason is using MMTextView not MMCoreTextView.
