### ISSUE TITLE
Python3.4 (macports) support unavailable in El Capitan?

### ISSUE THREAD

**Issue by mawimawi** [macvim-dev/macvim#206]
Yesterday I upgraded to El Capitan and reinstalled my macports distribution.
I also disabled rootless.
I use Python 3.4 as standard python, and want to use it in MacVim too.

```
$ which python
/opt/local/bin/python
$ ls -l /opt/local/bin/python
lrwxr-xr-x  1 root  admin  24 Jan 13 09:54 /opt/local/bin/python -> /opt/local/bin/python3.4
$ ls -l /opt/local/bin/python3.4
lrwxr-xr-x  1 root  admin  73 Jan 12 12:01 /opt/local/bin/python3.4 -> /opt/local/Library/Frameworks/Python.framework/Versions/3.4/bin/python3.4
````

Now I use this configuration to install MacVim:

```
git clone git://github.com/macvim-dev/macvim.git
cd macvim/src
export LDFLAGS=-L/usr/lib
vi_cv_path_python=/opt/local/bin/python ./configure \
    --with-features=huge \
    --enable-rubyinterp \
    --enable-perlinterp \
    --enable-cscope \
    --enable-python3interp
make
open MacVim/build/Release
```

Right now, I do not have a `~/.vim` directory and also no `~/.vimrc` file which could interfere with any settings.
When opening MacVim now, I typed the following into the status bar:
`:python print('ok')`
and got the response
`E319: Sorry, the command is not available in this version`

Here is the complete output (stdout and stderr) from the configure and make commands:
https://gist.github.com/mawimawi/ad9b0b3f1258153bd488

BTW: the directory `/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/config-3.4m` does exist and contains these files:
```
-rw-r--r--  1 root  wheel  64370 Jan 12 12:01 Makefile
-rw-r--r--  1 root  wheel  15130 Jan 12 12:01 Setup
-rw-r--r--  1 root  wheel    370 Jan 12 12:01 Setup.config
-rw-r--r--  1 root  wheel     41 Jan 12 12:01 Setup.local
-rw-r--r--  1 root  wheel   3148 Jan 12 12:01 config.c
-rw-r--r--  1 root  wheel   1619 Jan 12 12:01 config.c.in
-rwxr-xr-x  1 root  wheel   7122 Jan 12 12:01 install-sh
lrwxr-xr-x  1 root  wheel     15 Jan 12 12:01 libpython3.4.a -> ../../../Python
lrwxr-xr-x  1 root  wheel     15 Jan 12 12:01 libpython3.4.dylib -> ../../../Python
lrwxr-xr-x  1 root  wheel     15 Jan 12 12:01 libpython3.4m.a -> ../../../Python
lrwxr-xr-x  1 root  wheel     15 Jan 12 12:01 libpython3.4m.dylib -> ../../../Python
-rwxr-xr-x  1 root  wheel   7396 Jan 12 12:01 makesetup
-rwxr-xr-x  1 root  wheel   2091 Jan 12 12:01 python-config.py
-rw-r--r--  1 root  wheel   3988 Jan 12 12:01 python.o
```

Any ideas why this went wrong?

**Comment by splhack** [comment]
At first, as I wrote in https://github.com/macvim-dev/macvim/wiki/Building, using configure and make is not recommended. Please use [binary release](https://github.com/macvim-dev/macvim/releases). Or please use [the official Homebrew MacVim formula](https://github.com/macvim-dev/homebrew-macvim) if you really want to build MacVim by yourself. In both ways, MacVim requires Python 3.5.x not 3.4.x, but it doesn't matter in most `py3` case. Put these lines in your `.vimrc` if you did `brew install python3`.

    let $PYTHONHOME="/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5"
    set pythonthreedll=/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/Python

Still you want to solve the issue by yourself, you can check `src/auto/*` files.

**Comment by splhack** [comment]
feel free to reopen the issue.

**Comment by mawimawi** [comment]
After a lot of trying out, testing, fishing in muddy waters, hair pulling and swearing I gave up. Right now I'm starting to use PyCharm with the vi key bindings (so I have at least some of my programming motor skills still working) for Python development. Maybe I'll try again in a few months.
