### ISSUE TITLE
MacVim Snapshot 89: Transparency broken, ghosting when scrolling

### ISSUE THREAD

**Issue by mario-grgic** [macvim-dev/macvim#207]
I can reproduce this on OS X 10.9.5 and OS X 10.11.2 with MacVim Snapshot 89.

MacVim transparency no longer works (I don't know when this was introduced though, I last used snapshot 77). I set transparency=50 and the windows contents are still rendered with no transparency applied at all. Also, once you scroll you see ghosts of previous lines. 

If you try to view version for example with :ve the output is rendered over the top of windows contents and you can barely make out the output.  

Unfortunately, it's hard to take a screenshot since the window fixes itself once the window loses focus, so I have attached the screen recording instead:

[macvim_ghosting.zip](https://github.com/macvim-dev/macvim/files/89373/macvim_ghosting.zip)

**Comment by mario-grgic** [comment]
Apparently, even though use classic render is selected the setting is not taken into account. Turning it off then on ( restarting vim each time ) fixes it.

**Comment by splhack** [comment]
thanks, fixed in #208
