### ISSUE TITLE
No py3eval

### ISSUE THREAD

**Issue by ocehugo** [macvim-dev/macvim#209]
Hi, just installed the HEAD version with home-brew and there is no py3eval. there is any specifics to enable this?

I have py3do, py3 and others.

macvim compiled with python3.5 brewed

PS: also no pyeval()

**Comment by splhack** [comment]
interesting. did you follow the instruction? https://github.com/macvim-dev/homebrew-macvim

    $ brew tap macvim-dev/macvim
    $ brew install --HEAD macvim-dev/macvim/macvim

**Comment by ocehugo** [comment]
Yes. Currently Version: HEAD is now at 9443631 MacVim Snapshot 91

The config detect everything:

`checking --enable-pythoninterp argument... no
checking --enable-python3interp argument... yes
checking for python3... /usr/local/opt/python3/bin/python3
checking Python version... 3.5
checking Python is 3.0 or better... yep
checking Python's abiflags... m
checking Python's install prefix... /usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5
checking Python's execution prefix... /usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5
checking Python's configuration directory... /usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/config-3.5m
checking if -pthread should be used... no
checking if compile and link flags for Python 3 are sane... yes
checking if -fPIE can be added for Python3... yes
`

as mentioned  i can use the python3 commands py3do/py3 except py3eval. The funny thing is that i can access the help of py3eval but the command is not available from the mvim interface:


`:py3eval()
E492: Not a editor command: py3eval()
`

I'm just porting a vim script that have a lot of calls to pyeval to py3eval and this happen

**Comment by splhack** [comment]
:let a=py3eval("'b'")

**Comment by ocehugo** [comment]
very new to this. sorry about that... i was looking into an old log file... after substituting things worked and did;t realize the usage before
