### ISSUE TITLE
Implement auto update

### ISSUE THREAD

**Issue by jonashaag** [macvim-dev/macvim#210]
As far as I can tell, no auto update mechanism is installed for MacVim. There seem to be preparations for Sparkle but it looks like it's deactivated somehow.

**Comment by douglasdrumond** [comment]
According to Björn's e-mail:

>> Any plans to have a sparkle feed for the snapshot releases, or do we
>> need to update manually?

> Automatic updates slow me down so I'm only supporting it with the stable build.

Since we're moving from snapshot to snapshot, my guess it will be low priority for now.

**Comment by splhack** [comment]
It needs extra cost. If you really want to update automatically, you can use [this](https://github.com/splhack/macvim-kaoriya/releases/download/20160114/MacVim-KaoriYa-20160114.dmg). The update information is Japanese, but it is totally based on this MacVim snapshot.

**Comment by jonashaag** [comment]
Extra cost?

Why close this issue? Isn't this something you'd like to see implemented, and even if you don't want to spend much time on it, couldn't this be contributed by someone else?

Please reopen this this issue and add any important information for anyone wanting to work on this. Thanks.

**Comment by splhack** [comment]
there are plenty of issues already, but almost no one sends pull request, except a few cases. no one wanting to work on this, I guess.

**Comment by jonashaag** [comment]
Hey, cool, thanks for adding auto update despite your previous comment! I'll try it out in the next days.

**Comment by splhack** [comment]
@jonashaag You can try it out now. I've deployed snapshot-93.

**Comment by jonashaag** [comment]
Seems to work. Awesome! Thanks!
