### ISSUE TITLE
Sparkle framework too big?

### ISSUE THREAD

**Issue by chdiza** [macvim-dev/macvim#212]
I'm looking at `/src/MacVim/Sparkle.framework/Versions`, and I see that `A` and `Current` are both dirs in their own right.  I'm pretty sure this is wrong.  Isn't it usually the case that `Current` is a symlink to `A`?  That's how it is in every case I can remember, and in every Sparkle-enabled app I currently have on my machine.  I think we're carrying double the load.

**Comment by chdiza** [comment]
It's like that in the built MacVim app, too.

**Comment by splhack** [comment]
right, thanks
