### ISSUE TITLE
how to eliminate Control m characters when pasting into command.

### ISSUE THREAD

**Issue by jordwalke** [macvim-dev/macvim#214]
When pasting into `:` commands in MacVim, I get a ton of `^M` characters. It's always bothered me and I haven't found how to disable this. Does anyone know? Shouldn't MacVim solve this when pasting?

**Comment by jpetrie** [comment]
What is it you *expecting* to happen here? Are you expecting that copy-pasting:

    set foo=1
    set bar=2

will actually execute `:set foo=1` followed by `:set bar=2`?

**Comment by jordwalke** [comment]
A couple of things:
1. If you copy/paste that first line (not the second) there's still one `^M` at the end and it makes the command invalid. There's no need for it - I would simply trim the `^M` without submitting the command, waiting for the user to hit enter.
2. If you have multiple lines, just a anything would be better than what happens right now. A couple of options would be to simply execute it as you suggest. Another would be to have Macvim (or Vim) prompt the user much like iTerm does (you are about to submit multiple lines in command mode, continue?).

 It seems like just about anything would be better than the jarring `^M` characters. Little things like this make Vim a less practical choice for new developers.

**Comment by chdiza** [comment]
I wonder if this is how gVim behaves too.  If it is, then this issue should be taken up with Vim proper

But I don't think it's behaving incorrectly.  In the Terminal.app, when pasting the two liines, the buffer has `et foo=2`, because the `^M` causes vim to execute `set foo=1`, (an illegal command) and then enter normal mode, whereupon the `s` in `set foo=2` enters insert mode.  This doesn't seem like a good way to proceed.

As neither console nor GUI mode do what you want, the fix should be common to both.  So this is a plain Vim issue.

**Comment by jordwalke** [comment]
It might be a vim issue, or not - I'm not sure. But I suspect there's a way to have MacVim solve it - perhaps by entering something like an ephemeral Ex mode that enters each line, but is ephemeral, in that hitting another enter will re-enter visual mode (paste would set up that temporary key-mapping).

**Comment by jpetrie** [comment]
Both gvim *and* regular (terminal) vim insert the `^M` characters when pasting multiple lines of text into the `:` prompt; this is consequently a feature request that should be handled at the vim level itself; I don't think it's a good idea for us to diverge from vim behavior in this context.

FWIW, you can just use `:@x` to execute the contents of register `x` to achieve this; if you have text on the pasteboard it will probably be in the `*` or `"` registers.

**Comment by chdiza** [comment]
> Both gvim and regular (terminal) vim insert the ^M characters when pasting multiple lines of text into the : prompt;

Experimentation revealed, however, that MacVim refuses to take it as a pressed <CR>, while regular vim behaves as if it was.

I agree, of course, that if this is even an issue at all, it should be raised with Vim, not MacVim.
