### ISSUE TITLE
MacVim Window Resizing

### ISSUE THREAD

**Issue by tombell** [macvim-dev/macvim#219]
Is it possible to override something in MacVim so that the Window can be freely resized regardless of columns/lines.

For example like this option in iTerm 2:

<img width="662" alt="screen shot 2016-01-26 at 00 35 41" src="https://cloud.githubusercontent.com/assets/129327/12569232/d1b5e5aa-c3c4-11e5-8c30-b62869ffe24b.png">

**Comment by splhack** [comment]
https://github.com/macvim-dev/macvim/wiki/FAQ
> My question is not answered in this FAQ. Where can I ask for help?
> After doing so you may post your question to the vim_mac(https://groups.google.com/forum/#!forum/vim_mac) Google Group if it is MacVim related

**Comment by splhack** [comment]
No, and MacVim will not support.

`:set nowrap`
