### ISSUE TITLE
MacVim messes up shell environment

### ISSUE THREAD

**Issue by douglasdrumond** [macvim-dev/macvim#22]
_From @GoogleCodeExporter on March 16, 2015 9:26_

```
MacVim adds some variables to the environment with a potentially different 
value than the existing one. For example ":!printenv" in MacVim shows me the 
following for my PATH:

PATH=/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin
:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/MacGPG2/bin:/usr/texbin

But a few lines below the following appears:

PATH=/usr/bin:/bin:/usr/sbin:/sbin

Either definition might be picked up depending on the subshell. If I do ":!zsh 
-c 'echo $PATH'", I get the first definition. If I do ":!sh -c 'echo $PATH'" 
instead, I get the second definition.

This is a problem for me because I am using xelatex which tries to execute 
another program in a shell which picks up the wrong PATH definition and cannot 
find the program anymore.

Surprisingly, it works fine (with just a single PATH definition in the 
environment) if I start MacVim with the mvim command from my interactive zsh.

I am using:
MacVim 7.4 (2013 Aug 10, compiled Nov 16 2014 19:08:01), Included patches: 1-258
zsh 5.0.7 (x86_64-apple-darwin14.0.0)
sh is GNU bash, version 3.2.53(1)-release (x86_64-apple-darwin14)

```

Original issue reported on code.google.com by `j...@hyper-world.de` on 5 Jan 2015 at 1:38

_Copied from original issue: douglasdrumond/macvim#523_

**Comment by douglasdrumond** [comment]
_From @GoogleCodeExporter on March 16, 2015 9:26_

```
See also https://discussions.apple.com/thread/6751474?start=15&tstart=0
```

Original comment by `j...@hyper-world.de` on 2 Feb 2015 at 9:53

**Comment by eirnym** [comment]
I have same variables with this commands as I see from `Terminal` (I use `zsh` for login shell), and there's no mess with environment variables. I've tried run from console (`mvim`), from `Spotlight Search`, and using `Launchpad`.

In this situation you can:
 * use script which controls variables you need
 * check your shell scripts (include login one) to see where is bug 
 * execute your program only from console 

*MacVim*: Snapshot 76
*OS X*: 10.10.4
