### ISSUE TITLE
Can't get the characters shown when using Chinese input method

### ISSUE THREAD

**Issue by chemzqm** [macvim-dev/macvim#221]
Terminal vim does show the characters
<img width="330" alt="screen shot 2016-01-27 at 11 31 47 pm" src="https://cloud.githubusercontent.com/assets/251450/12618648/c0a70f6e-c54f-11e5-8c42-9abcdb3b35fc.png">
<img width="308" alt="screen shot 2016-01-27 at 11 32 05 pm" src="https://cloud.githubusercontent.com/assets/251450/12618656/c8c401a2-c54f-11e5-94cb-93fe25bf679b.png">
I'm using MacVim snapshot-93, is it possible for MacVim to support it?

**Comment by splhack** [comment]
Have you tried `defaults delete org.vim.MacVim`?

**Comment by chemzqm** [comment]
@splhack just tried, I can see the characters.
but I can't choose chinese characters any more, looks like it's a problem with one of my plugins, it works fine if I use `mvim -N -u NONE`
