### ISSUE TITLE
macvim failed to build on 10.9.5 via homebrew

### ISSUE THREAD

**Issue by dphenderson** [macvim-dev/macvim#227]
Last 15 lines from /Users/me/Library/Logs/Homebrew/macvim/02.make:
    cd /tmp/macvim20160127-3302-1dbpgch/macvim-snapshot-94/src/MacVim/qlstephen
    /usr/bin/touch -c /Users/Shared/builds/Release/QLStephen.qlgenerator

** BUILD SUCCEEDED **

cp: qlstephen/build/Release/QLStephen.qlgenerator: No such file or directory

** BUILD FAILED **

The following build commands failed:
	PhaseScriptExecution Run\ Script build/MacVim.build/Release/MacVim.build/Script-520E0E2B1C2FBAF300949DD8.sh
(1 failure)
make[1]: *** [macvim] Error 65
make: *** [first] Error 2
see https://gist.github.com/anonymous/40d132ef9cce5ef08c80 for full logs

**Comment by splhack** [comment]
No problems https://travis-ci.org/macvim-dev/homebrew-macvim/builds/100526784
Please use the official Homebrew MacVim formula https://github.com/macvim-dev/homebrew-macvim

**Comment by dphenderson** [comment]
Built from the given link and still failing for same reason:
Last 15 lines from /Users/me/Library/Logs/Homebrew/macvim/02.make:
    cd /tmp/macvim20160127-5485-cfbegf/src/MacVim/qlstephen
    /usr/bin/touch -c /Users/Shared/builds/Release/QLStephen.qlgenerator

** BUILD SUCCEEDED **

cp: qlstephen/build/Release/QLStephen.qlgenerator: No such file or directory

** BUILD FAILED **


The following build commands failed:
	PhaseScriptExecution Run\ Script build/MacVim.build/Release/MacVim.build/Script-520E0E2B1C2FBAF300949DD8.sh
(1 failure)
make[1]: *** [macvim] Error 65
make: *** [first] Error 2

brew logs: https://gist.github.com/9b407835c0ae88fed43c

**Comment by beepscore** [comment]
I get similar failure on OSX 10.11.3
https://gist.github.com/b8e86284992253f49b65
The logged build output directory shows my previous DerivedData custom location ~/xcode-build/Release... even though in Xcode gui I changed it back to default.
Today I downloaded and installed Xcode command line tools to see if that would clear old path but it didn't.
Does ./config refer to homebrew or to xcodebuild?
Is command line xcodebuild using an incorrect config or path?
PS Thanks for working on MacVim!

Last 15 lines from /Users/stevebaker/Library/Logs/Homebrew/macvim/02.make:
    cd /tmp/macvim20160128-23022-7su5zo/src/MacVim/qlstephen
    /usr/bin/touch -c /Users/stevebaker/xcode-build/Release/QLStephen.qlgenerator

** BUILD SUCCEEDED **

cp: qlstephen/build/Release/QLStephen.qlgenerator: No such file or directory

** BUILD FAILED **

The following build commands failed:
	PhaseScriptExecution Run\ Script build/MacVim.build/Release/MacVim.build/Script-520E0E2B1C2FBAF300949DD8.sh
(1 failure)
make[1]: *** [macvim] Error 65
make: *** [first] Error 2

**Comment by splhack** [comment]
I know the reason. Supporting MacVim build on OS X 10.6 is the only reason of the issue. I'll drop it.

**Comment by splhack** [comment]
Fixed. please use https://github.com/macvim-dev/homebrew-macvim
