### ISSUE TITLE
Add link to patch?

### ISSUE THREAD

**Issue by douglasdrumond** [macvim-dev/macvim#23]
_From @teoric on April 2, 2015 8:15_

The README file mentions “*patch vim7 src with MacVim patch*”, but does not indicate where the patch is. For inattentive people like me, it would be great if we were set on the right path.

_Copied from original issue: douglasdrumond/macvim#531_

**Comment by jpetrie** [comment]
I don't see this in README_mac.txt or the main repository README; I'm fairly certainly whatever it was referring to is outdated.
