### ISSUE TITLE
Does MacVim build against a custom Python Framework?

### ISSUE THREAD

**Issue by symbolix** [macvim-dev/macvim#233]
Hi,

I would like to check if there is an update regarding this issue. When I tried to compile MacVim from source, against my own Python, some time ago, I was not able to do so due to a problem in one of the make files. So I had to compiled against the default system Python.

Here is my original question:

[MacVim does not build against a custom Python Framework](http://stackoverflow.com/questions/23817871/macvim-does-not-build-against-a-custom-python-framework)

Will MacVim compile against a custom Python Framework provided that the correct compiler flags are supplied?

No homebrew. No macports.

Thanks.

**Comment by splhack** [comment]
Please take a look at https://github.com/macvim-dev/macvim/pull/220#issuecomment-175119658

**Comment by symbolix** [comment]
Thanks. However, that answer on that issue #220 is not very clear to me. Could you please help me with this? I am trying to figure out if things will work when I attempt to run configure against a custom Python Framework location. So the question is, "Is that option available?" or should I stick to the system wide Python Framework. Thanks.

**Comment by splhack** [comment]
Sorry I don't get what you don't understand. Have you read https://github.com/macvim-dev/macvim/pull/220#issuecomment-175119658 ?

**Comment by symbolix** [comment]
Yes. I am trying to figure out if I can point the configure script to a custom Python Framework location. For example, to compile against my own LUA, I would use this:

    --with-lua-prefix=/Users/me/apps/Darwin64/lua-5.2.3-clang-500.2

so the question is: `Is the option for compiling against a custom Python location working in the latest build?`

So when I do this:

    otool -L ./MacVim.app/Contents/MacOS/Vim | grep "Python"

I get this:

    /Users/me/apps/Darwin64/python2.7/lib/python2.7

Instead of this:

    /System/Library/Frameworks/Python.framework/Versions/2.7/Python

Thanks.

**Comment by splhack** [comment]
> Is the option for compiling against a custom Python location working in the latest build?

Yes. I totally don't understand why you asked it, I already wrote it in https://github.com/macvim-dev/macvim/pull/220#issuecomment-175119658.

**Comment by symbolix** [comment]
Thanks for your time and for your patience. What I see in your answer is:

item_1 of #220: This item explains how to use this as a binary release and some `.vimrc` changes. This is not a solution for me, as I would like to compile my own MacVim.

item_2 of #220: This item explains the Homebrew solution. I do not want to use Homebrew.

item_3 of #220: This is not relevant to my question.

Sorry, however none of these seems to be answering my question.

Once again, thank you for your help.

**Comment by splhack** [comment]
So you didn't recognize how to specify Python framework path at all? Really?

    vi_cv_path_python3=/usr/local/Frameworks/Python.framework/Versions/3.5/bin/python3
    vi_cv_dll_name_python=/usr/local/Frameworks/Python.framework/Versions/2.7/Python
    vi_cv_path_python=/usr/local/Frameworks/Python.framework/Versions/2.7/bin/python
    vi_cv_dll_name_python3=/usr/local/Frameworks/Python.framework/Versions/3.5/Python
    ./configure \
        --enable-pythoninterp=dynamic \
        --enable-python3interp=dynamic \
        --with-python-config-dir=/usr/local/Frameworks/Python.framework/Versions/2.7 \
        --with-python3-config-dir=/usr/local/Frameworks/Python.framework/Versions/3.5

**Comment by symbolix** [comment]
vi_cv_path_python3=/usr/local/Frameworks/Python.framework/Versions/3.5/bin/python3
    vi_cv_dll_name_python=/usr/local/Frameworks/Python.framework/Versions/2.7/Python
    vi_cv_path_python=/usr/local/Frameworks/Python.framework/Versions/2.7/bin/python
    vi_cv_dll_name_python3=/usr/local/Frameworks/Python.framework/Versions/3.5/Python

Well, those `vi_cv_` bits, I did not recognise. Are they ENV variables that I need to set before the build process? or are they Homebrew specific flags?

The rest is clear. Let me make it clearer:

    --with-python-config-dir=/usr/local/Frameworks/Python.framework/Versions/2.7

I have already used that. However, it was not working back in the days.

Some time ago, when I compiled MacVim, that `configure` flags did not have any effect on the final compiled application. Please see this post from the old dev forum:

[MacVim builds against a custom Python Framework, but eventually the default Python.Framework is what gets linked?!](https://groups.google.com/forum/#!topic/vim_dev/PjiyyqGsH-M/discussion)

The question that I intended to ask and probably failed to do so is, have this issue been fixed with the new development cycle of MacVim.

If you check the link, it reads as:

    This is a known issue with MacVim, and if you look in the vim_mac mailing list
    (which, by the way, is the appropriate place to report bugs in MacVim in the future),
    you will find that the maintainer refuses to fix it.
    (In his defense, he is happy to incorporate a fix if someone else will do the work,
    and nobody has taken him up on it).

He meant that the Python part was hardcoded as the system python, and custom python locations were being ignored.

Thanks. Sorry for the trouble.

**Comment by splhack** [comment]
> ENV variables that I need to set before the build process

Yes. I don't think I have to say that the path may vary with your system.

**Comment by symbolix** [comment]
Of course. Sure. Thanks for your time.
