### ISSUE TITLE
Guioptions reset after startup files are executed

### ISSUE THREAD

**Issue by steerio** [macvim-dev/macvim#238]
Hi,

the latest version, 7.4 (96) will reset guioptions to a default value after starting up, i.e. ignoring settings that I make in .gvimrc or .vimrc.

I issue `set guioptions-=erL` there, yet the value is `egmrL` after startup. Doing it again by hand will set the proper value.

**Comment by jpetrie** [comment]
This is _probably_ a vim bug, MacVim doesn't do anything to set this. What is the result of `:verbose set guioptions?" for you?

**Comment by jpetrie** [comment]
The default for `guioptions` is `egmrLtT`. The substring "erL" isn't present in that default value, so you can't remove it with `-=`. This is why it is recommended that you remove flag values one at a time (see `:help remove-option-flags`).

If you remove each flag one at a time, as in

    set guioptions-=e
    set guioptions-=r
    set guioptions-=L

then when you run MacVim, `:set guioptions?` prints `gm`, as it sounds like you want.
