### ISSUE TITLE
regex issue

### ISSUE THREAD

**Issue by ronaaron** [macvim-dev/macvim#239]
In MacVim, the regex  "[^"]\{-}" seems to ignore the "minimal" aspect of the match, and instead matches maximally, while in plain vim this is not the case.  So e.g.

"hi" something "there"

will match the entire string in MacVim, but in standard vim only "hi" and "there" are matched.  This is most noticeable when "hls" is on.

**Comment by splhack** [comment]
Please report in https://github.com/vim/vim/issues for Vim issues.

**Comment by chdiza** [comment]
@ronaaron said that plain Vim does not exhibit the incorrect behavior, while MacVim does.  That means the place to report it is right here.

**Comment by ronaaron** [comment]
body p { margin-bottom: 0cm; margin-top: 0pt; } 
  
  
    Yes, it happens on MacVim but not on standard vim.  
    
    
    On 09/02/2016 00:57, chdiza wrote:
    
    
      @ronaaron said that plain Vim does
        not exhibit the incorrect behavior, while MacVim does. That
        means the place to report it is right here.
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
    
    
    -- 
      
        
          Ron Aaron, CTO
          Aaron High-Tech, Ltd.
          +1 425.296.0766
          +972 52.652.5543
          GPG Key: 91F92EB8

**Comment by splhack** [comment]
@ronaaron Do you actually check https://github.com/vim/vim ? What is the version of "standard vim"?

**Comment by ronaaron** [comment]
Yes. 


I use vim (the most recent version built from the vim repo) every day. 


I also use MacVim (also the most recent version) every day.  So I can
categorically state that the behavior is different.

**Comment by splhack** [comment]
@ronaaron What is the version of vim?

**Comment by ronaaron** [comment]
7.4.1290, same as the MacVim I'm running right now.  Just like I said
before.

**Comment by splhack** [comment]
@ronaaron Can you create a vim script for reproducing the issue?

**Comment by ronaaron** [comment]
No.  The "matchstr()" function works correctly, but doing the same from
normal mode "/" does not


Here's what I tried w/ a script:


let m1 = matchstr('"one" "two"', '"[^"]\{-}"')
if (m1 == '"one"')
    echo "OK"
else
    echo "BAD: " . m1
endif

**Comment by splhack** [comment]
@ronaaron I can't repro the issue.

https://github.com/macvim-dev/macvim/wiki/Troubleshooting

$ killall MacVim
$ killall Vim
$ defaults delete org.vim.MacVim
$ /Applications/MacVim.app/Contents/MacOS/Vim -g -u NONE -U NONE

Can you explain the exact detail how to reproduce the issue from here.

**Comment by ronaaron** [comment]
OK.  It seems that the actual problem was "cpoptions=Bes" on my MacVim
setup.


Omitting the 'c' from there caused the problem.
