### ISSUE TITLE
colorschemes are all slightly off

### ISSUE THREAD

**Issue by acidjazz** [macvim-dev/macvim#241]
I have done a ton of research on making my .vimrc perfect and I am still getting slightly off-color differences, here is an example of the gruvbox colorscheme in MacVim compared to VIM in iterm2:

![image](https://cloud.githubusercontent.com/assets/967369/12972137/5d9b06ba-d057-11e5-984d-e0af20056dae.png)

Above is VIM using the proper blue () where as MacVim does not inherit that color

**Comment by splhack** [comment]
Please use vim_mac mailing list.
https://github.com/macvim-dev/macvim/wiki/FAQ

> My question is not answered in this FAQ. Where can I ask for help?
> After doing so you may post your question to the vim_mac(https://groups.google.com/forum/#!forum/vim_mac) Google Group if it is MacVim related

**Comment by acidjazz** [comment]
Actually I'm pretty sure it's a bug, its easily duplicatable and there are no solutions

**Comment by splhack** [comment]
Could you explain how to repro the issue, what the difference from the screen shot from https://github.com/morhetz/gruvbox/wiki/Gallery ?

**Comment by chdiza** [comment]
I don't think one can expect a colorscheme to look exactly the same in MacVim as it does in a console Vim.

**Comment by acidjazz** [comment]
Yes @chdiza I agree and you can tell the oranges and the reds are off a bit, but what I'm more concerned about is the complete different color being chosen which is the bug @splhack , the parenthesis in VIM for any OS and GVIM on Linux are blue, but in MacVim they appear to be grey.

I did a lot of testing with completely fresh installs of VIM, MacVim, VIMR, and GVIM on OSX and Linux, same vimrc's, various TERM settings and making sure t_co was 256, etc. No matter what MacVim still rendered the parenthesis in grey, where as VIM and GVIM (which is a GUI) kept the original blue which matches the screenshots and also on vimcolors.com

One other point that was odd is this bug is also reproducable with VIMR on OSX

**Comment by notnyt** [comment]
*rings bell* SHAME

https://github.com/morhetz/gruvbox/blob/master/colors/gruvbox.vim#L106

256 color terminals represent their colors in an arbitrary way.
GUI vim uses the specified color

**Comment by acidjazz** [comment]
haha @notnyt beat me to it, yea that .light3 should be #a8a8a8 to properly represent the cterm value 248. TIL not all colorschemes properly map hex to cterm.

**Comment by splhack** [comment]
> No matter what MacVim still rendered the parenthesis in grey, where as VIM and GVIM (which is a GUI) kept the original blue which matches the screenshots and also on vimcolors.com

@acidjazz Could you create a new issue about that if you still think it is problem? The issue should include the following.

- Minimal setting to reproduce the issue with `-u NONE -U NONE` option
- The ideal screenshot and MacVim screenshot
- Actual RGB value of the parenthesis from the ideal screenshot and MacVim screenshot

**Comment by notnyt** [comment]
@splhack  the theme he was using specified a different gui value vs cterm color value.  nothing to see here.
