### ISSUE TITLE
Merges and commit messages

### ISSUE THREAD

**Issue by chdiza** [macvim-dev/macvim#242]
Commit bd7d4b42889e1559f44 is recorded as "Merge remote-tracking branch 'vim/master'.  And yet, it has changes to src/MacVim/* in it.

I'm curious as to how a change to src/MacVim is part of a commit called a "merge" with plain Vim.  A real merge would only include changes made in plain Vim, right, since plain Vim doesn't have a src/Macvim directory?

When a change to src/MacVim is buried in a commit recorded in the log as a merge with plain Vim, it gets "lost".  There is no commit message in `git log` which indicates, *just in the message part*, that src/MacVim was changed.  This requires more work on the part of the user to discover which commits might have touched MacVim-specific files.

Please keep merges with plain Vim separate from MacVim-specific commits.

**Comment by splhack** [comment]
It is a part of MacVim development.

**Comment by chdiza** [comment]
Good answer!
