### ISSUE TITLE
Configure script does not check whether compiler can compile Obj-C

### ISSUE THREAD

**Issue by themightyoarfish** [macvim-dev/macvim#246]
If I run `./configure`, the script will set gcc as the compiler to use and then fail when I run `make`. I thought gcc6 could compile Objective-C code, but apparently it does not as evidenced by the errors when setting `CC=gcc`. I need to run `CC=clang ./configure` to compile with clang. It is not sufficient to set `CC` before running the configure script, although `echo $CC` prints `clang`. Is this intended?

**Comment by splhack** [comment]
Using `configure` directly is not recommended way to build MacVim.
Still you want to use it, please read the document https://github.com/macvim-dev/macvim/wiki/Building-%28not-recommended-way%29 .
And please please use vim_mac mailing list https://groups.google.com/forum/#!forum/vim_mac if you still have question about `configure`.

**Comment by chdiza** [comment]
You shouldn't need to do any setting of `CC` before configure.

But if the `./configure` script is picking up a nonstandard compiler on your system, either it should be fixed or a workaround found.  In this case, my hunch is the latter.  Maybe temporarily remove all nonstandard compilers (things that don't just come with XCode7) from your `PATH`.

While one shouldn't be forced to use a package manager just to build MacVim, it's also the case that the `./configure` script can't be expected to handle every idiosyncratic setup.

**Comment by themightyoarfish** [comment]
I agree that it is unrealistic to accomodate every possible setup, but I 
don't think having multiple compilers installed counts as an unusual 
configuration. As such I find it strange that I should be the only one 
with this problem. Maybe the problem is something else or the priority 
in my particular `PATH`.

chdiza wrote:

**Comment by themightyoarfish** [comment]
I agree that it is unrealistic to accommodate every possible setup, but I
don't think having multiple compilers installed counts as an unusual
configuration. As such I find it strange that I should be the only one
with this problem. Maybe the problem is something else or the priority
in my particular `PATH`.
