### ISSUE TITLE
make install does not install app correctly

### ISSUE THREAD

**Issue by themightyoarfish** [macvim-dev/macvim#247]
I cloned commit 4cc617ec77304c32aa35f453b7bbb7670da5b867 and compiled like this:

``` 
CC=clang ./configure
make
sudo make install
```

I then have an app in `/Applications`. But I can't open it, because OSX claims it is damaged.
![screen shot 2016-02-20 at 15 08 52](https://cloud.githubusercontent.com/assets/11613312/13197111/0bd2a66e-d7e4-11e5-848a-5a1fd93212e8.png)

The app in `macvim/src/MacVim/build/Release/MacVim.app` does work though.

OSX version: 10.10.5

**Comment by splhack** [comment]
Please read the document https://github.com/macvim-dev/macvim/wiki/Building-%28not-recommended-way%29 . It explains everything. And you are doing what is not recommended to build MacVim.
