### ISSUE TITLE
Auto-Updater could completely delete the old app dir

### ISSUE THREAD

**Issue by tobireif** [macvim-dev/macvim#248]
Great to see that MacVim became auto-updating! 

The update process leaves the old MacVim app dir in .Trash/ . I'd prefer it if it would clean up completely.

**Comment by splhack** [comment]
Sparkle does that, and I don't want to change it.
https://github.com/sparkle-project/Sparkle/blob/3c957096c64de93c93c9c49e7ebd3bbe254ee2a8/Sparkle/SUPlainInstaller.m#L144
