### ISSUE TITLE
Lost the ability to quicklook .tex files

### ISSUE THREAD

**Issue by themightyoarfish** [macvim-dev/macvim#249]
After #125, MacVim had the ability to quicklook all plain text file formats, including `.tex` files. But apparently, this does not work anymore. I compiled from ccd65be and there is no quicklook for `.tex` while other formats still work.

**Comment by splhack** [comment]
It's not possible from MacVim and QLStephen side. The following may fix the situation but it totally depends on your settings.

    $ qlmanage -r
    $ qlmanage -r cache
    restart Finder

**Comment by themightyoarfish** [comment]
This fixed it for me, many thanks.
