### ISSUE TITLE
MacVim window doesn't open when opening files from Finder, mvim from terminal works

### ISSUE THREAD

**Issue by jwmann** [macvim-dev/macvim#252]
I recently upgraded to El Capitan (10.11.3) and run the homebrew macvim.
I have the latest version running 7.4-98

Here's what's up.

#### Scenario 1 
I can open my alias inside `/Applications` that I linked using `brew linkapps macvim`.
MacVim totally works fine. I can open files from Finder and it will load in a new buffer in MacVim.

#### Scenario 2
When MacVim is not already open. I will open a file from Finder.
MacVim Starts, you can see a window *flash* on the screen, and then nothing. MacVim can't open any windows, not even new plain windows.

#### Scenario 3
Interestingly, if I run `mvim ~/myfile_I_want_to_open.txt` in the terminal, it opens MacVim _just fine_ and will work just the same as Scenario 1

So it seems like Finder just doesn't like opening MacVim right now.

Any ideas?

**Comment by splhack** [comment]
sounds the same as https://github.com/macvim-dev/macvim/issues/109

**Comment by jsfranko** [comment]
Typing gvim after a brew install MacVim (7.4 as of this post) opens MacVim and shows an icon in the macOS dock.  right click it and choose options and keep in dock.  it also shows up in the context menu right clicking a file in the finder.  you an also drag a doc to the icon in the dock.  I removed the Vim.app that was installed in the applications folder.  it crashed after bouncing a few times in the dock.  vim at the command line opens a shell vim.
