### ISSUE TITLE
Ruby files in Rails project replace each other in the buffer list

### ISSUE THREAD

**Issue by theunraveler** [macvim-dev/macvim#255]
Hello. After upgrading to Snapshot 98, I'm seeing a bug where opening a ruby file in the directory of a rails project, then opening another, replaces the first file in the buffer list.

The bug happens when I do the following, after removing all of my local vim configuration (`mv ~/.vim ~/.vim.bak && mv ~/.vimrc ~/.vimrc.bak`):

- First I open MacVim in my project directory, which opens the directory in `netrw`: `mvim .`
- Then, I navigate to a ruby file (`app/controllers/users_controller.rb` or whatever)
- Then, I go back to `netrw`: `:Explore`
- I navigate to a new ruby file (`app/models/user.rb` or whatever)
- The first file is now no longer in my list of buffers (`:ls`).

The bug is *not* present under the following conditions:

- When using Snapshot 97
- When launching MacVim with the `-u NONE` option (`mvim -u NONE .`). This leads me to believe that the bug is a result of something that MacVim adds at runtime.
- When editing 2 random ruby files in the same directory. I tried to reproduce the issue with just a random directory containing 2 ruby files, but the issue did not occur.
- When calling `:e` on the two files (i.e. `:e app/controllers/users_controller.rb`, then `:e app/models/user.rb`). This makes me think that `netrw` is involved in the bug in some capacity.

Any thoughts or pointers? Sorry about the mysterious bug report--I'm happy to try and reproduce the issue under different conditions if you'd like, or to provide you with more information about my environment if you need.

Thanks!

**Comment by theunraveler** [comment]
> When launching MacVim with the -u NONE option (mvim -u NONE .).

Actually, this sort of leads me to believe that the issue may be something from `vim` upstream. Please feel free to close this issue if you feel that to be the case.

**Comment by theunraveler** [comment]
Actually, it seems like this might be a similar issue to https://github.com/vim/vim/issues/484, which is apparently fixed by https://github.com/vim/vim/commit/e0fa3742ead676a3074a10edadbc955e1a89153d. If nothing is coming to mind immediately for you, I can just wait until that patch version is included in MacVim to see if it fixes the problem.

**Comment by splhack** [comment]
You can try snapshot-99 now.

**Comment by theunraveler** [comment]
Just tried snapshot-99, and the issue is still there.

**Comment by splhack** [comment]
have you tried the latest vim?

**Comment by theunraveler** [comment]
I just tried this with the latest vim, and am getting the same issue. Closing this issue in favor of https://github.com/vim/vim/issues/231 from the main vim repo. Thanks, and sorry for the bogus report!
