### ISSUE TITLE
"ATTENTION" alert often appears detached and behind buffer

### ISSUE THREAD

**Issue by steakknife** [macvim-dev/macvim#256]
Usually the alert displays correctly as a view animated from top inside a buffer window.  However it often appears detached and behind the buffer in a dangling view.

**Comment by steakknife** [comment]
![img](http://content.screencast.com/users/xzxzxzxx/folders/Jing/media/ce0cfe6b-61f1-48bb-90e1-523628d5ab35/00000041.png)

**Comment by steakknife** [comment]
Looks like a race condition.

**Comment by jpetrie** [comment]
I can't reproduce this, are there other steps you're taking? I'm doing this:

 - make sure swap files are enabled in my `.vimrc`
 - run terminal vim to edit some file
 - launch MacVim, choose `File -> Open` and pick the same file

I see the `NSAlert` displayed properly and I can't get it to appear behind the document window. Are you finding it there floating around after the document has been opened and edited? Or is it only there while the `ATTENTION` is also displayed in the buffer window?

I'm on the latest `HEAD` version of MacVim, built from source.

**Comment by steakknife** [comment]
Just built HEAD from source.  I found how to reproduce this nondeterministic behavior in the following contrived but more deterministic manner.

```shell
# OS X 10.11.5 / Xcode 7.3.1
# install build from HEAD source as /Applications/MacVim.app
# move local ~/.vimrc and ~/.vim/ out of the way
cd /tmp
touch a .a.swp
for X in `seq 5`; do mvim a; done
```

After that, some ways to get out is to ⌘-q or move the unclosable document windows (because of modal NSAlerts) out of the way to answer them beneath.

I'll create a rough-draft PR which demonstrates a fix to this.

**Comment by steakknife** [comment]
Opening 50 files with alerts, not a single problem so far.  Seems to work.

**Comment by steakknife** [comment]
Closing since there's a likely fix.
