### ISSUE TITLE
Tab order gets reset after rearranging by dragging tabs to the right

### ISSUE THREAD

**Issue by kyletolle** [macvim-dev/macvim#257]
I'm using MacVim 7.4 (99).

I've got two tabs open in MacVim. I want to rearrange their order, so I drag the first tab to be after the second one. Now, I can't click on the other tab to switch to it, like I'd expect. I can continue typing in the current window, but I can't get to that other tab with the UI.

Next, I try moving tabs with  Cmd+Shift+}. The tab order gets reset to what it was before I dragged the tabs to change their order.

This only seems to be a problem when I drag a tab toward the right. If, instead of dragging the first tab to be after the second tab, I drag the second tab to be before the first one, I can use the tabs in their new order just fine. It's something about dragging one tab to be "after" another that doesn't work properly. Dragging a tab to be "before" works fine. So there's a workaround for people who have noticed this issue.

Here's a gif of what I experience:
![macvim-dragging-tab-bug](https://cloud.githubusercontent.com/assets/260869/13758767/b26f88a2-e9f0-11e5-9d52-675f50841f3b.gif)

**Comment by sfcgeorge** [comment]
This has happened for a long time for me. I thought maybe the new Yosemite style tabs would fix it but hasn't. Though it wasn't always broken I'm sure, many months ago it was fine.

**Comment by RichardDooling** [comment]
I don't know if this is related, but I use Tim Pope's Obsession. And recently MacVim is not properly saving tab info. If I move a tab using :tabm1 for example, and then exit saving session info. When I reopen the session the tabs are in the order they were in before I issued the :tabm command.

**Comment by sfcgeorge** [comment]
It seems release 100 disabled Yosemite style tabs? The actual tab style hasn't affected this bug though, I experienced it before the tab change, during, and still now that it has been reverted. It's a shame Apple doesn't provide access to their tabs widget as so many apps have issues recreating tabs well.

**Comment by alisnic** [comment]
For me, MacVim will refuse to rearrange tabs using mouse **only** if they have unsaved changes.

```
$ mvim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Mar 26 2016 06:40:26)
MacOS X (unix) version
Included patches: 1-1655
Compiled by travis@Traviss-Mac-139.local
...
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -L/usr/local/lib -L. -L/usr/local/lib  -L/usr/local/lib -o Vim -framework Cocoa -framework Carbon       -lm  -lncurses -liconv -framework Cocoa   -fstack-protector  -L/System/Library/Perl/5.16/darwin-thread-multi-2level/CORE
```

```
$ ls .vim/plugged
YouCompleteMe        devdocs.vim          nerdtree             vim-coffee-script    vim-fugitive         vim-open-alternate
ack.vim              easy-gitlab.vim      tabular              vim-colors-solarized vim-haml             vim-ruby
auto-pairs           editorconfig-vim     tcomment_vim         vim-elixir           vim-javascript       vim-sensible
ctrlp-py-matcher     file-line            tern_for_vim         vim-endwise          vim-json             vim-togglecursor
ctrlp.vim            incsearch.vim        tube.vim             vim-expand-region    vim-monokai
```
