### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by abra** [macvim-dev/macvim#259]
Trying to compile MacVim from source, but stuck on these error messages:
```
Undefined symbols for architecture x86_64:
  "_iconv", referenced from:
      _readfile in fileio.o
      _buf_write_bytes in fileio.o
      _my_iconv_open in mbyte.o
      _string_convert_ext in mbyte.o
     (maybe you meant: _my_iconv_open)
  "_iconv_close", referenced from:
      _readfile in fileio.o
      _buf_write in fileio.o
      _utf_find_illegal in mbyte.o
      _my_iconv_open in mbyte.o
      _convert_setup_ext in mbyte.o
  "_iconv_open", referenced from:
      _my_iconv_open in mbyte.o
     (maybe you meant: _my_iconv_open)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [Vim] Error 1
make: *** [first] Error 2
```
[Full log of compilation](http://pastebin.com/sMr5AiRj)
Any ideas?

**Comment by splhack** [comment]
Please use `vim_mac` mailing list first. It's not macvim issue.
https://github.com/macvim-dev/macvim/wiki/FAQ
> My question is not answered in this FAQ. Where can I ask for help?
> After doing so you may post your question to the vim_mac(https://groups.google.com/forum/#!forum/vim_mac) Google Group if it is MacVim related

Using configure and make directly is not recommended way to build MacVim.
You can use the binary release https://github.com/macvim-dev/macvim/releases/latest .
If you still want to build MacVim by yourself, use the official Homebrew Tap https://github.com/macvim-dev/homebrew-macvim .
Still you really really want to build using configure and make, please read the document first https://github.com/macvim-dev/macvim/wiki/Building-%28not-recommended-way%29 and ask `vim_mac` mailing list if you have questions.
