### ISSUE TITLE
listchars issue reappeared with the latest build in gvim

### ISSUE THREAD

**Issue by junkblocker** [macvim-dev/macvim#260]
At commit  https://github.com/macvim-dev/macvim/commit/58c7dadefc83c23fd6b41b5cfd10c9fa32fa7fa0

```
E474: Invalid argument: listchars=tab:▶⋅,trail:·,precedes:…,extends:…,nbsp:‗
```

**Comment by splhack** [comment]
You should ask it at Vim mailing list or issues.

**Comment by chdiza** [comment]
There was just a thread on Vim for this (can't remember whether it was the ML or the GH issues).  The upshot was, one must set the new option `noemoji` earlier than one sets `listchars`.

**Comment by junkblocker** [comment]
Thanks a lot, @chdiza ! That worked.
