### ISSUE TITLE
MacVim always forces tabs on bulk open

### ISSUE THREAD

**Issue by smaili** [macvim-dev/macvim#261]
I've noticed that if I open many files in MacVim simultaneously, i.e., select all files in Finder and drag to MacVim, it takes some of the files and places them in a split window rather than giving them their own tabs.

Is there a way to disable this so that every file is always opened in its own tab? I've already selected the `with a tab for each file` option in the `Open files from applications` Preferences.

The interesting thing is if I open each file one by one, then they do always get their own tab. The problem occurs when I do a bulk open.

**Comment by chdiza** [comment]
You probably just need to set `tabpagemax` to a higher number in either your `vimrc` or `gvimrc`.

Make it higher than the typical number of files in a "bulk".

**Comment by smaili** [comment]
@chdiza absolutely right!
