### ISSUE TITLE
More obvious download links please

### ISSUE THREAD

**Issue by ryenus** [macvim-dev/macvim#263]
It looks currently the github pages at http://macvim-dev.github.io/macvim/ is the place to find the download links for MacVim.

The `README.md`, being the most "obvious" place to find download links, however is a copy from VIM, which is kinda like a trap, as it points the download page to http://www.vim.org/download.php, over there, the mac download page is again pointed back to https://github.com/macvim-dev/macvim, none of them mentioned http://macvim-dev.github.io/macvim/. Which is *fortunately*, included in the project description.

**Comment by splhack** [comment]
How about it https://github.com/macvim-dev/macvim/tree/test/readme

**Comment by ryenus** [comment]
@splhack, yes!

That's the simplest solution, though more information could be added.

BTW, it took me a little while to figure out that you've updated the *README.md* in branch `test/readme`.

Thanks
