### ISSUE TITLE
How to turn off the auto-update?

### ISSUE THREAD

**Issue by xiaohk** [macvim-dev/macvim#264]
I found MacVim would lose all the non-original color scheme after updating. How can I stop the auto-update?

**Comment by jpetrie** [comment]
There should be a "Check for updates" checkbox you can toggle in MacVim's preferences. Does this not work?

**Comment by jpetrie** [comment]
That said, what do you mean by "lose all non-original color scheme after updating?" Do you mean your custom color scheme doesn't show up in the menu of generated color schemes? That you can't change to it via `:color yourscheme`? That you get an error from you `.vimrc` after updating about `:color yourscheme`? That your color scheme files are deleted (you're not putting them in MacVim's runtime file directory, are you?)

**Comment by xiaohk** [comment]
@jpetrie Thanks for your reply. I didn't check "Check for updates", but macvim would update automatically (I found old macvim would be sent to Trash). Every time this happens, all the non-original color scheme `.vim` files in the `colors` directory would disappear, so I have to download the those files again. I store the color scheme files in `/Applications/MacVim.app/Contents/Resources/vim/runtime/colors`, that may be the problem.

**Comment by jpetrie** [comment]
> I store the color scheme files in /Applications/MacVim.app/Contents/Resources/vim/runtime/colors, that may be the problem.

That is the problem. That directory is for vim/MacVim to store its built-in runtime files, you should basically never put files in there yourself. You should create a `.vim` directory in your home directory and put your color schemes there (e.g., `~/.vim/colors`). MacVim will not touch that directory when it updates. see `:help runtimepath` for more information.
