### ISSUE TITLE
Window colors broken

### ISSUE THREAD

**Issue by themightyoarfish** [macvim-dev/macvim#268]
I just compiled `master` @53793980d40e6254a82f8f38277574f151cbce7d and the colors in the MacVim window (launched with `-u NONE`) look like this:

![screen shot 2016-04-25 at 14 35 35](https://cloud.githubusercontent.com/assets/11613312/14783906/01bc638a-0af3-11e6-9559-e8782c222e66.jpg)

It happens with any colorscheme.

**Comment by chdiza** [comment]
I cannot reproduce.

**Comment by themightyoarfish** [comment]
I made `clean` and `distclean` and recompiled and the behaviour is back to normal. This is weird. Maybe I had used different compile flags before.
