### ISSUE TITLE
Copy and paste umlauts does not work

### ISSUE THREAD

**Issue by douglasdrumond** [macvim-dev/macvim#27]
_From @GoogleCodeExporter on March 16, 2015 9:26_

```
When I copy a text which includes umlauts from Preview to MacVim all umlauts 
are broken.

I can't reproduce this with the Vim version included in OSX Yosemite (which is 
Vim 7.3), using the default Terminal.app

MacVim 7.4 (73) with 7.4.540
OSX Yosemite 10.10.2
```

Original issue reported on code.google.com by `thbohn` on 2 Feb 2015 at 4:52

Attachments:
* [Screen Shot 2015-02-02 at 05.49.29.png](https://storage.googleapis.com/google-code-attachments/macvim/issue-527/comment-0/Screen Shot 2015-02-02 at 05.49.29.png)

_Copied from original issue: douglasdrumond/macvim#527_

**Comment by jpetrie** [comment]
I cannot reproduce this as of snapshot 76. I tried copy-pasting the text "fübör" (as well as writing it manually) and both displayed fine. I used my usual RC files as well as testing with `mvim -u NONE`. 

Are you setting a specific guifont that might be contributing to the problem? Or copying from a specific PDF or something in Preview that might be encoding the umlauts differently?
