### ISSUE TITLE
Startup option `-u` is ignored in GUI mode

### ISSUE THREAD

**Issue by airblade** [macvim-dev/macvim#270]
To reproduce:

- Replace the contents of your `~/.vimrc` with (or add to it somewhere) `asdfsafsdfs`.
- Launch MacVim with `mvim -u NONE -N`.
- Expected: MacVim launches and nothing happens.
  Actual: MacVim launches and about 0.5-1s later this error is output to the launching terminal:

```
$ Error detected while processing /Users/andy/.vimrc:
line    1:
E492: Not an editor command: asdfsfsf
```

I get the same behaviour with `mvim -u NORC -N`.

However there is no error with non-GUI mode, i.e. `mvim -v -u NORC -N` – which the `mvim` script converts to `/path/to/MacVim.app/Contents/MacOS/Vim -g -v -u NORC -N`.

I'm using MacVim 7.4.1795 compiled via Homebrew.

**Comment by eirnym** [comment]
Can't reproduce on latest snapshot from GitHub. 

`Custom Version 7.4 (101)`

**Comment by airblade** [comment]
I can reproduce with the latest snapshot (101) from GitHub.

**Comment by chdiza** [comment]
I can't reproduce either on a snapshot or the latest HEAD.

**Comment by chdiza** [comment]
Wait, I get it, but only if I append the argument `--help`.

However, this is not a MacVim problem.  It happens in regular vim too, so it was introduced on their end and should be reported there.

**Comment by chdiza** [comment]
Wait, scratch that.  I can't yet pin it on regular vim.

And I only get the issue intermittently.

**Comment by chdiza** [comment]
Arrrgh, mistakenly introducing a custom wrapper into the picture.  When I use "stock" `mvim`, I cannot reproduce this issue at all.

**Comment by airblade** [comment]
I rebooted my computer and tried snapshot 101 again:

```
$ mvim -u NONE -U NONE -i NONE -N
<macvim gui launches...>

$ Error detected while processing /Users/andy/.vimrc:
line    1:
E492: Not an editor command: asdfasdf
```

The error message appears in the terminal about 1 second after the gui launches.

There's no error if I add the `-v` flag:

```
$ mvim -v -u NONE -U NONE -i NONE -N
```

Here are my MacVim's details:

```
$ mvim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr  4 2016 02:34:27)
MacOS X (unix) version
Included patches: 1-1707
Compiled by travis@Traviss-Mac-165.local
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     -tcl
+balloon_eval    +folding         +mouse_xterm     +terminfo
+browse          -footer          +multi_byte      +termresponse
++builtin_terms  +fork()          +multi_lang      +textobjects
+byte_offset     +fullscreen      -mzscheme        +timers
+channel         -gettext         +netbeans_intg   +title
+cindent         -hangul_input    +odbeditor       +toolbar
+clientserver    +iconv           +packages        +transparency
+clipboard       +insert_expand   +path_extra      +user_commands
+cmdline_compl   +job             +perl/dyn        +vertsplit
+cmdline_hist    +jumplist        +persistent_undo +virtualedit
+cmdline_info    +keymap          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       +python/dyn      +vreplace
+cscope          +lispindent      +python3/dyn     +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con_gui  +lua/dyn         +rightleft       +writebackup
+diff            +menu            +ruby/dyn        -X11
+digraphs        +mksession       +scrollbind      -xfontset
+dnd             +modify_fname    +signs           +xim
-ebcdic          +mouse           +smartindent     -xsmp
+emacs_tags      +mouseshape      +startuptime     -xterm_clipboard
+eval            +mouse_dec       +statusline      -xterm_save
+ex_extra        -mouse_gpm       -sun_workshop    -xpm
+extra_search    -mouse_jsbterm   +syntax          
+farsi           +mouse_netterm   +tag_binary      
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
Linking: clang   -L. -L/usr/local/lib -L. -L/usr/local/lib  -L/usr/local/lib -o Vim -framework Cocoa -framework Carbon       -lm  -lncurses -liconv -framework Cocoa   -fstack-protector  -L/System/Library/Perl/5.16/darwin-thread-multi-2level/CORE 
```

**Comment by splhack** [comment]
Download snapshot-103, and put MacVim.app into /Applications.

    $ rm -rf ~/.vim* ~/.gvimrc
    $ echo "asdfasdf" > ~/.vimrc
    $ /Applications/MacVim.app/Contents/MacOS/Vim -g -u NONE -U NONE -i NONE -N

still happing?

**Comment by airblade** [comment]
Thank you.  It's still happening...

**Comment by splhack** [comment]
@airblade you did exactly what I wrote? really?

    $ rm -rf ~/.vim* ~/.gvimrc
    $ echo "asdfasdf" > ~/.vimrc
    $ /Applications/MacVim.app/Contents/MacOS/Vim -g -u NONE -U NONE -i NONE -N

**Comment by kopischke** [comment]
At the risk of derailing this thread I would like to remark I have observed some very odd behaviour when running MacVim with the `-u` option, albeit not a quite the same as @airblade: when testing for a plugin conflict with the above option, I did get an uninitialised instance of MacVim **and, at times* a second instance that had processed my regular `vimrc`. As it does not happen reproducibly I dismissed that as an annoyance, but this thread makes me wonder if MacVim somehow runs afoul of recent OS X versions’ rather aggressive process caching, maybe only in some configurations?

**Comment by airblade** [comment]
@splhack Yes, I did exactly that.  I just did it all over again with the same result: MacVim launches and 2s later this gets written out in the terminal:

```
$ /Applications/MacVim.app/Contents/MacOS/Vim -g -u NONE -U NONE -i NONE -N

<...2 seconds...>

$ Error detected while processing /Users/andy/.vimrc:
line    1:
E492: Not an editor command: asdf
```

**Comment by airblade** [comment]
@kopischke When I launch MacVim as per my previous comment, I see one MacVim process and two Vim processes.  Here's a screenshot from Activity Monitor:

![screen shot 2016-05-05 at 2 55 54 pm](https://cloud.githubusercontent.com/assets/7265/15045265/985e27f2-12d1-11e6-97e4-ecf471e7e991.png)

**Comment by kopischke** [comment]
@airblade yeah, I had up to three Vim processes running when experiencing the issue I described. I think we might be experiencing aspects of the same problem, and if is an OS X version / configuration / machine specific caching issue, it’s not surprising @splhack cannot reproduce.

**Comment by splhack** [comment]
You can use `opensnoop` what process opened and read `/Users/andy/.vimrc`.

**Comment by splhack** [comment]
let me know if it's still happening.
