### ISSUE TITLE
Mac Smooth Scroll 

### ISSUE THREAD

**Issue by jordwalke** [macvim-dev/macvim#271]
What would be involved in implementing platform scrolling for text windows? IIRC Bjorn had already implemented a prototype of this.

**Comment by splhack** [comment]
MacVim already have it
https://github.com/macvim-dev/macvim/blob/53793980d40e6254a82f8f38277574f151cbce7d/src/feature.h#L1391-L1396

**Comment by jordwalke** [comment]
I think I did not explain very clearly what I meant. You'll notice that MacVim still only scrolls line by line. The scrolling on Mac should scroll individual pixels. (The Emacs Mac port does this fwiw)

**Comment by splhack** [comment]
you can create a new issue, pixel by pixel scroll or something like that.
