### ISSUE TITLE
"Cannot allocate color"

### ISSUE THREAD

**Issue by tobireif** [macvim-dev/macvim#275]
Error since latest update:
```
Error detected while processing /Applications/MacVim.app/Contents/Resources/vim/runtime/colors/macvim.vim:
line   54:
E254: Cannot allocate color MacSelectedTextBackgroundColor
line  109:
E254: Cannot allocate color MacTextColor
E254: Cannot allocate color MacTextBackgroundColor
```

**Comment by jas0nwhite** [comment]
I see this, too...

MacVim
Custom Version 7.4 (102)

OS X El Capitan
Version 10.11.5 Beta (15F28b)

**Comment by xparkm** [comment]
Seeing same issue. Started happening after I let MacVim autoupdate. I completely removed my .vim/, .vimrc and .gvimrc and still seeing the errors when starting MacVim with the mvim script.
No errors though if I start gvim with either 
/Applications/MacVim.app/Contents/MacOS/Vim -g -u NONE or 
/Applications/MacVim.app/Contents/MacOS/Vim -g -U NONE or
/Applications/MacVim.app/Contents/MacOS/Vim -g -u NONE -U NONE

MacVim
Custom Version 7.4 (102)

VIM - Vi IMproved 7.4 (2013 Aug 10, compiled May  1 2016 03:47:06)
MacOS X (unix) version
Included patches: 1-1811

OS X El Capitan
Version 10.11.4

**Comment by beanwonder** [comment]
same problem here

mac os El Capitan 10.11.4
Error detected while processing /Applications/MacVim.app/Contents/Resources/vim/runtime/colors/macvim.vim:
line   54:
E254: Cannot allocate color MacSelectedTextBackgroundColor
line  109:
E254: Cannot allocate color MacTextColor
E254: Cannot allocate color MacTextBackgroundColor

MacVim version 7.4 (102)

**Comment by 0x62ash** [comment]
here too

**Comment by chdiza** [comment]
As a temporary workaround, try putting "let macvim_skip_colorscheme=1" in your vimrc, and making sure to not subsequently do `colorscheme macvim` or call any other colorscheme that uses MacVim's pseudo-colors mentioned in the error message.

Vim recently messed around with their color internals.  I'm sure this will be fixed soon.

**Comment by splhack** [comment]
could you guys check https://github.com/macvim-dev/macvim/pull/276?

**Comment by tobireif** [comment]
Do the MacVim developers get the same error? It fills the console when MacVim is started via a command.

**Comment by jas0nwhite** [comment]
After a quick test, [#276](https://github.com/macvim-dev/macvim/pull/276) seems to fix the issue.
