### ISSUE TITLE
autocommand results in nesting too deep errors

### ISSUE THREAD

**Issue by grr** [macvim-dev/macvim#277]
I was using the vim tip from here to view NFO files: http://vim.wikia.com/wiki/View_NFO-files_correctly
MacVim used to work with these, but something changed at some point and it now causes "autommand nesting too deep" errors.

    # get a sample nfo file
    wget http://artscene.textfiles.com/asciiart/NFOS/wolf.nfo
    # works as expected, no error
    vim -N -u NONE -U NONE --cmd "au BufNewFile,BufRead *.nfo set filetype=nfo" --cmd "au FileType nfo edit ++enc=cp437" wolf.nfo
    # used to work, now results in error: "autocommand nesting too deep"
    mvim -N -u NONE -U NONE --cmd "au BufNewFile,BufRead *.nfo set filetype=nfo" --cmd "au FileType nfo edit ++enc=cp437" wolf.nfo

Running with -V shows MacVim is repeatedly executing the Filetype autocommand:

    Executing BufRead Auto commands for "*.nfo"
    autocommand set filetype=nfo
    Executing FileType Auto commands for "nfo"
    autocommand edit ++enc=cp437
    chdir(/Users/me)
    fchdir() to previous dir
    "wolf.nfo" [converted] 73 lines, 5935 characters
    Executing FileType Auto commands for "nfo"
    autocommand edit ++enc=cp437
    chdir(/Users/me)
    fchdir() to previous dir
    "wolf.nfo" [converted] 73 lines, 5935 characters
    ...

Tested against latest MacVim version (snapshot-103).

**Comment by splhack** [comment]
@grr How about snapshot-105?

**Comment by splhack** [comment]
It is not MacVim issue. I recommend you to post it in https://github.com/vim/vim/issues
