### ISSUE TITLE
Tabbar appearance in fullscreen mode

### ISSUE THREAD

**Issue by 0Captain** [macvim-dev/macvim#279]
version 7.4.186
* In fullscreen mode, the Close Button and New Tab Button needs retina resolution:
<img width="188" alt="tabbar appearance" src="https://cloud.githubusercontent.com/assets/2771843/15168967/fdb1265e-1768-11e6-9a24-0d88fe8c0378.png">

* I like the newest Safari's tabbar style more :)

**Comment by jordwalke** [comment]
Have you tried the latest build? I believe this is improved significantly.
