### ISSUE TITLE
MacVim crashes opening this file

### ISSUE THREAD

**Issue by douglasdrumond** [macvim-dev/macvim#28]
_From @GoogleCodeExporter on March 16, 2015 9:26_

```
(2.  Go through the [http://github.com/b4winckler/macvim/wiki/Troubleshooting 
Troubleshooting guide] before creating a new Issue to rule out common problems 
that are not bugs.

You might want to recommend using `mvim -u NONE` instead of the manual .vimrc 
dance there.)

What steps will reproduce the problem?

Open the attached file.


What is the expected output? What do you see instead?

MacVim should display the file. system-vim can open it. I tried opening it with 
`mvim -u NONE thefile`, it still crashes.


This is with snapshot 73.


Please provide any additional information below.


```

Original issue reported on code.google.com by `thakis@chromium.org` on 20 Jan 2015 at 3:24

Attachments:
* [id:000009,sig:11,src:001475,op:havoc,rep:2](https://storage.googleapis.com/google-code-attachments/macvim/issue-526/comment-0/id:000009,sig:11,src:001475,op:havoc,rep:2)

_Copied from original issue: douglasdrumond/macvim#526_

**Comment by jpetrie** [comment]
Fixed by e878fe5a3a31ccd2d0b80cc4523d49837d0b0d60.
