### ISSUE TITLE
Vim's job_start() in MacVim stops listening to messages on channel after first message

### ISSUE THREAD

**Issue by neowit** [macvim-dev/macvim#282]
Steps to reproduce:
- given the file demo.vim

```vim
function! s:callbackWithArguments(channel, msg)
    echo a:msg 
endfunction    

function! JOB_START_1()
    call ch_logfile('channel-1.log', 'w')
    
    let command = "ping google.com"
    
    call job_start(command, {"callback": function('s:callbackWithArguments')})

endfunction 
```

- Execute in mvim: `mvim -u NONE -U NONE -N -S demo.vim`

Inspect the channel log with `cat channel-1.log` (in the shell).

Expected:

    ==== start log session ====
      0.000045 : Starting job: ping  google.com
      0.000096 on 0: Created channel
      0.002064 : looking for messages on channels
      0.021145 RECV on 0: 'PING google.com (216.58.213.142): 56 data bytes
    64 bytes from 216.58.213.142: icmp_seq=0 ttl=56 time=15.222 ms
    '
      0.022323 on 0: Invoking channel callback <SNR>109_callbackWithArguments
      0.022454 on 0: Invoking channel callback <SNR>109_callbackWithArguments
      1.024770 RECV on 0: '64 bytes from 216.58.213.142: icmp_seq=1 ttl=56 time=14.990 ms
    '
      1.024790 : looking for messages on channels
      1.024819 on 0: Invoking channel callback <SNR>109_callbackWithArguments
      2.029703 RECV on 0: '64 bytes from 216.58.213.142: icmp_seq=2 ttl=56 time=17.375 ms
    '
      2.029714 : looking for messages on channels
      2.029738 on 0: Invoking channel callback <SNR>109_callbackWithArguments
      3.030963 RECV on 0: '64 bytes from 216.58.213.142: icmp_seq=3 ttl=56 time=18.371 ms
    '
      3.030985 : looking for messages on channels
      3.031010 on 0: Invoking channel callback <SNR>109_callbackWithArguments
      4.033689 RECV on 0: '64 bytes from 216.58.213.142: icmp_seq=4 ttl=56 time=17.573 ms
    '
      4.033701 : looking for messages on channels
      4.033739 on 0: Invoking channel callback <SNR>109_callbackWithArguments
      5.035973 RECV on 0: '64 bytes from 216.58.213.142: icmp_seq=5 ttl=56 time=14.737 ms
    '
    ... and so on until you quit vim ...

Actual:

    ==== start log session ====
      0.000037 : Starting job: ping  google.com
      0.000091 on 0: Created channel
      0.005557 : looking for messages on channels
      0.020418 RECV on 0: 'PING google.com (216.58.208.142): 56 data bytes
    64 bytes from 216.58.208.142: icmp_seq=0 ttl=56 time=14.785 ms
    '
      0.020917 on 0: Invoking channel callback <SNR>111_callbackWithArguments
      0.021132 on 0: Invoking channel callback <SNR>111_callbackWithArguments
      4.025299 : looking for messages on channels

    no further messages in the log, log stops here

Compare this to `mvim -v` where everything works as expected.

MacVim 7.4.1831 from Homebrew, installed as per instructions here: https://github.com/macvim-dev/homebrew-macvim

**Comment by jpetrie** [comment]
This looks like potentially the same underlying problem as #272, which was addressed [here](https://github.com/macvim-dev/macvim/pull/281).

**Comment by neowit** [comment]
I confirm - this fix solves the problem for me. Thank you @splhack !
