### ISSUE TITLE
Switching active tabs relocates the window

### ISSUE THREAD

**Issue by rainhead** [macvim-dev/macvim#286]
As of v104, hitting ⇧⌘[ or ⇧⌘] to switch the active tab will relocate the window to the top-left corner of my left-side monitor. Clicking the tab itself works fine.

v103 does not have the issue.

Thanks for keeping this project active!

**Comment by RichardDooling** [comment]
I didn't know there was such a command. Does it do the same as gt and gT?

On Fri, May 27, 2016 at 5:13 PM, Peter Abrahamsen <notifications@github.com>
wrote:

> As of v104, hitting ⇧⌘[ or ⇧⌘] to switch the active tab will relocate the
> window to the top-left corner of my left-side monitor. Clicking the tab
> itself works fine.
>
> v103 does not have the issue.
>
> Thanks for keeping this project active!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/macvim-dev/macvim/issues/286>, or mute the thread
> <https://github.com/notifications/unsubscribe/ABaFwqtEq7ScViKCG1Rk_HHRd1PxSe_Zks5qF2ySgaJpZM4Io5yZ>
> .
>



-- 

rd

**Comment by RichardDooling** [comment]
I am using v104 and it seems to do the same as gt and gT.

I don't see the window move.

RD

On Sat, May 28, 2016 at 8:26 AM, Richard Dooling <rpdooling@gmail.com>
wrote:

> I didn't know there was such a command. Does it do the same as gt and gT?
>
> On Fri, May 27, 2016 at 5:13 PM, Peter Abrahamsen <
> notifications@github.com> wrote:
>
>> As of v104, hitting ⇧⌘[ or ⇧⌘] to switch the active tab will relocate the
>> window to the top-left corner of my left-side monitor. Clicking the tab
>> itself works fine.
>>
>> v103 does not have the issue.
>>
>> Thanks for keeping this project active!
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/macvim-dev/macvim/issues/286>, or mute the thread
>> <https://github.com/notifications/unsubscribe/ABaFwqtEq7ScViKCG1Rk_HHRd1PxSe_Zks5qF2ySgaJpZM4Io5yZ>
>> .
>>
>
>
>
> --
>
> rd
>
>


-- 

rd

**Comment by rainhead** [comment]
It's now happening inconsistently. I couldn't repro the behavior above, but I could get it to reset position when closing the second to last tab (and therefore the tab bar). I disconnected the second monitor and couldn't get it to do anything wrong with a single monitor. Then I reconnected the second monitor and I can't repro any of it.

Is there any way for me to debug this, or find some relevant information? If I knew where to set a breakpoint, I could try to get it to happen again.

**Comment by steakknife** [comment]
@rainhead Have a look at src/MacVim/MM{Vim,Window}Controller.m, especially `handleMessage::` and the various Cocoa delegate callbacks.

**Comment by splhack** [comment]
@rainhead I can't repro it. How about snapshot-105?

**Comment by rainhead** [comment]
I stopped being able to repro this as well, so *shrug*. Sorry for the bother.
