### ISSUE TITLE
MavVim & VimBox / Python problem / Py_Initialize: unable to load the file system codec

### ISSUE THREAD

**Issue by Robert-M-Muench** [macvim-dev/macvim#287]
I compiled MacVim with:

mac-pro:~ robby$ ./configure --with-features=huge --with-macarchs=x86_64 --enable-python3interp=yes --enable-cscope=yes --enable

And I use:
https://github.com/jordwalke/VimBox

but I get:

mac-pro:~ robby$ mvim
mac-pro:~ robby$ Fatal Python error: Py_Initialize: unable to load the file system codec
ImportError: No module named 'encodings'

Current thread 0x00007fff77c57000 (most recent call first):
Vim: Caught deadly signal ABRT
Vim: Finished.

Wondering where this problem comes from. There aren't any python related environment variables set.

**Comment by Robert-M-Muench** [comment]
Seems when I use:

./configure --with-features=huge --with-macarchs=x86_64 --enable-python3interp=yes --enable-cscope=yes --enable-gui=macvim

things are working much better.

**Comment by Robert-M-Muench** [comment]
Hm... sorry for spamming this issue, but it's not so easy to sort out. Seems things are better because no Python is included at all:

checking --enable-pythoninterp argument... no
checking --enable-python3interp argument... yes
checking for python3... (cached) /opt/local/bin/python3
checking Python version... (cached) 3.5
checking Python is 3.0 or better... yep
checking Python's abiflags... (cached) m
checking Python's install prefix... (cached) /opt/local/Library/Frameworks/Python.framework/Versions/3.5
checking Python's execution prefix... (cached) /opt/local/Library/Frameworks/Python.framework/Versions/3.5
(cached) checking Python's configuration directory... (cached) /opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/config-3.5m
(cached) checking Python3's dll name... (cached) Python.framework/Versions/3.5/Python
checking if -pthread should be used... no
checking if compile and link flags for Python 3 are sane... no: PYTHON3 DISABLED

So, any idea why Python3 can't be compiled in?

**Comment by splhack** [comment]
You don't need to compile MacVim to use Python 3.5.

https://github.com/macvim-dev/macvim/wiki/Python-2.x-and-Python-3.x

> MacVim binary distribution is enabled to use Python 2.7 and Python 3.5 out of the box with Homebrew Pythons (These Python 2.x and 3.x version number may vary with MacVim snapshot version. Please take a look at release description.)

Example .vimrc settings for pyenv 3.5.1.

    let $PYTHONHOME=$HOME."/.pyenv/versions/3.5.1"
    set pythonthreedll=$HOME/.pyenv/versions/3.5.1/lib/libpython3.5m.dylib

**Comment by Robert-M-Muench** [comment]
I'm using MacPorts and have added this to .vimrc

`
let $PYTHONHOME="/opt/local/Library/Frameworks/Python.framework/Versions/Current"
set pythonthreedll=/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/libpython3.5m.dylib
let g:python_host_prog="/opt/local/bin/python"
`

And get this error when starting:

`mac-pro:~ robby$ Error detected while processing /Users/robby/.vimrc:
line    2:
E518: Unknown option: pythonthreedll=/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/libpython3.5m.dylib
UltiSnips requires py >= 2.7 or py3`

**Comment by splhack** [comment]
There are no reason to use MacPorts for this case. Just Install the latest binary https://github.com/macvim-dev/macvim/releases/latest

**Comment by Robert-M-Muench** [comment]
I know, and I really don't get why it's such a mess. If I use the latest binary, I get the same problem as the first post in this issue.

Adding: let $PYTHONHOME="/opt/local/Library/Frameworks/Python.framework/Versions/Current"
to .vimrc seems to get things up & working.
