### ISSUE TITLE
Throws "Only one file name allowed"

### ISSUE THREAD

**Issue by MarkVillacampa** [macvim-dev/macvim#296]
I did not see any open or closed issue about this problem. The fix is documented in this blog post from 2011 but I still experienve this issue with the latest binary release (Custom Version 7.4 (104)).

http://blog.jameskyle.org/2011/02/vim-only-one-filename-allowed-fix/

**Comment by jpetrie** [comment]
You should probably report this upstream to [vim itself](https://github.com/vim/vim); `runtime/syntax/vim.vim` is not a MacVim-specific file and that bug, from how it's described there, appears to be something that would manifest anywhere where `s:perlpath` has a space in it.

**Comment by MarkVillacampa** [comment]
Thanks! I'll report it upstream.
