### ISSUE TITLE
`%` no longer includes the far matched fence in visual mode

### ISSUE THREAD

**Issue by jdthorpe** [macvim-dev/macvim#297]
I just grabbed the latest MacVim (version 7.4.1831) and noticed that in visual mode using the `%` command to select a block, the selection does not include the far matched paren, bracket, or brace.  For example with the cursor at the start of this line in normal mode: 

```
hello(world)
```
using `v%` to select the function call, the selection will only include `hello(world`

Curiously `d%`,  `y%`, etc.  in normal mode still do the right thing.

**Comment by jpetrie** [comment]
It seems *very* unlikely MacVim could break this; are you sure it does not happen in terminal vim as well? Does it also happen when you run without plugins/your own vimrc files?

**Comment by jpetrie** [comment]
I also cannot reproduce this locally building from source (at https://github.com/macvim-dev/macvim/commit/bdcab3eb7f01dfcae917cad2588b58baeba01f5e).

**Comment by jdthorpe** [comment]
Turns out I had this left over in my `.vimrc` from umpteen years ago when I first started using vim.  

	" SYSTEM GENERATED STUFF BELOW
	source $VIMRUNTIME/vimrc_example.vim
	source $VIMRUNTIME/mswin.vim
	behave mswin

and in `$VIMRUNTIME/vimrc_example.vim`  there is this line:

	" Add optional packages.
	"
	" The matchit plugin makes the % command work better, but it is not backwards
	" compatible.
	packadd matchit


which was the problem.

**Comment by jpetrie** [comment]
Cool, glad you sorted it out.
