### ISSUE TITLE
winrestview() bug breaks output to status line

### ISSUE THREAD

**Issue by jcordasc** [macvim-dev/macvim#298]
In MacVim v104 gui the following code will output 'foo' to the status line when pressing ```<leader>zx```, but not when pressing ```<leader>zy```:

```
function! TestZZ(restore)
  let l:winview = winsaveview()
  if a:restore == 1
    call winrestview(l:winview)
  endif
  echo 'foo'
endfunction

nnoremap <leader>zx :call TestZZ(0)<CR>
nnoremap <leader>zy :call TestZZ(1)<CR>
```

However, in the terminal version it outputs 'foo' either way.

I believe this is the same issue referenced in this thread: http://vim.1045645.n5.nabble.com/winrestview-bug-on-mac-td5716442.html

Hopefully this can be revisited given what it takes to track down a difference in behavior like this between terminal and gui.

**Comment by splhack** [comment]
@jcordasc Could you test #319 ?
