### ISSUE TITLE
void _MDItemMarkAsUsedForPath(CFStringRef): was called with a NULL path

### ISSUE THREAD

**Issue by jamyouss** [macvim-dev/macvim#299]
Hi,

I've just installed macvim with homebrew and when i have the following error when editing a file with `mvim`:
`2016-06-23 18:06:16.339 MacVim[27385:813662] Metadata.framework [Error]: void _MDItemMarkAsUsedForPath(CFStringRef): was called with a NULL path`

**Comment by jpetrie** [comment]
_Always_? Or occasionally? 

I've see that before, but I can never reproduce it when I want. It's an indirect message; `_MDItemMarkAsUsedForPath` is never called by MacVim as it's a private API. Something else is indirectly calling it.

This has been around since Mavericks, I think.

**Comment by jamyouss** [comment]
Thank you for your answer but restart fix this issue.
