### ISSUE TITLE
The 'macmeta' option has not effect when using a Greek layout

### ISSUE THREAD

**Issue by sindex** [macvim-dev/macvim#300]
Meta keybindings don't work when using a Greek layout. I'm using MacVim v104.

**Comment by chdiza** [comment]
It is both a known and documented limitation of MacVim that mappings involving "meta" are flaky and unreliable.  (See `:help macmeta`).  You can try `:set macmeta`, but over the last eight years I've found that it hardly improves the situation at all.

My guess is that it's probably got nothing to do with the Greek layout, and if setting macmeta doesn't help, you're just running into the known limitations of MacVim.

**Comment by sindex** [comment]
Editing the conditional at line 161 of the "MMTextViewHelper.m" file to include additional characters works but Meta+Greek chars keybindings now produce the corresponding Greek character. The same thing probably happens with a Cyrillic layout.

**Comment by splhack** [comment]
@sindex you mean this?

    diff --git a/src/MacVim/MMTextViewHelper.m b/src/MacVim/MMTextViewHelper.m
    index d6dedfb..d93fecc 100644
    --- a/src/MacVim/MMTextViewHelper.m
    +++ b/src/MacVim/MMTextViewHelper.m
    @@ -159,8 +159,7 @@ - (void)keyDown:(NSEvent *)event
         // Note that this implies that 'mmta' (if enabled) breaks input methods
         // when the Alt key is held.
         if ((flags & NSAlternateKeyMask) && [mmta boolValue] && [unmod length] == 1
    -            && [unmod characterAtIndex:0] > 0x20
    -            && [unmod characterAtIndex:0] < 0x7f) {
    +            && [unmod characterAtIndex:0] > 0x20) {
             ASLogDebug(@"MACMETA key, don't interpret it");
             string = unmod;
         } else if (imState && (flags & NSControlKeyMask)

**Comment by sindex** [comment]
@splhack yes
