### ISSUE TITLE
set hidden keeps netrw buffer open

### ISSUE THREAD

**Issue by ricka** [macvim-dev/macvim#303]
I believe this is an issue with Macvim, as I've tried it on my system vim on OSX as well as other vims on various Linux boxes.

Steps to reproduce:
1. No .vimrc or plugins
2. Open macvim
3. :set hidden
4. :e .
5. open any file
6. :bn

It switches to netrw's buffer still.  :bd won't kill the netrw buffer, and strangely, :bp doesn't work.

**Comment by jpetrie** [comment]
Setting `hidden` *should* keep the active buffer (netrw's in this case) open when you open another file. Hidden buffers should also show up in the buffer list and should also be switchable via `bn` and `bp`. So far this sounds like intended behavior.

`bd` seems to work fine for me, as does `bp` until I actually cycle to the netrw buffer (at which point it acts like it doesn't work, but I'd chalk this up to a bug in netrw (which is fairly buggy)).

MacVim doesn't do anything in particular here; it doesn't implement `hidden` or alter the behavior of `hidden` from regular vim.

**Comment by ricka** [comment]
For anyone else that stumbles upon this, I was able to use `:Ex` instead of `:e .` and not have this issue.
