### ISSUE TITLE
Python 2.x and 3.x not working (anymore?)

### ISSUE THREAD

**Issue by sdressler** [macvim-dev/macvim#304]
I was following the [https://github.com/macvim-dev/macvim/wiki/Python-2.x-and-Python-3.x](wiki page on Python 2.x and 3.x) to have support for both python versions. Before that, I removed all python versions on my system and used `pyenv` only. However, it seems that the link-option is not working, when Python 3.x is not installed via homebrew. That is, when typing `:ver` I get `+python/dyn` but `-python3`. Once I install python 3 via homebrew, I also see `+python3/dyn` but it will crash on e.g. `py3 print("Hello!")`.

**Comment by eirnym** [comment]
Which exact `Python` versions do you have? Have you read release notes about compatible versions?

**Comment by sdressler** [comment]
Sorry for not providing this information directly.

Python versions are: `2.7.11` and `3.5.1` both installed via pyenv and verified with `otool`. I'm using the `HEAD` of MacVim as described on the wiki page. OS X version is `10.11.4`.

**Comment by sdressler** [comment]
Maybe as note, actually I'm seeing two issues:

1. Following the wiki page, then Python 3 support is not available when I do not have Python 3 installed via homebrew. 

2. MacVim will crash when trying to use Python 3 when I additionally installed it with homebrew.

**Comment by splhack** [comment]
> 1. Following the wiki page, then Python 3 support is not available when I do not have Python 3 installed via homebrew.

I can't understand that situation. brew automatically installs `python3` if brew doesn't detect any Python 3.

> 2. MacVim will crash when trying to use Python 3 when I additionally installed it with homebrew.

Needless to say, you should use your pyenv Python 3.x if you really really want to use Python 2.x and Python 3.x at the same time.

**Comment by eirnym** [comment]
I can also suggest to `let $PYTHONHOME=/path' with path to your python's installation.
