### ISSUE TITLE
The toolbar fills the full width after updated to the lastest version.

### ISSUE THREAD

**Issue by kran** [macvim-dev/macvim#305]
I want the original style of toolbar (fixed width), is there any options to configure it ?

**Comment by jpetrie** [comment]
Can you provide screenshots of what you mean? What version were you using before?

**Comment by kran** [comment]
sorry, I mean the tabbar.

![7 4 622](https://cloud.githubusercontent.com/assets/635474/16862348/4d235cb2-4a7b-11e6-8a94-9d413086a6a4.png)

This is the older version , core vim is 7.4.622. the tabbar is fix-width.

![7 4 1831](https://cloud.githubusercontent.com/assets/635474/16862305/113afe6c-4a7b-11e6-9a72-dec197e245d8.png)

This is the lastest version, vim version is 7.4.1831, and the tabbar will fill full width of window, even there are only two tabs.

**Comment by jpetrie** [comment]
This appears to be by design, it was added by @splhack last year in https://github.com/macvim-dev/macvim/commit/e268fb8d6761cd79f254ce05cd7ed6465ecf7fb2 based on an earlier PR against Bjorne's repository.

**Comment by kran** [comment]
@jpetrie is there any way  to get the elder style ?

**Comment by jpetrie** [comment]
Not currently, no.

It's not impossible to hide this behind an `NSUserDefaults` key, but I'm not so sure committing to maintain that preference is a great idea. Every such switch we add compounds an already complicated set of interacting options, and the tabs in particular are built on a framework that we don't directly control and which is relying on a bunch of deprecated stuff. That makes me a bit wary.

What is the motivating factor for wanting to use the old tabs?

**Comment by kran** [comment]
Thank you jpetrie. 
I just like the old tabs.
It's not a big deal, so just let it go.  :)
