### ISSUE TITLE
"Special Characters..." menu item not consistent with OS X default in OS X > 10.8

### ISSUE THREAD

**Issue by ernstwi** [macvim-dev/macvim#311]
The menu item `Edit -> Special Characters...` has been renamed `Emoji & Symbols` in newer versions of OS X. The keyboard shortcut for this menu item has also been changed, from Alt-Command-T (which MacVim uses) to Control-Command-Space.

I'm not sure, but [I think](http://apple.stackexchange.com/questions/106288/how-to-disable-mavericks-emoji-shortcut) this change was made in OS X 10.9.

**Comment by splhack** [comment]
#320

**Comment by ernstwi** [comment]
Thank you for the fix!
