### ISSUE TITLE
CTRL-E behavior for completion in Insert mode

### ISSUE THREAD

**Issue by akanosora** [macvim-dev/macvim#318]
In versions prior to 7.4 (105), after typing *CTRL-N*/*CTRL-P* in Insert mode to activate completion, you can type [*complete_CTRL-E*](http://vimdoc.sourceforge.net/htmldoc/insert.html#complete_CTRL-E) to stop completion and return to the original Insert mode. It seems to me that in the latest version, even when completion is activated, pressing CTRL-E will behave as if [*i_CTRL_E*](http://vimdoc.sourceforge.net/htmldoc/insert.html#i_CTRL-E) instead of *complete_CTRL-E* which inserts the character under the cursor (from the next line) instead. I wonder if this is intended because it breaks some plugins for auto completion. If so, is there anything to change the behavior to that of previous versions?

**Comment by splhack** [comment]
https://groups.google.com/forum/#!msg/vim_dev/e2Rr8Px3qkQ/1XWiAQ0LAgAJ ?

**Comment by akanosora** [comment]
Yep, that is the issue. So it has been patched?

**Comment by jpetrie** [comment]
The fix (to core vim) was merged down in https://github.com/macvim-dev/macvim/commit/8d7a68e9fa3b4cd18a9e5709374ecda3c8947912 it looks like.
