### ISSUE TITLE
MacVim always checks for updates, even if disabled

### ISSUE THREAD

**Issue by lkuchenb** [macvim-dev/macvim#323]
I installed MacVim from source using the homebrew recipe

    brew install --with-cscope --with-lua macvim

I dont' want MacVim to install any binary updates, since I'd loose lua and cscope. However, unchecking "Check for updates" in the general preferences doesn't prevent MacVim from asking me to install updates.

Due to the nature of this problem, I can't say if it is still present in the current version (snapshot-106), but it was present in the previous version.

**Comment by splhack** [comment]
Please take a look at #262 

btw binary release https://github.com/macvim-dev/macvim/releases supports cscope and Lua out of the box.

**Comment by lkuchenb** [comment]
Thanks. Maybe the FAQ should also explain the difference between the checkbox in the settings and the user defaults system?
