### ISSUE TITLE
Incorrect syntax for .vim files

### ISSUE THREAD

**Issue by akanosora** [macvim-dev/macvim#324]
Not sure what causes this but this is how it looks like in MacVim (706)

![capture](https://cloud.githubusercontent.com/assets/9272721/17705002/72b24440-639c-11e6-8a92-25bbe08aafd5.PNG)

But in gVim Windows (7.4), it looks totally fine

![capture2](https://cloud.githubusercontent.com/assets/9272721/17705028/906e3ea8-639c-11e6-96cf-1fd4a7b0af18.PNG)

**Comment by splhack** [comment]
Could you check with exact same patch version of gVim and Vim?

**Comment by splhack** [comment]
Could you check it with snapshot-110 binary?
https://github.com/macvim-dev/macvim/releases/tag/snapshot-110

**Comment by splhack** [comment]
please let me know if it is still happening.
