### ISSUE TITLE
Why does brew version of macvim looks different in tab bar appearance?

### ISSUE THREAD

**Issue by clavichord93** [macvim-dev/macvim#329]
I used to use brew version of macvim and now switch to this origin version, but I found these two looks different in tab bar. Brew version looks in a more post Yosemite style but this origin version looks in a Mavericks style. Why does this happen?

**Comment by splhack** [comment]
please clarify the versions. what is "brew version of macvim"? "this origin version"?

**Comment by clavichord93** [comment]
when I do ```brew install macvim```, it looks like this:


when I download ```.dmg``` from github, it looks like this:

why?

**Comment by clavichord93** [comment]
both are 7.4-106.
brew version is installed with ```brew install macvim```.
origin version is downloaded from github with ```MacVim.dmg```.

**Comment by sfcgeorge** [comment]
I've also noticed this. I installed via Brew but it also keeps auto updating and so the tab styles change. "About" menu shows I'm on the latest version even though I'm seeing old style tabs.

**Comment by amw** [comment]
@splhack In case you are wondering what we're talking about. Here are tab bars from macvim-dev releases stream:

<img width="652" alt="screen shot 2016-09-09 at 17 05 44" src="https://cloud.githubusercontent.com/assets/29783/18391876/d0b57c3a-76af-11e6-8014-1b85e43f27a5.png">

And here are tab bars when compiling MacVim through Homebrew:

<img width="653" alt="screen shot 2016-09-09 at 17 02 51" src="https://cloud.githubusercontent.com/assets/29783/18391904/f8eaa05e-76af-11e6-9672-b91dca02b578.png">

**Comment by sfcgeorge** [comment]
My hunch is build machine. I'm guessing there's a compile time flag that detects the OS version being compiled on and sets the tab style accordingly. The Homebrew version is always compiled on your machine, so you get the new tabs. The release version is pre-compiled so you get the tabs of the build machine.

**Comment by splhack** [comment]
I'll change MAC_OS_X_VERSION_MIN_REQUIRED check to NSAppKitVersionNumber runtime version check for the tab bar style.

**Comment by rappazzo** [comment]
I find the new tabbar style hideous.  Can I request a config setting for the former style?  Pretty please? Or is the old style deprecated in OSX/MacOS?

**Comment by amw** [comment]
This new style is nothing like native macOS tabs. Some issues not present in apps like Safari/Finder/Pages:

1. Tab bar only holds a small, finite number of tabs. Additional tabs go into a hidden list – even the currently active tab.
2. The icons for new tab and that expansion list are custom-made and poorly aligned.

<img width="1152" alt="screen shot 2016-10-24 at 14 20 11" src="https://cloud.githubusercontent.com/assets/29783/19645581/b59d03e6-99f5-11e6-9bcb-222a82a49b46.png">
<img width="822" alt="screen shot 2016-10-24 at 14 22 24" src="https://cloud.githubusercontent.com/assets/29783/19645590/c0f7c302-99f5-11e6-8ad9-61656fe77f20.png">
<img width="132" alt="screen shot 2016-10-24 at 14 24 58" src="https://cloud.githubusercontent.com/assets/29783/19645596/cb4f4ba4-99f5-11e6-9ecc-0c598a00644c.png">

**Comment by sfcgeorge** [comment]
There wasn’t previously an official OS X tab widget, apps like MacVim did their best to copy. Now their is an official way of doing tabs (that MacVim doesn’t use yet) that looks like the new style. So the new style is consistent across Apple apps and increasingly 3rd party apps. I’m in favour of keeping it the new way, rather than going down the rabbit hole of config for every little thing. Though the new style doesn’t quite match the true Apple tabs, the colours are too light, but that could be fixed.

**Comment by rappazzo** [comment]
I am running Mavericks and I see the style in @amw's second image from the comment on Sep 9.  That is the offensive looking tab bar.  It is also missing the close button on each tab (which seems like a regression).
