### ISSUE TITLE
Pref option for changing the window title font size

### ISSUE THREAD

**Issue by tobireif** [macvim-dev/macvim#334]
A wish: It would be great if there'd be an option in MacVim Preferences for changing the GUI MacVim window title font size.

**Comment by eirnym** [comment]
@tobireif

This  #912 has been added to cover this.

**Comment by ychin** [comment]
I'm not sure if this is something we would want to support. Window title font is kind of a system-level preference, and you should change that globally. I don't think I have seen a single other editor that supports a feature like this (if you know of one though, let me know).

**Comment by eirnym** [comment]
to be honest, I don't know any app directly supporting this. I've added to the chain as @splhack has added it as a valid feature request.
