### ISSUE TITLE
Holding down navigation keys (H, J, K, L) doesn't repeat them

### ISSUE THREAD

**Issue by mocksailor** [macvim-dev/macvim#342]
In command-line Vim (normal mode), when I want to navigate a file, I can simply hold down the 'J' key and navigate downwards until the end of the file (holding down repeats the command). The issue with MacVim is that I hold down the 'J' key and it only works for one row. This means I have to keep tapping the key over and over to navigate downwards. The arrow keys work fine, only the navigation keys ('H', 'J', 'K' and 'L') seem to be affected. Also, using 'ctrl-B' and 'ctrl-F' works as expected and I get to the bottom of the document without having to constantly tap.

I know there's an issue (erm… feature) with OSX ever since Lion and holding down a key shows key alternatives instead of repeating (see http://osxdaily.com/2011/08/04/enable-key-repeat-mac-os-x-lion/) but this is not my problem. I've already deactivated the OSX pop-up. And when in insert mode I can just hold down 'J' and it repeats automatically.

If anything about my description was unclear, or if there are any questions, please ask. I really use MacVim a lot and would be thankful for a fix.

My System: 

- MacBook Pro (Retina, 13-inch, Early 2015), 
- OSX El Capitan, Version 10.11.6 (15G31)
- MacVim, Version 7.4 (107) - tested with an empty .vimrc file

**Comment by mocksailor** [comment]
I've just tested this on a different MacBook Pro (Retina, 13-inch, Early 2015) with El Capitan, version 10.11.6 (15G1004) and MacVim, version 7.4 (107). On this one it works. So the problem might just be local. I'll keep trying to figure it out.

**Comment by jpetrie** [comment]
What is your key repeat set to in System Preferences, under Keyboard?

**Comment by mocksailor** [comment]
OK, two days later it works again. I have no idea what happened, nor what fixed it. Anyway, it doesn't look like a bug anymore. Sorry for the trouble.

These are my key repeat settings but I don't think that was it. Maybe playing around with the 'ApplePressAndHoldEnabled' setting had something to do with it.

![screenshot 2016-09-08 14 44 37](https://cloud.githubusercontent.com/assets/14991122/18349686/ccb5b542-75d2-11e6-9227-c277515c0dd6.png)

**Comment by kliuless** [comment]
The `ApplePressAndHoldEnabled` does in fact affect MacVim. (reference: http://deferred.io/2015/08/03/macvim-disable-press-and-hold.html).

It's easy to disable though:
```defaults write org.vim.MacVim ApplePressAndHoldEnabled -bool false```

Nice thing about the above command is that you can still have press-and-hold enabled for other apps.

Note that you must quit the `MacVim` application and relaunch it. Before relaunching, I found a new window opened by typing `mvim` in Terminal does have the setting applied yet.

**Comment by Meuko** [comment]
> The `ApplePressAndHoldEnabled` does in fact affect MacVim. (reference: http://deferred.io/2015/08/03/macvim-disable-press-and-hold.html).
> 
> It's easy to disable though:
> `defaults write org.vim.MacVim ApplePressAndHoldEnabled -bool false`
> 
> Nice thing about the above command is that you can still have press-and-hold enabled for other apps.
> 
> Note that you must quit the `MacVim` application and relaunch it. If I didn't relaunch, but only opened a new window by typing `mvim` in Terminal, that window doesn't have the setting applied.

Late to the party but I've been having issues with scrolling around in Vim (in Iterm and Terminal) and nothing seemed to be working. I thought it was my plugins and/or vimrc settings but it ended up being this. After using:

`defaults write org.vim.ITerm ApplePressAndHoldEnabled -bool false`

Everything started scrolling smoothly.

**Comment by bugkill3r** [comment]
<img width="378" alt="Screenshot 2021-08-24 at 4 19 22 AM" src="https://user-images.githubusercontent.com/2924124/130529222-514a4357-69ef-4c61-9448-c2ab77260137.png">
For Terminal, having this Secure Keyboard Entry checked helps.
