### ISSUE TITLE
MacVim randomly slows down to a crawl

### ISSUE THREAD

**Issue by Coaxial** [macvim-dev/macvim#344]
I can't understand why, but after a while MacVim becomes incredibly slow.

Inserting a character takes a few seconds just to change modes, and then between each character being printed on screen. Same with pressing `Ctrl-L` to remove search result highlights, for example. Or when having multiple buffers open in split view, and clicking to move the cursor to a different buffer than the one it was currently in.

The only solution is to close MacVim, and reopen it with the exact same buffers. I'm sorry I don't know how to reproduce it, it seems to happen randomly. If there is any way for me to get some debug information when it's happening, LMK how and I'll post the information the next time it occurs.

Using MacVim 7.4 (107) on OS X 10.11.6

**Comment by afshinm** [comment]
I have this issue, too. But I think mine because of the plugins.

**Comment by guenti** [comment]
Same here (macOS 10.12, MacVim Snapshot 113), esp. if the file has 100+ lines. MacVim becomes useless for me. Typing has a delay of 1 second or more and scrolling is really slow.

Vanilla Vim 8.0.46 (without GUI), with the same config and plugins, is fast as aspected.

**Comment by splhack** [comment]
It sounds because you have many plugins or some heavy plugin. Please reopen it if you are still confident MacVim itself is the reason of that.

**Comment by philipn** [comment]
This is definitely happening to me as well. After using MacVim for a day or two it becomes unusable until it's restarted. No specific event seems to trigger it. I'll be using MacVim and everything works fine, close my laptop for a day, open my laptop and drop back into MacVim and it'll be unbearably slow.

Maybe it has to do with the update / update-notification functionality?

**Comment by philipn** [comment]
I've verified that this happens with no plugins installed. After a day or two, MacVim will slow to a crawl.

But the weird thing is is, it *only* seems to happen if I open a new tab (control+T) without specifying a new file name.  If I open an existing file, e.g. "file.txt," it won't be slow.  It's only slow in the newly-opened tab.

Restarting MacVim entirely fixes the issue.

The "update MacVim" dialog appears prior to this happening, each time.
