### ISSUE TITLE
Sparkle window doesn't display release notes

### ISSUE THREAD

**Issue by sfsam** [macvim-dev/macvim#345]
I'm on macOS 10.12 GM seed.

My MacVim just updated to 7.4 (108) from either (106) or (107). The Sparkle update window didn't display the release notes. The scrollview where release notes are normally shown was just a blank white rectangle. Perhaps related to Apple's App Transport Security policies?

I should add that the update proceeded normally except for the missing release notes.

**Comment by splhack** [comment]
It's just empty. I'll fix update script.
https://github.com/macvim-dev/macvim/blob/gh-pages/appcast/latest.xml

**Comment by sfsam** [comment]
That was fast! Also, thank you for MacVim - it's awesome!

**Comment by splhack** [comment]
Fixed https://github.com/macvim-dev/macvim/commit/94825a34da8ef8c43827a73c04852400804f448d
