### ISSUE TITLE
Snapshot 109 Bug?

### ISSUE THREAD

**Issue by windless0530** [macvim-dev/macvim#349]
After updated to snapshot 109, every time I start vim and open a python script for the 1st time, error occurs in the buffer below:

Error: jedi-vim failed to initialize Python: jedi#setup_py_version: Vim(pyfile):E887: Sorry, this command is disabled, the Python's site module could not be loaded. (in function jedi#init_python[3]..<SNR>66_init_python[48]..jedi#setup_py_version, line 16)

Also, jedi does not work, navigation between python codes is not capable.

If I use the system default vim, or snapshot 108, everything works fine.

**Comment by amcgregor** [comment]
Similar on macOS Sierra (10.12) running build 109; my entire pymode setup is currently broken due to missing symbols (linting, folding, etc., etc.) as configured in [my dotfiles](https://github.com/amcgregor/dotfiles).

**Comment by splhack** [comment]
Fixed in snapshot-110 https://github.com/macvim-dev/macvim/releases/tag/snapshot-110
