### ISSUE TITLE
Extreme slow down when working with very long lines

### ISSUE THREAD

**Issue by brukatv** [macvim-dev/macvim#35]
I'm a new vim/macvim user so forgive me if this is a known problem.

My code periodically generates lines that are 100K + characters long. Usually a gigantic hash/json object that's all on one line. 

When i attempt to work with these in Macvim the editor pretty much comes to a standstill. Vim process CPU usage spikes to 99% and I basically can't do anything until i close the file with the very long line. 

Opening the files with normal vim has the same problem, though the slowdown is significantly worse in Macvim.

On OSX, Macvim version 7.4.712, Vim version 7.4.488

**Comment by eirnym** [comment]
This is about how Vim do syntax highlighting. Regular Expressions are slow for very long lines.

You can temporary disable syntax highlighting (`sy off` for example) and Vim will be fast again.

**Comment by brukatv** [comment]
Solved! Thanks! Any good workarounds?
