### ISSUE TITLE
Error saving file after git commit

### ISSUE THREAD

**Issue by srijanmishra** [macvim-dev/macvim#355]
This had been for quite sometime now. When one completes the commit message and save the file I get the following error:

```
error: There was a problem with the editor 'vi'.
Please supply the message using either -m or -F option.
```

The commit is aborted and one has to start again.
Also, I think that I have found the reason too. Steps to reproduce:

1.  After completing the git commit message try to save the file and by mistake type `:Wq`
2.  Then save the file with correct command and it will give the above error message. 

PS: Tested it without any plugin. Happy to provide any other detail.

**Comment by splhack** [comment]
Please post it in https://github.com/vim/vim/issues. It's not MacVim specific issue.
