### ISSUE TITLE
allow configuration of MacVim's tab width

### ISSUE THREAD

**Issue by Jaymon** [macvim-dev/macvim#356]
I have a tendency to keep lots of page tabs open and after upgrading to MacVim 8.0 I noticed after I got to about 7-8 tabs open, the "add tab" button would change to a double more arrow and all new tabs would be placed in there, this means I can't easily jump to tabs using `Ngt` because I don't know the tab number of the off screen tabs, or what's open.

Digging into the documentation I saw that I could set `MMTabMinWidth` which seemed exactly like what I wanted, but setting it had no effect, so I dug into the source code and it looks like a change made in [MMVimView](https://github.com/macvim-dev/macvim/blob/e268fb8d6761cd79f254ce05cd7ed6465ecf7fb2/src/MacVim/MMVimView.m#L128) (specifically, [this commit](https://github.com/macvim-dev/macvim/commit/e268fb8d6761cd79f254ce05cd7ed6465ecf7fb2)) might be the culprit:

```objective-c
#if MAC_OS_X_VERSION_MIN_REQUIRED >= MAC_OS_X_VERSION_10_10
    CGFloat screenWidth = [[NSScreen mainScreen] frame].size.width;
    [tabBarControl setStyleNamed:@"Yosemite"];
    [tabBarControl setCellMinWidth:120];
    [tabBarControl setCellMaxWidth:screenWidth];
    [tabBarControl setCellOptimumWidth:screenWidth];
#else
    [tabBarControl setCellMinWidth:[ud integerForKey:MMTabMinWidthKey]];
    [tabBarControl setCellMaxWidth:[ud integerForKey:MMTabMaxWidthKey]];
    [tabBarControl setCellOptimumWidth:
                                     [ud integerForKey:MMTabOptimumWidthKey]];
#endif
```

If you are on a newer version of the OS, the minimum tab width looks to be pegged at 120 instead of being set to `MMTabMinWidth`, is there a reason for this? 

I would much rather have control over this value or have it set back to the previous default of 64.

Thanks :)

**Comment by splhack** [comment]
Could you test #357?

**Comment by Jaymon** [comment]
👍  Awesome! Seems to be working as expected. 

Thank you :)
