### ISSUE TITLE
Copy to clipboard no longer works

### ISSUE THREAD

**Issue by kdart** [macvim-dev/macvim#358]
I have the new MacVim 8, thanks!  But now it seems to not copy the visual selection to the clipboard as it did before. Nothing happens when D-c is used.

**Comment by splhack** [comment]
Have you followed https://github.com/macvim-dev/macvim/wiki/Troubleshooting ?

    $ killall -9 MacVim
    $ killall -9 Vim
    $ defaults delete org.vim.MacVim
    $ /Applications/MacVim.app/Contents/MacOS/Vim -g -u NONE -U NONE
    
    write something
    select the text
    ⌘-c

**Comment by kdart** [comment]
Ok, after clearing the config it seems to be working normal now. Thanks.
