### ISSUE TITLE
NSToolbarItem had to adjust the size of <NSPopUpButton: 0x7faad1109df0> from {40, 25} to the expected size of {42, 27}

### ISSUE THREAD

**Issue by alisnic** [macvim-dev/macvim#361]
That's a warning when running MacVim, it does not crash the editor

```
$ 2016-09-22 12:30:20.061 MacVim[8798:73328] NSToolbarItem (<NSToolbarItem: 0x7faad111f3f0>) had to adjust the size of <NSPopUpButton: 0x7faad1109df0> from {40, 25} to the expected size of {42, 27}. Make sure that this toolbar item view has a valid frame/min/max size. This is an app bug, please do not file a bug against AppKit or NSToolbar! Break on _NSToolbarAdjustedBorderedControlSizeBreakpoint
```

OS: macOS Sierra
version: 8.0 (110)

**Comment by camwright** [comment]
I'm getting similar warnings, see #359

**Comment by eirnym** [comment]
@alisnic @camwright @tverghis  Does it still an issue for you?

**Comment by alisnic** [comment]
I’m not on Sierra anymore so I can’t say for sure. I can check the latest build on Mojave if you want

**Comment by eirnym** [comment]
Yes, please. I'd be helpful. The issue is too old and I suppose that this issue was actually fixed long ago

**Comment by alisnic** [comment]
Cannot reproduce anymore :+1:
