### ISSUE TITLE
Escape key in MacVim.app doesn’t work in Sierra

### ISSUE THREAD

**Issue by Kwpolska** [macvim-dev/macvim#362]
The Escape key doesn’t get out of a mode in MacVim.app v8.0 (110) on macOS Sierra. (It works fine in Terminal.)

**Comment by chdiza** [comment]
Did you try starting with `mvim -u NONE -U NONE -N`?

I have no problem with the escape key on Sierra.

**Comment by Kwpolska** [comment]
Yes, and I can still reproduce.

**Comment by chdiza** [comment]
Try adding `--noplugin` to the flags, or move your `~/.vim` out of the way, and try again.

If that doesn't work, I'm at a loss; it works for me on multiple machines.

**Comment by Kwpolska** [comment]
I tried the old tech support mantra: Have you tried turning it off and on again?

And after rebooting my Mac, the Escape key works fine. Strange.
