### ISSUE TITLE
Wrong download link (Snapshot 110)?

### ISSUE THREAD

**Issue by Edderic** [macvim-dev/macvim#365]
I downloaded Snapshot 110, replaced my binary, sourced by `.bash_profile`, ran `mvim --version` and got the following:
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr 21 2014 14:54:22)
MacOS X (unix) version
Included patches: 1-258
Compiled by Bjorn Winckler <bjorn.winckler@gmail.com>
```

I was expecting that the version would be 8.0. Is this the right expectation?

**Comment by splhack** [comment]
No. You didn't launch the right one.
