### ISSUE TITLE
One pixel in being cut off of Meslo Powerline font

### ISSUE THREAD

**Issue by ericbn** [macvim-dev/macvim#382]
Issue was not present in snapshot 100, and it started to be present since snapshot 101 until latest snapshot 111. Issue in not present using iTerm2 and terminal vim.
## Character affected (now, before)

![tiles](https://cloud.githubusercontent.com/assets/4120606/19369583/f9303cd2-916b-11e6-90f8-b1a990fefd35.png)
## MacVim Snapshot 100

![screen shot 2016-10-13 at 4 36 37 pm](https://cloud.githubusercontent.com/assets/4120606/19369485/55662b84-916b-11e6-83fd-03b854a0be17.png)
## MacVim Snapshot 101

![screen shot 2016-10-13 at 4 33 58 pm](https://cloud.githubusercontent.com/assets/4120606/19369510/81fec50c-916b-11e6-80d9-2680fef9b813.png)
## MacVim Snapshot 111 (latest)

![screen shot 2016-10-13 at 4 40 10 pm](https://cloud.githubusercontent.com/assets/4120606/19369530/a40a6dfe-916b-11e6-9f69-862bb2461991.png)

**Comment by Splarv** [comment]
Perhaps this bug is dublicate this one #572

**Comment by eirnym** [comment]
@ericbn Hi, quite a lot had been happened and could you have a chance to tell us if this is still an issue for you?

**Comment by ericbn** [comment]
Just checked with "Custom Version 8.1.1517 (156)" and the issue is gone. Thanks for keeping an eye on this!
