### ISSUE TITLE
MacVim should disable Input Source in command mode

### ISSUE THREAD

**Issue by Atry** [macvim-dev/macvim#383]
All commands are broken in command mode if an Input Source is activated.

MacVim should disable Input Source in command mode.

<img width="802" alt="screen shot 2016-10-15 at 17 14 35" src="https://cloud.githubusercontent.com/assets/601530/19408921/f8111d7c-92fa-11e6-9e42-751923c449aa.png">
The snapshot shows the broken commands when I press `j` repeatedly if an Input Source is activated. The commands should have moved down the cursor if this bug is fixed.

**Comment by splhack** [comment]
Have you tried this setting?

    set noimdisable
