### ISSUE TITLE
Full-screen mode on Sierra is broken

### ISSUE THREAD

**Issue by kovpack** [macvim-dev/macvim#388]
Full-screen mode on Sierra is broken. Only current cursor character (in files) or lines (in NerdTree) are visible - everything else is black. Entering full-screen mode is ok, but when you move cursor - it gets black as on screenshot below

![image](https://cloud.githubusercontent.com/assets/883341/19416163/ebc77132-9391-11e6-8ac9-535536f4d841.png)

**Comment by kovpack** [comment]
Sorry, checked settings one more time and just selected `Prefer native full-screen support` checkbox in `Advanced` tab in preferences - and it works.

**Comment by mgee** [comment]
Also see #312.
