### ISSUE TITLE
Please change the URL in the Wiki build instructions

### ISSUE THREAD

**Issue by fasiha** [macvim-dev/macvim#39]
On this repo's Wiki, the section titled [“How to get the MacVim source code”](https://github.com/macvim-dev/macvim/wiki/Building#how-to-get-the-macvim-source-code) still references @b4winckler's repo. I can see this tripping up some unfortunate soul who doesn't pay attention.

Please edit that URL to point to macvim-dev/macvim ☺️.

**Comment by douglasdrumond** [comment]
Thanks, done.
