### ISSUE TITLE
fatal error:  'os/log.h' file not found

### ISSUE THREAD

**Issue by harrissAvalon** [macvim-dev/macvim#394]
## Actions: 
Following the instructions in [README_mac.txt](https://github.com/macvim-dev/macvim/blob/master/READMEdir/README_mac.txt):
I got the error

    /Applications/macvim/src/MacVim/MacVim.h:77:10: fatal error: 'os/log.h' file not found

when trying to run the `make` command. 

## Expected:
The make command would compile the build successfully

**Comment by splhack** [comment]
First of all, in most of the cases, you don't need to build MacVim by yourself. You can use the binary release from https://github.com/macvim-dev/macvim/releases/latest.

Still you'd like to build MacVim by yourself, you should use the latest version of Xcode (currently it's Xcode 8) if you can use it on your environment. And follow the instruction here https://github.com/macvim-dev/homebrew-macvim.

https://github.com/macvim-dev/macvim/wiki/Building

--

If you're trying to build MacVim on older OS X, like 10.7, 10.8, 10.9 or 10.10, please paste the build error log.
