### ISSUE TITLE
Option to disable native tabs in Sierra

### ISSUE THREAD

**Issue by garetmckinley** [macvim-dev/macvim#397]
So in Sierra, there's now the ability to group windows with the built in tab system. This is great and all, but breaks integration with the popular command-t vim plugin. It would be really nice if there was a way to modify the key maps inside macvim, or just disable the native tabs altogether.

Obviously I can remap the command-t plugin, but having non-remapable keys in macvim limits your ability to ever map command-t to anything other than native tabs.

**Comment by jpetrie** [comment]
Since MacVim's already implemented tab functionality itself, is there any reason at all for us to support the new Sierra tabbing system? Or alternatively, should we just adopt Sierra's system on Sierra+ and relegate the custom tabs to older builds?

**Comment by ericvaladas** [comment]
@jpetrie would the new Sierra tabbing system fix the "new tab" button?
<img width="416" alt="screen shot 2016-11-07 at 4 06 57 pm" src="https://cloud.githubusercontent.com/assets/828125/20075918/41ace590-a504-11e6-80a2-bbce9006fef6.png">

**Comment by NuckChorris** [comment]
^ would love a patch for that bug, it's minor but it's been irking me for months

**Comment by cmcginty** [comment]
In dock preferences, set **prefer tabs when opening documents** to **Manually**.
![image](https://user-images.githubusercontent.com/277249/34087085-b4c38486-e355-11e7-93b0-4773c11fb5a1.png)

**Comment by ychin** [comment]
Fixed in #788. Native tabs are now disabled and likely won't be supported in foreseeable future.
