### ISSUE TITLE
Python syntax file does not include "yield from" statement in Python 3.3+

### ISSUE THREAD

**Issue by papajohn** [macvim-dev/macvim#398]
There is now a `yield from` statement type in Python. In the current `python.vim` syntax file, `yield` is highlighted as a regular statement, but `from` is highlighted as part of an include statement, so the colors of these two adjacent words (which are part of one keyword) don't match.

Wish I knew something about vim syntax files to fix it myself... maybe one day. Thanks!

**Comment by splhack** [comment]
I recommend you to write the issue in https://github.com/vim/vim/issues since the file is a part of Vim.
