### ISSUE TITLE
Latest commits broke build on Leopard

### ISSUE THREAD

**Issue by chdiza** [macvim-dev/macvim#40]
While building what has been tagged "Snapshot 76" works on Leopard, the last couple of commits since then have broken the build:

```
The following build commands failed:
MacVim:
    CompileC build/MacVim.build/Release/MacVim.build/Objects-normal/ppc/MMAppController.o /bld/kakvim/src/MacVim/MMAppController.m normal ppc objective-c com.apple.compilers.gcc.4_0
    CompileC build/MacVim.build/Release/MacVim.build/Objects-normal/ppc/MMVimController.o /bld/kakvim/src/MacVim/MMVimController.m normal ppc objective-c com.apple.compilers.gcc.4_0
(2 failures)
```

Looking back in the build output, this is the only thing that looks relevant:
```
CompileC build/MacVim.build/Release/MacVim.build/Objects-normal/ppc/MMAppController.o /bld/kakvim/src/MacVim/MMAppController.m normal ppc objective-c com.apple.compilers.gcc.4_0
    cd /bld/kakvim/src/MacVim
    /Developer/usr/bin/gcc-4.0 -x objective-c -arch ppc -fmessage-length=0 -pipe -Wno-trigraphs -fpascal-strings -Os -mdynamic-no-pic -Wreturn-type -Wunused-variable -mtune=G5 -fvisibility=hidden -I/bld/kakvim/src/MacVim/build/MacVim.build/Release/MacVim.build/MacVim.hmap -F/bld/kakvim/src/MacVim/build/Release -F/bld/kakvim/src/MacVim -I/bld/kakvim/src/MacVim/build/Release/include -I/bld/kakvim/src/MacVim/build/MacVim.build/Release/MacVim.build/DerivedSources/ppc -I/bld/kakvim/src/MacVim/build/MacVim.build/Release/MacVim.build/DerivedSources -c /bld/kakvim/src/MacVim/MMAppController.m -o /bld/kakvim/src/MacVim/build/MacVim.build/Release/MacVim.build/Objects-normal/ppc/MMAppController.o
/bld/kakvim/src/MacVim/MMAppController.m: In function ‘-[MMAppController fileOpen:]’:
/bld/kakvim/src/MacVim/MMAppController.m:1100: error: ‘NSModalResponseOK’ undeclared (first use in this function)
/bld/kakvim/src/MacVim/MMAppController.m:1100: error: (Each undeclared identifier is reported only once
/bld/kakvim/src/MacVim/MMAppController.m:1100: error: for each function it appears in.)
```

I'm sure this also means it broke on Tiger.

**Comment by jpetrie** [comment]
In the [related pull request](https://github.com/macvim-dev/macvim/pull/34) I noted:

> This will let somebody build a binary against older deployment targets if desired, but they'll still need the latest SDK (to see the appropriate availability macros). Is this sufficient or should I also take steps to make sure I check the SDK version somehow before doing the availability check? I don't really see this being done elsewhere, but MacVim.h does have a redefinition of the OS version macros up to 10.7; should I add the ones through 10.10 if I'm going to be using them?

I guess this is probably the consequence of the decision to merge the pull without redefining those additional availability macro definitions (`MAC_OS_X_VERSION_MIN_REQUIRED >= MAC_OS_X_VERSION_10_10` will be true because `MAC_OS_X_VERSION_10_10` isn't defined in Leopard and the C preprocessor considers identifiers that are not defined macros within the context of an `#if` to be equivalent to 0 if `-Wundef` isn't set).

This will also break pull #38, which you were worried about. Explicitly redefining `MAC_OS_X_VERSION_10_10` with appropriate values from the real AvailabilityMacros.h header should fix it, I believe. I'll add that change to #38.

**Comment by chdiza** [comment]
I can confirm that the most recent commit (which amounts to Snapshot 77) has built on Tiger and Leopard.  I see no problems yet.

**Comment by douglasdrumond** [comment]
Thanks!


--
Douglas Drumond
*​​Café Linear <http://www.cafelinear.com/> – GDG Campinas
<http://www.gdg-campinas.org/>​*
*google.com/+DouglasDrumond
<http://google.com/+DouglasDrumond> – @douglasdrumond
<http://twitter.com/douglasdrumond>​​*
