### ISSUE TITLE
channels throw exceptions when given sufficiently large files repeatedly

### ISSUE THREAD

**Issue by w0rp** [macvim-dev/macvim#402]
I have written a Vim plugin which feeds file buffer data via stdin to programs for linting code as you type in Vim. For a few months now, I've been receiving reports from MacVim users that my plugin doesn't work. All attempts to fix this bug have failed. I am now reasonably convinced that the problem actually lies internally in MacVim. The issue reported for my plugin is here: https://github.com/w0rp/ale/issues/39

For whatever reason, when sufficiently large files are fed to jobs using the `in_buf` and `"in_io": "buffer"` options for `job_start`, MacVim throws an exception saying the buffer cannot be written to: `E631: write_buf_line()(): write failed` I don't have a Mac I can personally use to create an isolated test case for this issue, but it can probably be repeated by feeding large files to programs from MacVim after a short delay with timers with an `autocmd` for the `TextChangedI` event. This is pretty much what my plugin does.

I would appreciate it if someone could have a look at this. I would be happy to be wrong and for there to be some way for me to fix this in my plugin. If this is a MacVim bug, I would be happy to see a patch which fixes it, so I can tell my user to update their version of MacVim. I have tried some versions of Vim on Mac OSX when I was able to grab a machine, and I couldn't repeat the issue myself, so there might be a specific version needed to be able to see the error.

**Comment by splhack** [comment]
So it's enough to repro the issue?
- install ale
- open https://gist.github.com/junkblocker/8ecf9fc7940a8e42802f241cdf4fcedc

**Comment by w0rp** [comment]
Yeah, just about. Install the plugin, install jshint if you don't have that, open the file, and type a little bit.

**Comment by splhack** [comment]
followed manual installation https://github.com/w0rp/ale#manual-installation, I only have .vim/bundle/ale and .vimrc as follows, no other plugins and .gvimrc. And installed jshint as `npm install -g jshint`.

    set nocompatible
    filetype off
    let &runtimepath.=',~/.vim/bundle/ale'
    filetype plugin on

Then opened https://gist.github.com/junkblocker/8ecf9fc7940a8e42802f241cdf4fcedc in MacVim snapshot 114. I can see `Missing semicolon.` message.

How to repro the issue??

**Comment by junkblocker** [comment]
Hi, original submitter of the issue over at w0rp/ale . Please use these instructions for repro instead with `jcsc` without a `.jcscrc` file present and not with `jshint`.

https://github.com/w0rp/ale/issues/39#issuecomment-252692485

Thanks

**Comment by splhack** [comment]
It would have been helpful if you had explained... how to install jcsc? you mean jscs? `npm install -g jscs`, right? and .vimrc as follows?

    set nocompatible
    filetype off
    let &runtimepath.=',~/.vim/bundle/ale'
    filetype plugin on
    let g:ale_linters = {'javascript': ['jscs']}

**Comment by junkblocker** [comment]
yes, sorry for the typo. You have the instructions right.

**Comment by splhack** [comment]
Ok, I don't think it's MacVim specific issue. More likely, channel.c select/write issue on OS X. You can repro it with Vim. So select syscall returns the file descriptor is writable, but write syscall fails with EPIPE. I recommend you to repro it with the latest Vim and report it in https://github.com/vim/vim/issues.

**Comment by w0rp** [comment]
Okay, thank you for taking a look. I'll see if I can get it fixed in Vim.

**Comment by splhack** [comment]
@w0rp I believe just `jscs` closed stdin at that moment, it's not Vim issue.
