### ISSUE TITLE
MacVim don't open after new update. Py_Initialize problem. 

### ISSUE THREAD

**Issue by sysek** [macvim-dev/macvim#411]
Hi guys, I don't know what happend, but after the update I have problem.

`Fatal Python error: Py_Initialize: unable to load the file system codec`
`ImportError: No module named 'encodings'`

`Current thread 0x00007fffbff583c0 (most recent call first):`
`Vim: Caught deadly signal ABRT`
`Vim: Finished.`

I don't have $PYTHONPATH, but I read that I don't need this. Does anyone have problem after the update ?

**Comment by splhack** [comment]
The update is MacVim snapshot-116, right? https://github.com/macvim-dev/macvim/releases/tag/snapshot-116

You should update Python 3.5.2 or later if you want to use if_python3 with the sanpshot-116 binary.

You may need to set `$PYTHONHOME` and `pythonthreedll` in your $HOME/.vimrc.

For example, if you have installed https://www.python.org/ftp/python/3.5.2/python-3.5.2-macosx10.6.pkg , your $HOME/.vimrc looks like

    let $PYTHONHOME="/Library/Frameworks/Python.framework/Versions/3.5"
    set pythonthreedll=/Library/Frameworks/Python.framework/Versions/3.5/lib/libpython3.5m.dylib

**Comment by splhack** [comment]
maybe I'm gonna change system vimrc to check installed Python3 and set `$PYTHONHOME` and `pythonthreedll` automatically.

**Comment by settermjd** [comment]
@splhack, thanks for listing the fix. I had to change it from 3.5 to 3.6, but otherwise, it worked perfectly and MacVim IS BACK!!! Thanks!

**Comment by llinfeng** [comment]
Alternative solution from https://stackoverflow.com/questions/46367739/unable-to-use-vim-to-open-latex-files-on-mac-caused-by-python:

`brew upgrade python3` solved my problem with using macvim, with exactly the same error as above.

**Comment by rodgert** [comment]
This issue cropped up for me this morning after installing the latest update. Downgrading homebrew python from 2.7.14 to 2.7.13_1 seemed to fix it.
