### ISSUE TITLE
Powerline not loaded in pre-compiled MacVim

### ISSUE THREAD

**Issue by justinmayer** [macvim-dev/macvim#414]
As I mentioned in [an issue I filed in the Powerline repository](https://github.com/powerline/powerline/issues/1687), the only way I have ever been able to use Powerline with MacVim is by installing Xcode and then compiling MacVim with Homebrew via the [method outlined in the Powerline docs](https://powerline.readthedocs.io/en/latest/installation/osx.html#vim-installation). I have tried `brew cask install macvim` as well as downloading the DMG directly from the [MacVim releases page](https://github.com/macvim-dev/macvim/releases) in this repository, but the Powerline status bar never loads when using these instances of MacVim.

I guess my question is... why? What are the pre-built MacVim applications missing? Conversely, what is it about compiling MacVim via Homebrew that allows Powerline to function properly?

I see references to Powerline in other issues in this repository, so it seems clear enough that folks are able to get this combination to function properly. For the life of me, I cannot figure out how. Does anyone have any suggestions?

**Comment by splhack** [comment]
I don't know what Powerline is, but apparently it needs if_python2 or 3 support.

- MacVim binary release snapshot-116 https://github.com/macvim-dev/macvim/releases/tag/snapshot-116 supports if_python2 and if_python3 out of the box.
- No setup requires for if_python2. MacVim automatically uses OS X Python 2.7.x.
- MacVim is built with Python 3.5.2. You should use Python 3.5.2 or later and you may need to setup your .vimrc for if_python3. See #411

**Comment by splhack** [comment]
Install powerline
    $ brew install python3
    $ pip3 install powerline-status

Setup .vimrc
    " Powerline
    py3 from powerline.vim import setup as powerline_setup
    py3 powerline_setup()
    py3 del powerline_setup
    set laststatus=2
    set showtabline=2
    set noshowmode

Launch MacVim binary release snapshot-116, it works fine. With snapshot-117(not released yet) or later, you may not need to set Python3 setting in your .vimrc #411, it will be set automatically.

**Comment by justinmayer** [comment]
Many thanks for the quick response, Kazuki. Following are steps to reproduce this issue (and apologies for not providing this in the original description):

    brew install python
    pip install powerline-status

    # .vimrc
    python from powerline.vim import setup as powerline_setup
    python powerline_setup()
    python del powerline_setup
    set laststatus=2

With the above setup on a fresh instance of macOS 10.12.1 Sierra, Powerline does not load on snapshot-116.

After some experimentation, one workaround is to add the following line to `~/.vimrc`:

    let $PYTHONHOME="/usr/local/Frameworks/Python.framework/Versions/2.7"

Once that line is added, Powerline loads as expected.

That said, would it be possible for MacVim to handle this automatically, without that additional (and Mac-specific) .vimrc configuration directive?

**Comment by splhack** [comment]
maybe. By the way, for the record, if you didn't installed Python2 via Homebrew, just installed pip http://softwaretester.info/install-and-upgrade-pip-on-mac-os-x/ then no additional settings required.
