### ISSUE TITLE
Keep current working directory when relaunching

### ISSUE THREAD

**Issue by fxn** [macvim-dev/macvim#425]
You launch MacVim in some directory via `mvim`, get the upgrade suggestion, proceed, and on relaunch your cwd is the home directory. I find this change in cwd unexpected. In particular, instinctively I fire CtrlP completion to go on with whatever I was going to do, just to realize it was a bad idea.

What do you think about relaunching with the same cwd?

**Comment by splhack** [comment]
maybe it would be good to have the functionality but I won't fix. you can try the updater settings here https://github.com/macvim-dev/macvim/issues/390#issuecomment-254455708
