### ISSUE TITLE
Ctrl+w o Closes All Buffers

### ISSUE THREAD

**Issue by blueshirts** [macvim-dev/macvim#426]
After installing snapshot-117: MacVim Snapshot 117 on 10.10.5 the ctrl+w o command seems to close all buffers.

It should maximize the current buffer.  I downgraded to the previous version and I no longer have the issue.

**Comment by splhack** [comment]
I can't see any related changes between snapshot-116 to snapshot-117. It is still happening with snapshot-119?

**Comment by blueshirts** [comment]
No longer an issue in 119.
