### ISSUE TITLE
pipe stdin to mvim only have 65537 bytes

### ISSUE THREAD

**Issue by SolaWing** [macvim-dev/macvim#427]
Macvim is the newest 117 release version, installed by brew cask.
it's ok when pipe to `/Applications/MacVim.app/Contents/MacOS/Vim -`

**Comment by splhack** [comment]
It's some sort of bash limitation?
I'm using zsh alias

    vi='/Applications/MacVim.app/Contents/MacOS/Vim "$@"'

**Comment by SolaWing** [comment]
@splhack I use fish. and in test, I think it's not the shell's problem. issue exists when use fish or bash.

anyway, I mean using command like `git log | mvim -` to open output in macvim. not using `mvim file` to open file directly.

**Comment by chdiza** [comment]
I can't reproduce.

**Comment by chdiza** [comment]
I should add that I am not using a precompiled MacVim.  I build from source with `--disable-netbeans` and `--disable-nls` as the only `configure` flags.  The resulting MacVim has no problem with piped stdin.

**Comment by splhack** [comment]
@SolaWing you are saying what is your interactive shell, right? `mvim` is bash script. I think this article explains why http://unix.stackexchange.com/a/11954 So I recommend you to use shell alias instead of `mvim` bash script for that case.

**Comment by SolaWing** [comment]
@splhack. Thanks for the tip. It is indeed caused by the pipe buffer. and after I use `-f` argument to block command execute, it work correctly.

**Comment by chdiza** [comment]
I don't understand.  I can do `git log | mvim -` and MacVim will fully show a buffer containing far more than 65K.

**Comment by SolaWing** [comment]
@chdiza I use fish shell, And I notice `Vim: Reading from stdin...` shows after my next prompt show.
so I guess this may means my previous command which open macvim has end, and only the buffering 65536 send to macvim.
This should be fish issue.  My old test was wrong, bash is fine. Sorry.
