### ISSUE TITLE
mksession and source not working

### ISSUE THREAD

**Issue by ncp1113** [macvim-dev/macvim#428]
On MacVim 8, I can :source a session that was saved before the update but if I then overwrite it, it opens a blank window. I did a test and saved a log. I made 2 new files with a split screen and saved it to a new mksession. Then I opened a new window and :so did not restore the files or split screen. I just got a new window.

[test.vim.txt](https://github.com/macvim-dev/macvim/files/629119/test.vim.txt)
[macvim.log.txt](https://github.com/macvim-dev/macvim/files/629120/macvim.log.txt)

.

**Comment by splhack** [comment]
@ncp1113 can you try snapshot-118? https://github.com/macvim-dev/macvim/releases/tag/snapshot-118

**Comment by ncp1113** [comment]
Thanks for your reply.  I was prompted for an update, which I did.  The current version is still 8.0.  Here is what it says Custom Version 8.0 (119).  

It seems to be working okay now.  So I guess you can close it.

**Comment by ncp1113** [comment]
I didn't realize I could close it. So I just did.
