### ISSUE TITLE
Build fails with python support

### ISSUE THREAD

**Issue by themightyoarfish** [macvim-dev/macvim#429]
My system is 10.12.1.

I configure like this:
```
./configure --with-features=Huge --enable-perlinterp=yes --enable-rubyinterp=yes --enable-python3interp=yes --enable-cscope --enable-multibyte
```
The build works, but `echo has('python')` prints `0` as well as `echo has('python3')`. If instead I try with Python 2.7 (`--enable-pythoninterp=yes`), I get this error at linking stage:
```
Undefined symbols for architecture x86_64:
  "_PyInt_AsLong", referenced from:
      _NumberToLong in if_python.o
      __ConvertFromPyObject in if_python.o
      _ListItem in if_python.o
      _ListAssItem in if_python.o
  "_PyInt_FromLong", referenced from:
      _DoPyCommand in if_python.o
      _run_do in if_python.o
      _OutputGetattr in if_python.o
      _DictionaryGetattr in if_python.o
      _ListGetattr in if_python.o
      _OptionsItem in if_python.o
  "_PyString_AsString", referenced from:
      _run_do in if_python.o
      _CurrentGetattr in if_python.o
      _RBItem in if_python.o
      _RBSlice in if_python.o
  "_PyString_AsStringAndSize", referenced from:
      _StringToLine in if_python.o
      _StringToChars in if_python.o
      __ConvertFromPyObject in if_python.o
  "_PyString_FromFormat", referenced from:
      _BufferRepr in if_python.o
      _WindowRepr in if_python.o
      _TabPageRepr in if_python.o
      _RangeRepr in if_python.o
  "_PyString_FromString", referenced from:
      _DoPyCommand in if_python.o
      _OutputGetattr in if_python.o
      _BufferGetattr in if_python.o
      _FunctionRepr in if_python.o
      _FunctionGetattr in if_python.o
      _ObjectDir in if_python.o
      _ConvertToPyObject in if_python.o
      ...
  "_PyString_FromStringAndSize", referenced from:
      _run_do in if_python.o
      _CurrentGetattr in if_python.o
      _RBItem in if_python.o
      _RBSlice in if_python.o
  "_PyUnicodeUCS2_AsEncodedString", referenced from:
      _StringToLine in if_python.o
      _StringToChars in if_python.o
      __ConvertFromPyObject in if_python.o
  "_Py_FindMethod", referenced from:
      _OutputGetattr in if_python.o
      _BufferGetattr in if_python.o
      _WindowGetattr in if_python.o
      _TabPageGetattr in if_python.o
      _RangeGetattr in if_python.o
      _CurrentGetattr in if_python.o
      _DictionaryGetattr in if_python.o
      ...
  "_Py_InitModule4_64", referenced from:
      _DoPyCommand in if_python.o
  "__Py_ZeroStruct", referenced from:
      _BufferGetattr in if_python.o
      _WindowGetattr in if_python.o
      _TabPageGetattr in if_python.o
      _FunctionGetattr in if_python.o
      _AlwaysFalse in if_python.o
      __DictionaryItem in if_python.o
      _ConvertToPyObject in if_python.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Vim] Error 1
```

**Comment by splhack** [comment]
- First of all, in most of the cases, you don't need to build MacVim by yourself. You can use the binary release from https://github.com/macvim-dev/macvim/releases/latest.

- Still you'd like to build MacVim by yourself, follow the instruction here https://github.com/macvim-dev/homebrew-macvim.

- Still you have specific reason to build MacVim with certain configuration by yourself, you can read the https://github.com/macvim-dev/macvim/blob/master/src/auto/configure script in order to set configuration properly.

**Comment by themightyoarfish** [comment]
I should mention that the binary release seems to lack python support add well, at least the results are the same as above. so I'm forced to build it myself.

 As I use macports, I can't use the homebrew formula.

**Comment by splhack** [comment]
> the binary release seems to lack python support add well

could you elaborate on that?

> As I use macports, I can't use the homebrew formula.

could you elaborate on the technical reason of that?

**Comment by themightyoarfish** [comment]
When I downloaded the binary a couple of hours ago `has('python')` was false while now it is not. Maybe I accidentally opened the wrong one, I don't know.

While it my technically be possible to have two package managers, I see little but potential for conflict therein. Duplicate binaries will cause confusion I'm sure.

I'd still be interested in comments to the actual problem of building MacVim. Do you think it is related to my system or what exactly is missing? Because I really have no clue.

**Comment by splhack** [comment]
Still you would like to know why your MacVim build was failed, I would recommend you to read the build error message and read https://github.com/macvim-dev/macvim/blob/master/src/auto/configure script thoroughly in order to set configuration properly.
