### ISSUE TITLE
MacVim doesn't play well with split-screen view in OS X 10.11

### ISSUE THREAD

**Issue by jckarter** [macvim-dev/macvim#43]
When MacVim is put in a split-full-screen view on OS X 10.11, it appears to think that its window is the size of the entire screen instead of its half of the screen. This leads to weird stretching and skewing drawing artifacts, and causes text and cursor navigation to go past the edge of the window.

**Comment by ericcong** [comment]
+1, really hope this can be fixed.

**Comment by kjoonlee** [comment]
Sorry if this isn't too relevant, but split-screen modes when you press <Esc> so I wonder if enabling split-screen modes is something that can be accomplished.

**Comment by ttylec** [comment]
+1, would be great for LaTeX editing.

@kjoonlee: Terminal and macvim captures `<Esc>` before system does. Actually, full-screen works perfectly for MacVim and one can get split-full-screen with vim in terminal (although synctex is impossible/complicated with vim in terminal).
