### ISSUE TITLE
Any plans for Touch Bar support? 😁

### ISSUE THREAD

**Issue by easybills-admin** [macvim-dev/macvim#435]
https://developer.apple.com/macos/touch-bar/

**Comment by johnelliott** [comment]
It would be cool to have letter registers appear, allowing you to build macro keys and know what's in what register.
```
"q   ihello world^[0
"w   $F'd$^[0
```

**Comment by xjkdev** [comment]
maybe a bigger esc button can be added to it.

**Comment by nilsbecker** [comment]
buffer list with touch-to-switch?

**Comment by m4c0** [comment]
IMHO, in the good spirit of VIM being extensible, the ideal solution could be a new toolbar named TouchBar, then, users can customise it by using commands like:

`:amenu icon=FooIcon TouchBar.Foo :echo "Foo"<CR>`

Or, maybe, just move the existing toolbar to the Touch Bar with some new config (similar to "statusline").

I would love to do code it and do a PR, but I don't have a MacBook with Touch Bar... :(

**Comment by wiomoc** [comment]
#568

**Comment by tomlankhorst** [comment]
@m4c0 https://github.com/sindresorhus/touch-bar-simulator

**Comment by jpetrie** [comment]
Merged PR #715 which adds this.
