### ISSUE TITLE
`mvim` command behaves weird within tmux

### ISSUE THREAD

**Issue by okuramasafumi** [macvim-dev/macvim#437]
I installed macvim from official homebrew formula. It works fine with `vim` command or GUI app. However, when I run `mvim` command in tmux session, the window opens but it doesn't accept any key input. I tried to run `mvim` command in normal terminal window without tmux and it worked as expected.
Is it the known limitation?

Version info:
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Dec 17 2016 17:07:21)
MacOS X (unix) version
Included patches: 1-134
Compiled by okuramasafumi@OkuraMasafumi-no-MacBook-Pro.local
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl             +cmdline_info    +eval            +iconv           +menu            +multi_byte      +python/dyn      +tag_binary      +vertsplit       -xpm
+arabic          +comments        +ex_extra        +insert_expand   +mksession       +multi_lang      +python3/dyn     +tag_old_static  +virtualedit     -xsmp
+autocmd         +conceal         +extra_search    +job             +modify_fname    -mzscheme        +quickfix        -tag_any_white   +visual          -xterm_clipboard
+balloon_eval    +cryptv          +farsi           +jumplist        +mouse           +netbeans_intg   +reltime         -tcl             +visualextra     -xterm_save
+browse          +cscope          +file_in_path    +keymap          +mouseshape      +num64           +rightleft       +termguicolors   +viminfo
++builtin_terms  +cursorbind      +find_in_path    +lambda          +mouse_dec       +odbeditor       +ruby/dyn        +terminfo        +vreplace
+byte_offset     +cursorshape     +float           +langmap         -mouse_gpm       +packages        +scrollbind      +termresponse    +wildignore
+channel         +dialog_con_gui  +folding         +libcall         -mouse_jsbterm   +path_extra      +signs           +textobjects     +wildmenu
+cindent         +diff            -footer          +linebreak       +mouse_netterm   +perl/dyn        +smartindent     +timers          +windows
+clientserver    +digraphs        +fork()          +lispindent      +mouse_sgr       +persistent_undo +startuptime     +title           +writebackup
+clipboard       +dnd             +fullscreen      +listcmds        -mouse_sysmouse  +postscript      +statusline      +toolbar         -X11
+cmdline_compl   -ebcdic          +gettext         +localmap        +mouse_urxvt     +printer         -sun_workshop    +transparency    -xfontset
+cmdline_hist    +emacs_tags      -hangul_input    +lua/dyn         +mouse_xterm     +profile         +syntax          +user_commands   +xim
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/local/Cellar/macvim/HEAD-4bf9153/MacVim.app/Contents/Resources/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -L/usr/local/lib -L. -L/usr/local/lib  -L/usr/local/lib -o Vim -framework Cocoa -framework Carbon       -lm  -lncurses -liconv -lintl -framework Cocoa   -fstack-
protector  -L/System/Library/Perl/5.16/darwin-thread-multi-2level/CORE
```
I use macOS 10.11.6 and macvim snapshot 119.

**Comment by splhack** [comment]
I can't repro this issue. maybe depends on `.tmux.conf`?

**Comment by okuramasafumi** [comment]
I started `tmux` with `-f` option pointing empty file, but the result was the same.
I use `tmux` version `2.3`.

**Comment by npalasseri** [comment]
A related question, I don't see the mvim script in the DMG bundle. Is that intentional? Currently I downloaded the b4winckler bundle and took the mvim script. Or is this that mvim approach is not a good choice?

**Comment by chdiza** [comment]
The `mvim` script is here in this repo; you don't need to go to the b4winckler one, and probabl shouldn't, since `mvim` has been modified since then.  Look in src/macvim.

(That said, `mvim` really should be put in with the dmg if it isn't already.)

**Comment by splhack** [comment]
`mvim` script is in the dmg.

https://github.com/macvim-dev/macvim/releases/latest

<img width="645" alt="screen shot 2016-12-29 at 8 36 39 am" src="https://cloud.githubusercontent.com/assets/81904/21548576/f85b75f2-cda1-11e6-8611-45ed0b2e0d64.png">

**Comment by chinhau5** [comment]
I had exactly the same issue as you. It seems that starting the shell with reattach-to-user-namespace in tmux solved the problem. I have yet to pinpoint the problem though.

**Comment by okuramasafumi** [comment]
@chinhau5 You're right, using `reattach-to-user-namespace` solves the problems magically.
I think I can close this issue by mentioning using `reattach-to-user-namespace`, because it's so simple to install and use it.
FYI, `tmux`'s copy and paste through clipboard works fine without `reattach-to-user-namespace`, which, weirdly, is the main purpose of the program. So the root cause might be how macvim gets key input from OS.
