### ISSUE TITLE
Window height increases after every startup

### ISSUE THREAD

**Issue by jcw** [macvim-dev/macvim#44]
When I quit MacVim and reopen, the height of the window increases by one. Quitting and reopening again, it increases once more. I assume this is unintended behaviour.

Is this a bug?

One workaround is to _not_ enable "e" in `guioptions`.
Another workaround is to _not_ set `showtabline` to 2.

I'm using MacVim 7.4 w/ patches 1-712, on a retina pro running Mac OSX 10.10.3.

-jcw

**Comment by eirnym** [comment]
I can't reproduce it. I use MacVim 76, Mac OS X 10.10.4

**Comment by jcw** [comment]
It's a combination of settings, as I said. I've worked around it by removing "e" from guioptions.
This was driving me up the wall, but now I'm ok with it :)

**Comment by eirnym** [comment]
I've added these options: `set guioptions+=e` and `set showtabline=2` to the end of my `~/.vimrc`, and remove all plugins I use. I can't reproduce this.

**Comment by jcw** [comment]
You're right. All settings gone, just the above two, and it doesn't happen on my MBA either.
Could it be a Retina thing?
