### ISSUE TITLE
Strange Issue Due to a1fa892

### ISSUE THREAD

**Issue by amadeus** [macvim-dev/macvim#442]
~~A very strange issue has show up ever since 0bdef25 was merged. I tried running a git bisect and even tried checking out the specific commits associated with that merge, however there are no issues until that merge takes place, which, I can only guess is the result of a mis-merged conflict?~~

I believe the issue came about from a1fa892, and perhaps how it may have been merged in. Not sure if this is a MacVim issue or a Vim issue.

Anyways, the issue has showed up in the https://github.com/maralla/completor.vim plugin. It hasn't been updated in a couple weeks and used to work just fine.

Specifically the error output I get is:

```
Error detected while processing /Users/amadeus/.vim/bundle/completor.vim/autol
oad/completor/utils.vim:
line   65:
E126: Missing :endfunction
Error detected while processing function <lambda>1[1]..<SNR>99_complete:
line    4:
E117: Unknown function: completor#utils#get_completer
E15: Invalid expression: completor#utils#get_completer(s:status.ft, s:status.i
nput)
line    5:
E121: Undefined variable: info
E116: Invalid arguments for function empty(info) | return | endif
E15: Invalid expression: empty(info) | return | endif
line    6:
E121: Undefined variable: info
E15: Invalid expression: info
line    8:
E121: Undefined variable: is_sync
E15: Invalid expression: is_sync  
```

I believe it has something to do with this file:

https://github.com/maralla/completor.vim/blob/master/autoload/completor/utils.vim

Since it's trying to do some python execution however it's now completely broken.

**Comment by amadeus** [comment]
Actually, scratch most of what I said.

I believe the issue actually stems from this commit: a1fa892 - and since it wouldn't build on MacOSX after that until it was merged, I believe it's something to do with that.

**Comment by splhack** [comment]
It sounds Vim issue. I recommend you to check the issue with the origin Vim.
https://github.com/macvim-dev/macvim/wiki/Troubleshooting#test-the-original-vim
