### ISSUE TITLE
Cannot allocate color none

### ISSUE THREAD

**Issue by dimaqq** [macvim-dev/macvim#443]
A patch has been proposed in the forum: http://www.linuxquestions.org/questions/slackware-14/vim-7-4-1938-e254-cannot-allocate-color-'none'-4175582317/
Also posted upstream: https://github.com/vim/vim/issues/1400

**Comment by jpetrie** [comment]
MacVim would merge this in eventually if core vim accepted it, but it doesn't seem like something MacVim should fix or support on its own.
