### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by fingermark** [macvim-dev/macvim#444]
I hope this isn't similar to a `+1` type comment, but would it be possible to cut a new release?  There's a new feature in vim that I want to use.  Sorry if this is already scheduled.  I'm not familiar with the release process for MacVim.

**Comment by jpetrie** [comment]
Which feature? Has it been integrated down into vim by any of the [commits](https://github.com/macvim-dev/macvim/commits/master) yet?

**Comment by fingermark** [comment]
@jpetrie nice.  https://github.com/vim/vim/commit/9be7c04e6cd5b0facedcb56b09a5bcfc339efe03

I noticed the dmg wasn't produced.  Is that why MacVim's check for updates isn't showing anything?

Thanks again, splhack / jpetrie

**Comment by splhack** [comment]
Apparently Travis CI is busy (or something wrong https://www.traviscistatus.com/ doesn't mention it though) https://travis-ci.org/macvim-dev/macvim/builds/194583426
