### ISSUE TITLE
Under OSX when pasting to :ex or / <PasteStart> and <PasteEnd> is pasted, literally

### ISSUE THREAD

**Issue by mianos** [macvim-dev/macvim#445]
This commit:
https://github.com/macvim-dev/macvim/commit/ec2da36ca48b40c0654b32a8d2c9f52e796daa5e
Breaks normal terminal paste, both term and item2.

**Comment by chdiza** [comment]
This is a Vim issue and should be opened on their github page.

**Comment by mianos** [comment]
OK posted in the upstream project and closing this.
