### ISSUE TITLE
"Don't Save" button tries to save unnamed file

### ISSUE THREAD

**Issue by cmcginty** [macvim-dev/macvim#446]
Open MacVim, and enter some text into an unnamed buffer. Now in command mode: `:confirm qa`.

A prompt opens asking: "Do you want to save the changes ...". Select "Don't Save". 

Instead of quitting, MacVim opens up a Save Dialog box.

![image](https://cloud.githubusercontent.com/assets/277249/22313270/dc7d993a-e310-11e6-905e-6125fe1988f5.png)

![image](https://cloud.githubusercontent.com/assets/277249/22313249/c66b3314-e310-11e6-9b1d-13e01d7e0d7f.png)

**Comment by splhack** [comment]
I can't repro this with snapshot-124.

**Comment by cmcginty** [comment]
my version info:
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jan 30 2017 23:18:05)
MacOS X (unix) version
Included patches: 1-273
Compiled by Homebrew
```

**Comment by ychin** [comment]
I can't repro this. Does it still happen for you in the latest release @cmcginty?

If it does you can also try `mvim -u NONE -U NONE` to load a vanilla MacVim with no vimrc to see what happens. Also, if you could post your preferences that would be great. You can do that by going to Terminal and copy the result of the command `defaults read org.vim.MacVim | grep MM`.

**Comment by cmcginty** [comment]
Looks fixed to me.
