### ISSUE TITLE
Too wide character spacing without Core Text renderer

### ISSUE THREAD

**Issue by lsnizek** [macvim-dev/macvim#45]
In snapshot 73, disabling Core Text renderer leads to very wide character spacing (Monaco font in screenshot, also tried Courier). OS X 10.9.5.

![core_text_disabled](https://cloud.githubusercontent.com/assets/12996687/8277731/86ff0fd0-18bd-11e5-9e28-db20b57be916.png)
![core_text_enabled](https://cloud.githubusercontent.com/assets/12996687/8277730/86fc1b40-18bd-11e5-93c5-d41899b31432.png)

**Comment by splhack** [comment]
I can't reproduce it. it still happens?

I recommend you to check the following.

    $ defaults delete org.vim.MacVim
    $ /Applications/MacVim.app/Contents/MacOS/Vim -g -u NONE -U NONE

**Comment by Mishail** [comment]
I'm observing the very same behavior with Snapshot 102. OS X 10.11.5 Beta (15F31a).
![Withour "Core Renderer"](https://cloud.githubusercontent.com/assets/278751/14973932/862ebd10-10a3-11e6-8070-b20dee9b3674.png)
![With "Core Renderer" enabled](https://cloud.githubusercontent.com/assets/278751/14973934/88c9d5be-10a3-11e6-92b5-b43c350b405b.png)
