### ISSUE TITLE
Character only draw half width

### ISSUE THREAD

**Issue by reliveyy** [macvim-dev/macvim#451]
<img width="249" alt="screen shot 2017-02-05 at 12 39 03" src="https://cloud.githubusercontent.com/assets/4723958/22623753/4aacd9c4-eba0-11e6-9045-01071717b76e.png">

You can see from the above screenshot that the first character (UNICODE: 201C - LEFT DOUBLE QUOTATION MARK) was only drawn the left half.

**Comment by splhack** [comment]
Have you set `ambiwidth` option?

    set ambiwidth=double

**Comment by reliveyy** [comment]
@splhack You save my day. Thanks a lot!
