### ISSUE TITLE
Flicker when resizing the window

### ISSUE THREAD

**Issue by ericvaladas** [macvim-dev/macvim#453]
Since updating to macOS Sierra, I think, my MacVim flickers whenever I resize the window. I have tried the version from GitHub and the one from homebrew. The flicker is almost painful to look at.

Warning: fast black and white strobe effect in this video.

[https://cloud.githubusercontent.com/assets/828125/22670826/0a80f656-ec99-11e6-8e0d-0c1aee37433e.gif](https://cloud.githubusercontent.com/assets/828125/22670826/0a80f656-ec99-11e6-8e0d-0c1aee37433e.gif)

**Comment by splhack** [comment]
Same as #32
