### ISSUE TITLE
Double-width font-awesome/vim-devicon clipped

### ISSUE THREAD

**Issue by xguerin** [macvim-dev/macvim#456]
Hello there,

It seems that double-width icons provided in font sets like font-awesome of vim-devicons are truncated when using the CoreText rendered (without ambiwidth, this option has its own set of inconvenience and is not required in terminal mode).

The issue disappear when using the non-CoreText renderer, although the alignment of the double-width character is completely off.

There is some patch floating around (https://github.com/xusiyuan841028/macvim/commit/27bcfd27d6c3500b6ca27c7387a19b5a8306df17) which solves some of the issues but not all (double-width character in the tabline are still truncated).

**Comment by jordwalke** [comment]
I noticed this too.

**Comment by ychin** [comment]
I believe this was fixed a couple years ago when stateful renderer went in.
