### ISSUE TITLE
MacVim is perfect, it's necessary to  neovim version.

### ISSUE THREAD

**Issue by FinallyFinancialFreedom** [macvim-dev/macvim#461]
all the neovim GUI on MacOS is not good to use.
neovim has a buildin terminal and work good with fzf.
neovim is faster in asynchronous process though vim8 has support it. like denite.vim

**Comment by splhack** [comment]
I'm sorry, that is not in this project's scope.

**Comment by ychin** [comment]
Duplicate of #47. Use that if you are still interested in such prospects @FinallyFinancialFreedom .
