### ISSUE TITLE
What are "sane compile and link flags" for Python 3?

### ISSUE THREAD

**Issue by themightyoarfish** [macvim-dev/macvim#465]
I'm trying to build from the current master bc5505e503ae5408e30c165516586d9edac7ad60 with the only option being `--enable-python3interp=yes`, and `configure` spits out this bit.

```
...
checking Python's install prefix... /opt/local/Library/Frameworks/Python.framework/Versions/3.5
checking Python's execution prefix... /opt/local/Library/Frameworks/Python.framework/Versions/3.5
checking Python's configuration directory... /opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/config-3.5m
checking Python3's dll name... Python.framework/Versions/3.5/Python
checking if -pthread should be used... no
checking if compile and link flags for Python 3 are sane... no: PYTHON3 DISABLED
...
```
I have Python 3.5 installed via MacPorts on macOS and have not seen this problem before.
Using Python 2.7 (also MacPorts) instead does not have this problem. 
Does someone have an idea what the issue might be?

**Comment by splhack** [comment]
I'll close this since it's not MacVim issue. I encourage you to post your question to the vim_mac Google Group https://groups.google.com/forum/#!forum/vim_mac
