### ISSUE TITLE
MacVim app does not have Python3 or py3

### ISSUE THREAD

**Issue by Wanghongkua** [macvim-dev/macvim#467]
I have the latest version of MacVim app. 
Even though it is showing +python3/dyn when I type _:version_ in vim, when I type _:python3 print("hello")_ I get 
**E837: This Vim cannot execute :py3 after using :python
E263: Sorry, this command is disabled, the Python library could not be loaded**
This issue makes some plugins crash also. Could someone help me?

**Comment by splhack** [comment]
MacVim does support if_python3. The exact same reason as the error message says `E837: This Vim cannot execute :py3 after using :python`, your .vimrc or somewhere else, it uses if_python. That's why MacVim couldn't use if_python3 at that time.
