### ISSUE TITLE
MacVim always links to system Ruby

### ISSUE THREAD

**Issue by shadowhand** [macvim-dev/macvim#468]
Unlike Vim, which will link to the first available Ruby (for instance, Homebrew Ruby in `/usr/local`), MacVim always links the OS version of Ruby. This causes plugins that depend on Ruby to be usable under Vim *or* MacVim, but not both.

Refs Homebrew/homebrew-core#10824

**Comment by splhack** [comment]
you are right. thanks.

**Comment by shadowhand** [comment]
@splhack thanks so much! Will this require a downstream change in Homebrew?

**Comment by splhack** [comment]
It'll work without any changes, I think.

**Comment by shadowhand** [comment]
@splhack awesome. Any idea when the next snapshot will be taken?

**Comment by splhack** [comment]
maybe after the test failure fixed.
