### ISSUE TITLE
MacVim / Norton Firewall Issue

### ISSUE THREAD

**Issue by cweilemann** [macvim-dev/macvim#470]
My apologies if this isn't the right forum for this, but I thought I'd at least start here...

I use Norton Internet Security as a firewall for my Mac, and with a recent update to MacVim (via Homebrew), I've been receiving the following warning approximately every 10-15 minutes, and it won't go away regardless of whether I click accept or decline...

![image](https://cloud.githubusercontent.com/assets/505478/23809844/c67ea2cc-0594-11e7-8647-f10d74e86d2b.png)

Is this a possible issue in MacVim? Or should I reach out to Norton about this? Other ideas?

Again, sorry for wasting time if this is the wrong forum, but thanks in advance for at least having a look.

*Update*

Here's where I see the files in question:

```
/usr/local/Cellar/macvim/8.0-127/MacVim.app/Contents/Resources/vim/runtime/autoload/decada.vim
/usr/local/Cellar/macvim/8.0-127/MacVim.app/Contents/Resources/vim/runtime/compiler/decada.vim
/usr/local/Cellar/vim/8.0.0386/share/vim/vim80/autoload/decada.vim
/usr/local/Cellar/vim/8.0.0386/share/vim/vim80/compiler/decada.vim
```

**Comment by splhack** [comment]
Please take a look at https://github.com/macvim-dev/macvim/issues/366
And you can stop auto update (Sparkle) https://github.com/macvim-dev/macvim/wiki/FAQ#how-can-i-disable-autoupdate-sparkle
Please let me know if you find something suspicious.
