### ISSUE TITLE
Bundle .po files when builds with +gettext

### ISSUE THREAD

**Issue by CarterLi** [macvim-dev/macvim#471]
MacVim won't bundle `.po` files so that NLS won't work even built with `+gettext`.
After copy them manually, it works.

<img width="950" alt="2017-03-12 9 39 41" src="https://cloud.githubusercontent.com/assets/6134068/23832453/511d49f2-076f-11e7-888c-bf49ba8057a0.png">

Yes, native menu is not translated. I'd like to contribute (for Chinese) if I knows how to do :)

Related: https://github.com/Homebrew/homebrew-core/pull/10951

**Comment by splhack** [comment]
Updated the official MacVim Homebrew formula to install gettext po files https://github.com/macvim-dev/homebrew-macvim/commit/22c39f35bf938c3a7d7df36e2e011c6cf0f1eac3

**Comment by splhack** [comment]
I'll update .travis.yml to bundle po files for the binary release if needed.
