### ISSUE TITLE
How to make macvim as editor in vimperator?

### ISSUE THREAD

**Issue by 3xp10it** [macvim-dev/macvim#473]
When I tried to make macvim as vimperator's editor in ~/.vimperatorrc as:
set editor='/Applications/MacVim.app/Contents/MacOS/MacVim -g -f'
it works not well,can you help me?
My os is macOS sierra.
Thx.

**Comment by jpetrie** [comment]
> it works not well

What exactly does this mean? Does it silently fail? Does it crash? Does it behave unexpectedly? How so?

I'm not familiar with vimperator, but it's possible you shouldn't be trying to launch MacVim by directly specifying the executable in the bundle. I'm not even sure the `MacVim` executable will parse those arguments. [The `mvim` script](https://github.com/macvim-dev/macvim/blob/master/src/MacVim/mvim) launches the `Vim` executable (see lines [44](https://github.com/macvim-dev/macvim/blob/master/src/MacVim/mvim#L44) and [86](https://github.com/macvim-dev/macvim/blob/master/src/MacVim/mvim#L86). Perhaps that's what you want?

**Comment by 3xp10it** [comment]
When I add a line `set editor='/usr/share/mvim -g $opts ${1:+"$@"}'` to ~/.vimperatorrc,it does not work(/usr/share/mvim is <a href="https://github.com/macvim-dev/macvim/blob/master/src/MacVim/mvim">the mvim script</a>),then I change the line to `set editor='/usr/share/mvim -g -f'`,it works,
but performs not very good,the detail is:
1st:I pressed ctrl+i in some input box in firefox,then macvim activated
2nd:I input some words in the activated macvim(gui) and run :wq
3rd:The macvim(gui) exited
4th:I found my current activated windows is not firefox,but still in macvim app(though the current macvim windows is
closed,but the macvim app is still running)that's to say,macvim didn't make me return back to
firefox after I have run :wq in macvim

Can you help me?

**Comment by jpetrie** [comment]
There's a setting you can set in MacVim's preferences, I believe, which will cause it to terminate after all windows are closed. This sounds like it will resolve your issue.

**Comment by 3xp10it** [comment]
Hi, @jpetrie I have realized the this may not be macvim's issue,but macos's issue,I have searched a lot about how to auto terminate a app after all windows are closed,but can not find a solution for my macOS sierra10.12.3,`RedQuits` seems good,but it seems not support macOS sierra.Here is the link:<a href="https://superuser.com/questions/53935/getting-mac-os-x-applications-to-close-after-last-window-closed">Solution</a>

**Comment by jpetrie** [comment]
Right. As I said, it's up to the application to decide whether or not it closed when all windows are closed. MacVim has a setting in the preferences to control this behavior, you should set it and that will fix your issue.

**Comment by 3xp10it** [comment]
Thanks,it works by setting MacVim's preferences.
