### ISSUE TITLE
Working directory changed when new file is open.

### ISSUE THREAD

**Issue by andrewplummer** [macvim-dev/macvim#474]
My workflow has always been `:cd parentdir` then open files with `:e path/to/file`.

However recently when I do this the working directory gets changed so that it becomes `parentdir/path/to/file` and `:e path/to/file` can't find the file because the path has changed.

Looking online I see old issues about this but it must be due to something that changed recently, as I've been working like this and haven't noticed it until recently... is there some setting that can prevent auto-changing directories?

**Comment by RichardDooling** [comment]
I'm not sure what your exact problem is, but try doing :h :lcd and :h filename-modifiers

I have this in my .vimrc, but I confess I had to look up the components when considering your problem.

" Change Working Directory Of Active File:
autocmd BufEnter * lcd %:p:h

I think you can come up with your own autocmd that will set yours anyway you want it.

Rick

**Comment by RichardDooling** [comment]
Even better

http://vim.wikia.com/wiki/Set_working_directory_to_the_current_file

**Comment by andrewplummer** [comment]
Apologies, I had recently updated my plugins and it turned out it was [a plugin update](https://github.com/mtscout6/syntastic-local-eslint.vim/issues/18) that is causing this behavior. I should have checked this first before opening this issue.
