### ISSUE TITLE
Vim runtime is not set properly

### ISSUE THREAD

**Issue by 13k** [macvim-dev/macvim#480]
When running from a symlinked binary, vim runtime is not set properly:

```shell
$ ls -l /usr/local/bin/vim
lrwxr-xr-x 1 k admin 43 Mar 22 15:17 /usr/local/bin/vim -> /Applications/MacVim.app/Contents/MacOS/Vim
```

```shell
$ /usr/local/bin/vim -u NONE -c 'syntax on'
# Error detected while processing command line:
# E484: Can't open file /usr/local/bin/vim/runtime/syntax/syntax.vim
# Press ENTER or type command to continue
```

```shell
output="/tmp/macvim.runtimepath"; for binary in /Applications/MacVim.app/Contents/MacOS/vim /Applications/MacVim.app/Contents/MacOS/Vim /usr/local/bin/vim; do echo -e "\n\n---\n\n${binary}" >> "$output"; "$binary" -u NONE -c "redir>>$output | echo &runtimepath | redir END | quit"; done
```

```shell
cat /tmp/macvim.runtimepath
```

```
---

/Applications/MacVim.app/Contents/MacOS/vim

/Users/k/.vim,/Applications/MacVim.app/Contents/Resources/vim/vimfiles,/Applications/MacVim.app/Contents/Resources/vim/runtime,/Applications/MacVim.app/Contents/Resources/vim/vimfiles/after,/Users/k/.vim/after

---

/Applications/MacVim.app/Contents/MacOS/Vim

/Users/k/.vim,/Applications/MacVim.app/Contents/Resources/vim/vimfiles,/Applications/MacVim.app/Contents/Resources/vim/runtime,/Applications/MacVim.app/Contents/Resources/vim/vimfiles/after,/Users/k/.vim/after

---

/usr/local/bin/vim

/Users/k/.vim,/usr/local/bin/vim/vimfiles,/usr/local/bin/vim/runtime,/usr/local/bin/vim/vimfiles/after,/Users/k/.vim/after
```

Exporting the env var `VIMRUNTIME=/Applications/MacVim.app/Contents/Resources/vim/runtime` works as expected.

Compiling vim via homebrew works. It seems it "hardcodes" the runtime path at compile time (at least the fallback path), so maybe this is an issue when compiling vim with macvim, I'm not sure.

**Comment by splhack** [comment]
I put vim script as well in the bundle, `/Applications/MacVim.app/Contents/bin/vim`. We can use this vim script instead of the binary.

**Comment by 13k** [comment]
I had previously tried with both the `Vim` binary and the `vim` script, but both fail to set the runtime path when symlinked

```shell
$ rm /usr/local/bin/vim
$ ln -s /Applications/MacVim.app/Contents/MacOS/vim /usr/local/bin/vim
$ vim -u NONE
# Error detected while processing command line:
# E484: Can't open file /usr/local/bin/vim/runtime/syntax/syntax.vim
# Press ENTER or type command to continue
```

**Comment by 13k** [comment]
Ignore my previous comment, I forgot the (default) filesystem is case insensitive and linking `vim` will actually point to `Vim`. Sorry about that.

So you mentioned `/Applications/MacVim.app/Contents/bin/vim` (which doesn't currently exists), I take it will be published in another release?

**Comment by splhack** [comment]
yes, `MacVim.app/Contents/bin/vim` script (symbolic link to the `mvim` script that was also fixed for symbolic link in master) will be included in the next release.

The `VIM_APP_DIR` setting line in the mvim script will be replaced as this.

    if [ -L $0 ]; then VIM_APP_DIR=`dirname "$(readlink $0)"`/../../..; else VIM_APP_DIR=`dirname "$0"`/../../..; fi

**Comment by 13k** [comment]
Thank you @splhack!
