### ISSUE TITLE
Upgraded to 128, again crashes instantly upon loading Python source.

### ISSUE THREAD

**Issue by amcgregor** [macvim-dev/macvim#483]
Opening text, makefiles, textile, markdown, vimrc, or C has no problem.  Opening Python explodes instantly.  Tested both with and without custom `PYTHONHOME` and `pythonthreedll` using homebrew-installed Python 3.6.0.  Only began crashing after the latest update (8.0.501 / 128).  Recovering version 127 from the trash, that one continues to work.  VimR (other than the expected poorer Unicode glyph handling) and CLI vim continue to operate correctly.  Third time there's a recurrence of an issue like this.  T_T

Crash report: http://s.webcore.io/3l1V0Q0a142C/Vim_2017-03-23-103942_asmodeus.crash

**Comment by splhack** [comment]
Have you tried to use `pythonthreehome` instead of PYTHONHOME?

**Comment by amcgregor** [comment]
Version 127 works without defining any environment variables to control Python functionality.  Setting `PYTHONTHREEHOME` does not cause version 127 to fail, but doesn't make version 128 work, either.  Same instant crash.

**Comment by splhack** [comment]
It's `pythonthreehome` in Vim not `PYTHONTHREEHOME` environment variable. Have you?

**Comment by amcgregor** [comment]
Case was irrelevant to the test.  I tested every possible combination of lower case, upper case, title case, and underscore separated with each case.  I'm through like that.

**Comment by splhack** [comment]
In Vim, could you paste of the result of `:set pythonthreehome?` and `:set pythonthreedll?`

**Comment by splhack** [comment]
Maybe Homebrew Python3 has issue. It is worth to try to reinstall python3, `brew install python3`.

**Comment by amcgregor** [comment]
Fair number of test combinations to get that output for.  Additionally, for some reason I doubt that the component that _didn't_ change is the one causing the problems instead of the only one that _did_ change (MacVim), but I'll give reinstallation of that a go after finishing the below matrix.

---

### No Configuration

#### MacVim 127 (Works)

```
pythonthreehome=
pythonthreedll=/usr/local/Frameworks/Python.framework/Versions/3.6/Python
```

#### MacVim 128 (Explodes)

```
pythonthreehome=
pythonthreedll=/usr/local/Frameworks/Python.framework/Versions/3.6/Python
```

---

### Old Explicit Configuration

Old configuration:

```
let $PYTHONHOME="/usr/local/Cellar/python3/3.6/Frameworks/Python.framework/Versions/3.6"                                                                                                                  
set pythonthreedll=/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/libpython3.6m.dylib
```

(Paths do exist.)

#### MacVim 127 (Works)

```
pythonthreehome=
pythonthreedll=/usr/locla/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/libpython3.6m.dylib
```

#### MacVim 128 (Explodes)

```
pythonthreehome=
pythonthreedll=/usr/locla/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/libpython3.6m.dylib
```


### New Explicit Configuration

```
set pythonthreehome="/usr/local/Cellar/python3/3.6/Frameworks/Python.framework/Versions/3.6"                                                                                                              
set pythonthreedll=/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/libpython3.6m.dylib
```

Doesn't seem to do anything at all.

#### MacVim 127 (Still Doesn't Explode)

```
pythonthreehome=
pythonthreedll=/usr/locla/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/libpython3.6m.dylib
```

#### MacVim 128 (Still Explodes)

```
pythonthreehome=
pythonthreedll=/usr/locla/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/libpython3.6m.dylib
```

**Comment by pstjohn** [comment]
on updating to the most recent snapshot (129) I also would get the python-related crash
```
Fatal Python error: Py_Initialize: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007fff79181000 (most recent call first):
Vim: Caught deadly signal ABRT
Vim: Finished.
```
When trying to load any modules which required python. I was able to fix it with a `brew reinstall python3`

**Comment by amcgregor** [comment]
@pstjohn I'd have been curious as to the result of running `python3 -c 'import encodings'` prior to reinstallation.  That command exhibits no errors for me, indicating to me that MacVim is failing to perform some step or set some variable (such as PYTHONHOME) prior to invocation of the embedded interpreter, leading to the failure to discover the stdlib.

**Comment by splhack** [comment]
python3 supporting code has not been changed between snapshot 127 and HEAD. So the solution might be `brew reinstall python3`.

**Comment by pstjohn** [comment]
@amcgregor, ran into this issue again today (not sure why, I don't think I updated..) `brew reinstall python3` fixed the problem again. Before that though I ran `python3 -c 'import encodings'` and got the same error:
```
Fatal Python error: Py_Initialize: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'
```

**Comment by amcgregor** [comment]
@pstjohn Mine behaves correctly everywhere except MacVim.  Build 127 continues to work.  I'll stay pinned at this version (will check newer ones occasionally) until time comes to reinstall the machine.

**Comment by splhack** [comment]
Because snapshot-130 binary requires Python 3.6.1. Python 3.6.0 and 3.6.1 are NOT binary compatible.
