### ISSUE TITLE
How to set macvim ruby to higher version

### ISSUE THREAD

**Issue by thefonso** [macvim-dev/macvim#484]
I use rbenv and my native cli vim internal ruby is set to ruby 2.4. how can I set macvim internal ruby to 2.4 instead of 2.0.0 so that the command :ruby p RUBY_VERSION displays 2.4 ?

**Comment by splhack** [comment]
The binary release supports only system Ruby, 2.0. You need to build MacVim by yourself for that. I updated the official Homebrew MacVim formula to support that as well.

https://github.com/macvim-dev/homebrew-macvim

    (Install Homebrew)
    (One time set up)
    $ brew tap macvim-dev/macvim
    (Set up $PATH environment to ensure to have the ruby command what you want to use if_ruby with)
    (Install MacVim)
    $ brew install --HEAD macvim-dev/macvim/macvim

**Comment by thefonso** [comment]
Followed above instructions...problem persist.  cli vim :ruby p RUBY_VERSION displays 2.4. macvim :ruby p RUBY_VERSION displays 2.0.
