### ISSUE TITLE
GUI doesn't find ssh-askpass

### ISSUE THREAD

**Issue by ZeerakW** [macvim-dev/macvim#485]
Using the terminal application I can use the fugitive plugin to push and pull from git, however when I'm trying to use the GUI application I receive the following error:

```
ssh_askpass: exec(/usr/local/Cellar/openssh/7.4p1/libexec/ssh-askpass): No such file or directory
|| Permission denied (publickey).
|| fatal: Could not read from remote repository.
```

The file does indeed not exist, but I'm not entirely sure why it tries to access it.

**Comment by splhack** [comment]
The reason might be that `$SSH_ASKPASS` was overridden by your vimrc or something.

That value is set correctly by the system gvimrc.
https://github.com/macvim-dev/macvim/blob/a8e1b3df21954b6259f66d1541a56d811ac0067f/src/MacVim/gvimrc#L41
