### ISSUE TITLE
Can not use fpp(Fackbook Path Picker) with Macvim

### ISSUE THREAD

**Issue by DemonCloud** [macvim-dev/macvim#489]
http://7j1zwt.com1.z0.glb.clouddn.com/error.png

shell error

but in terminal vim , it work currently.

I install fpp with homebrew
`brew install fpp`

**Comment by splhack** [comment]
fpp uses `/dev/tty`. GVim and MacVim doesn't support it.
Maybe we can use `pty` instead, but fpp uses terminal feature to draw the GUI. It also won't work on GVim and MacVim.
