### ISSUE TITLE
How to set column number to be visible in status bar?

### ISSUE THREAD

**Issue by 3xp10it** [macvim-dev/macvim#494]
When I come to macvim from vim,I found the displayed column number in the status bar disappered,
in vim,the column number displays like below:
<img src="https://raw.githubusercontent.com/3xp10it/pic/master/vimcolumnnuber.JPG">

upon 2,18 shows the current cursor's position is in line2,column18

but macvim doesn't have that message,I don't know how to set ~/.vimrc to make it act like vim to show column number in status bar? Can you help me? thanks.

**Comment by jpetrie** [comment]
I can think of two things offhand:

You could set the [`ruler` option](http://vimdoc.sourceforge.net/htmldoc/options.html#'ruler') (`set ruler` in your `.vimrc`); this will display the line and column of the cursor.

You can also configure the [`statusline` option](http://vimdoc.sourceforge.net/htmldoc/options.html#'statusline'). `%l` and `%c` in the status line string will show the line and column number of the cursor.

**Comment by 3xp10it** [comment]
It works,thanks. @jpetrie
