### ISSUE TITLE
Fullscreen no longer fills entire screen, leaving black borders

### ISSUE THREAD

**Issue by sidyll** [macvim-dev/macvim#496]
I just updated to the last MacVim version (8.0.567 (131)) and my full screen no longer works properly. When entering full screen, the window height remains the same from the max possible before entering full screen, which is smaller. The remaining space is left as black borders.

Previously this also happened, but using ⌃⌘Z to zoom the window would fix the problem and fill the entire screen. This no longer happens, the zoom basically does nothing. More on the video below:

![output](https://cloud.githubusercontent.com/assets/24523768/25204641/e9bf9ad8-2534-11e7-8800-9094e582c0d0.gif)

I'm using Yosemite (10.10.5). Using core text render or not makes no difference, also no difference in my main or secondary monitor. Disabling the native full screen support preference however causes the menu bar to remain stuck, as in the screenshot below. The borders are gone, but with the cut this mode is not usable either.

![screenshot](https://cloud.githubusercontent.com/assets/24523768/25204745/55170d8e-2535-11e7-9601-990f58de1530.png)

**Comment by m4c0** [comment]
For me, it's even worse. The black bands are really tall. After some trial-and-error, it seems the fullscreen window height is: `total_screen_height - top_bar_height - dock_bar_height` (for me, the full screen height and the space between the top bar and the dock are both exactly 710px. If I auto-hide my dock, the black band gets smaller.
