### ISSUE TITLE
Window goes black when using Spectacle to position it

### ISSUE THREAD

**Issue by DrRob** [macvim-dev/macvim#497]
I like that the latest version doesn't flicker when resizing, but a side-effect seems to be that when using Spectacle (https://github.com/eczarny/spectacle) to resize the window to the left or right half of the screen, sometimes the MacVim window goes black, with only the character under the cursor visible in white.  Pressing CTRL-L causes the contents to reappear.

**Comment by ralfpapenkordt** [comment]
Same here with Moom as window manager. The problem was introduced with the commits 3fb41cc and 32e1fc9, especially the line 664 in `src/MacVim/MMCoreTextView.m`:

`
drawPending = NO;
`

Commenting this line eliminates the redraw problem (and wrong resize problem of the MacVim window).

But I do not think, that this is the final solution. Maybe someone with a deeper understanding of the window redrawing in MacVim can take a look at the aforementioned commits.

**Comment by JESii** [comment]
Same situation for me; I banged on this for a bit and it seems to happen only with the following Spectacle command sequence:
`{Alt-Cmd-C}{Alt-Cmd-F}`
In other words, I center the window, then go full-screen with the window. All other combinations worked just fine in my testing.
El Capitan 10.11.6
MacVim Custom Version 8.0.596 (133)

**Comment by fanzeyi** [comment]
Same here, I always manually resize the window by a little to make the black screen go away. It is super annoying though.

**Comment by sc68cal** [comment]
Same here, with Amethyst

**Comment by L-Cafe** [comment]
Can confirm, Amethyst as well.

Easy to reproduce on Amethyst too.

1 - Have MacVim as the only window.
2 - Open a new window (preferably one without strict resizing limits, Safari or a text editor should do the job fine).
3 - Amethyst kicks in and resizes both windows to halves of the screen.
4 - Close the previously opened window.
5 - Amethyst kicks in and puts MacVim fullscreen again.
6 - Vim is now almost entirely black except the current line.

**Comment by drifkin** [comment]
I find the same problem using Slate (https://github.com/jigish/slate). If I create a new window (e.g., using `mvim` or cmd+N), and size the window so it's completely fullscreen, some of the window will be black and if there's text on screen, it will often be duplicated.

I can confirm that ctrl+L seems to fix it, or just resizing it a little bit.

**Comment by yalmasri** [comment]
I found this:
https://github.com/macvim-dev/macvim/issues/557#issuecomment-339864889

**Comment by benoittgt** [comment]
Isn't an issue that could be fixed regardless the comment https://github.com/macvim-dev/macvim/issues/497#issuecomment-299442827 ?
