### ISSUE TITLE
Scroll Performance on Retina Screens

### ISSUE THREAD

**Issue by amadeus** [macvim-dev/macvim#499]
It appears that scroll performance on retina screens is significantly worse that non-retina screens. It is also much worse when there's only 1 document open and the app is full screen, vs have multiple documents open (and thus far less width for each document).

I can look into making some videos of the performance differences, but it really is mostly an issue when in full screen.

I have the 5k iMac and it is REALLY bad when running full screen with a single document open. Are there any places that draw performance could be optimized?

[Video Example](https://dl.dropboxusercontent.com/s/nvnbkfr0cy8fg32/screencast_2017-05-17_21-23-45.mp4?dl=0)

**Comment by jordwalke** [comment]
Do you have a ligature font with ligatures enabled by any chance?

**Comment by amadeus** [comment]
I don't think so? I'm using Source Code Pro. What would be the setting to disable ligatures?

**Comment by jordwalke** [comment]
You'd have to go out of your way to enable it. Do `:set nomacliga` to disable them.

**Comment by amadeus** [comment]
I'll look to make a video tonight, but it will be from a 5k imac screen, so rather large. I think the issue has something to do with how wide the document is. If I split the screen a bunch, even with the same file, performance definitely improves.

**Comment by amadeus** [comment]
As promised, here's a link to a video showing off the performance differences:

[video](https://dl.dropboxusercontent.com/s/nvnbkfr0cy8fg32/screencast_2017-05-17_21-23-45.mp4?dl=0)

As an FYI, all 'scrolling' was done by holding down `<c-e>` or `<c-y>`

**Comment by amadeus** [comment]
Just a bump on this, any ideas on why it might be performing like so and could it be improved?

**Comment by StaverDmitry** [comment]
I also experience this issue on mbp 2017, it's better compared to terminal but still laggy. The 5k video provided in the answer above is a great example

**Comment by amadeus** [comment]
I also want to add an additional video - of nearly the same experiment but using a non retina, or a 1x monitor:

![1x example video](http://wtf.amadeus.wtf/monosnap/screencast_2017-11-27_15-08-29.mp4)

Notice how there's almost no difference in scroll speeds.  This leads me to believe there's something that gets wildly inefficient on retina displays.

Also another anecdote I think I've seen as well - native full screen performs a bit better than non-native full screen.

**Comment by amadeus** [comment]
I don't really know Objective-C, however doing a little digging I did notice a couple additional things to add to this issue:

The issue appears when using non-native full screen.

The issue seems to surface whenever `cgLayerEnabled` is set to true in `MMCoreTextView`. Based on my experiments, that value is normally false in native full screen or windowed mode.

For reference, I use these MacVim settings:

![settings](http://wtf.amadeus.wtf/monosnap/Advanced_2018-04-30_00-19-20.png)

I did some poking around in the `drawRect` function of `MMCoreTextView`, and sure enough, when using non-native full screen, `cgLayerEnabled` becomes true and we get  very sluggish performance (on large, high pixel density screens):

https://github.com/macvim-dev/macvim/blob/27bdb64a26aa4f69905b576ee8bbbf8b93cc5080/src/MacVim/MMCoreTextView.m#L607-L650

From what I can tell, the non `cgLayerEnabled` codepath (aka the `else` path):

https://github.com/macvim-dev/macvim/blob/27bdb64a26aa4f69905b576ee8bbbf8b93cc5080/src/MacVim/MMCoreTextView.m#L642-L649

is super efficient as it only updates parts of the screen that are necessary unlike non-native full screen that re-renders the entire document, killing performance on 5k retina monitors.

When I tried forcing that codepath on non-native full screen, i would just see black, unless I scrolled or did something and then would temporarily see region'd updates to the screen before going black in the next frame.

Looks like the only way to fix this would be for non-native full screen to use the `batchDrawData` function somehow, but that gets a bit out of my league.

**Comment by CodeMonkeyKevin** [comment]
Any update on this.

**Comment by ychin** [comment]
I'm closing this issue.

For 10.14 (Mojave), #757 has introduced a new renderer that doesn't use CGLayer and it's used across the board including non-native fullscreen. It's faster than the old CGLayer renderer (non-native fullscreen used to use), but a little slower than the old normal non-fullscreen renderer. If you are not satisfied with the new renderer's performance, use #796 to track.

For 10.13 (High Sierra) or below, this is a wontfix. Non-native fullscreen uses CGLayer and it's slow. You can either upgrade to 10.14 or use native fullscreen if the performance is too slow. The fix for #796 may be backported to 10.13 but that may not work if it involves using newer APIs.
