### ISSUE TITLE
Unable open file with space character in path

### ISSUE THREAD

**Issue by L3rchal** [macvim-dev/macvim#505]
Unable to open file which has space character in path. File is opened as an empty file.
Error: ```/usr/local/bin/vim: line 25: cd: /Users/ales/Library/Mobile: No such file or directory```

This happens when I am in the folder. I have to open file with escaped space char```vim ~/file/topath\ withspace/file```

Version: ``
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled May  6 2017 20:26:18)
MacOS X (unix) version
Included patches: 1-596
Compiled by Homebrew
``

**Comment by splhack** [comment]
I think #504 fixed this
