### ISSUE TITLE
The lower right corner contains some garbled pixels it seems

### ISSUE THREAD

**Issue by tobireif** [macvim-dev/macvim#507]
The lower right corner sometimes contains some garbled pixels it seems, eg:

<img width="508" alt="screenshot" src="https://cloud.githubusercontent.com/assets/80411/25795072/f62e1404-33d3-11e7-89bf-cd005dac4677.png">

**Comment by jpetrie** [comment]
Which renderer are you using? CoreText or non?

**Comment by tobireif** [comment]
Which command would tell us that?

**Comment by jpetrie** [comment]
In MacVim's preferences window (accessible from the menu bar) there's a checkbox for it; there's also one for native full screen or not, that would be interesting to know. Also, do you see this immediately when launching MacVim and opening a file? Or do you need to go into and come back from a fullscreen view?

**Comment by tobireif** [comment]
Core Test Renderer is checked, Native Full-Screen as well.

New windows have a white ~square, after resizing it becomes black with a tiny mixed-color square (eg as in the screenshot).

**Comment by tobireif** [comment]
<img width="455" alt="screenshot" src="https://cloud.githubusercontent.com/assets/80411/25816549/b4b1678c-3424-11e7-8048-269437261fd0.png">

**Comment by tobireif** [comment]
Its just a small detail, and it doesn't bother me, but when I create screenshots and publish them it would make MacVim look cleaner if this were fixed ...

**Comment by eirnym** [comment]
@tobireif Does it still an issue? Please, close if not
