### ISSUE TITLE
`set fuopt-=maxhorz` doesn't work anymore in non-native FS

### ISSUE THREAD

**Issue by chdiza** [macvim-dev/macvim#509]
Make macvim set to do non-native fullscreen (NNFS) mode.  Then do `mvim -u NONE -U NONE -N` then do:
```
:set co=80
:set fuopt-=maxhorz
:set fu
```
What should happen is that MacVim enters NNFS, but `&co` is still 80.  What actually happens is that MacVim acts as if the `-=maxhorz` didn't happen.

It might be related to one of the additional difficulties from #488.

**Comment by ychin** [comment]
@chdiza Do you actually use `fuopt`? I barely remember that option exists and curious what the use cases for this option is. Is it just to focus or avoiding having too large an edit area?

**Comment by chdiza** [comment]
@ychin I used to use `&fuopt` very frequently, until it broke.  It's been broken for a long time, which is too bad.  I miss this feature.  I can fake an approximation by having one MacVim window in (non-native) fullscreen and a second MacVim window on top of it that isn't in fullscreen, and make sure they have the same colorscheme.

I don't know what others use it for, but *I* use it so that I can be in (non-native) fullscreen but have a more normal number of columns (e.g., 80).  That way the lines don't get too long to read comfortably, while at the same time I fit as many lines as possible on the screen, and everything is easier visually to deal with because other things are blocked by the rest of the fullscreen-ness.

I don't think I ever made use of the `maxvert` piece, myself.  (I never had a monitor that was "too tall", even before the unfortunate widescreen revolution.)

Perhaps getting this to work correctly causes too many problems, I have no idea.  It's much more important to have a properly functioning non-native fullscreen than it is to have a half-working `&fuopt`.

Oh, also I never personally used the `background` piece of `&fuopt`.
