### ISSUE TITLE
GUI MacVim does not mark buffer as modifed when changing case using ~

### ISSUE THREAD

**Issue by thblt** [macvim-dev/macvim#51]
When editing a file using the MacVim GUI, the buffer isn't marked as modified when changing the case of one or more characters using the ~ command in normal mode. Strange enough, when repeating the operation with dot, the buffer is correctly marked as modified.

The problem doesn't occur when using the text version of MacVim.

It may be a keyboard mapping-specific bug, if you can't replicate it, I can try to refine the report by testing other mappings (I'm using French azerty).

Thanks,

**Comment by chdiza** [comment]
I cannot replicate this.

Did you try `mvim -u NONE -U NONE -N`?

**Comment by thblt** [comment]
Yes, exact same problem.

It seems to be somehow related to the way the French azerty mapping behaves : it all works fine with an US qwerty mapping (where, IIUC, ~ is Cmd+Opt+n). The Swiss French Qwertz has the same problem as the French azerty, though.

For some reason, my Linux VM won't boot, I'm going to reinstall it and try in gvim to compare. It may be a vim bug.

**Comment by thblt** [comment]
It seems to have to do with the way the ~ key (and not the command) behaves:
 * The buffer gets the modified flag when another gey gets pressed after ~, like : (which obviously hasn't changed it). Weird enough, after ~, even Cmd-S doesn't save the buffer but instead marks it as modified. I would suspect some strange dead key behavior.
 * To insure that the problem doesn't have to with the toggle case command, i remapped p to ~ (```nnoremap p ~```) :  p correctly changes the case and sets the buffer modified flag. 
 * If instead I remap ~ to x (```nnoremap ~ x```) the problem continues to occur with ~, even though it now does a very different thing.

**Comment by thblt** [comment]
Found it : disabling “draw marked text inline” in MacVim's preferences fixes the problem.
