### ISSUE TITLE
How to make it possible to auto switch input method in MacVim as console mode

### ISSUE THREAD

**Issue by 3xp10it** [macvim-dev/macvim#510]
I want to change input method to English when MacVim exit insert method,and want MacVim change back to my own input method (not English input method),but I can not find any way to solve this?
Can you help me?
(I use MacVim as console mode in my iterm2)
(Below is my own solution:
https://github.com/3xp10it/AutoIM
but it performs not perfect,each time I press Esc,I have to wait around 1 second,I don't want to wait this 1 second any more)
Thanks.

**Comment by splhack** [comment]
Unfortunately, Vim (or MacVim CUI on console) doesn't have any capability to do that.
Maybe you can use Karabiner to send ESC and key combination to disable IM when you hit ESC, or something like that.
https://pqrs.org/osx/karabiner/
