### ISSUE TITLE
typo in title of snapshot-132 release

### ISSUE THREAD

**Issue by davidchambers** [macvim-dev/macvim#511]
The title of <https://github.com/macvim-dev/macvim/releases/tag/snapshot-132> is currently "snapshot-132: MacVim Snapshot 131". I assume the last character should be a "2" rather than a "1".

**Comment by splhack** [comment]
thanks for the report. won't fix.

**Comment by davidchambers** [comment]
I assumed someone would edit the title of the GitHub release. It wouldn't break anything, as it's not used in URLs. It was just a suggestion, though. :)
