### ISSUE TITLE
"Screen Bounce" when using mouse to resize windows

### ISSUE THREAD

**Issue by JESii** [macvim-dev/macvim#512]
I am experiencing what I call "screen bounce" -- MacVim is automatically repositioning / resizing windows without any request on my part.

For example, I have MacVim open with NERDTree on the left and three windows open for text editing. I am working in the bottom window, and use the mouse to make the middle window smaller so that I have more room in my active window.  After a few seconds, MacVim automatically resizes that middle window back to its previous size.

I have a SWF / MP4 video of the behavior

**Comment by ychin** [comment]
@JESii Does this still happen? A few resizing fixes have gone in to MacVim over the last few releases which should make it more robust now.

**Comment by JESii** [comment]
Yes; definitely seems resolved; thanks!

**Comment by ychin** [comment]
Good to know! Always nice to close off these old loose ends.
