### ISSUE TITLE
"Are you sure you want to quit MacVim?"

### ISSUE THREAD

**Issue by tobireif** [macvim-dev/macvim#513]
After I closed the last window, I got this:
```
Are you sure you want to quit MacVim?
There are 2 windows open in MacVim. Do you want to quit anyway?
```
<img width="420" alt="screenshot" src="https://cloud.githubusercontent.com/assets/80411/26753798/aec3622c-486e-11e7-9c71-2defa8ac57a5.png">

... although there are no Vim windows/buffers/files open, neither minimized windows nor normal windows.

**Comment by ychin** [comment]
@tobireif is this still an issue? I couldn't reproduce this and curious what the "General" page of your MacVim preference pane looks like.

**Comment by tobireif** [comment]
Thanks for asking! Closing.
