### ISSUE TITLE
Launching a second gvim window from gvim crashes due to python3

### ISSUE THREAD

**Issue by Benhgift** [macvim-dev/macvim#518]
I installed python3 via the python website. I installed MacVim via `brew install macvim --with-python3` and then launched `gvim myfile.py`. From gvim I typed `:!gvim %<cr>` and it opened. This second window crashed after running any python3 command (`:py3 print('hi')<cr>`) but the first window runs them fine. 

I worked around this by separating the processes. https://vi.stackexchange.com/questions/12764/osx-cant-run-gvim-from-gvim 

Let me know if I put this issue in right or not. I'm happy to change it. I'm also happy to work on fixing this if someone wants to help me on it.

**Comment by eirnym** [comment]
It works fine with MacVim build 155.

**Comment by Benhgift** [comment]
@eirnym Tested and working fine for me now too 👍 

Thanks
