### ISSUE TITLE
Typing in Japanese text doubles its input

### ISSUE THREAD

**Issue by douglasdrumond** [macvim-dev/macvim#52]
When typing text in Japanese, after choosing the right kanji in the dropdown menu (IME system), MacVim input the text twice. For instance, typing おはよう inputs おはようおはよう.

**Comment by splhack** [comment]
Have you tried this setting?

    :set backspace=indent,eol,start

In my understanding, Vim uses backspace for updating IME input. Thus it needs proper setting.
