### ISSUE TITLE
There is a bug with `getchar(0)` !

### ISSUE THREAD

**Issue by Yggdroot** [macvim-dev/macvim#522]
In my plugin [LeaderF](https://github.com/Yggdroot/LeaderF), there is an issue https://github.com/Yggdroot/LeaderF/issues/48, it turn out to be a bug of MacVim.
The issue is located in [this](https://github.com/Yggdroot/LeaderF/blob/master/autoload/leaderf/cli.py#L307-L400) code block.
Could it be fixed please?

**Comment by Yggdroot** [comment]
This is a known issue, the same as https://groups.google.com/forum/#!searchin/vim_mac/getchar%7Csort:relevance/vim_mac/5adx7eFV_fU/BAJMrdzkFDkJ,
Can it be fixed?

**Comment by ichizok** [comment]
Could you try this patch?

```diff
--- a/src/MacVim/gui_macvim.m
+++ b/src/MacVim/gui_macvim.m
@@ -333,7 +333,7 @@ gui_mch_update(void)
     static CFAbsoluteTime lastTime = 0;

     CFAbsoluteTime nowTime = CFAbsoluteTimeGetCurrent();
-    if (nowTime - lastTime > 0.2) {
+    if (nowTime - lastTime > 0.033) {
         [[MMBackend sharedInstance] update];
         lastTime = nowTime;
     }
```

**Comment by Yggdroot** [comment]
This patch makes performance a little better, but does not fix the issue completely.
