### ISSUE TITLE
Cursor is redrawn after the character is inserted

### ISSUE THREAD

**Issue by lifepillar** [macvim-dev/macvim#524]
Using MacVim 8.0.648 (134). To reproduce:

```vim
:set ft=markdown
:autocmd TextChangedI * sleep 1
```

Then, start typing. You will clearly see that the cursor is redrawn after the character is inserted. The same happens even if `TextChangedI` is replaced by `CursorMovedI`.

That seems to happen only if the filetype has an associated syntax file (try with `set ft=`, the cursor won't lag any more). The setting “Use Core Text renderer” does not matter.

FYI, the issue was discussed [here](https://github.com/lifepillar/vim-mucomplete/issues/67#issuecomment-314044012) (scroll down, it took me a while to figure out that MacVim was involved).

**Comment by eirnym** [comment]
@lifepillar Can't reproduce it in build 155

**Comment by lifepillar** [comment]
I cannot reproduce it either (build 155). Thanks!
