### ISSUE TITLE
Warning on launch on macOS 10.13 Beta 3 (17A306f)

### ISSUE THREAD

**Issue by sfsam** [macvim-dev/macvim#525]
On macOS 10.13 Beta 3, I get this warning when launching MacVim. It does not seem to affect the app's behavior.

`*** WARNING: Textured window <MMWindow: 0x7f9e7f453d60> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.`

**Comment by drougojrom** [comment]
The same issue on macOS High Sierra 10.13 GM candidate.

**Comment by UncleVic** [comment]
Like thus issue on macOS High Sierra 10.13

`Electron[14728:1079433] *** WARNING: Textured window <AtomNSWindow: 0x7fc6fa699bd0> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.`

**Comment by questdev** [comment]
I also stumble on the same issue on High Sierra 10.13:

> MacVim[8898:804453] *** WARNING: Textured window <MMWindow: 0x7fe9cf42dc20> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.

**Comment by joevo2** [comment]
Same issue with high sierra https://github.com/electron/electron/issues/10559

**Comment by DexIO** [comment]
same issue
WARNING: Textured window <AtomNSWindow: 0x7f9094593e00> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
Also electron icon looks different

**Comment by basmoura** [comment]
Same issue here

**Comment by AlexVentura** [comment]
Same issue
**MacVim Custom Version 8.0.1175 (138)**
**MacOS 10.13 High Sierra 10.13 (17A405)**

**Comment by jakechan2012** [comment]
I have the same issue when install with dmg or `brew cask install macvim`, but `brew install macvim` works well

**Comment by vitahlin** [comment]
I found that if update Command Line Tools to the latest version in App store then it works well.

- macOS version : macOS High Sierra 10.13
- Command Line Tools version : Command Line Tools(macOS High Sierra version 10.13) for Xcode.(I updated that in Oct 17 2017 and **I do not install Xcode**)
- macvim: `brew cask install macvim`

**Comment by vitahlin** [comment]
Same issue.

**Comment by splhack** [comment]
Could you guys try to use snapshot-139? https://github.com/macvim-dev/macvim/releases/tag/snapshot-139

**Comment by merqurio** [comment]
@splhack No warnings with snapshot-139.

**Comment by AlexVentura** [comment]
@splhack Good job! Now it works like a charm using `MacVim Snapshot 139` on **MacOS 10.13 High Sierra 10.13 (17A405)**!

**Comment by questdev** [comment]
Just downloaded snapshot-139, no more warnings on macOS 10.13 17A405.
Great job, thanks a lot!

**Comment by vitahlin** [comment]
Thanks a lot.

**Comment by alanning** [comment]
@splhack Sorry to comment on an old issue but I was wondering if you might remember what you did to correct this?  I'd like to try to fix this in [electron](https://github.com/electron/electron/issues/12814) and would like to use your patch for reference but I'm having trouble locating it in the following snapshot commits:

https://github.com/macvim-dev/macvim/commits/snapshot-139

If you have time, would you mind pointing me to the commit that fixed this issue, please?

**Comment by splhack** [comment]
@alanning I think it just changed Xcode from 8 to 9.1. https://github.com/macvim-dev/macvim/commit/50e45d2e95ea8a074810bd59f842ad38253727ea
