### ISSUE TITLE
Ctrl-C cannot interrupt running command

### ISSUE THREAD

**Issue by yousong** [macvim-dev/macvim#526]
I installed MacVim with MacPorts.  The version combination is `MacVim @8.0.snapshot133` and and `Vim version 8.0.596`.

The issue can be reproduced by issuing the following command

```
:call system('sleep 5')
```

I can interrupt it with `Ctrl-C` on vim command line mode, but this is not possible in MacVim window.

I have encountered several times with this issue and it's really annonying

 - CtrlP is a plugin I use and sometimes it was called to search a very BIG directory and I have to switch to command line to find then kill the "find" process
 - The other day I fat-fingered and told NerdTree to delete my home directory...  Again I need to switch to command line to kill the `rm -rf` call...

**Comment by alisnic** [comment]
Not really a fix for your problem, but did you try using thesilversearcher together with CtrlP? The search performance is huge

**Comment by yousong** [comment]
I thought CtrlP is a file finder plugin and ag is a file content searcher utility.  I only occasionally use ag with Ack plugin, most of the time I just invoke ag directly on the console.  But I digressed ;)

**Comment by alisnic** [comment]
here's how I configured it https://github.com/alisnic/.dotfiles/blob/macos/.vimrc#L55

the nicest thing is that if you have a properly configured .agignore in your home (https://github.com/alisnic/.dotfiles/blob/macos/.agignore), CtrlP will benefit from that too

**Comment by yousong** [comment]
Hi, @alisnic , the "grep" in my original post it's typo and I was actually using "find" (https://github.com/yousong/dconf/blob/master/data/_vimrc.plugins#L75).

It also seems that in this case "find" is the more appropriate tool for listing directory content: it does not need to scan through file content.  But we really digressed more here ;)

```
➜  ~/.vim/bundle/ctrlp.vim git:(dconf) time find . -type f >/dev/null
find . -type f > /dev/null  0.00s user 0.00s system 72% cpu 0.006 total
➜  ~/.vim/bundle/ctrlp.vim git:(dconf) time ag . -l --nocolor --hidden -g "" >/dev/null
ag . -l --nocolor --hidden -g "" > /dev/null  0.00s user 0.01s system 73% cpu 0.011 total
```

**Comment by alisnic** [comment]
-l and -g tells `ag` to search for filenames by pattern, not contents, from ag docs:

```
  -g --filename-pattern PATTERN
                          Print filenames matching PATTERN
  -l --files-with-matches Only print filenames that contain matches
                          (don't print the matching lines)
```

**Comment by eirnym** [comment]
Does this work in original vim?

**Comment by yousong** [comment]
@eirnym, when I searched for vim gui, macvim pops up in the google results.  I never tried original vim gui on osx.  Does it exist?  I will happily switch to it if it works.

**Comment by eirnym** [comment]
I haven't seen that `CTRL-C` and other signals well supported in GUI vim (e.g. GViM or MacVim) as it require TTY emulation which is not fully made as it isn't intended to be. 

From `:help gui-pty`:
> When using ":make" it's not possible to interrupt with a CTRL-C.

I found a recent topic in `vim_use`:
http://vim.1045645.n5.nabble.com/Issue-with-using-gvim-system-and-fzy-td5728786.html

**Comment by yousong** [comment]
@eirnym , thank you for the info.   I just tried `:!sleep 5` and `:r !sleep 5`, both can be interrupted by Ctrl-C in comparison to `:call system("sleep 5")`.  Do you know if this is expected result?  I will try to patch the said plugins.

**Comment by eirnym** [comment]
I think yes. `Vim Plug` has it's own version of `system` to handle this situation

**Comment by yousong** [comment]
Close this for now.  Guess I will be more careful playing with vim plugins ;)

**Comment by yousong** [comment]
And thank you guys for your previous times on this
