### ISSUE TITLE
MacVim Snapshot 135 crash

### ISSUE THREAD

**Issue by jasonkit** [macvim-dev/macvim#532]
After upgraded to MacVim Snapshot 135, it crash with following console log
```
Fatal Python error: Py_Initialize: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007fffc7d5a3c0 (most recent call first):
Vim: Caught deadly signal ABRT
Vim: Finished.
```

**Comment by splhack** [comment]
`brew reinstall python3` may fix if you are using Homebrew.

**Comment by pstjohn** [comment]
I can't get either snapshot 135 or 136 to work, with the same error message.
`brew reinstall python3` hasn't fixed it as it has in the past.

Snapshot 134 works fine.
