### ISSUE TITLE
Preferences uses non-Retina icon for Advanced tab

### ISSUE THREAD

**Issue by sfsam** [macvim-dev/macvim#533]
The Preferences panel uses a non-Retina icon for the Advanced tab. MacOS has a standard image for this. It looks like MacVim attempts to use this standard image, but fails and falls back to a custom non-Retina image included in the project.

I created a pull request that uses the macOS standard Advanced icon: https://github.com/macvim-dev/macvim/pull/528

**Comment by splhack** [comment]
merged, thanks.
