### ISSUE TITLE
MacVim is overriding runtimepath

### ISSUE THREAD

**Issue by alexluecke** [macvim-dev/macvim#538]
When loading MacVim, I set additional folders for the runtime path (which includes Vundle bundle directory). However, when I load MacVim I see none of the folders I have added to my `rtp`.

Running the command `echom &rtp` from MacVim gives only the following paths:

```
/Users/USERNAME/.vim,
/Applications/MacVim.app/Contents/Resources/vim/vimfiles,
/Applications/MacVim.app/Contents/Resources/vim/runtime,
/Applications/MacVim.app/Contents/Resources/vim/vimfiles/after,
/Users/USERNAME/.vim/after /Users/USERNAME/.vim,
/Applications/MacVim.app/Contents/Resources/vim/vimfiles,
/Applications/MacVim.app/Contents/Resources/vim/runtime,
/Applications/MacVim.app/Contents/Resources/vim/vimfiles/after,
/Users/USERNAME/.vim/after
```

which does not include any of my paths.

**Comment by splhack** [comment]
I don't think it's MacVim issue. You may post your question to the vim_mac Google Group ( https://groups.google.com/forum/#!forum/vim_mac ).
https://github.com/macvim-dev/macvim/wiki/FAQ#my-question-is-not-answered-in-this-faq--where-can-i-ask-for-help

**Comment by alexluecke** [comment]
You were correct, this ended up being a zsh issue. I had to symlink my main `.zsh` profile to `~/.zprofile` and MacVim behaved normally.
