### ISSUE TITLE
Black dot under Dock item sometimes remains after last file/buffer has been closed

### ISSUE THREAD

**Issue by tobireif** [macvim-dev/macvim#539]
The Black dot under the Dock item sometimes remains after the last file/buffer has been closed.

Can't reproduce it.

**Comment by tobireif** [comment]
Screenshot:
<img width="125" alt="screenshot" src="https://user-images.githubusercontent.com/80411/29169398-2d8db4c8-7dd4-11e7-95df-923db6f73f7f.png">

No windows are open, but there's a black dot under the MacVim icon in the Dock.

**Comment by douglasdrumond** [comment]
That's the usual behavior on macOS. If an app is still open, there's a dot below the icon, even without windows. Except for a few apps that quit after closing the last window (but then you would see the icon disappearing from the Dock, except for the apps you choose to keep), the app is open and the dot remains. Example: Terminal.app or Preview.app

**Comment by tobireif** [comment]
I had and have this MacVim pref set:

<img width="483" alt="screenshot" src="https://user-images.githubusercontent.com/80411/29205096-0abf34d8-7e7b-11e7-8195-47c69f0085f6.png">

Normally it works. For example just now I closed the last MacVim window and the black dot in the Dock disappeared, as desired (and the MacVim icon in the Dock stayed, as desired).

But sometimes/often it doesn't work, the black dot (and I guess also the MacVim app) stays around.

**Comment by tobireif** [comment]
It still happens:

<img width="182" alt="screenshot" src="https://user-images.githubusercontent.com/80411/29969627-3d5c915e-8f21-11e7-9a26-e2257e7f6128.png">

**Comment by tobireif** [comment]
Is this fixable?

**Comment by splhack** [comment]
`applicationShouldTerminateAfterLastWindowClosed:` returns YES if "Quit MacVim" selected. And it worked as expected. I guess the cause of issue might be related to plugins you're using.

**Comment by tobireif** [comment]
I haven't added any plugins in years, but the issue I reported started a few weeks/months ago.

The issue does happen here.

Please re-open.

**Comment by tobireif** [comment]
What data could I supply in order to enable you to reproduce the issue?

**Comment by tobireif** [comment]
It only happens with MacVim, not with any other app I use.

**Comment by tobireif** [comment]
It seems the issue is gone (perhaps it was caused by an issue in MacOS?), closing.
