### ISSUE TITLE
Latest Macvim update via Homebrew installs Python dependency

### ISSUE THREAD

**Issue by bdielman** [macvim-dev/macvim#54]
Couldn't find anything in the latest release notes nor the Homebrew formula that made this dependency obvious to me.

**Comment by douglasdrumond** [comment]
MacVim releases are built with Python, but anyone willing to compile it
without Python support can do so. You need to check with Brew project how
is the formula for MacVim, it doesn't depend on us.

2015年7月10日(金) 21:41 Brad Dielman <notifications@github.com>:

> Couldn't find anything in the latest release notes nor the Homebrew
> formula that made this dependency obvious to me.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/macvim-dev/macvim/issues/54>.
>
-- 

Douglas Drumond

Androidから送信。
