### ISSUE TITLE
MMNoTitleBarWindowKey for hiding titlebar doest not work properly

### ISSUE THREAD

**Issue by mirca** [macvim-dev/macvim#540]
As reported by a few users, looks like the solution merged in #111 is not working as intended.

I'm using macOS Sierra 10.12.5 and MacVim 8.0.891 (136).

_PS: Sorry if this is a duplicate_

**Comment by garbagemule** [comment]
Possible duplicate: https://github.com/macvim-dev/macvim/issues/490

**Comment by ychin** [comment]
Dup of #490
