### ISSUE TITLE
term_sendkeys() + term_wait() may cause the shell to exit

### ISSUE THREAD

**Issue by lifepillar** [macvim-dev/macvim#542]
To reproduce, source this file:

```vim
let bn = term_start(&shell)
sleep 3
call term_sendkeys(bn, "echo 'Hello world'\<cr>")
call term_wait(bn)
```

After executing the code above, the shell unexpectedly exits.

The issue does not occur if you either

- (a) remove the `sleep` command, or
- (b) replace the last line with a call to `WaitFor()` (from `src/testdir/shared.vim`):

```vim
call WaitFor('term_getline(bn)!=""')
```

Besides, the code above works as expected in terminal Vim (as of 8.0.946).

I can reproduce the issue using the current master.

**Comment by splhack** [comment]
Since 8.0.0957, term_sendkeys has been non-blocking. However I don't know how to wait it.

**Comment by lifepillar** [comment]
I have made some tests, and it seems that MacVim does not need `term_wait()` as terminal Vim does. It still is a bit puzzling to see different behaviours (does MacVim do buffering differently? Or is simply just faster?), but I can live with that. Documenting such differences would be nice, though.

**Comment by splhack** [comment]
The timing of channel handling are totally different between GUI and non-GUI. Contribution(updating document) is always welcome :)

**Comment by lifepillar** [comment]
For reference, this is my function to send keys to a terminal buffer, which appears to work in both Vim and MacVim:

```vim
fun! TerminalSend(bn, lines)
  for l:line in a:lines
    call term_sendkeys(a:bn, l:line . "\r")
    call s:term_wait(a:bn)
  endfor
endf

if has('gui_running')
  fun! s:term_wait(bn)
  endf
else
  fun! s:term_wait(bn)
    call term_wait(a:bn)
  endf
endif
```

**Comment by lifepillar** [comment]
>The timing of channel handling are totally different between GUI and non-GUI. Contribution(updating document) is always welcome :)

If anything, I'd like non-GUI Vim to behave like MacVim :)
