### ISSUE TITLE
Ruby not enabled in Snapshot 137

### ISSUE THREAD

**Issue by stevenharman** [macvim-dev/macvim#549]
Am I correct in expecting Ruby to be enabled, or has that changed (very) recently? After upgrading to the latest snapshot - 137 - Ruby is no longer enabled. This impacts anyone who uses the pre-built images, including Homebrew users.

<img width="1670" alt="macvim-no-ruby" src="https://user-images.githubusercontent.com/48658/30815598-aa8d48a4-a1e1-11e7-8acc-80f5100afc43.png">

**Comment by stevenharman** [comment]
Well, I think I'm wrong. I believe the Homebrew pre-built image of MacVim was incorrectly built w/o Ruby support. That's what the above screen shot was from - I incorrectly assumed it was due to a change in MacVim. My mistake.

**Comment by splhack** [comment]
yep, using Travis CI to ensure ruby support https://github.com/macvim-dev/macvim/blob/2a33867b14fe6639ed906c61aaa6852f391e0008/.travis.yml#L44

**Comment by stevenharman** [comment]
👍 I pulled down the latest release and confirmed Ruby is enabled. It's a problem with the Homebrew pre-compiled bottle for (at least) Sierra. Thanks.

**Comment by mvcouwen** [comment]
@stevenharman A similar problem occurs when trying to update to snapshot 159. Any idea how it got solved back then?

**Comment by eirnym** [comment]
@mvcouwen Please tell how do you installed MacVim? I can't reproduce it with official builds from GitHub.

**Comment by mvcouwen** [comment]
@eirnym Actually, I don’t think there is any problem with MacVim itself. It seems more likely that there is a problem with Homebrew. There seems to be a Ruby mismatch when trying to build a bottle for MacVim on Mojave. See Homebrew/homebrew-core#45455

**Comment by eirnym** [comment]
Please, look at #947 for the issue you have
