### ISSUE TITLE
Link to download page? 

### ISSUE THREAD

**Issue by yufangfred** [macvim-dev/macvim#55]
I started using vim about a year ago. 
It was this afternoon when I had an issue with my python configuration, I came across this link in some website almost irrelevant to downloading vim. https://github.com/b4winckler/macvim/downloads

I was surprised that you can unload and use pre-build snapshot so easily, like other mac softwares(I remembered I spend hours trying to figure out how to download and install etc.)

I went back to the project homepage. Still I can't find any link to that page. Imagine if I need to download vim again, I probably still would spend very long time and detour to homebrew or Mercurial... and still can't find that download subfolder of the project. 

So, are there any tricks in github or hidden button that can easily link to the download page which I don't know about, or the author is making it obscure on purpose? Thanks.

**Comment by eaoliver** [comment]
You can download binaries from the release page of the project: https://github.com/macvim-dev/macvim/releases

**Comment by douglasdrumond** [comment]
Thanks, Earl.


--
Douglas Drumond
*​​Café Linear <http://www.cafelinear.com/> – GDG Campinas
<http://www.gdg-campinas.org/>​*
*google.com/+DouglasDrumond
<http://google.com/+DouglasDrumond> – @douglasdrumond
<http://twitter.com/douglasdrumond>​​*
