### ISSUE TITLE
External search hangs on High Sierra

### ISSUE THREAD

**Issue by bdarfler** [macvim-dev/macvim#551]
First off thank you so much for MacVim. Now onto my troubles ;-)

I've been using https://github.com/mileszs/ack.vim configured to use https://github.com/BurntSushi/ripgrep for searching through projects for a while now. Today I upgraded to High Sierra and that functionality now hangs MacVim. I've tried to create as minimal a test case as I can. I'm also new to debugging vim/macvim so please let me know if there is additional information I should add. 

I have a [minimal vimrc](https://github.com/macvim-dev/macvim/files/1342746/vimrc-minimal.txt) 

```
" Use rg for grepping
set grepprg=rg\ --vimgrep

" https://robots.thoughtbot.com/faster-grepping-in-vim
command -nargs=+ -complete=file -bar Rg silent! grep! <args>|cwindow|redraw!
```

When I use the `Rg` command in vim it works successfully. However, I do notice that the output of the `rg` command shows in the terminal after quitting vim which I don't believe was the case before High Sierra (sorry for my spotty memory as I primarily use macvim).

When I use the `Rg` command in mvim it simply hangs.

![rg-hang-high-sierra](https://user-images.githubusercontent.com/197776/30996684-90fd0eae-a490-11e7-9900-745de0e594f8.gif)

[mvim-version.txt](https://github.com/macvim-dev/macvim/files/1342744/mvim-version.txt)
[vim-version.txt](https://github.com/macvim-dev/macvim/files/1342745/vim-version.txt)

**Comment by markevich** [comment]
Same issues with ack.vim. Mvim is completely freezes after search

**Comment by adimitri** [comment]
I was able to solve this issue by building the latest version of MacVim with instructions here: https://github.com/macvim-dev/homebrew-macvim

I believe the issue was fixed with this commit: c958b31

**Comment by bdarfler** [comment]
@adimitri thank you! that worked for me as well. Anyone know how to get a new release cut?

**Comment by bdarfler** [comment]
Ah, https://github.com/macvim-dev/macvim/releases/tag/snapshot-138 fixes this.
