### ISSUE TITLE
Error building MacVim on macOS 10.13 High Sierra.

### ISSUE THREAD

**Issue by mario-grgic** [macvim-dev/macvim#552]
I get the following error building on macOS 10.13:

```
/Library/Frameworks/Python.framework/Versions/3.5"' -DDYNAMIC_PYTHON3_DLL=\"Python.framework/Versions/3.5/Python\"  -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/if_python3.o if_python3.c
gcc -c -I. -I/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0 -I/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/universal-darwin17 -DRUBY_VERSION=23 -DRUBY_VERSION=23 -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/if_ruby.o if_ruby.c
if_python.c:68:11: fatal error: 'Python/Python.h' file not found
# include <Python/Python.h>
          ^~~~~~~~~~~~~~~~~
if_ruby.c:121:11: warning: non-portable path to file '<ruby/ruby.h>'; specified path differs in case
      from file name on disk [-Wnonportable-include-path]
# include <Ruby/ruby.h>
          ^~~~~~~~~~~~~
          <ruby/ruby.h>
1 error generated.
```

Fixing if_python.c and changing ```#include <Python/Python.h>``` to just ```#include <Python.h>``` fixes it.

**Comment by basmoura** [comment]
I'm having this issue
```
2017-10-02 22:00:25.847 MacVim[37856:14232413] *** WARNING: Textured window <MMWindow: 0x7ff207435de0> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
```

The MacVim do not stars on fullscreen

**Comment by ActionScripted** [comment]
@basmoura I believe your issue may be related more to #525

**Comment by AlexVentura** [comment]
Same issue
**MacVim Custom Version 8.0.1175 (138)**
**MacOS 10.13 High Sierra 10.13 (17A405)**

**Comment by mario-grgic** [comment]
It seems this error only happens if you have both Xcode and command line tools installed. MacVim builds fine with only Xcode installed.

**Comment by AlexVentura** [comment]
Mmmm taking your answer, I think the problem goes with **_command line tools_** because I just have this installed and not _Xcode_ and I still getting same issue in both, MacBook Pro and iMac.

**Comment by outprog** [comment]
but, how can i fix it?

**Comment by vitahlin** [comment]
The same issue.
```c
2017-10-17 17:47:38.419 MacVim[1386:31868] *** WARNING: Textured window <MMWindow: 0x7fac00f52730> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
```

I installed macvim with brew cask:`brew cask install macvim`

I do not install Xcode , just command line tools.

**Comment by vitahlin** [comment]
I found that if  **update Command Line Tools  to the latest version** in App store then it works well.

- macOS version : macOS High Sierra 10.13
- Command Line Tools version : Command Line Tools(macOS High Sierra version 10.13) for Xcode.(I updated that in Oct 17 2017)
- macvim: `brew cask install macvim`

**Comment by AlexVentura** [comment]
I try what @vitahlin said but it didn't work for me.

* To list all available updates you need to run the next command:
	`softwareupdate -l`
* Then to update only _**command line tools**_ run the following command:
	`sudo softwareupdate -i "Command Line Tools (macOS High Sierra version 10.13) for Xcode-9.0"`

Then I tried open MacVim but I still getting the same error.

**Comment by vitahlin** [comment]
@AlexVentura Sorry,  I found that it did not work so I removed my comment.

**Comment by splhack** [comment]
@mario-grgic I recommend you to use [the official Homebrew Tap for MacVim](https://github.com/macvim-dev/homebrew-macvim) if you'd like to build MacVim by yourself.

**Comment by mario-grgic** [comment]
That’s a silly recommendation. One should be able to clone the code, configure and build locally. If that does not work, the project is broken.

**Comment by mario-grgic** [comment]
By the way the current home-brew tap for MacVim assumes Xcode 8 anyway. I am using Xcode 9.0.1 on MacOS 10.13. 

In any case, there is no Python/Python.h header anywhere on the system:

```
$ open -h python
python?
[0]	cancel
[1]	all

[2]	/usr/include/python2.7
[3]	/usr/local/include/fontforge/ffpython.h
[4]	/Library/Frameworks/Python.framework/Headers/pythonrun.h
[5]	/Library/Frameworks/Python.framework/Headers/Python-ast.h
[6]	/Library/Frameworks/Python.framework/Headers/Python.h
[7]	/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/Python.framework/Headers/pythonrun.h
[8]	/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/Python.framework/Headers/Python-ast.h
[9]	/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/Python.framework/Headers/Python.h
[10]	/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/python2.7
```

But there are multiple Python.h headers (one for System python2.7 and one for Python3 that I built myself).

**Comment by splhack** [comment]
> That’s a silly recommendation.

Can you elaborate on why the recommendation is "silly"? Homebrew Tap is one of the greatest tool to provide a way of building app to people who would like to compile the app by themselves. And the important thing is that anyone can do that without deep knowledge of compiler toolchain, shell environment, configure flags, and so forth.


By the way, why don't you elaborate on your bug report? You didn't mention about any useful information to look into the issue, like Xcode version, configure flags, or so on.

**Comment by splhack** [comment]
> By the way the current home-brew tap for MacVim assumes Xcode 8 anyway

No, it works fine with Xcode 8 and Xcode 9, on 10.11, 10.12 and 10.13.

**Comment by mario-grgic** [comment]
@splhack Sorry, I should have been more explicit in my bug report. Here is the missing information:

macOS 10.13, Xcode Version 9.0 (9A235). This is how I configure MacVim:

```
./configure --with-features=huge --enable-rubyinterp --enable-pythoninterp --enable-python3interp --enable-perlinterp --enable-cscope  --enable-terminal
```

**Comment by splhack** [comment]
Still it is not enough information to look into if it is really MacVim issue. Since it may vary with your system, environment, and so on. Please let me know where we should fix if you noticed something wrong in MacVim repository. There are useful information in Homebrew Tap and .travis.yml.

- https://github.com/macvim-dev/macvim/blob/50e45d2e95ea8a074810bd59f842ad38253727ea/.travis.yml#L17
- https://github.com/macvim-dev/macvim/blob/50e45d2e95ea8a074810bd59f842ad38253727ea/.travis.yml#L21
- https://github.com/macvim-dev/homebrew-macvim/blob/01db141d85b85200ec2ee7b1bf550709647dc964/macvim.rb#L27
- https://github.com/macvim-dev/homebrew-macvim/blob/01db141d85b85200ec2ee7b1bf550709647dc964/macvim.rb#L30

**Comment by junkblocker** [comment]
@splhack , here's a log with latest everythin if it helps - https://gist.github.com/junkblocker/5d53f1a1aa15c2dadcfefb6f545532ee

**Comment by mario-grgic** [comment]
From what I remember MacVim builds fine with Xcode 9 only installed. It's when you install Xcode 9 and command line tools that you start getting this error. 

I will try doing clean install of High Sierra and confirm this. If my conjecture is correct, then it's not really MacVim problem, but problem with Apple dev tools, in which case I will post a bug with Apple.

**Comment by splhack** [comment]
@junkblocker @mario-grgic could you try https://github.com/macvim-dev/homebrew-macvim first? It is really helpful to track down the issue.

**Comment by AlexVentura** [comment]
@mario-grgic As you said, it maybe ok with only _Xcode_ installed. Because with only _command line tools_ installed do not work yet!
I have tried in two different MBP's and it didn't work to only install _clt_.

**Comment by junkblocker** [comment]
@splhack , that did work.

**Comment by splhack** [comment]
@junkblocker you mean you were able to install MacVim using https://github.com/macvim-dev/homebrew-macvim , right?

Then you can use the build log in order to figure out why your build was failed.

    $ HOMEBREW_VERBOSE=1 brew install -vd --HEAD macvim-dev/macvim/macvim |& tee log

**Comment by petertsengruihon** [comment]
I updated macvim with the latest version and now when I open it then it just flashback. Why?

**Comment by AlexVentura** [comment]
There's a new MacVim release to fix it! Now it works like a charm using `MacVim Snapshot 139` on **MacOS 10.13 High Sierra 10.13 (17A405)**! https://github.com/macvim-dev/macvim/releases/tag/snapshot-139

**Comment by petertsengruihon** [comment]
I have installed the latest MacVim but it still flashback

**Comment by markwu** [comment]
I installed CLT 9.1 two days ago (I already have Xcode 9.1), then I have this issue. I already build macvim more then ten times without problems before I install CTL for Xcode 9.1.

I have to patch the if_python.c to fix issue. After that, macvim build successful without any problems.

My env.
- MacOS 10.13.1
- Homebew 1.3.8 (HEAD)
- Formula comes from https://github.com/macvim-dev/homebrew-macvim

**Comment by splhack** [comment]
@markwu could you paste the build error?

**Comment by markwu** [comment]
Here comes with the build error log: https://gist.github.com/markwu/f2f02457d268668f1725fca0f48f88d8

Thanks.

**Comment by markwu** [comment]
Just in case you need my `brew config`, here it is:

https://gist.github.com/markwu/3900aa2d557fef56bc1f4b3f5ec71857

**Comment by mario-grgic** [comment]
@chdiza Command Line Tools 9.1 for macOS 10.13 were pushed through macOS App Store as update for users that had previous version(s) installed.

They are conspicuously missing as separate download from https://developer.apple.com/download/more/

Not sure why.

**Comment by markwu** [comment]
@chdiza Kindly see my 2nd attachment, it is the result comes from my `brew config`, the CLT version is `CLT: 9.1.0.0.1.1508540944`.
