### ISSUE TITLE
Feature Request: Trigger balloon via keyboard at cursor position

### ISSUE THREAD

**Issue by marcotrosi** [macvim-dev/macvim#555]
Hi,

I want to trigger the balloon text via keyboard at cursor position. I read the documentation and it looks like that at the moment the balloon textbox can be triggered only with the mouse, which is in my humble opinion not very Vim-like. Mouse is okay of course, but keyboard should have higher priority, or am I wrong?

It could be a function or a command that I can map (nmap/imap/vmap/xmap/smap) or use in Vimscript. Just the standard Vim solutions.

What do you think?

Thanks for your feedback

Have a great day

--marco

**Comment by eirnym** [comment]
@marcotrosi this could be done by a plugin without integrating into core functionality.

**Comment by marcotrosi** [comment]
@eirnym thanks for your feedback. maybe you can give me a hint how you would do it?

But besides that if Bram will implement [popup window](https://github.com/vim/vim/issues/4063#issuecomment-492529595) in a way that it can be triggered via keyboard, then my issue can probably be closed in the future.

**Comment by ychin** [comment]
Hi @marcotrosi, I think this feature request should probably go to https://github.com/vim/vim instead of MacVim (and as you mentioned there are already discussions on this in Vim). MacVim aims to be a nice GUI port of Vim with additional support for native macOS features but cross-platform basic functionality like this should be done in Vim instead (benefits everyone and decreases divergence from core Vim codebase).

**Comment by marcotrosi** [comment]
Hello @ychin, you are absolutely right. I will close this issue here. Thank you.

**Comment by eirnym** [comment]
@marcotrosi There's `balloon_show()` function and a few plugins like w0rp/ale.

**Comment by marcotrosi** [comment]
I know that function, and I don't think that is how balloon_show() works. I tried to use it in the passed but the manual says clearly it's for asynch fetches. The trigger is still the mouse hover. But if you have a working example then this would be helpful.

**Comment by eirnym** [comment]
I have no working examples for you here. I use YCM to fetch docs and go to the declaration. It's more convenient for me personally 

The Vim [todo help file](
https://github.com/vim/vim/blob/dc6855af974f2ef553aceee619fadcb858e25d39/runtime/doc/todo.txt#L188) has quite usable information for you
