### ISSUE TITLE
VisualSelection util function not working after upgrading to MacVim 801175 (138)

### ISSUE THREAD

**Issue by WayneYe** [macvim-dev/macvim#556]
I have a util function `VisualSelection` borrowed from: https://github.com/amix/vimrc/blob/master/vimrcs/basic.vim#L383, and after upgrading to MacVim 801175 (138), the `<leader>r` replacement doesn't work any more, can someone provide some light? Thanks!

**Comment by weijiahan** [comment]
Same issue.

`macvim: stable 8.0-138 (bottled), HEAD`

**Comment by amix** [comment]
Has been fixed [here](https://github.com/amix/vimrc/commit/37297ddae675d0727ec3f1e0e560cc2dd5a0c4de). Note it wasn't the VisualSelection that was the problem, but the hack that happened in `CmdLine`.

The fix was to replace 
```vim
function! CmdLine(str)
    exe "menu Foo.Bar :" . a:str
    emenu Foo.Bar
    unmenu Foo
endfunction 
```
with 
```vim
function! CmdLine(str)
    call feedkeys(":" . a:str)
endfunction 
```

**Comment by WayneYe** [comment]
@amix it works for me, thanks for the help!
