### ISSUE TITLE
Unable to upgrade to version 8.0-138 on Mac High Sierra

### ISSUE THREAD

**Issue by longthanhtran** [macvim-dev/macvim#558]
When I tried to do `brew upgrade`, macvim always stuck with below error message

> Last 15 lines from /Users/longtran/Library/Logs/Homebrew/macvim/02.make:
>     export XCODE_DEVELOPER_USR_PATH=/Applications/Xcode.app/Contents/Developer/usr/bin/..
>     /Applications/Xcode.app/Contents/Developer/usr/bin/ibtool --strip /tmp/macvim-20171011-23711-1pt0x98/macvim-snapshot-138/src/MacVim/build/Release/MacVim.app/Contents/Resources/English.lproj/FindAndReplace.nib --output-format human-readable-text /tmp/macvim-20171011-23711-1pt0x98/macvim-snapshot-138/src/MacVim/English.lproj/FindAndReplace.nib
> 
> CopyPlistFile build/Release/MacVim.app/Contents/Resources/KeyBinding.plist KeyBinding.plist
>     cd /tmp/macvim-20171011-23711-1pt0x98/macvim-snapshot-138/src/MacVim
>     builtin-copyPlist --outdir /tmp/macvim-20171011-23711-1pt0x98/macvim-snapshot-138/src/MacVim/build/Release/MacVim.app/Contents/Resources -- KeyBinding.plist
> 
> ** BUILD FAILED **
> 
> The following build commands failed:
> 	StripNIB English.lproj/MainMenu.nib
> (1 failure)
> make[1]: *** [macvim] Error 65
> make: *** [first] Error 2

I have checked xcode readiness

**Comment by QuentinGibson** [comment]
I had the same problem. I solved it by opening Xcode. It gave me a prompt to install more components, and after installing the components, the installation worked afterward.

**Comment by longthanhtran** [comment]
@QuentinGibson many thanks, your instruction helps me to solve this issue.
