### ISSUE TITLE
"After last window closes" setting not saving sometimes

### ISSUE THREAD

**Issue by WillEccles** [macvim-dev/macvim#567]
Since I updated to High Sierra, the "After last window closes" setting does not save sometimes. When I say sometimes, I mean I will set it to "Quit MacVim," and it works for a few sessions. Then, I'll open a file, and then when I do `:q`, MacVim is gone but still keep focus. I then do `⌘,` and lo and behold, the setting has been reset to "Keep MacVim Running."

This is using version 8.0.1175 (138) (supposedly the latest, according to MacVim) on High Sierra 10.13 (17A405).

**Comment by kfox** [comment]
I'm seeing the same thing with MacVim 8.0.1207 (140) on High Sierra 10.13 (17A405), but it appears that all preferences are eventually reset to their defaults after opening several files.

**Comment by WillEccles** [comment]
I'm not sure if they are all getting reset, I haven't tested since that's the only one I changed (I think).

**Comment by splhack** [comment]
You can check the preferences anytime from Terminal.

    $ defaults read org.vim.MacVim

**Comment by WillEccles** [comment]
Haven't had this issue in ages, assuming it's been fixed. Closing.
