### ISSUE TITLE
MacVim ignores ctrl key completely

### ISSUE THREAD

**Issue by elfi** [macvim-dev/macvim#57]
Hi,

I've installed MacVim on my MacOS 10.10.4 via homebrew and discovered that the ctrl key is being ignored completely - it is like it has never been pressed. Nothing goes wrong but also nothing happens. 

MacVim is the only app I have encountered such a problem with. Ctrl works perfectly with all other (gui) apps and vim in terminal is fine too.

So I though that something is wrong with the released brew package 7.4-77 and tried with HEAD build from source, but that did not help either.

Any hints for debugging this behavior?

Best,
Miroslav

**Comment by eirnym** [comment]
`ctrl` is binded to help you with right mouse click in Mac OS X by default, isn't it? Some programs may use it as modifier.

**Comment by elfi** [comment]
You are right, ctrl-click behaves as right click. And this actually 
works for me in MacVim ... I get the right click 'menu'.
Thus the ctrl key is not ignored completely completely :-)

**Comment by douglasdrumond** [comment]
Ctrl-click as right click is the desired behavior on Mac OS.
The original post doesn't say anything about click, though, just that ctrl isn't working. @elfi, what do you mean by that? I use ctrl- shortcuts all the time (such as ctrl-v for block select) and I haven't experienced problems so far.

**Comment by elfi** [comment]
As I wrote in my first post, none of the ctrl- shortcuts works. Pressing 
ctrl-v or ctrl-whatever does not have any effect, regardless of mode 
(normal, insert, command : )

Please not that pressing, eg ctrl-a, does not have effect of ctrl-a, nor 
a alone. It is really just nothing happens. MacVim is the only program I 
experience this issue with. And I tried to start MacVim with -u NONE   
-- no change.

**Comment by chdiza** [comment]
Did you try starting MacVim from the terminal with `mvim -u NONE -N`?  That will rule out any interference from your `vimrc` or `gvimrc` or plugins.

**Comment by elfi** [comment]
Yes, I did. It did not help :-/

**Comment by elfi** [comment]
Ha, I've just found the root course. It is the Programmer Dvorak keyboard. When I switch to the default - Swedish Pro in my case - ctrl- commands work fine. 

Now the question what is wrong with Programmer Dvorak CTRL key concretely in MacVim as other applications are fine with it.

**Comment by elfi** [comment]
The problem has disappeared with latest MacOS update.

**Comment by Leandros** [comment]
Still not working for me.

**Comment by eirnym** [comment]
I'd test these layouts with software like [Karabiner](https://github.com/tekezo/Karabiner) to understand what exactly is going on and what is the difference

**Comment by Leandros** [comment]
I did exactly that. There is no difference in what key code is sent based on what layout I'm using.

**Comment by eirnym** [comment]
This sounds quite strange, to be honest.

**Comment by district10** [comment]
> Still not working for me. I, too, am using a custom keyboard layout (build using Ukelele). Seems to work if I use an english or german layout. Shouldn't interfere, though, since I do no remapping of the ctrl key.

+1 I'm using Dvorak ([customized layout](https://github.com/district10/neo_keyboard_layout/blob/master/neo4mac/neo.keylayout) built with Ukelele).

**Comment by dlejay** [comment]
I get the same issue with a custom layout, the control key is ignored. Any update?

**Comment by district10** [comment]
Leave only `<layout first="0" last="17" mapSet="ANSI" modifiers="Modifiers"/>` in `<layouts>` does not solve my problem.

**Comment by stefansommer** [comment]
Any solution to this? The solution by dlejay does not fix the problem for me either.

**Comment by eirnym** [comment]
@stefansommer what is your issue exactly? I don't believe it's sufficient for us to even reproduce the problem when very custom macOS settings are involved

**Comment by stefansommer** [comment]
Thanks for the quick reply! My issue is as described above, however, I can make it a bit more precise:

I have a custom keymap created by Ukelele. I have installed macvim using brew. I open mvim using the terminal. If the keymap is the custom keymap, ctrl is ignored in the sense that e.g. ctrl-u, ctrl-d, ctrl-v etc. has no effect in macvim. If I switch to the standard keyboard (in the same macvim session), ctrl works again, if I switch back to the custom keymap, ctrl is ignored.

When macvim ignores ctrl keypresses I get
"IsMenuKeyEvent: found no unichar data in event; retranslation without deadkeys did not produce unichar output"

in the terminal.

As for the reports above, I have not experienced the issue in other programs.

I can uploaded the custom keymap if it can help.

**Comment by stefansommer** [comment]
OK, thank you very much for the reply. I'll look into it.

**Comment by trach99** [comment]
Hi folks,
Seems that I to have this issue when using a custom [key layout](https://github.com/ThePrimeagen/keyboards/blob/master/MacOS/real_prog_dvoark.keylayout), works fine with all other standard layouts.
Ctrl key is apparently taking mouse right click as input (ofc i have disabled use of ctrl as right click in the macvim settings).

**Comment by eirnym** [comment]
@trach99 could you try to investigate by Karabiner Events? This app shows everything what is going with keys

**Comment by trach99** [comment]
Karabiner registers the keystrokes correctly. As a matter of fact <C-any key> works just fine with vim running in terminal. Only exception being Macvim

**Comment by ychin** [comment]
@trach99 sorry this issue is a little old. Can you re-iterate exactly what "this issue" means to you?

What is not working, and how would you expect it to work? Are you saying you can't use e.g. Ctrl-6, or map it in mappings?

**Comment by dlohm** [comment]
I have the same Problem, but for me it appeared only recently, with recently probably being a few weeks in a setup I have been using for more than five years. Unfortunately I cannot say it was after this-and-that change or so, because I really noticed it just yesterday.

**The Problem**

- When using a custom keyboard layout (mine was created with Ukelele years ago), MacVim does not seem to pass Ctr+KEY keystrokes to the vim engine (e.g., Ctr+a to increment a number). 
- When I press Ctrl, the "MacVim" Menu is briefly highlighted.
- The problem disappears (without restarting MacVim), when I switch to a standard keyboard layout.
- The problem occurs _only_ in MacVim. Vim in the Terminal works as expected.
- While writing these lines I figured out: **It also occurs in VimR**, so **graphical vim/neovim apps** seem to face the issue! 

The last point is a strong pointer to MacOS, not MacVim. But maybe with the help of the community we can figure it out anyway.

**Comment by ychin** [comment]
> Update 2: I figured it out. I had registered "Files an Folders" services for Ctr+a and Ctrl+w. Theses used to be available only in the Finder (where one can find them in the "Services" menu), but apparently they are now active (even though not listed in the "Services" menu) in all applications, eating the respective Shortcuts.

Huh, ok. @dlohm So I guess it's an issue specific to your setup then?  If so I won't investigate further.

**Comment by dlohm** [comment]
Yes, it seemed to be specific to my setup (and apparently a bug/changed behaviour in MacOS wrt application-specific shortcuts).  I just left it here to help others that run into similar issues.
