### ISSUE TITLE
GUI glitch. "Next Tab" icon is blurred.

### ISSUE THREAD

**Issue by technoiswatchingyou** [macvim-dev/macvim#570]
Hi

- MacVim Custom Version 8.0.1207 (140) (without any of additional plugins)
- MacOS 10.13.2
- Macbook Pro MD101 (non-Retina)

![screen shot 2017-10-24 at 4 23 57 pm](https://user-images.githubusercontent.com/25575840/31927567-0c79d3c2-b8d8-11e7-8871-972faca9f45f.png)

**Comment by eirnym** [comment]
@technoiswatchingyou Does it still an issue for you?

**Comment by technoiswatchingyou** [comment]
> @technoiswatchingyou Does it still an issue for you?

Dunno. I do not use it anymore.

**Comment by ychin** [comment]
Closing the issue. Feel free to re-file the issue in the future. The tab interfaces work a little differently in post-Mojave macOS versions anyway and as long as the older macOS versions work I don't see too much value in fixing minor issues like this.
