### ISSUE TITLE
MacVim Crash With UltiSnip

### ISSUE THREAD

**Issue by kaich** [macvim-dev/macvim#573]
Ultisnips is definitely crashing macvim the second i upgraded to 8.0.1175. Except, I was using the gui version of macvim which just crashes without saying anything. E.g. the second I type 'o' to insert a newline. As soon as I uninstall ultisnips it stops happening.

When I use vim in terminal , It works fine. How to solve the problem? Expect your answer.

**Comment by kiryph** [comment]
You probably have to update your python3 version to 3.6.3. The previous macvim version was compatible to python3.6.2!

**Comment by kaich** [comment]
It works fine now.  refer: https://github.com/SirVer/ultisnips/issues/900#issuecomment-342171827

**Comment by kiryph** [comment]
I see that you enforce to use python2. That actually sounds that my suspicion regarding incomptatible python3 versions could be right. I am curious what your exact python3 version is. Could you post `:!which -a python3` and `:!python3 --version`?

**Comment by kaich** [comment]
@kiryph The python inform:  `:!which -a python3`   is `(B[m/usr/local/bin/python` and ` :!python3 --version`    is `(B[mPython 3.6.2   `

**Comment by kiryph** [comment]
Thanks for sharing. Your result is as I had expected. As I said earlier, updating `python3` to `python3.6.3` should also help instead of enforcing ultisnips to use python2.

**Comment by kaich** [comment]
@kiryph It's great. It works fine as your way. Thank you very much 👍

**Comment by kiryph** [comment]
You are welcome.
