### ISSUE TITLE
Does ViM support only single version of python?

### ISSUE THREAD

**Issue by eirnym** [macvim-dev/macvim#58]
When I compile MacVim (snapshot 77) with both Python2.7 *and* Python3.4 support, it crashes on start.

I compile it from macports (`+huge +python34 +python27`),  and I don't know if it's macports-specific

Related Macports tickets: 
* [update to snapshot 77](https://trac.macports.org/ticket/48391)
* [bug](https://trac.macports.org/ticket/48392) 

I need Python3.4 support for my work, but I want to be able to use it with Python 2.7 too.

**Comment by eirnym** [comment]
ViM crashes on calliing any Python 2.7 instruction. `:python3` works well

**Comment by splhack** [comment]
From Snapshot 80, MacVim(Vim) doesn't crash (SIGSEGV) at the situation.

    $ vim --cmd 'py3 print("test")' --cmd 'py print("test")' --cmd 'quit'   
    test
    Error detected while processing pre-vimrc command line:
    E836: This Vim cannot execute :python after using :py3
    E263: Sorry, this command is disabled, the Python library could not be loaded.

    $ vim --cmd 'py print("test")' --cmd 'py3 print("test")' --cmd 'quit'
    test
    Error detected while processing pre-vimrc command line:
    E837: This Vim cannot execute :py3 after using :python
    E263: Sorry, this command is disabled, the Python library could not be loaded.
