### ISSUE TITLE
latest version gets buftype option is set

### ISSUE THREAD

**Issue by vahvarh** [macvim-dev/macvim#584]
After upgrading to latest version on opening remote file :tabnew scp://germany/myfile.txt and trying to save it with :w, vim writes "buftype option is set" (set to "nofile").
has to do :set buftype: " " each time before saving.

**Comment by dq2nd** [comment]
I met this issue with environment below:

> VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov  6 2017 11:52:53)
macOS version
Included patches: 1-1272
Compiled by Homebrew

> macOS High Sierra version 10.13.1

**Comment by alr94** [comment]
Same issue here.
VIM - Vi IMproved version 8.0.1349
Ubuntu 16.04 LTS

**Comment by Melkster** [comment]
I have the same issue.

> vim 8.0.1297-1
> Arch Linux x86_64

**Comment by chdiza** [comment]
This is MacVim, whichis macOS-only.  If you're on Linux, you're reporting this in the wrong place.

**Comment by chdiza** [comment]
The problem described in this thread seems to be a Vim issue, not a MacVim one.  It should be reported upstream.
