### ISSUE TITLE
Installing MacVim

### ISSUE THREAD

**Issue by commanderh** [macvim-dev/macvim#585]
Currently I'm experiencing installing MacVim.

After downloading the "MacVim.dmg" file, when opening up the disk, I get the error "MacVim can't be opened because the original item can't be found"

OS: macOS High Sierra 10.13.1
Macbook pro 2014 retina

**Comment by commanderh** [comment]
FIXED
Installed using homebrew.

**Comment by splhack** [comment]
Also https://support.apple.com/kb/PH25088?locale=en_US
