### ISSUE TITLE
Pressing 'o' in normal mode closes the window

### ISSUE THREAD

**Issue by dickscheid** [macvim-dev/macvim#586]
Since having installed the latest binary release (snapshot-142), my macvim windows will close without any further notice whenever I press the 'o' key in normal mode (which otherwise brings me into insert mode with a new text line). 

The key is not mapped from within vim (':map o'  says 'no mapping found'), and also not listed in the MAc system settings for custom application shortcuts. Also, other Mac applications won't do this when pressing 'o'.

Any ideas to track this problem down?

**Comment by splhack** [comment]
how about crashlogs?

**Comment by dickscheid** [comment]
Sorry about that. I was assuming that it is not a crash, since the window closed but the macvim application kept on running. But indeed, there is a crashlog - it is attached.
[Vim_2017-11-09-174540.crash.zip](https://github.com/macvim-dev/macvim/files/1458483/Vim_2017-11-09-174540.crash.zip)

**Comment by splhack** [comment]
Apparently Python 3 crashed. Are you using Python 3.6.3?

**Comment by dickscheid** [comment]
I recently changed my python environment, from homebrew-based to Canopy. This may coincide with the problem - I will cross-check the python setup and post the result here. Thanks a lot.

**Comment by dickscheid** [comment]
A python 3.6.2 installation in homebrew was the problem, thanks again for the quick help!

Explanation:
Some weeks ago I did remove my python2.7 environment in homebrew, and replaced it with a canopy python installation. However, python 3.6.2 was still available at /usr/local/bin/python3 from homebrew. After uninstalling python3 and dependencies in homebrew, and restarting vim, the error does not appear any more.
