### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by tobireif** [macvim-dev/macvim#587]
MacVim just crashed.

That is horrible.

Please ensure it won't ever crash again.

Stacktrace was sent to Apple.

**Comment by splhack** [comment]
could you elaborate the crash? and could you paste the stack trace in gist?

**Comment by tobireif** [comment]
> could you elaborate the crash?

All MacVim windows disappeared (one or more), and then the window by Mac OS X appeared offering to send the report to Apple.

>  could you paste the stack trace in gist?

I'm sorry, I had clicked on the window by the OS which had offered to send it to Apple, then it seems to have sent it, then the stack trace was gone. I should have copied it and provided it to you.

**Comment by splhack** [comment]
you may have Vim or MacVim crashlogs in `~/Library/Logs/DiagnosticReports`.

**Comment by tobireif** [comment]
Yep just found it, just a sec

**Comment by tobireif** [comment]
Here you go:

https://gist.github.com/tobireif/cfb0d3f4ac94e4d587db809de173cdd3

**Comment by tobireif** [comment]
Please feel free to request any additional info.

I hope you can ensure that MacVim won't crash in the future 😀

**Comment by splhack** [comment]
We need a repro step to crash MacVim, as simple and short as possible.

**Comment by tobireif** [comment]
I was simply using MacVim for editing a .txt file (and perhaps more), then it crashed. I have no idea how I could trigger another crash.

You had requested the stack trace - does it not help?

**Comment by tobireif** [comment]
All I remember is that after editing something using MacVim I switched away from MacVim perhaps the Transmit https://panic.com/transmit/ window, then MacVim crashed.

**Comment by kenng** [comment]
have the same problem. pressing on "I" or "O" will crash the vim. 

Tried the solution from [#667](https://github.com/macvim-dev/macvim/issues/667). But have error during the built
```
❯ brew reinstall macvim --build-from-source
==> Reinstalling macvim
==> Downloading https://github.com/macvim-dev/macvim/archive/snapshot-146.tar.gz
==> Downloading from https://codeload.github.com/macvim-dev/macvim/tar.gz/snapshot-146
######################################################################## 100.0%
==> ./configure --with-features=huge --enable-multibyte --with-macarchs=x86_64 --enable-perlinterp --enable-rubyinterp --enable-tclinterp --enable-terminal --with-tlib=ncurses --with
==> make
Last 15 lines from /Users/itwonders/Library/Logs/Homebrew/macvim/02.make:
    export XCODE_DEVELOPER_USR_PATH=/Applications/Xcode.app/Contents/Developer/usr/bin/..
    /Applications/Xcode.app/Contents/Developer/usr/bin/ibtool --strip /tmp/macvim-20180419-11072-14i0064/macvim-snapshot-146/src/MacVim/build/Release/MacVim.app/Contents/Resources/English.lproj/FindAndReplace.nib --output-format human-readable-text /tmp/macvim-20180419-11072-14i0064/macvim-snapshot-146/src/MacVim/English.lproj/FindAndReplace.nib

CopyPlistFile build/Release/MacVim.app/Contents/Resources/KeyBinding.plist KeyBinding.plist
    cd /tmp/macvim-20180419-11072-14i0064/macvim-snapshot-146/src/MacVim
    builtin-copyPlist --outdir /tmp/macvim-20180419-11072-14i0064/macvim-snapshot-146/src/MacVim/build/Release/MacVim.app/Contents/Resources -- KeyBinding.plist

** BUILD FAILED **


The following build commands failed:
	StripNIB English.lproj/Preferences.nib
(1 failure)
make[1]: *** [macvim] Error 65
make: *** [first] Error 2
```

Then I uninstall all the macvim, and install it again and it fixed the problem. 
```
brew uninstall macvim --force macvim
brew install macvim
```

**Comment by eirnym** [comment]
@tobireif @kenng I can't reproduce your issue

Does it still an issue with recent versions of MacVim? Have you tried to run it `mvim -u NONE -U NONE` to reproduce an issue?

**Comment by tobireif** [comment]
MacVim hasn't crashed here since many months or even years.

**Comment by eirnym** [comment]
Could this issue be closed?

**Comment by tobireif** [comment]
You had also asked @kenng . I can't talk for him. As for as the issue concerns me, yes you could close this ticket.

**Comment by eirnym** [comment]
There was a lot of such issues that time and the underlying issues were fixed. If something crashing MacVim nowadays, it's mostly incompatible plugins. It's easier to reopen the issue if it's still hitting users.

**Comment by tobireif** [comment]
Closing. @kenng please open a new ticket if/when necessary.

**Comment by kenng** [comment]
@tobireif yes can close, it is working as for now, after uninstall & install again.

**Comment by tobireif** [comment]
@kenng Good to hear!
