### ISSUE TITLE
search will highlight whole window

### ISSUE THREAD

**Issue by gatspy** [macvim-dev/macvim#590]
in my `.vimrc`, have the following setting, when use `/` key, the all window will highlight.
```
set hlsearch
map <space> /
nnoremap / /\v
vnoremap / /\v
```

current vim version:
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov  6 2017 11:53:24)
macOS version
Included patches: 1-1272
Compiled by Homebrew
```

**Comment by joonhocho** [comment]
I am having the same problem.

**Comment by jonathanpatt** [comment]
Same, very annoying.

**Comment by ichizok** [comment]
This was solved at 8.0.1393 (https://github.com/vim/vim/commit/6621605eb97cf5fbc481282fd4d349a76e168f16)

**Comment by eirnym** [comment]
is it still actual?

**Comment by ychin** [comment]
Closing this as the bug was fixed in Vim and merged to MacVim a while ago.
