### ISSUE TITLE
Window Menu Issue (MacOS 10.13.1)

### ISSUE THREAD

**Issue by isaki-x** [macvim-dev/macvim#593]
For some reason, the "Enter Full Screen" Window menu item is showing up repeatedly (and it is there more times than I have windows open, so it does not appear to be tied to that, though windows have been closed, so that's not guaranteed).

<img width="403" alt="screen shot 2017-11-10 at 11 29 24 am" src="https://user-images.githubusercontent.com/10616227/32668111-ad363500-c60a-11e7-957f-3118dffec828.png">

**Comment by eaoliver** [comment]
This is a duplicate of #566

**Comment by isaki-x** [comment]
Didn't see it was a duplicate; sorry!
