### ISSUE TITLE
brew upgrade on MAC High Seirra of macvim 8.0.1250 failed in build.

### ISSUE THREAD

**Issue by gpaulsen** [macvim-dev/macvim#597]
Hello.  I just wanted to post a failure I saw when upgrading to macvim 8.0.1250 from 8.0.142.

I just upgraded to MAC High Sierra from MAC Sierra, but hit this build issue during the brew upgrade.

I have all MAC updates, and brew updates as of Nov 15, 2017.

**WORKAROUND:** Uninstall and reinstall DID work as a workaround, (posted at the bottom)

> --> brew upgrade
> ==> Upgrading 1 outdated package, with result:
> macvim 8.0-142
> ==> Upgrading macvim --with-lua --with-luajit
> ==> Downloading https://github.com/macvim-dev/macvim/archive/snapshot-142.tar.gz
> Already downloaded: /Users/gpaulsen/Library/Caches/Homebrew/macvim-8.0-142.tar.gz
> ==> ./configure --with-features=huge --enable-multibyte --with-macarchs=x86_64 --enable-perlinterp --en
> ==> make
> Last 15 lines from /Users/gpaulsen/Library/Logs/Homebrew/macvim/02.make:
>     builtin-copyPlist --outdir /tmp/macvim-20171115-26581-16rozxu/macvim-snapshot-142/src/MacVim/build/Release/MacVim.app/Contents/Resources -- KeyBinding.plist
> 
> StripNIB English.lproj/FindAndReplace.nib
>     cd /tmp/macvim-20171115-26581-16rozxu/macvim-snapshot-142/src/MacVim
>     export XCODE_DEVELOPER_USR_PATH=/Applications/Xcode.app/Contents/Developer/usr/bin/..
>     /Applications/Xcode.app/Contents/Developer/usr/bin/ibtool --strip /tmp/macvim-20171115-26581-16rozxu/macvim-snapshot-142/src/MacVim/build/Release/MacVim.app/Contents/Resources/English.lproj/FindAndReplace.nib --output-format human-readable-text /tmp/macvim-20171115-26581-16rozxu/macvim-snapshot-142/src/MacVim/English.lproj/FindAndReplace.nib
> 
> ** BUILD FAILED **
> 
> 
> The following build commands failed:
> 	StripNIB English.lproj/Preferences.nib
> (1 failure)
> make[1]: *** [macvim] Error 65
> make: *** [first] Error 2
> 
> READ THIS: https://docs.brew.sh/Troubleshooting.html

--------------------------------------------------------------------

**WORKAROUND:**  

> --> brew uninstall macVIM
> Uninstalling /usr/local/Cellar/macvim/7.4-99... (2,077 files, 32.8MB)
> macvim 7.4-93 1 is still installed.
> Remove all versions with `brew uninstall --force macvim`.
> --> brew uninstall --force macVIM
> Uninstalling macVIM... (2,084 files, 32.7MB)
> --> brew install macvim
> ==> Downloading https://homebrew.bintray.com/bottles/macvim-8.0-142.high_sierra.bottle.tar.gz
> ######################################################################## 100.0%
> ==> Pouring macvim-8.0-142.high_sierra.bottle.tar.gz
> 🍺  /usr/local/Cellar/macvim/8.0-142: 2,142 files, 34.2MB

**Comment by splhack** [comment]
I only support Homebrew Tap for MacVim https://github.com/macvim-dev/homebrew-macvim and don't forget to launch Xcode first https://github.com/macvim-dev/macvim/issues/546#issuecomment-331941850
