### ISSUE TITLE
Ruby broken in snapshot-142 on 10.9.5

### ISSUE THREAD

**Issue by RubenVerborgh** [macvim-dev/macvim#598]
When running `:ruby 1`, I get:

```
E370: Could not load library libruby.2.4.dylib
E266: Sorry, this command is disabled, the Ruby library could not be loaded. 
```

**Comment by splhack** [comment]
https://github.com/macvim-dev/macvim/wiki/FAQ#how-to-use-pythonrubylua-interface-in-macvim

> How to use Python/Ruby/Lua interface in MacVim?

> The easiest way is using Homebrew https://brew.sh/. Install Homebrew and brew install python3, brew install ruby, or brew install lua.
> You can use any distribution of Python/Ruby/Lua dylib binaries as long as those versions are the same as the MacVim binary supported version. You may need to set up your .vimrc like following.

    set pythonthreedll=/opt/Python3.6.3/Frameworks/Python.framework/Versions/3.6/Python
    set rubydll=/opt/Ruby2.4.1/lib/libruby.2.4.dylib
    set luadll=/opt/Lua5.2.1/lib/liblua.dylib

**Comment by RubenVerborgh** [comment]
Thanks! Might be useful to document this in upgrade notes, as this suddenly broke for me.

For reference, here's what I needed with MacPorts:

```
set rubydll=/opt/local/lib/libruby2.4.dylib
```
