### ISSUE TITLE
Unable to use netrw with username from MacVim

### ISSUE THREAD

**Issue by dlindelof** [macvim-dev/macvim#60]
When I try to open a netrw session from MacVim, it works fine unless I need to specify a username.

For example, when I run `:e scp://user@example.com/` nothing happens until the connection attempt times out, with a message saying: 

`ssh: connect to host userexample.com port 22: Operation timed out`

Doing the same operation from the command-line (i.e., from plain vim) works fine. It looks like MacVim drops the at-sign `@` between the username and the hostname.

**Comment by chdiza** [comment]
I can't reproduce it, not even with `mvim -u dummyrc -N`, where `dummyrc` is a blank file.

What about if you run it from the `Vim` located at `/Applications/MacVim.app/Contents/MacOS/Vim`?

**Comment by dlindelof** [comment]
Hello,

Running the Vim that ships with MacVim yields the same results.

I have prepared a screencast that shows the problem. On the right pane I
use Vim from MacVim. In the left pane I use the system-installed (i.e.,
brew) vim. I try to connect to a host called 'strider-local', with my
username 'dlindelof'. The right pane times out after about 1'30''.

http://screencast.com/t/i0YiBbhkL

Hope this helps,

On Tue, Jul 21, 2015 at 8:50 PM chdiza <notifications@github.com> wrote:

> I can't reproduce it, not even with mvim -u dummyrc -N, where dummyrc is
> a blank file.
>
> What about if you run it from the Vim located at
> /Applications/MacVim.app/Contents/MacOS/Vim?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/macvim-dev/macvim/issues/60#issuecomment-123439209>.
>
-- 
-------------------------------
David Lindelöf, PhD
Chief Technology Officer
M +41 (0)79 415 66 41
T +41 (0)22 552 11 62
F +41 (0)22 552 11 60
david.lindelof@neurobat.net
http://neurobat.net
http://computersandbuildings.com
-------------------------------

**Comment by chdiza** [comment]
I can see in that screencast that your version of MacVim is old.  Please try it with Snapshot 77.

**Comment by chdiza** [comment]
When I try your exact command with the latest MacVim, I get a `netrw` error, probably because the URL `scp://dlindelof@strider-local` looks like a typo.  Did you mean `strider.local`?

I strongly suspect this is a `netrw` issue, not a MacVim one.  We haven't ruled that out yet, because you have only compared console vim 7.3 with MacVim 7.4.258.  Among other things, they will have different versions of `netrw` contained in them.

**Comment by chdiza** [comment]
For example, the version of `netrw` contained in MacVim 7.4.258 might not like a URL like yours where there is no dot.

We'll know more after you try MacVim Snapshot 77.  If it still doesn't work there, it's a `netrw` issue.

**Comment by dlindelof** [comment]
Well, what do you know. It works with MacVim Snapshot 77. Thanks!

On Thu, Jul 23, 2015 at 5:37 PM chdiza <notifications@github.com> wrote:

> For example, the version of netrw contained in MacVim 7.4.258 might not
> like a URL like yours where there is no dot.
>
> We'll know more after you try MacVim Snapshot 77. If it still doesn't work
> there, it's a netrw issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/macvim-dev/macvim/issues/60#issuecomment-124142708>.
>
-- 
-------------------------------
David Lindelöf, PhD
Chief Technology Officer
M +41 (0)79 415 66 41
T +41 (0)22 552 11 62
F +41 (0)22 552 11 60
david.lindelof@neurobat.net
http://neurobat.net
http://computersandbuildings.com
-------------------------------
