### ISSUE TITLE
Adding a mac action to a PopUp menu item fails due to multiple menu modes

### ISSUE THREAD

**Issue by dougfales** [macvim-dev/macvim#602]
When you try to add a menu item to the PopUp menu and attach a mac action to it, the mac action is never invoked, even when it is properly declared and defined in the Obj-C code. 

The reason this fails is that the `ex_menu` function handles PopUp menu items specially, [looping over each mode and adding a new menu for that mode](https://github.com/macvim-dev/macvim/blob/c8a233bc285f08ea2c247c3a702613949c836db2/src/menu.c#L395-L420). 

The `ex_macmenu` function does not handle this special case of PopUp items having multiple menus defined for them, and so whichever `action=myAction:` you define is not propagated to these additional modes. The result is that, when MacVim receives the message to define a new menu, the action is empty. When `MMVimController` encounters this empty action, [it just assigns `vimMenuItemAction:` as a default](https://github.com/macvim-dev/macvim/blob/c8a233bc285f08ea2c247c3a702613949c836db2/src/MacVim/MMVimController.m#L1157-L1160), effectively hiding the action you defined using `macm`.  

## To Reproduce

To reproduce, just try to define a PopUp menu under the existing entries in `runtime/menu.vim` and give it an action using the `macm` command. For example:

```
  an 1.110 PopUp.-SEP3-			<Nop>
  " This action will not work. If you open the context menu and click Add New
  " Tab, nothing happens because the action is overwitten by the multiple PopUp modes
  " added in ex_menu.
  an 1.110 PopUp.Add\ New\ Tab	  <Nop>
  macm PopUp.Add\ New\ Tab	  action=addNewTab:
```

You would expect the "Add New Tab" item in the PopUp menu to call the `addNewTab:` action and cause a new tab to appear. It never does, since the default `vimMenuItemAction:` overshadows the `macm` action.

## To Fix

One approach would be to make `ex_macmenu` heed this PopUp special case. I'll attach a PR momentarily.

**Comment by splhack** [comment]
merged. thanks!

**Comment by dougfales** [comment]
Thank you @splhack !
