### ISSUE TITLE
No combining accents with Core Text

### ISSUE THREAD

**Issue by georgd** [macvim-dev/macvim#604]
This might be related to https://github.com/macvim-dev/macvim/issues/400

With Core Text on, combining diacritic characters like U+0300 are not displayed at all. Terminal Vim with same Font is fine.

MacVim Version: 8.0.1272 (142)
Mac OS: 10.13.1 (17B48)

**Comment by eirnym** [comment]
@georgd  Does it still an issue? #400 is closed and patch was merged. 

@ychin I can't reproduce it

**Comment by georgd** [comment]
I can't reproduce it any longer either. I close this now.
