### ISSUE TITLE
wont install on high sierra

### ISSUE THREAD

**Issue by oohogwash** [macvim-dev/macvim#611]
here is the error I get, i have deleted the file and brew continues to find the file is bad.
gavans-MBP:ISA 95 gavan1$ sudo brew install macvim
Warning: You are using OS X 10.13.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
==> Downloading https://github.com/macvim-dev/macvim/archive/snapshot-103.tar.gz
==> Downloading from https://codeload.github.com/macvim-dev/macvim/tar.gz/snapsh
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: ad6cdee1178d4b8fddc126eb209481710803256f6826913c4bbc30224e290e0b
Actual: 5df21d0c16fd9b33fa291250bce2e8456261ccf6869070be8901002d655fb30a
Archive: /Library/Caches/Homebrew/macvim-7.4-103.tar.gz
To retry an incomplete download, remove the file above.

**Comment by chdiza** [comment]
`brew update` then try again.  If that doesn't work, it's a Homebrew problem and you should go to them.

**Comment by oohogwash** [comment]
i tried that, it continues to happen with same error. 
Is there any other way to get macVim onto High Sierra ?

On 8 Dec 2017, at 11:39 pm, chdiza <notifications@github.com> wrote:

brew update then try again. If that doesn't work, it's a Homebrew problem and you should go to them.

**Comment by chdiza** [comment]
Your Homebrew is messed up, because it's saying that 10.13 isn't supported.  It is.  Your Homebrew installation is stuck in an old state somehow.

**Comment by splhack** [comment]
> Is there any other way to get macVim onto High Sierra ?

I recommend to use binary snapshot release. The second option is Homebrew tap for MacVim https://github.com/macvim-dev/homebrew-macvim . Both works pretty well on 10.13 as well.
