### ISSUE TITLE
gx calls curl to download the webpage and opens the local copy in the browser

### ISSUE THREAD

**Issue by arturoherrero** [macvim-dev/macvim#612]
### What is `gx`

For those that don't know, if you are using Vim 7.4 or later, in normal mode, put your cursor below the URL, then click `gx`, the URL will be opened in the browser automatic.

### My problem with `gx`

My problem is that `gx` calls the `curl` command to download the URL and opens the downloaded copy in the browser. I'm trying to solve the problem and there are more people with [other issues][1] related to the `gx` behaviour. In my case, it doesn't matter the URL format, `curl` is called every single time.

Is this the behaviour of every MacVim user? How can I check some internal variables/settings, eg `g:netrw_browsex_viewer`? I don't know too much about Vim/MacVim internals, nor how to check the value of that settings but I'm happy to investigate or configure my `.vimrc`, please help!

### Version / OS

I'm using the latest possible software (MacVim 8.0.1376, macOS High Sierra Version 10.13.2) but I know this was happening with previous MacVim and OS X versions, so I don't think it's a system related issue.

[1]: https://vi.stackexchange.com/questions/5439/why-does-gx-call-curl-when-the-cursor-is-on-a-url-with-trailing-slash

**Comment by arturoherrero** [comment]
For the record, this is no longer happening to me (MacVim 8.0.1522, macOS High Sierra Version 10.13.3).

**Comment by 9mm** [comment]
woah.............. this use to open in browser but now it uses curl. i just updated

what happened?

**Comment by lucasmaystre** [comment]
Same as @9mm - `gx` used to open my browser, and now it downloads it first using `curl`.

**Comment by eirnym** [comment]
There's an issue for the upstream for this.

**Comment by arturoherrero** [comment]
For reference: #925 and #935.
