### ISSUE TITLE
`:gui` doesn't work anymore on High Sierra

### ISSUE THREAD

**Issue by chdiza** [macvim-dev/macvim#614]
On MacVim 8.0.1376, if I start it with `-u NONE -U NONE -N`, and then do `:gui`, it fails and the following is spewed to the terminal:
```
ion initialize] may have been in progress in another thread when fork() was called.
objc[36925]: +[NSConnection initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
Vim: Caught deadly signal ABRT
Vim: Finished.
E852: The child process failed to start the GUI
```

This is on 10.13.2.  I don't know if this has always been broken on High Sierra, but I know that it at least *used to* work on Sierra.  I no longer have a Sierra machine on which to test, but I can look at El Capitan later today.

**Comment by chdiza** [comment]
I have manually bisected, and found that the last good commit was 96b4e927fb09b992ab4eece46cb38a, which is the most recent merge-in after 8.0.1216.

The next commit that will actually build MacVim so that I can try `:gui` is the very next merge-in, afc384eafa35234a5ef34cca6e44e, which is the next merge-in after 8.0.1238.

I'm not qualified to know which commits between those are the culprits, but just by looking at commit messages, my first suspect would be 8.0.1236, which messes with a bunch of macos-related stuff all at once.

I have no idea how to get a more fine-grained bisection, because if I `git checkout [one-of-Bram's-commits], the gui doesn't build because there's no MacVim source apparatus after the checkout.

I'm hoping someone either knows how to do this, or will be able to spot the bug by looking at diffs.

**Comment by chdiza** [comment]
(The problem could also, of course, be a merging error.)

**Comment by splhack** [comment]
How about this https://github.com/vim/vim/pull/2178 ?

**Comment by chdiza** [comment]
That one's already been merged: it's 8.0.1236, which would be my initial suspect.

**Comment by chdiza** [comment]
@nuko8 Would you mind taking a look at this thread to see if you have any idea whether 8.0.1236 might be the problem?

**Comment by nuko8** [comment]
> @nuko8 Would you mind taking a look at this thread to see if you have any idea whether 8.0.1236 might be the problem?

Not at all, absolutely.

An off-hand idea: at gui.c:40 or around it, changing the preprocessor directive from
```
#if defined(UNIX) && !defined(FEAT_GUI_MAC)
```
to something like
```
#if defined(UNIX) && ! (defined(FEAT_GUI_MAC) || defined(FEAT_GUI_MACVIM))
```
might fix the issue.

> my first suspect would be 8.0.1236, which messes with a bunch of macos-related stuff all at once.

Too harsh to me :)

**Comment by chdiza** [comment]
@nuko8 Thanks!  I just tried it and it seems to work.  I'll test it a bit more just to make sure that nothing else went awry.

**Comment by nuko8** [comment]
OK, let me know if you find anything bad with it.  Actually, I more or less predicted that issues like this would happen, but, since I didn't have a good idea as to how to collaborate with good people here, I hadn't done nothing about that.  Thanks to your effort, that outstanding issue will be likely to be resolved, and I'm happy with it.

**Comment by chdiza** [comment]
I'm pleased to report that @nuko8's fix has been working without noticeable incident for the last 6 days.  But I'm also not knowledgeable enough to say whether it's The Right Fix.  @splhack Does it look OK to you?

**Comment by splhack** [comment]
thanks!

**Comment by chdiza** [comment]
This issue has returned.  I see it on 8.0.1848.

**Comment by nuko8** [comment]
(Just in case MacVim people missed a change done by the upstream...)

That's due to Patch 8.0.1795 (b0b98d523) where `MAY_FORK` that had been used only in `gui.c` was renamed to `GUI_MAY_FORK` so that it would be available to `channel.c`.  The condition when the latter is defined is now given in `gui.h`.  Accordingly, the regression should be fixed by exactly the same way as we did before: Append `|| defined(FEAT_GUI_MACVIM))` to the tail of the existing `#if` conditions at `gui.c:568`.

**Comment by chdiza** [comment]
Line 568 of `gui.h` is the middle of a comment block.  Do you mean line 580?

**Comment by nuko8** [comment]
I meant [this](https://github.com/vim/vim/blob/4d6cd291cec668b991f2b43d76c6feab8b2e7d98/src/gui.h#L568) by `gui.h:568`.  That's the one of Vim's codebase.  I guess MacVim's is a bit different from that in copyright header etc.

**Comment by chdiza** [comment]
I tried it, and it works.  Thanks!
