### ISSUE TITLE
搞不明白了

### ISSUE THREAD

**Issue by xiaoyin199** [macvim-dev/macvim#615]
初始化，总是有，“$p”
![image](https://user-images.githubusercontent.com/12995542/33866970-9c41a494-df34-11e7-9afd-496fa1ac8fbb.png)

**Comment by tracyone** [comment]
```
set nocompatiable
```

**Comment by xiaoyin199** [comment]
不行

**Comment by tracyone** [comment]
@xiaoyin199 https://github.com/vim/vim/issues/2008
