### ISSUE TITLE
terminal: terminal buffer was not wiped out  using ctrl-d

### ISSUE THREAD

**Issue by tracyone** [macvim-dev/macvim#620]
Hi,

In lastest macvim,

I open terminal with following command:

```
:terminal ++close bash
```

Then I press ctrl-d in terminal, but the buffer was not wiped out.

Instead, I execute  `exit` comand in terminal can exit terminal and it's buffer was wiped out successuflly.

<img width="771" alt="screen shot 2017-12-23 at 10 37 06" src="https://user-images.githubusercontent.com/4246425/34316307-3f4e727a-e7cd-11e7-95aa-6ac0be29ab72.png">

**Comment by qiqiboy** [comment]
`tnoremap <c-d> <C-w>q`

**Comment by tracyone** [comment]
@qiqiboy thanks.

But` terminal ++close zsh`  or vim is work well.
