### ISSUE TITLE
new MacVim icon is too light

### ISSUE THREAD

**Issue by 7stud** [macvim-dev/macvim#624]
Hi,

I'm running macOS High Sierra (10.13.2), and I had to reinstall MacVim for some reason, and I find that the new MacVim icon as it appears in the Dock  is too light of a color.  The default color of the Dock is white, and the white "V" in the  MacVim icon fades into the Dock's white background making the icon hard on the eyes.   I think the old icon that was dark green stood out nicely, and because I'm used to looking for the highly visible dark green icon in the Dock, I don't like the new color.  

I looked at the new MacVim.icns file, and it contains ten icons  while my old MacVim.icns file contains five icons.  Is it possible to make available a ten icon file with the old dark green icon?  Thanks.

**Comment by jpetrie** [comment]
The [history of the MacVim icon in the repository is here](https://github.com/macvim-dev/macvim/commits/master/src/MacVim/icons/MacVim.icns), which you can use to fetch the desired version of the icon yourself.

All the document-type icons are generated (there is a Makefile in `src/MacVim/icons` used to do so) if you want to regenerate everything yourself, although I think applying those would require you to rebuild MacVim yourself as well.
