### ISSUE TITLE
Window Size bug when using :wq command 

### ISSUE THREAD

**Issue by RileyTheRed** [macvim-dev/macvim#625]
When using the :wq command after editing a file, some visual bug with, im guessing the window size, happens. Using :w followed by :q works just fine, and even when using the :wq command the file is written properly but the result is ugly. Here is what im looking at whenever I use said command.

<img width="684" alt="screen shot 2018-01-11 at 12 09 28 pm" src="https://user-images.githubusercontent.com/20608846/34837536-1d2cddd4-f6c9-11e7-8ea7-15a4fd9af0e7.png">

Any ideas on how to go about it for a fix?

**Comment by eirnym** [comment]
@RileyTheRed Does it still an issue for you?

**Comment by ychin** [comment]
Closing. I don't think this kind of rendering corruption issue is still relevant today.
