### ISSUE TITLE
:terminal colors

### ISSUE THREAD

**Issue by amadeus** [macvim-dev/macvim#626]
It would be nice if there was a way to customize the colors in the `:terminal` feature.

Currently I have a color scheme for iTerm that is set, however I believe that terminal vim just inherits the color from your current terminal, however with MacVim, I am not sure if there is a way to set this?

![example](http://wtf.amadeus.wtf/monosnap/Desktop_2018-01-19_02-22-03.png)

**Comment by ptzz** [comment]
Since it's an xterm terminal, could the settings from `~/.Xresources` or `~/.Xdefaults` be used?

**Comment by ptzz** [comment]
This works on MacVim `HEAD` , since commit https://github.com/macvim-dev/macvim/commit/f59c6e8cee092433d325ba21a107654a8d84f776 I assume (set the `g:terminal_ansi_colors` variable).

**Comment by amadeus** [comment]
Yup, this fixes it! Thanks for the tip!

**Comment by hukl** [comment]
@amadeus I'm running into the same issue and from your comments I can't quite figure out what to do to get nice colors in the macvim term. Could you help me out with more detailed instructions?

**Comment by eirnym** [comment]
You should call `term_setansicolors()` function to set them.

**Comment by eirnym** [comment]
Example from the test from the commit mentioned above:

```vim
let s:test_colors = [
 	\ '#616e64', '#0d0a79',
 	\ '#6d610d', '#0a7373',
 	\ '#690d0a', '#6d696e',
 	\ '#0d0a6f', '#616e0d',
 	\ '#0a6479', '#6d0d0a',
 	\ '#617373', '#0d0a69',
 	\ '#6d690d', '#0a6e6f',
 	\ '#610d0a', '#6e6479',
 	\]

let g:terminal_ansi_colors = s:test_colors;
" or 
call term_getansicolors(buf);

```

**Comment by hukl** [comment]
Hmm I tried it just now and your example does not seem to work in my up to date MacVim

let g:terminal_ansi_colors = s:test_colors;

This line produces an error. Am I right to assume that I should put your example in my vimrc?
