### ISSUE TITLE
How to use ruby 2.5 with newest snapshot-145

### ISSUE THREAD

**Issue by 23tux** [macvim-dev/macvim#641]
In the newest snapshot release it states "Update Ruby interface from 2.4 to 2.5". I've installed ruby with rbenv, und set `rbenv global 2.5.0`. Then I restarted MacVim.

However, when I type 

```
:!ruby -v
2.4.3p205 (2017-12-14 revision 61247) [x86_64-darwin17]
```
Checking rbenv I get

```
:!rbenv version
2.5.0 (set by /Users/my_user/.rbenv/version) 
```
And using `which` I get

```
:!which ruby
/usr/local/bin/ruby 
```

But when I look into that ruby executable, I get

```
$ /usr/local/bin/ruby  -v
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin15]
```

So I'm a little stuck here. How can I convince MacVim to use ruby 2.5?

**Comment by splhack** [comment]
first of all, the ruby interface is if_ruby http://vimdoc.sourceforge.net/htmldoc/if_ruby.html

:! http://vimdoc.sourceforge.net/htmldoc/various.html#:! depends on your shell environment.
