### ISSUE TITLE
ctrlp plugin stopped working with latest brew install of macvim (stable 8.0-145)

### ISSUE THREAD

**Issue by trak3r** [macvim-dev/macvim#642]
It still works in normal command-line vim so I would guess this is a path issue but I don't know where to start looking to troubleshoot it.

I can post more info if you can direct me where to look. Thanks.

https://github.com/ctrlpvim/ctrlp.vim

```
brew info macvim
macvim: stable 8.0-145 (bottled), HEAD
GUI for vim, made for macOS
https://github.com/macvim-dev/macvim
/usr/local/Cellar/macvim/8.0-145_1 (2,151 files, 34.3MB) *
  Poured from bottle on 2018-03-02 at 11:51:25
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/macvim.rb
==> Dependencies
Recommended: cscope ✔, python ✔
Optional: lua ✘, luajit ✘, python@2 ✘
==> Requirements
Build: xcode ✔
==> Options
--with-lua
	Build with lua support
--with-luajit
	Build with luajit support
--with-override-system-vim
	Override system vim
--with-python@2
	Build with python@2 support
--without-cscope
	Build without cscope support
--without-python
	Build without python support
--HEAD
	Install HEAD version
```

**Comment by trak3r** [comment]
UPDATE

Seems the core issue actually stems from this extension to ctrlp:

https://github.com/JazzCore/ctrlp-cmatcher

Removing this line from my config allowed vanilla ctrlp to work again:

```
let g:ctrlp_match_func = {'match' : 'matcher#cmatch' }
```

This extension seems to have a dependency on Python so perhaps the combination of brew-Macvim and brew-Python are the cause.

**Comment by trak3r** [comment]
UPDATE

I still haven't resolved this issue.

For any future Googlers that land here trying to solve the same problem, I have temporarily switched to `FelikZ/ctrlp-py-matcher`. Its pattern matching isn't as good as the former but it'll do for now.

https://github.com/FelikZ/ctrlp-py-matcher

**Comment by ychin** [comment]
Did you resolve this issue?

**Comment by trak3r** [comment]
> Did you resolve this issue?

Nope I just learned to love `FelikZ/ctrlp-py-matcher`

**Comment by ychin** [comment]
I'm going to close this for now. This seems like a Python configuration issue. It may have been a misconfiguration in the Homebrew set up.
