### ISSUE TITLE
bug when opening python files

### ISSUE THREAD

**Issue by diegoholiveira** [macvim-dev/macvim#647]
I'm having problems opening python files with macvim. This is what's happen when I try to open a python file (with other files everything works fine):

```
$ Fatal Python error: Py_Initialize: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007fff9f2173c0 (most recent call first):
Vim: Caught deadly signal ABRT
Vim: Finished.
```

Here's the trick: when I remove all my plugins and use a vanilla macvim, it works, so the problem may be one of the plugins that I use. Nevertheless, I've decided to report this here because the same set of plugins work perfect fine with the standard vim (installed with brew install vim).

Thanks :)

**Comment by diegoholiveira** [comment]
An extra detail: sounds like a problem with macvim version available with cask. I just remove the cask version and install macvim with brew install and everything is working as it should.

This is what I had before:

```
$ brew cask info macvim
macvim: 8.0.145
```

This is what I have now:

```
$ brew info macvim
macvim: stable 8.0-145 (bottled), HEAD
```

**Comment by dejavuzhang** [comment]
I think it's not the problem of opening python files. I had the same issue after reinstalling python and macvim, and if happens when opening any files in command line. If I open the application directly, nothing renders.
Interestingly, the problem was solved after I switched to the cask version.

**Comment by schar** [comment]
I've observed similar behavior. In my case, the issue wasn't opening python *files* (as noted in the comment above mine). Rather, it was that one of my plugins was *using* python, and something about python integration appears to be broken in current builds of Macvim. (I couldn't duplicate this problem with neovim or vim.)

For example, `:py3 print('test'.encode('utf8'))` was enough to crash Macvim for me. Give this a try and see if it's the same for you.

The issue persisted, whether I brewed Macvim (`brew install macvim`) or uninstalled the brew version and then installed the binary directly. [Tapping then brewing](https://github.com/macvim-dev/homebrew-macvim) does give me a working Macvim, with working python. (Something was going wrong with the cask install, so I didn't get a chance to test that.)

**Comment by diegoholiveira** [comment]
> For example, :py3 print('test'.encode('utf8')) was enough to crash Macvim for me. Give this a try and see if it's the same for you.

Yes, when I run the tests that you suggest, MacVim crashes.

**Comment by c0llision** [comment]
This sounds like the same issue as #649 

This is what solved it for me:

`brew unlink macvim
brew install macvim --HEAD`

**Comment by chuanchan1116** [comment]
This problem can be resolved if you `brew reinstall macvim --build-from-source`. I have made an PR for rebuilding the bottle, waiting for merge.
