### ISSUE TITLE
Recent update to python 3.6.4 breaks macvim

### ISSUE THREAD

**Issue by alex-protean** [macvim-dev/macvim#649]
Brewed python3 was updated, now brewed macvim gives the following error:
```
Fatal Python error: Py_Initialize: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007fff8e4af340 (most recent call first):
Vim: Caught deadly signal ABRT
Vim: Finished.
```
Other threads have suggested upgrading to the development version of python (but these threads were quite old, so the development version of python that they are referring to is not the same as the current dev version). I tried this (brew upgrade python3 --devel), and it basically broke everything:
``dyld: Library not loaded: /usr/local/opt/python/Frameworks/Python.framework/Versions/3.6/Python``

vim still works in the terminal, but macvim won't open

**Comment by alecshaw** [comment]
Thank you for the issue. Duplicate of https://github.com/macvim-dev/macvim/issues/562. I would recommend looking at the solutions proposed there to see if they resolve your issue.

**Comment by c0llision** [comment]
This is what fixed it for me:

`brew unlink macvim`
`brew install macvim --HEAD`

**Comment by alex-protean** [comment]
@c0llision That fixed it:
```
brew unlink macvim
brew install macvim --HEAD
```
