### ISSUE TITLE
Support Emoji

### ISSUE THREAD

**Issue by kentcdodds** [macvim-dev/macvim#65]
Would love to have this support emoji as discussed [here](https://github.com/b4winckler/macvim/pull/38). Am I missing something? Or has this just not had priority?

**Comment by nornagon** [comment]
:rotating_light: :+1: :rotating_light: 

this is EXTREMELY important for writing documentation.

**Comment by splhack** [comment]
Emoji will be available from Snapshot 81🐱

**Comment by kentcdodds** [comment]
Hooray!
