### ISSUE TITLE
Env variable to know if :terminal shell is within MacVim

### ISSUE THREAD

**Issue by jeromedalbert** [macvim-dev/macvim#655]
I have this in my .zshrc:
```
if [ -z $TMUX ]; then; tmux-start; fi
```

It works well for terminal and terminal vim.

But for MacVim, I get this:

<img width="1386" alt="screen shot 2018-03-20 at 8 49 01 pm" src="https://user-images.githubusercontent.com/236461/37693936-26cddcc0-2c80-11e8-88ea-7a2a7c3979f1.png">

There is a `tmux` inside `:terminal` (see black bar at the bottom of the screenshot). I would like to disable tmux in macvim because I don't think it makes much sense. Maybe if I could test against an environment variable like `$MACVIM` available inside a `:terminal`, I would be able to disable this.

**Comment by edouardp** [comment]
$MYVIMRC appears to be set when I launch a terminal from within MacVim and Vim, but not from opening a new shell in Terminal.app. I'm not sure who is setting that variable, but it might be enough to test for that in you .zshrc file.

**Comment by jeromedalbert** [comment]
Thanks for the tip @edouardp. I have changed my line to 

```
if [ -z $TMUX ] && [ -z $MYVIMRC ]; then; tmux-start; fi
```

and that did the trick 👍
