### ISSUE TITLE
Open in same terminal without vi mode?

### ISSUE THREAD

**Issue by i-schuetz** [macvim-dev/macvim#666]
When entering `mvim` it will open a new window. How do I prevent this? I want the same behavior as with the `vim` command.

Vi mode (i.e. the `-v` flag) prevents this, but it disables other things like setting a custom font.

**Comment by chdiza** [comment]
`mvim` opens a GUI, which means it necessarily opens a window not in your terminal.

**Comment by i-schuetz** [comment]
Ah okay. Thought it was possible to somehow get it to display in the terminal. Just to understand, what I open with `mvim -v` is then not Macvim?

**Comment by eirnym** [comment]
There's two executables in the `MacVim.app` bundle, `Vim` and `MacVim`. The first one is a terminal-based MacVim, and `MacVim` is a graphical UI.

`mvim` will run `MacVim` binary and `mvim -v` will open `Vim`.

**Comment by i-schuetz** [comment]
@eirnym That explains it, thanks!

**Comment by i-schuetz** [comment]
@eirnym That explains it, thanks!

But why does the terminal based MacVim use Vi mode (which makes not possible to e.g. set a custom font)?

**Comment by eirnym** [comment]
Terminal based MacVim is like an original Vim. 
The font option is an option for GUI only as you can open a text terminal in text mode like 80x25 and there's no option to recognise it. You should tweak settings of your terminal to change font.

**Comment by i-schuetz** [comment]
@eirnym thanks!
