### ISSUE TITLE
Vim process crashes instantly.

### ISSUE THREAD

**Issue by Phosphor303** [macvim-dev/macvim#667]
When opening a new window in MacVim, it appears for a split second and instantly vanishes. MacVim is still running. The crash logs indicate it's Vim that's actually crashing. See here:

https://gist.github.com/Phosphor303/921c4b15cd288e1192d66b9465fa3e8c

Starting MacVim in the terminal yields the following error:

```
Fatal Python error: Py_Initialize: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007fffa4125340 (most recent call first):
Vim: Caught deadly signal ABRT
Vim: Finished.
```

I have system Python (2.7.10) and homebrew Python (3.6.5) installed. In both REPLs I am able to `import encodings`. System vim works fine.

I'm using macOS 10.13.3.

**Comment by JadingTsunami** [comment]
This has happened before (see: #562, #647).

Advice:

1. If you are using Homebrew, try: `brew reinstall macvim --build-from-source`
2. Try:

```vimscript
if has('python3')
    command! -nargs=1 Py py3 <args>
    set pythonthreedll=/usr/local/Frameworks/Python.framework/Versions/3.6/Python
    set pythonthreehome=/usr/local/Frameworks/Python.framework/Versions/3.6
else
    command! -nargs=1 Py py <args>
    set pythondll=/usr/local/Frameworks/Python.framework/Versions/2.7/Python
    set pythonhome=/usr/local/Frameworks/Python.framework/Versions/2.7
endif
```

**Comment by Phosphor303** [comment]
I added your second advice to my `.vimrc` and it worked. Thank you very much!

**Comment by nilsbecker** [comment]
same issue here. started after update to high sierra. solved by adding explicit paths to .vimrc as described above.
