### ISSUE TITLE
mouse clicks do not work on inputlist() entries

### ISSUE THREAD

**Issue by gcavallanti** [macvim-dev/macvim#668]
Macvim releases after 135 (vim patch 771) can't detect mouse clicks on inputlist() entries.
Inputlist() works fine, that is, mouse clicks are correctly registered, in Macvim 134 (vim patch 648) though.

Start vim with `mvim -u NONE -U NONE` and run:
`let color = inputlist(['Select color:', '1. red','2. green', '3. blue'])`

**Comment by epheien** [comment]
such as me

**Comment by ychin** [comment]
Seems to work for me. How does it not work for you @epheien?

I confirmed it wasn't working in 135, but the newest versions (at least for the last 3 releases from 153) should work. Do note that you won't get a mouse over selection effect. Only the mouse click registers so it's not obvious.

**Comment by epheien** [comment]
> Seems to work for me. How does it not work for you @epheien?
> 
> I confirmed it wasn't working in 135, but the newest versions (at least for the last 3 releases from 153) should work. Do note that you won't get a mouse over selection effect. Only the mouse click registers so it's not obvious.

I test in MacVim Snapshot 154, It works.
So, please close this issue.
