### ISSUE TITLE
MacVim silently fails to save a file when a conversion error is present

### ISSUE THREAD

**Issue by dschuessler** [macvim-dev/macvim#671]
Steps to reproduce:
1. Create a text file that yields a `CONVERSION ERROR` when saved in Vim (e.g. when trying to save it with `:w`).
2. Try to close the corresponding MacVim window (e.g. by clicking on the red wine gum).
3. When the dialogue appears, that asks if you want to save the file, confirm.

Expected behavior: I get some alert that the file did not actually save and why.

Actual behavior: The dialogue, that asks if you want to save the file, disappears and the window simply does not close.

**Comment by dschuessler** [comment]
1. Open an empty buffer.
2. `:set fileencoding=latin1`
3. Write an Emoji into the buffer.
4. Try to safe as described above.

**Comment by eirnym** [comment]
@dschuessler I reproduced the issue in terminal Vim and filled the issue to the upstream. Please, follow up there.

**Comment by eirnym** [comment]
@ychin the underlying issue was fixed in vim-patch:8.1.1349. Please update the base

**Comment by ychin** [comment]
Will do. Thanks. Will close this issue after I release a new MacVim update.

**Comment by ychin** [comment]
Released a new update. Closing.
