### ISSUE TITLE
Graphical problems when MacVim is in fullscreen

### ISSUE THREAD

**Issue by louiswolfers** [macvim-dev/macvim#674]
Can't really give a way to reproduce this, but sometimes, when switching between fullscreen apps, MacVim has a seizure. 

<img width="1663" alt="screen shot 2018-04-14 at 21 11 24" src="https://user-images.githubusercontent.com/7440721/38781098-baceea1c-40e0-11e8-82a0-a5328a8dacba.png">

Happened to me three times, and the pattern of the "bug" is not the same. When I took the screenshot, every transparent pixel was black. I have no idea why.

It's not a really important bug, as it disappears as soon as I click on the screen.

**Comment by slmcrs** [comment]
Also have experienced this, seems to happen when the native full screen feature is enabled.

**Comment by Shane325** [comment]
Same issue for me, when the native full screen feature is on. macOS High Sierra.

**Comment by ZeerakW** [comment]
There are suggestions for workarounds in #557

**Comment by louiswolfers** [comment]
Workarounds either don't work or slow down MacVim :(

**Comment by marr** [comment]
This is a pretty major problem for me. I'm using an external monitor, and have tried turning off Core Renderer as well as native full screen. Neither really fix the problem or introduce other issues that are just as bad. Are the authors able to address whats going on here?

**Comment by louiswolfers** [comment]
Well, MacVim is an open source project and their authors do not have the obligation to fix the bugs of other users. The only "good" solutions here are:

- turning off native fullscreen: just create a new desktop for each MacVim instance you want to have in fullscreen
- moving on vimR/neovim
- fixing the bugs yourself (good luck)
