### ISSUE TITLE
Cyrillic characters are rendered using Monaco

### ISSUE THREAD

**Issue by ferrum-salvator** [macvim-dev/macvim#675]
guifont and guifontwide are both set to Source Code Pro, which has Cyrillic characters. Terminal Vim and other apps use those without issues, MacVim uses the fallback monospace font.

**Comment by eirnym** [comment]
Google Fonts, official readme and github page doesn't claim that this font does support Cyrilic characters, does it?

**Comment by ferrum-salvator** [comment]
I haven't checked, but it certainly does. That said, the issue appears to have disappeared in 8.1, or was transient to begin with.
<img width="477" alt="screenshot 2018-06-18 10 09 41" src="https://user-images.githubusercontent.com/5638404/41522767-24224708-72e0-11e8-9bbc-68ebebce2be9.png">
