### ISSUE TITLE
EXC_BAD_ACCESS in MacVim

### ISSUE THREAD

**Issue by thpani** [macvim-dev/macvim#677]
MacVim erratically segfaults with `EXC_BAD_ACCESS` when running [lervag/vimtex](https://github.com/lervag/vimtex)'s continuous LaTeX compilation.
Backtraces end in symbol `syn_current_attr` before the exception handler is called, and the exception code is `KERN_INVALID_ADDRESS` or `EXC_I386_GPFLT`.

Mac OS X 10.11.6
MacVim 8.0.1633 (146)

So far, it seems this does not occur in (vanilla) vim 8.0.1700

This happens with a minimal `vimrc`:

```vim
set nocompatible
call plug#begin('~/.vim/plugged')
Plug 'lervag/vimtex'
call plug#end()
```

`.latexmkrc`:
```
$pdflatex = "pdflatex -synctex=1 %O %S";
```

I'm attaching two crashlogs:

[Vim_2018-04-23-160534_Thomass-MacBook-Pro.txt](https://github.com/lervag/vimtex/files/1938979/Vim_2018-04-23-160534_Thomass-MacBook-Pro.txt)
[Vim_2018-04-23-171057_Thomass-MacBook-Pro.txt](https://github.com/lervag/vimtex/files/1938980/Vim_2018-04-23-171057_Thomass-MacBook-Pro.txt)

I've also posted this as lervag/vimtex#1112, but I agree this seems more likely a MacVim issue.

**Comment by thpani** [comment]
> do you have you python 3 installed?
yes
> and have you set up MacVim to use it?
yes

The plugin works in general. The problem is that macvim randomly crashes.

**Comment by eirnym** [comment]
@thpani Does it still a problem? Could you try Vim in terminal if the issue is present there?

**Comment by thpani** [comment]
@eirnym Hasn't occurred for some time, closing the issue.
