### ISSUE TITLE
:terminal view won't update without additional keypresses/mouse movement

### ISSUE THREAD

**Issue by amadeus** [macvim-dev/macvim#682]
Not sure if this is a vim or macvim issue, but it appears that when I use `:term` on the latest MacVim built from this repo, the terminal buffer won't update until after I press a key or move the mouse, so it's always continuously one update behind.

Not sure how obvious it will be in this example video:

[example](http://wtf.amadeus.wtf/monosnap/screencast_2018-05-14_02-05-50.mp4)

**Comment by chdiza** [comment]
I see the same problem.
