### ISSUE TITLE
Macvim doesn't update properly after it runs a term_start callback

### ISSUE THREAD

**Issue by jonleighton** [macvim-dev/macvim#685]
Minimal test case by @junegunn:

```
function! OnExit(...)
  close
endfunction
call term_start('sleep 1', {'exit_cb': function('OnExit')})
```

From https://github.com/junegunn/fzf.vim/issues/604:

> Adding redraw after close helps, but the cursor stays in a weird place until you hit a key.

**Comment by mario-grgic** [comment]
Interestingly enough, if you move the mouse over the MacVim window, the terminal window disappears right away. Forcing redraw! makes the cursor jump around jarringly.
