### ISSUE TITLE
Plugins with python dependencies

### ISSUE THREAD

**Issue by mredolatti** [macvim-dev/macvim#688]
First of all my apologies if this is a repeated question.

What should be the best approach to handle python dependencies when installing this with hombrew?

It seems like the macvim is linked to the system's python installation which cannot be modified on high sierra. I need to get `websocket-client` and  `sexpdata` python packages installed and reachable by vim in order to use http://ensime.github.io/editors/vim/

Thank you very much in advance and sorry for my english.

**Comment by eirnym** [comment]
Python path used for ViM can be modified like in a snippet below. I use Python from MacPorts and a binary installation from GitHub. Python checks PYTHONPATH variable if virtualenv is running and uses libraries from it.  

```
set pythonthreehome=/opt/local/Library/Frameworks/Python.framework/Versions/3.6
set pythonthreedll=/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/libpython3.6.dylib

set pythonhome=/opt/local/Library/Frameworks/Python.framework/Versions/2.7
set pythondll=/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib
```

**Comment by ychin** [comment]
@mredolatti Did the answers work for you? If so please close the issue.

Also, MacVim will now automatically use Homebrew / MacPort / official Python installations if they exist (2.7 or 3.7 as of the latest version today) so if you have those installed you don't even need to configure manually.

**Comment by mredolatti** [comment]
Thank you!
