### ISSUE TITLE
homebrew macvim build failed on macOS 10.14 with Xcode 10 beta

### ISSUE THREAD

**Issue by kaitolucifer** [macvim-dev/macvim#690]
<pre>Last 15 lines from /Users/kaito/Library/Logs/Homebrew/macvim/02.make:
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin18/rbconfig.rb:214:in `<module:RbConfig>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin18/rbconfig.rb:7:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems.rb:9:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems.rb:9:in `<top (required)>'
	from <internal:gem_prelude>:4:in `require'
	from <internal:gem_prelude>:4:in `<internal:gem_prelude>'

** BUILD FAILED **

The following build commands failed:
	CompileC /tmp/macvim-20180611-46855-pbvqpw/src/MacVim/build/MacVim.build/Release/MacVim.build/Objects-normal/x86_64/MMPreferenceController.o /tmp/macvim-20180611-46855-pbvqpw/src/MacVim/MMPreferenceController.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
make[1]: *** [macvim] Error 65
make: *** [first] Error 2</pre>

**Comment by eirnym** [comment]
Please, tell if official vim is compatible with Ruby 2.3 and can be compiled on macOS 10.14 with XCode 10 beta. If not, please report to the upstream.

**Comment by kaitolucifer** [comment]
Looks like vim can be compiled.
<pre>
==> Upgrading vim 
==> Downloading https://github.com/vim/vim/archive/v8.1.0050.tar.gz
==> Downloading from https://codeload.github.com/vim/vim/tar.gz/v8.1.0050
######################################################################## 100.0%
==> ./configure --prefix=/usr/local --mandir=/usr/local/Cellar/vim/8.1.0050/shar
==> make
==> make install prefix=/usr/local/Cellar/vim/8.1.0050 STRIP=/usr/bin/true
==> Not running post_install as we're building a bottle
You can run it manually using `brew postinstall vim`
🍺  /usr/local/Cellar/vim/8.1.0050: 1,432 files, 23.3MB, built in 11 minutes 33 seconds
</pre>
