### ISSUE TITLE
Completion is broken in snapshot 148

### ISSUE THREAD

**Issue by micbou** [macvim-dev/macvim#691]
A bug was introduced in [Vim 8.1.0035](https://github.com/vim/vim/commit/6d41c78e353b630bc1a72cbff9160311d2a81e8c) that makes completion unusable when the preview window is used. See [this thread on vim-dev](https://groups.google.com/forum/#!topic/vim_dev/9x4mx_qfLQ4) for more detail. The bug has been fixed in [8.1.0042](https://github.com/vim/vim/commit/f98b845dd185dfadfa7a622a42452bfa6809d4e0). I don't know your policy about releases containing serious bugs but I would suggest to remove snapshot 148 and publish a new release including patch 8.1.0042.

**Comment by simonask** [comment]
This seems to be fixed in snapshot 149.

**Comment by micbou** [comment]
Yes, it is. I'll close the issue (even though I think snapshot 148 should still be removed).
