### ISSUE TITLE
Wrong rendering of some chars

### ISSUE THREAD

**Issue by dond--** [macvim-dev/macvim#693]
Hi, I found recently that last update (8.1.72, build 149) has broken some rendering in normal mode. Attached are two screenshots with misrendered chars.

I've found the issue occurs when there's some non-latin Unicode character placed in the middle of the line. I experimented mostly with Greek chars (α, ω, …), some other Unicode chars seems to be OK. When a Greek char is placed in the first position on the line, rendering is OK.

Putting cursor over problematic (and subsequent) char(s) temporarily fixes rendering. When cursor moves to other line, the issue is back. It doesn't matter if problematic char was in the file or it is entered in insert mode. Wrapping settings don't matter, apparent rest of the line is misrendered anyway.

Core Text renderer is used, macOS is High Sierra 10.13.5.

Can I provide more info to track down the issue?

Thanks, dond

<img width="827" alt="screen shot 2018-06-18 at 17 06 33" src="https://user-images.githubusercontent.com/3584845/41544876-233f590e-731a-11e8-8293-a9d52a7c0dec.png">
<img width="828" alt="screen shot 2018-06-18 at 16 56 22" src="https://user-images.githubusercontent.com/3584845/41544877-23601c34-731a-11e8-9f98-12c49ec4c5d4.png">

**Comment by eirnym** [comment]
Is this GUI or terminal version? I have no problem with my settings. I have follwoing settings set in my vimrc and I didn't changed the fallback font:

```
set macligatures
set guifont=Fira\ Code\ Light:h16
```

**Comment by dond--** [comment]
It's in GUI, terminal version is OK.

Perhaps it somehow relates to particular font(s) – when I run MacVim with `-u NONE`, it starts with Menlo font and everything looks good. Once I change font to Fira Code (nice one I wasn't aware of, BTW), issue appears again.
<img width="819" alt="screen shot 2018-06-18 at 21 07 42" src="https://user-images.githubusercontent.com/3584845/41556745-ef0b8f50-733b-11e8-8921-9491ebbeb639.png">

**Comment by eirnym** [comment]
I found a random Greek text and can't reproduce your issue. Could you provide more details?
My MacVim is build 149 and macOS 10.12.

Is it some specific text?

**Comment by dond--** [comment]
> *Is it some specific text?*

Not much – see my previous comments, for me it's enough to write α β ω somewhere but start of the line and rendering goes wrong. Since it's present only with some fonts I'd suspect it may relate to particular font. Previous build was OK though.

**Comment by dond--** [comment]
Oh, and I just found another subtle detail: Greek char has to be followed by another latin char (or even space or non-breakable space and *then* latin char.

So, schema is:
1. latin chars
2. Greek char(s)
3. latin chars (optional space)

And yet another detail: build 146 is OK, build 148 and 149 are broken.

See attached screenshot, upper half is build 146, lower half is build 149. Font *Source Code Pro*.

<img width="931" alt="screen shot 2018-06-22 at 16 58 40" src="https://user-images.githubusercontent.com/3584845/41783850-3eb40e4c-763e-11e8-9493-6707c8343fd1.png">
