### ISSUE TITLE
Update Prompt Version Precision Cutoff

### ISSUE THREAD

**Issue by jkulesza** [macvim-dev/macvim#694]
The window that prompts a user to update cuts off the version in such a way that may lead to confusion.  See attached.  

The window currently begs the question "Why should I upgrade, I appear to have a version newer than the one advertised?"
 
<img width="464" alt="screen shot 2018-06-18 at 11 26 01" src="https://user-images.githubusercontent.com/9939059/41551956-9d80749e-72ea-11e8-9f44-273a25a6d0d6.png">

**Comment by eirnym** [comment]
Could we put whole version in `sparkle:shortVersionString`?

**Comment by sloanlance** [comment]
As mentioned in the closed issue that had referenced this one, I saw an even greater difference in version numbers, 8.1.235 → 8.0:

<img width="732" alt="screen shot 2018-08-21 at 11 36 11" src="https://user-images.githubusercontent.com/17595351/44412392-d549ca00-a536-11e8-9972-b7fb39f6e60d.png">

I was told that actually it was offering me 8.1.280.  The only indication of that was in the description, which was written as 8.1.0280 (with a leading "0" on the last segment).

Overall, very confusing as to what version the user should expect to receive as a result of the update.

**Comment by ychin** [comment]
The latest update should show you the Vim patch version (instead of 8.0) so it's clear what you are getting, and the release notes would cover the MacVim portion of what features are added.

**Comment by ychin** [comment]
<img width="684" alt="screen shot 2018-12-05 at 6 43 08 am" src="https://user-images.githubusercontent.com/1217449/49521022-57959a00-f859-11e8-8dba-e83e313e9ef2.png">
