### ISSUE TITLE
Cannot remap <C-h> in insert mode

### ISSUE THREAD

**Issue by klassegeljakt** [macvim-dev/macvim#695]
Hi, I have attempted to remap some insert mode keys with

```
inoremap <C-h> <Left>
inoremap <C-j> <Down>
inoremap <C-k> <Up>
inoremap <C-l> <Right>
```

All remaps work, except for `<C-h>`, why is this the case? `<C-h>` appears to send `<Backspace>`.

**Comment by eirnym** [comment]
Just tried it both in GUI and text MacVim and everything worked as intended to work. What is your environment?

**Comment by klassegeljakt** [comment]
Woops, just found out it was a plugin and not macvim, sorry.
