### ISSUE TITLE
Arabic broken

### ISSUE THREAD

**Issue by moti-kagan** [macvim-dev/macvim#696]
Latest update seems to have broken handling of Arabic text.

**Comment by moti-kagan** [comment]
When opening an Arabic text file, and entering the vim command "set arabic", the resulting right-to-left display of the text isn't happening correctly.
This occurred in version 8.1.0072.
Things work okay when I downgrade to 8.0.1633.

**Comment by ichizok** [comment]
Can you provide an example of problematic text and expected/actual displays?

**Comment by moti-kagan** [comment]
I'm sorry but I already uninstalled 8.1.0072--I should have saved a screen cap. I think the order of letters within words was backwards. The last letter of each words was first, second-to-last was second, etc.

**Comment by andreasmhallberg** [comment]
I experience the same issue on 8.1.72. When doing `:set arabic` characters are still displayed LTR (as in the bottom line in the image). If I pass the cursor over the word characters are then order correctly as RTL (top line).

The word in the example is المسؤولين



![image](https://user-images.githubusercontent.com/10603171/42087142-94e27c7a-7b95-11e8-8bec-d7287e6ed825.png)


![image](https://user-images.githubusercontent.com/10603171/42087099-777e9bfa-7b95-11e8-9de6-50eef98e92cf.png)
