### ISSUE TITLE
`set go+="!"` doesn't work

### ISSUE THREAD

**Issue by chdiza** [macvim-dev/macvim#698]
In 8.1.72, there appears to be no way to add "!" to `&go`.  If I try, and then do `:set go`, there is no exclamation point in it.

This used to work.

**Comment by eirnym** [comment]
I done it with `set go+=!` without quotes. Did we need quotes before to set this option?

**Comment by chdiza** [comment]
What a brain lapse!  I have no idea why I was putting it in quotes; I know better.
