### ISSUE TITLE
Vim Window Randomly Closes

### ISSUE THREAD

**Issue by wyattsweet** [macvim-dev/macvim#701]
A few times throughout the day the main window will close. MacVim continues to run but all open windows get closed out. This happened 6 times today. Here is a copy of the crash log – https://gist.github.com/wyattsweet/a6f6e0ffc11c6d21addf51d28cc78c2e. System Vim seems to work fine. Any help would be greatly appreciated!

**Comment by eirnym** [comment]
Could you provide additional following info:
* Do you experience these crashes for both terminal and GUI MacVim?
* If MacVim with no config (`mvim -u NONE -N`) runs smoothly or have same crashes? 
* If there're binary plugins you're using?
