### ISSUE TITLE
How to make work CTRL X + E with MVIM properly?

### ISSUE THREAD

**Issue by tkgreg** [macvim-dev/macvim#702]
I setup mvim as a default editor(`export EDITOR='mvim'`), but when I use combination ctrl x + e it doesn't except command line text which I'm trying to edit and doesn't pass text back to command line too. What I'm doing wrong?

Environment: MacOs 10.13.5, Terminal.app, zsh.

**Comment by eirnym** [comment]
You need to use MacVim to wait to finish the edit. Otherwise, it will detach from running process. To use this feature of zsh, you should use something like this: `mvim -f -c "au VimLeave * !open -a Terminal` or `mvim -v`

**Comment by eirnym** [comment]
@tkgreg My reply works for me, does it still an issue for you?

**Comment by tkgreg** [comment]
`mvim -v` works for me

**Comment by eirnym** [comment]
could this issue be closed?
