### ISSUE TITLE
Python 3.7 and imp module

### ISSUE THREAD

**Issue by adah1972** [macvim-dev/macvim#705]
After updating Python to 3.7 (kind of forced by Homebrew), executing simply `pyx print('Hello')` generates a warning:

the imp module is deprecated in favour of importlib …

Any idea how to suppress it or solve it entirely?

**Comment by Khalilw1** [comment]
It is an ongoing issue on vim over - https://github.com/vim/vim/issues/3117

**Comment by ichizok** [comment]
Workaround: do `:silent! pyx import sys` first of all.

**Comment by dantezhu** [comment]
@ichizok good

**Comment by sloria** [comment]
I'm currently working around this issue by compiling with python 2 support:

```
brew reinstall macvim --with-python@2 --with-lua --with-luajit --with-override-system-vim
```

**Comment by sloria** [comment]
Actually, this is a better workaround then installing with python 2: Put the following at the top of your vimrc.

```viml
if has('python3')
  silent! python3 1
endif
```


From https://github.com/vim/vim/issues/3117#issuecomment-402622616

**Comment by HolaYang** [comment]
Two weeks passed, any pr to resolve this problem? Or should I install an older version macvim?

**Comment by sloria** [comment]
@HolaYang as mentioned above, this is a vim issue--not a macvim issue--so I think this issue should be locked and/or closed. I recommend using the workaround I posted above in the meantime.

**Comment by ichizok** [comment]
This was fixed in [v8.1.0201](https://github.com/vim/vim/commit/79a494d5e2f97c10e74f92ea529552623c314422) and MacVim already merged it.

**Comment by korya** [comment]
@ichizok Any idea when it is going to be released and available in homebrew?

**Comment by eirnym** [comment]
there's also vim/vim#6063 which also seems to be important

**Comment by eirnym** [comment]
@ychin Fixed in vim, this issue can be closed.
