### ISSUE TITLE
Macvim link to wrong python3 dll

### ISSUE THREAD

**Issue by markwu** [macvim-dev/macvim#706]
I recompile macvim after homebrew upgrade python from 3.6 to 3.7, I found the python3 link to wrong dll folder.

I use the following command to check python3 installed correctly or not:

`mvim -u NONE -U NONE --noplugin -c 'py3 print("test")'`

It shows me:

```
處理 command line 時發生錯誤:
E370: 無法重新載入程式庫 /usr/local/Frameworks/Python.framework/Versions/3.6/Python
E263: 抱歉，這個命令無法使用，Python 程式庫沒有載入。
```

I check my configure log, it just shows me the dll name is cached, and still point to python 3.6.

```
checking Python version... 3.7
checking Python is 3.0 or better... yep
checking Python's abiflags... m
checking Python's install prefix... /usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7
checking Python's execution prefix... /usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7
checking Python's configuration directory... /usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/config-3.7m-darwin
checking Python3's dll name... (cached) /usr/local/Frameworks/Python.framework/Versions/3.6/Python
```

Is it the configure file problem? Or my system setup problem? Really no idea how to fix it.

**Comment by markwu** [comment]
OK, I think I found the problem. It is hard coded in homebrew formula.

https://github.com/macvim-dev/homebrew-macvim/blob/master/macvim.rb#L30

**Comment by hurricane1026** [comment]
My macvim also linked to python3 after a homebrew upgrading.

**Comment by ksletmoe** [comment]
This appears to be causing issues with vim plugins that utilize Python. 

See https://github.com/davidhalter/jedi-vim/issues/526, https://github.com/davidhalter/jedi-vim/issues/841

**Comment by markwu** [comment]
Since the bug already fixed by this PR https://github.com/macvim-dev/homebrew-macvim/pull/10 , I'll close this issue.
