### ISSUE TITLE
YouCompleteMe unavailable but vim in CLI works

### ISSUE THREAD

**Issue by znculee** [macvim-dev/macvim#709]
![image](https://user-images.githubusercontent.com/15342165/42451937-3ac6d2f8-83bb-11e8-9b87-1930c10dc24e.png)
I installed the macvim with `brew cask install macvim` and vim with `brew install vim --with-override-system-vi --with-lua`. I compiled YCM after comment the conda path in the bash_profile as following.
![image](https://user-images.githubusercontent.com/15342165/42452398-73eb4306-83bc-11e8-8aca-61efc463e6b9.png)
And I also put `let g:ycm_server_python_interpreter='/usr/bin/python'` in my .vimrc. Then vim in CLI works fine as following, checked with `:YcmDebugInfo`.
![image](https://user-images.githubusercontent.com/15342165/42452151-d85932f4-83bb-11e8-81d6-d9271f8f7445.png)
But the macvim still cannot work as the first figure. Despite macvim can work after comment conda in bash_profile. However, I still need conda to work.
How to solve this problem of the disagreement with macvim and vim, in terms of YCM? Thans a lot!
My full configuration of vim can be found at [https://znculee.github.io/blogs/tools/vim#configuration](https://znculee.github.io/blogs/tools/vim#configuration).

**Comment by znculee** [comment]
My full configuration of vim can be found at [https://znculee.github.io/blogs/tools/vim#configuration](https://znculee.github.io/blogs/tools/vim#configuration).

**Comment by eirnym** [comment]
is your MacVim built with Python 3.7? if yes, ViM (and MacVim as well) doesn't really well support it.

**Comment by eirnym** [comment]
YCM uses python interpreter from PATH by default, enabling importing and checking from virtualenv. 

Probably you should address this issue to YCM repo itself rather than to MacVim repo.

**Comment by znculee** [comment]
@eirnym Thank you for your reply. My macvim is installed with brew cask, which is a pre-compiled version. I open this issue in macvim repo because my vim in CLI, installed with brew, can work well in the same situation.

**Comment by znculee** [comment]
Hi Arseny,

Thanks for your reply! My MacVim is installed with brew cask, which is probably a pre-complied version, packed in a dmg file, therefore, I am not sure whether it is built with Python 3.7.

I have solve this issue in both  previous versions of MacVim and Vim of CLI, with `let g:ycm_server_python_interpreter='/usr/bin/python’`. But in the last MacVim version, this problem cannot be solved as I issued in GitHub.

Best,
Xintong

**Comment by eirnym** [comment]
Does MacVim built with dynamic python2? If yes, could you directly specify which Python2 library to load?

**Comment by znculee** [comment]
@eirnym The MacVim is installed by brew cask, which is in a dmg file. That means I have not built it on my own. However, I found there is the same error when I use fish instead of bash. So maybe this is issue may belong to YCM. Thanks anyway.

**Comment by znculee** [comment]
@eirnym I fixed this problem by add `let $PATH='$HOME/.cargo/bin:/usr/bin:/usr/local/bin:/bin:/usr/sbin:/sbin'` in my `.gvimrc`.
