### ISSUE TITLE
Vim icon for macvim-dev organization

### ISSUE THREAD

**Issue by jasonlong** [macvim-dev/macvim#71]
In case you'd like to update the macvim-dev org to use the new icon, here's a PNG that you could use.

![vim](https://cloud.githubusercontent.com/assets/6104/9444616/ceed85aa-4a55-11e5-8ee3-858df6addfca.png)

**Comment by jpetrie** [comment]
:+1:

**Comment by eirnym** [comment]
:+1:

**Comment by douglasdrumond** [comment]
:+1:
