### ISSUE TITLE
`set nomacligatures` leaves ligatures enabled

### ISSUE THREAD

**Issue by zerowidth** [macvim-dev/macvim#711]
On the current snapshot 149, setting `nomacligatures` has no effect on ligature rendering, and I see ligatures whether the option is enabled or disabled. I check with the non-coretext renderer with the same effect.

Current `guifont` is `Fira Code Retina:h14`, which supports ligatures (but which I want to disable).

**Comment by ichizok** [comment]
This was fixed by #713 .
