### ISSUE TITLE
A very recent commit broke building on both Tiger and Leopard

### ISSUE THREAD

**Issue by chdiza** [macvim-dev/macvim#72]
One of the recent commits (I wouldn't be surprised if it was ligature-related) broke builds on both Tiger and Leopard.

[Here](https://gist.github.com/9495284851016fe0b73c) is a gist of the Tiger build error.

[Here](https://gist.github.com/aa7e7a39dac957748433) is a gist of the Leopard build error.

I'm hoping that this is one of those cases where there were just a couple of overlooked IFDEFS.

**Comment by chdiza** [comment]
I don't know exactly which commit (or commits) it was.  Bisecting takes a long time, since this is on a Powerbook G4, and I have to do it for Tiger and Leopard.  I'm away from that machine for a while.

**Comment by jpetrie** [comment]
The Leopard build issue is due to the for loop in https://github.com/macvim-dev/macvim/commit/6824350c203116e5505e3bc6b1015a6fcd0024eb not being written in the C89 style (index declared outside the body). PR #70 addresses this.

The Tiger build failure comes from https://github.com/macvim-dev/macvim/commit/9e2a5437a01f7ecce816af3c188216c8124c3e55 (transparent window support), which pulled in the "CGSInternal" source files, which have headers that use `AVAILABLE_MAC_OS_X_VERSION_10_5_AND_LATER`, which is not defined in the Tiger SDK (Tiger is 10.4).

That entire feature will need to be `#ifdef`-guarded with checks like `MAC_OS_X_VERSION_MIN_REQUIRED >= MAC_OS_X_VERSION_10_5` in order to support compilation on older SDKs.

**Comment by rhendric** [comment]
Thanks for the analysis, @jpetrie! I'll take a shot at a fix.

**Comment by rhendric** [comment]
@chdiza, if you would like to test [rhendric/macvim/master](/rhendric/macvim/master), it should contain fixes for both issues.

**Comment by chdiza** [comment]
I'll test that as soon as I'm in the same room as my G4.

**Comment by chdiza** [comment]
No luck yet on Tiger, but the failure point is different now.  It gets to the end building the plain Vim portion, and then stops. Here is the new output:

```
gcc   -L/usr/local/lib  -o Vim objects/buffer.o objects/blowfish.o objects/charset.o objects/crypt.o objects/crypt_zip.o objects/diff.o objects/digraph.o objects/edit.o objects/eval.o objects/ex_cmds.o objects/ex_cmds2.o objects/ex_docmd.o objects/ex_eval.o objects/ex_getln.o objects/fileio.o objects/fold.o objects/getchar.o objects/hardcopy.o objects/hashtab.o  objects/if_cscope.o objects/if_xcmdsrv.o objects/mark.o objects/memline.o objects/menu.o objects/message.o objects/misc1.o objects/misc2.o objects/move.o objects/mbyte.o objects/normal.o objects/ops.o objects/option.o objects/os_unix.o objects/pathdef.o objects/popupmnu.o objects/quickfix.o objects/regexp.o objects/screen.o objects/search.o objects/sha256.o objects/spell.o objects/syntax.o  objects/tag.o objects/term.o objects/ui.o objects/undo.o objects/version.o objects/window.o objects/gui.o objects/gui_beval.o objects/pty.o objects/gui_macvim.o objects/MMBackend.o objects/MacVim.o        objects/os_macosx.o objects/os_mac_conv.o    objects/main.o objects/memfile.o -framework Cocoa -framework Carbon       -lm -lncurses  -liconv -framework Cocoa          
/usr/libexec/gcc/powerpc-apple-darwin8/4.0.1/ld: Undefined symbols:
_gui_macvim_set_blur
collect2: ld returned 1 exit status
make[1]: *** [Vim] Error 1
make: *** [first] Error 2
```

**Comment by chdiza** [comment]
However, the build now completes on Leopard.

I'll play around and make sure it seems to be working OK.

**Comment by rhendric** [comment]
Hm. At first glance I don't see how that could happen—unless maybe you didn't `make clean` first?

**Comment by chdiza** [comment]
@rhendric But I did it off a fresh clone of your repo using the master branch as you indicated.

**Comment by rhendric** [comment]
Interesting. I'll take another look.

**Comment by chdiza** [comment]
Here's a possibly informative observation: if I comment out line 1775 of `vim.h`, to ensure that `BLUR_TRANSPARENCY` is not defined, then I don't get the error I reported above.  However, for some reason the xcodebuild phase of things doesn't auto-start.

Perhaps the conditional test in line 1754 is somehow faulty?

**Comment by chdiza** [comment]
I should've mentioned, the line numbers refer to the `vim.h` in rhendric/macvim.

**Comment by eirnym** [comment]
I always do `#define SOME_THING 1` instead of simple `#define SOME_THING`

**Comment by chdiza** [comment]
Hmmm.  It appears that on Tiger, there is no such thing as `MAC_OS_X_VERSION_10_5` defined in AvailiabilityMacros.

I don't know C or anything, but I'm going to test replacing `MAC_OS_X_VERSION_10_5` with `1050` in line 1754 and see what happens.

**Comment by chdiza** [comment]
@rhendric Yep, that was it.  Just replace, in line 1754 of `vim.h`, the `MAC_OS_X_VERSION_10_5` with `1050`.

**Comment by eirnym** [comment]
better is to check than define

    /* Needs to be before option.h, which uses BLUR_TRANSPARENCY */    
    #ifdef MAC_OS_X_VERSION_10_5    
    #if defined(FEAT_TRANSPARENCY) && (MAC_OS_X_VERSION_MIN_REQUIRED >= MAC_OS_X_VERSION_10_5)
    # define BLUR_TRANSPARENCY
    #endif
    #endif

**Comment by rhendric** [comment]
Thanks @chdiza! Added to the PR and my master branch. (I'm still ignorant as to how that ends up being a linker error, but I'm no expert on C preprocessing either.)

**Comment by eirnym** [comment]
:+1:

**Comment by chdiza** [comment]
It works, thanks :)

**Comment by jpetrie** [comment]
Fixed by https://github.com/rhendric/macvim/commit/a02a24b75109936f1431c0133a5a26c5d4e4e58b.
