### ISSUE TITLE
:-tabf breaks scrollbar

### ISSUE THREAD

**Issue by kevinlawler** [macvim-dev/macvim#720]
version 8.1.235 (150)
macOS 10.13.6

repro:
open any file1 in a tab
open file2 using `:-tabf file2.txt<CR>`

expected:
file2 has up-to-date scrollbar for itself

actual:
file2 sees a frozen version of file1's scrollbar, regardless of movement inside the tab. persists until tab is changed via `gtgT`. presumably this is a bug

**Comment by eirnym** [comment]
@kevinlawler can't reproduce on 8.1.950 (155)
