### ISSUE TITLE
Screen error

### ISSUE THREAD

**Issue by lkebin** [macvim-dev/macvim#721]
I have extra monitor. When I start MacVim on the extra monitor, it looks like that:
![screen shot 2018-08-06 at 11 41 51 am](https://user-images.githubusercontent.com/1335935/43695966-52669c54-996e-11e8-92f3-e061fa331488.png)

If I drag the MacVim program window to resize it, the screen will be fine.
![macvim](https://user-images.githubusercontent.com/1335935/43696040-b1dde5d4-996e-11e8-9f76-248bcde702c9.gif)

**Comment by mikedupuis** [comment]
I can confirm that I'm seeing the same issue on a second monitor.

**Comment by lowderchris** [comment]
Running into the same issue (and resizing fix) on an external DisplayPort monitor. With the same monitor connected, when opening a macvim window on the laptop display, the window renders as expected.

**Comment by fortman** [comment]
+1 , same issue here.  Resizing window with mouse makes the window immediately snap to correct size

**Comment by JTMosaic** [comment]
+1, same issue.

**Comment by tachijuan** [comment]
+1 here. If you open on the main monitor, it works just fine. If you open it on the second (non-main) monitor you get the behavior described

**Comment by dctucker** [comment]
+1 Confirmed. This is particularly troubling since I want MacVim to always launch on my rightmost monitor.

**Comment by ahmedelz** [comment]
+1

**Comment by muddysteel** [comment]
+1 same issue.

**Comment by choonggg** [comment]
+1

**Comment by eirnym** [comment]
The same is happening when you open a narrow window, for example, 69x42, and then open a window with local setting set width (or height) bigger than it was. Any way to force redrwaw works, including hiding MacVim or switching an app

Build 149 didn't had this issue.

**Comment by fericit-bostan** [comment]
+1

**Comment by rbm-aalsaleh** [comment]
+1

**Comment by btlewan** [comment]
+1

**Comment by jason0** [comment]
Hello, 

I switched back to version 8.1-149_1 (brew) but had the same problem.  switching further back to version 8.1-147 resolved my problem for the moment.

--jason

**Comment by ichizok** [comment]
This problem is due to https://github.com/macvim-dev/macvim/commit/378032d85e8cbb75d02d58c77cdc530dfd7b418a (#708). And this guioptions-k seems not to work (in my environment).
I think should revert it once.

**Comment by symonty** [comment]
+1

**Comment by jdandrews** [comment]
+1; reverted to snapshot-149 (8.1.72 (149)) which does not manifest the problem.

**Comment by davidozog** [comment]
+1

**Comment by mrallen1** [comment]
+1

**Comment by ZGainsforth** [comment]
+1

**Comment by ychin** [comment]
I submitted a PR #727 to revert the change that introduced this bug. If someone can grab it and build locally to test it out that would be appreciated. I'm not at a place to be able to test external monitors right now.

**Comment by dctucker** [comment]
Building ychin's branch solved the problem for me. Can anyone else confirm?

**Comment by ychin** [comment]
> The same is happening when you open a narrow window, for example, 69x42, and then open a window with local setting set width (or height) bigger than it was. Any way to force redrwaw works, including hiding MacVim or switching an app

@eirnym Can you explain a little more in how your repro case worked? What commands are you running?

**Comment by eirnym** [comment]
1) Open a window with a random file, e.g. `~/.vim/vimrc` and set some small width, like 20, next time it should open a _window_ with the same width, you can check it by pressing `Cmd-N`
2) set for some filetype specific width to use, e.g. for Python files (it doesn't matter)
3) open file of this type, with `$ vim ~/example.py` or with `:e ~/example.py`

Notes:
if you don't open a file but an empty buffer on step 1, MacVim might won't save and trick won't work from command line (but will with `:e` command)

```vim
  if has('gui_running')
        setlocal columns=85
    endif
```

**Comment by ychin** [comment]
@eirnym I couldn't reproduce the issue on my laptop. Did you only reproduce this using your method on an external monitor? If so I just need to hunt down an external monitor to connect to so I can debug it.

**Comment by eirnym** [comment]
@ychin I have no external monitor 

my vimrc with I able to reproduce it (build 150)

```vim
fun! PythonSetup()
    setlocal ts=4 sts=4 sw=4 nu
    setlocal colorcolumn=79
    if has('gui_running')
        setlocal columns=85
    endif
endfun

autocmd FileType python call PythonSetup()
```

**Comment by ychin** [comment]
@eirnym Oh good to know. But also sad that that means I will have to hunt down an external monitor to test still.

Also check out #557 which I suspect could be related. You can try the suggestions from this comment (https://github.com/macvim-dev/macvim/issues/557#issuecomment-339556291) to see if it helps by setting `MMUseCGLayerAlways` to true. It causes other issues such as scrolling performance but it's nice to know if it's related at least.

**Comment by eirnym** [comment]
@ychin please, look into #732, it could be the source of many resizing issues
