### ISSUE TITLE
"zoom" option in window menu stopped working with snapshot-150

### ISSUE THREAD

**Issue by Viqsi** [macvim-dev/macvim#724]
The "zoom" window option in MacVim (which normally vertically maximizes the window) seems to have been broken in snapshot 150. If I resize Vim windows using any other method, all is well and 'set lines' and 'set columns' are updated accordingly. If I use the Zoom command in the Window menu, however (either by selecting it from the menu, using a keyboard shortcut, or double-clicking on the title bar), the window does not appear to resize, and from then on out MacVim's display is strangely corrupted, as though it thinks it's changed sizes but it hasn't. (I have been unable to get a consistent enough failure mode to narrow it down precisely).

Was able to reproduce this issue with `gvim -N -u NONE`, so I don't believe it's a settings issue on my part. I am running macOS High Sierra 10.13.6.

EDIT: Also experiencing this issue with another system running macOS 10.11.6.

**Comment by eirnym** [comment]
I think this issue is strongly related (if not duplicated by) #721

**Comment by Viqsi** [comment]
I didn't consider #721 because that seems to involve multiple displays, and I only ever use the one.

**Comment by eirnym** [comment]
Bug works on one display as well. You can read other comments as well (beside +1 there's a lot of other details including workarounds.
