### ISSUE TITLE
Error on launch

### ISSUE THREAD

**Issue by osenvosem** [macvim-dev/macvim#740]
MacOS 10.13.6, MacVim 8.1.280 (151)
Installed with brew or downloaded binary, no difference.

Getting this at the app launch.

![screen shot 2018-08-29 at 13 40 35](https://user-images.githubusercontent.com/6762673/44782810-27bb6400-ab91-11e8-9c31-730f6f8b58e8.png)

**Comment by osenvosem** [comment]
@eirnym I also like it )

Launching with `mvim -u NONE -N` gives no errors. Launching vim in terminal also works without errors (the vim binary is from MacVim, installed using brew with `--with-override-system-vim`).

**Comment by osenvosem** [comment]
I usually launch macvim from terminal with the `macvim` command.
Here is my .vimrc
[vimrc.txt](https://github.com/macvim-dev/macvim/files/2332074/vimrc.txt)

**Comment by eirnym** [comment]
PS: I have similar script for restoring my settings on a new machine.

**Comment by eirnym** [comment]
@osenvosem Does the problem persist in your environment?

**Comment by osenvosem** [comment]
@eirnym yes, it still persists.

**Comment by eirnym** [comment]
Could you check if there's some changes or some plugins weren't updated? Could you try to clean up your ~/.vim directory and create it from scratch?

**Comment by osenvosem** [comment]
I completely removed the .vim folder and reinstalled everything from scratch and it seems that it works well now. Thank you.
