### ISSUE TITLE
MacVim can't run Go debugger Delve (i.e. VimShell)

### ISSUE THREAD

**Issue by arrayofchar** [macvim-dev/macvim#743]
Go's debugger Delve depends on the VimShell to run, so apparently, MacVim can't run VimShell.

Here is the error when I try to run `:DlvDebug`

`Error detected while processing function delve#dlvDebug[3]..delve#runCommand:`
`line   40:`
`E117: Unknown function: vimshell#util#substitute_path_separator`
`E116: Invalid arguments for function <SNR>22_call_vimshell`
`line   51:`
`E117: Unknown function: vimshell#interactive#send_region`
`Error detected while processing function delve#dlvDebug[3]..delve#runCommand[52]..<SNR>22_call_vimshell:`
`line   20:`
`E117: Unknown function: vimshell#init#_start`

**Comment by eirnym** [comment]
@arrayofchar, thank you for your issue.

I have a few questions about it.

1. Does it still an issue for you with recent changes?
2. Does it reproducible in recent terminal version of MacVim? 
2. Does it reproducible in recent version of Vim? 
3. Which Delve and VimShell plugins source do you mean? 
4. Does VimShell claim that it works in Vim/MacVim?

I found `sebdah/vim-delve` references to `Shougo/vimshell.vim` which is discontinued. Please, correct me if I'm wrong.

**Comment by arrayofchar** [comment]
Sorry, I've not used MacVim for awhile. I probably should put a version number in there originally. My bad. Maybe just close this bug if you can't reproduce it? I think I just used the master branch at the time for both repositories.

**Comment by eirnym** [comment]
I see. I'd not be using discontinued projects if I have choice. 

As per [Delve editor integrations page](https://github.com/go-delve/delve/blob/master/Documentation/EditorIntegration.md) I'd select [vim-go](https://github.com/fatih/vim-go) which has active development when I'd use Vim (even in terminal).

MacVim is only the GUI part for Vim, it's not a fully independent project.

**Comment by ychin** [comment]
I'm closing it if @arrayofchar is not actively using MacVim as this seems like a very specific combination of plugins causing issues.
