### ISSUE TITLE
Any plan to support `Dark Mode` in Mojave?

### ISSUE THREAD

**Issue by J-Liu** [macvim-dev/macvim#747]
Mojave will be released next Monday, and the `Dark Mode` looks pretty cool, the SDK has been released and detail is here [https://developer.apple.com/documentation/appkit/supporting_dark_mode_in_your_interface](url)

Will you please support `Dark Mode` next release?

**Comment by eirnym** [comment]
Do you mean a dark theme for toolbar?

**Comment by J-Liu** [comment]
@eirnym 
I mean the window manager, that is the title bar and scroll bar.
![wechatimg5661](https://user-images.githubusercontent.com/1065112/45684587-5cf81800-bb79-11e8-9e77-7cb5bd34e05f.jpeg)

**Comment by J-Liu** [comment]
Just build MacVim using Xcode 10 on Mojave, will support dark mode.
Looking for bottle binary.

**Comment by dedwarmo** [comment]
"Using binary release is highly recommended."
"Building (not recommended way)"

https://github.com/macvim-dev/macvim/wiki/Building
