### ISSUE TITLE
Error building MacVim on Mojave with Xcode 9.3

### ISSUE THREAD

**Issue by mario-grgic** [macvim-dev/macvim#754]
I am attempting to build MacVim from git clone on macOS 10.14 Mojave with Xcode 9.3. I am configuring MacVim as follows:

````
./configure --with-features=huge --enable-rubyinterp --enable-pythoninterp --enable-python3interp --enable-perlinterp --enable-cscope  --enable-terminal
````

and get an error:

```
if_perl.xs:57:10: fatal error: 'EXTERN.h' file not found
#include <EXTERN.h>
         ^~~~~~~~~~
1 error generated.
make: *** [objects/if_perl.o] Error 1
make: *** Waiting for unfinished jobs....
```

However, ```open -h EXTERN.h``` does find ```EXTERN.h``` in ```/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/simd```

Building with Xcode 10 works, but the binary produced has known issues with Core Text renderer.

**Comment by chdiza** [comment]
I thought Mojave requires at least Xcode 10.

**Comment by mario-grgic** [comment]
> I thought Mojave requires at least Xcode 10.

Apparently, at least Xcode 9.4.1 or higher. So my Xcode 9.3 is not supported.
