### ISSUE TITLE
Pre-built packages?

### ISSUE THREAD

**Issue by FGasper** [macvim-dev/macvim#76]
Hello,

Where did the pre-built packages for this project go?

MacPorts just updated my ncurses, which broke my own MacVim. I’d like to recompile, but I ran into issue #75. I want to download a pre-built package, but now that the Google Code page redirects here, I don’t see those anymore … ?

**Comment by RichardDooling** [comment]
https://github.com/macvim-dev/macvim/releases

**Comment by steakknife** [comment]
There doesn't seem to be a prebuilt app for [snapshot 78](https://github.com/macvim-dev/macvim/releases/tag/snapshot-78).

**Comment by chdiza** [comment]
> There doesn't seem to be a prebuilt app for snapshot 78.

That's probably because 78 contained a regression and was immediately reverted.

**Comment by splhack** [comment]
I'm now trying to build binary on Travis CI, and to release the binary from GitHub Releases.
https://github.com/macvim-dev/macvim/releases/tag/snapshot-test (not finished yet)

**Comment by splhack** [comment]
Test build settings for pre-built package https://github.com/macvim-dev/macvim/blob/test/release/.travis.yml

**Comment by splhack** [comment]
@douglasdrumond is there any document about prebuilt app configure options?

**Comment by splhack** [comment]
- https://github.com/macvim-dev/macvim/wiki/Deployment
- https://github.com/macvim-dev/macvim/releases
