### ISSUE TITLE
Add an event for macOS appearance change 

### ISSUE THREAD

**Issue by L-TChen** [macvim-dev/macvim#766]
As macOS 10.14 supports dark mode, it would be very useful to have an event for the appearance change and also a variable for the current appearance. Some snippet code for detecting the current appearance can be found [here](https://stackoverflow.com/questions/51672124/how-can-it-be-detected-dark-mode-on-macos-10-14).  The official document suggests 
> Apps can also use key-value observing (KVO) to monitor changes to the effectiveAppearance property of a view or window and make custom changes. [(see here)](https://developer.apple.com/documentation/appkit/supporting_dark_mode_in_your_interface)

I wrote a simple [script](https://github.com/L-TChen/vim-dark-mode-switcher) to change the appearance by running some AppleScript and set the option `background` accordingly. It would be ideal to have the change of option fired whenever the system changes its appearance.

Or, please suggest where I can put the code. I am not familiar with Obj-C, though.

**Comment by L-TChen** [comment]
While trying to implement this myself I realise this feature should be added to Vim itself instead of MacVim, because even in a terminal emulator Vim may use this change of appearance to change background and colour theme as well. 

Hence, I am closing this issue now.

**Comment by ychin** [comment]
Hmm, I was thinking about ways to add this in MacVim and I'm not sure if Vim would add something so platform specific like this. If you add an issue to Vim please cross-reference it here.

**Comment by eirnym** [comment]
@L-TChen 
I'm not sure about adding this feature to the Vim core. In `Terminal.app` you have independent settings, even they're defaults.

**Comment by L-TChen** [comment]
Hi, thanks for your comments. 

The basic idea is to have (optionally) a global variable, say, `g:os_dark_mode` and an event emitted when the OS switch its appearance, so the users can hook a vim function to act accordingly. It should not touch `background` by default.

It was platform specific until the dark mode support is added in Windows 10. I am not sure about linux, although it appears that GNOME has a similar setting. 

In some terminal emulators like iTerm2, there is a way to change profile theme based on system-wide setting (https://gitlab.com/gnachman/iterm2/issues/6764). 

So, in my opinion, it makes sense to add this functionality to Vim instead of MacVim.

**Comment by L-TChen** [comment]
> @L-TChen , thank you for the improvement.
> I'm not sure about adding this feature to the Vim core. In `Terminal.app` you have independent settings, even they're defaults.

Aha, I see your point here. Right, an app may have its own appearance setting different than the global setting. So, getting the setting from the global setting (e.g., via defaults) may give an incorrect behaviour.

The core Vim should get the appearance setting from the GUI frontend or the terminal emulator where Vim is running. So, the MacVim frontend does need to add this directly to send a command to the core Vi. Does that make sense?

**Comment by eirnym** [comment]
This event by nature goes from GUI subsystem to _optionally_ trigger the background check.  The processing of this event (setting `background` option to dark or light, I assume, may be some additional triggers to change window decorations in GUI) could be in core, but triggered by GUI.

I would be personally fine if a GUI event will trigger the change only by my _explicit_ setting if I want to do it, as I and most people I know prefer personally exact themes and colours for specific programs despite the fact they could use light or dark GUI in system.

**Comment by L-TChen** [comment]
Yes. That’s exactly what I am implementing now. 

I am working half way through it. I will open a draft PR later.
