### ISSUE TITLE
Macvim will not start after Sierra updated with latest security update from Apple

### ISSUE THREAD

**Issue by wfiveash** [macvim-dev/macvim#769]
After I updated my Mini running Sierra (there are reasons I have not updated the OS on that system) with the latest Security update from Apple, the homebrew version of macvim (and gvim, etc…) became unable to run giving this error:

$ gvim
dyld: Library not loaded: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/libruby.2.0.0.dylib
Referenced from: /usr/local/Cellar/macvim/8.1-151/MacVim.app/Contents/bin/…/MacOS/Vim
Reason: image not found
Abort

I have checked /System/Library/Frameworks/Ruby.framework/Versions and there is now a 2.3 folder which contains the ruby binary unlike the 2.0 folder. Looking at a Time Machine backup of the Versions folder I see that 2.3 was introduced by the security update.

As an aside, there is also a Current symlink in Versions that points to the most recent version of Ruby, so I’m wondering if it is possible to compile macvim to use that symlink instead of specifying the version of ruby to use?

**Comment by LukasRypl** [comment]
I had the same problem. I found the following after running `brew reinstall --build-from-source macvim`: https://github.com/Homebrew/homebrew-core/issues/33656 and it seems that the option `--env=std` fixes this. 

I am not sure if  all the options are required, but the following worked:
`brew reinstall --build-from-source --env=std -v macvim`

**Comment by ychin** [comment]
@wfiveash Did that resolve your issue?

**Comment by wfiveash** [comment]
I resolved it by updating macOS from Sierra to Mojave.  I would say that this may still be an issue for others running Sierra but I'm happy to close this.

**Comment by ychin** [comment]
Hmm actually do you mind doing `:version` for me? You should see `ruby/dyn` which should mean ruby should only be lazily loaded in instead of at launch time, so I'm curious if you have that setting in `:version`.

**Comment by wfiveash** [comment]
I just noticed that on my Mini now running Mojave that macvim was not updating the display properly.  I realized that I had only installed the CLI version of macvim, not the cask.  So I just did "brew cask install macvim" which worked and now macvim is working normally.  Here is the output of :version on the cask version of macvim:

:version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Aug 14 2018 05:28:49)
macOS version
Included patches: 1-280
Compiled by travis@Traviss-Mac-1044.local
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl               +farsi             +mouse_sgr         -tag_any_white
+arabic            +file_in_path      -mouse_sysmouse    -tcl
+autocmd           +find_in_path      +mouse_urxvt       +termguicolors
+autochdir         +float             +mouse_xterm       +terminal
-autoservername    +folding           +multi_byte        +terminfo
+balloon_eval      -footer            +multi_lang        +termresponse
+balloon_eval_term +fork()            -mzscheme          +textobjects
+browse            +fullscreen        +netbeans_intg     +timers
++builtin_terms    -gettext           +num64             +title
+byte_offset       -hangul_input      +odbeditor         +toolbar
+channel           +iconv             +packages          +transparency
+cindent           +insert_expand     +path_extra        +user_commands
+clientserver      +job               +perl/dyn          +vartabs
+clipboard         +jumplist          +persistent_undo   +vertsplit
+cmdline_compl     +keymap            +postscript        +virtualedit
+cmdline_hist      +lambda            +printer           +visual
+cmdline_info      +langmap           +profile           +visualextra
+comments          +libcall           +python/dyn        +viminfo
+conceal           +linebreak         +python3/dyn       +vreplace
+cryptv            +lispindent        +quickfix          +wildignore
+cscope            +listcmds          +reltime           +wildmenu
+cursorbind        +localmap          +rightleft         +windows
+cursorshape       +lua/dyn           +ruby/dyn          +writebackup
+dialog_con_gui    +menu              +scrollbind        -X11
+diff              +mksession         +signs             -xfontset
+digraphs          +modify_fname      +smartindent       +xim
+dnd               +mouse             +startuptime       -xpm
-ebcdic            +mouseshape        +statusline        -xsmp
+emacs_tags        +mouse_dec         -sun_workshop      -xterm_clipboard
+eval              -mouse_gpm         +syntax            -xterm_save
+ex_extra          -mouse_jsbterm     +tag_binary
+extra_search      +mouse_netterm     +tag_old_static
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-u
nknown-pragmas -pipe  -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FO
RTIFY_SOURCE=1
Linking: clang   -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml
/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib -L. -fstack-prot
ector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib
 -L/usr/local/opt/readline/lib  -L/usr/local/lib -o Vim -framework Cocoa -framew
ork Carbon       -lm  -lncurses -liconv -framework AppKit   -fstack-protector  -
L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE

**Comment by ychin** [comment]
Oh ok. If that has resolved it please close the issue. If you run into issues like this you can always re-open.
