### ISSUE TITLE
macmenu does not detect Window.Show Next Tab

### ISSUE THREAD

**Issue by segeljakt** [macvim-dev/macvim#770]
I'd like to unmap the `Window.Show Next Tab` key, but it does not appear to work.
```
macmenu Window.Show\ Next\ Tab	    key=<Nop>
```
results in
```
E334: Menu not found: Window.Show\ Next\ Tab
```

**Comment by eirnym** [comment]
I see menu title "Window.Select Next Tab", not "Show" in build 151. Could it be a solution in your case?

**Comment by ychin** [comment]
`macmenu Window.Select\ Next\ Tab key=<Nop>` seems to work for me.

You need to make sure to put this in your `gvimrc` for it to work. See `:h macmenu` for more info:

```
 						*:macm* *:macmenu*
:macm[enu] {menu} {key}={arg} ...
			Set Mac specific properties for {menu}.  The
			properties that can be set are:
			    action	the action this menu sends
			    alt		"yes" if alternate of previous menu
			    key		the key equivalent of this menu
			This command must be used in a startup file, for
			example in "~/.gvimrc".  It has no effect otherwise.
```

**Comment by segeljakt** [comment]
Thanks for the comments, it seems like my mac for some reason both has a `Show Next Tab` and a `Select Next Tab` button, but the former only appears occasionally. It's no big issue.

![img](https://imgur.com/a/Bazukkz)

**Comment by ychin** [comment]
You may want to make sure to restart MacVim to make sure it doesn't have any stale settings, and also double check that you are not erroneously adding the "Show Next Tab" menu there. Otherwise I'm closing this issue since it seems resolved.
