### ISSUE TITLE
MacVim deletes searcch string of other apps even with MMShareFindPboard set to false

### ISSUE THREAD

**Issue by chdiza** [macvim-dev/macvim#773]
I have `MMShareFindPboard` set to `false` so that MacVim's search string doesn't interfere with that of other Cocoa apps.  (There's nothing worse than e.g., hitting Cmd-F in Safari only to find the little search box pre-populated with something like `\(foo\|bar\)\+`.)

I've noticed however that MacVim will *clear* another app's search string.

Reproduce: Open Safari, go to some webpage, and search (Cmd-F) for some string that is present on the page.  Maybe hit Cmd-G to go to the next instance.  Do not close the "find bar" in Safari.  Then Cmd-Tab to an open MacVim document (or just open one afresh) and hit `/`; enter a search string and hit <CR>.  Then Cmd-Tab back to Safari and observe that, while the find bar is still open and occurrences of your search string are still highlighted, your search string is gone, and Cmd-G no longer works because it doesn't know what string it should be looking for the next occurrence of.

**Comment by eirnym** [comment]
additionally, with some plugins like better-whitespace, Safari's search string will be last search to clear whitespaces.

**Comment by ychin** [comment]
Can confirm this happens. Will look into it.
