### ISSUE TITLE
Tabs do not pick dark theme on Mojave

### ISSUE THREAD

**Issue by pointlessone** [macvim-dev/macvim#775]
Tabs do not fully pick up dark theme in Mojave. Only text changes color. This results in a really low-contrast look. It wouldn't be much issue if it didn't change text color but currently it make it hard to use MacVim tabs with dark theme.

This is most probably related to #544.

<img width="835" alt="screen shot 2018-11-10 at 5 06 41 pm" src="https://user-images.githubusercontent.com/7405/48302865-05d44b00-e50b-11e8-8fa4-665b0dfe9f4b.png">

**Comment by pointlessone** [comment]
I use Homebrew binary.

I know about #751. I have Core Text Renderer disabled. It works (doesn't flicker) apart from minor space width issues on otherwise blank lines.

**Comment by bhargavshivkumar** [comment]
Is there a work around for this until #751 is resolved?

**Comment by ychin** [comment]
@bhargavshivkumar You could do one of the following:

1. Use the snapshot version in https://github.com/macvim-dev/macvim/releases (they are all built against High Sierra instead of Mojave for now).
1. Build MacVim using Xcode 9 yourself. I don't know if Homebrew provides a method to do that.

**Comment by ychin** [comment]
@bhargavshivkumar Yes I meant installing the prebuilt dmg file from Github releases (we just call them snapshots). The latest one (151) should be fine and is built against High Sierra.

I plan to merge in all Mojave support soon so Homebrew builds won't stay broken. There should be a corresponding snapshot-152 release as well and it would be built against Mojave.
