### ISSUE TITLE
Use the translations

### ISSUE THREAD

**Issue by scootergrisen** [macvim-dev/macvim#776]
I tested macvim 8.1.280 a bit to see how well the translations works.
It seems the translation for vim itself is not used.
The gVim menu seems to be disabled on purpose in the vimrc file because of only partial translation of the menu.
I would think there was a common translation in macOS for applications to reuse common strings like "About ...", "Preferences", "Quit ...", etc. but i dont know.
If there is then i suggest using it and enabling the translations (remove the set langmenu=none in the vimrc file)

**Comment by chdiza** [comment]
Translations have been intentionally disabled on MacVim for years (and maybe even never have been enabled).  There is (or at least was) no way to reliably get it to work.  See `:h macvim-todo`.

**Comment by scootergrisen** [comment]
Is there a problem using the po/mo files?

**Comment by chdiza** [comment]
I don't know what the problem was (is), I'm just relaying that there was (is) one.  And it's been so since (if I recall correctly) the beginning of MacVim in 2007.

My guess, however, is that the macOS way of localizing menus (.lproj) simply doesn't mix with MacVim (or Vim) `menu.vim`.

**Comment by scootergrisen** [comment]
Hopefully someone that knows more about it reads this and knows what to do.
I have translated Vim to danish so of course i would like my translation work to get to the users.

**Comment by ychin** [comment]
I don't know the full context behind this but looking around seems like it's mostly due to the fact that some of the default menus in MacVim don't exist in Vim and therefore isn't translated, and also the same for the ones defined in the nib as well. I'm not sure if there's more to it than that. Pinging @splhack to see if he knows.

**Comment by eirnym** [comment]
Also there's a lot of MacVim-specific part of documentation which is also was never translated as well. Menu translation is the smallest part of work required to fully complete this task

**Comment by ychin** [comment]
Just an update, per #991, Vim's own translations are now used. But menus are still using the English version only.

**Comment by ychin** [comment]
This is now closed and MacVim has translated menus. Only a few items are not translated at the moment, and please use #1102 to discuss adding remaining translations for the remaining items or other parts of the UI.
