### ISSUE TITLE
Can I build Macvim with RVM Ruby instead of System Ruby?

### ISSUE THREAD

**Issue by markwu** [macvim-dev/macvim#779]
Here comes with my system versions:

My system is  MacOS `10.14.1`
Homebrew version is `1.8.2-96-g4021aa8`
RVM version is `1.29.4`
RVM ruby is `2.5.3`
System Ruby is `2.3.7`
I use the formula here https://github.com/macvim-dev/homebrew-macvim to build Macvim.

I want to build macvim with my RVM ruby, but always get system ruby installed.
`:ruby print RUBY_VERSION`
I always get 2.3.7.

Does there any way can let me build macvim with RVM ruby? Thanks!

**Comment by eirnym** [comment]
Macvim from GitHub is compiled with `+ruby/dyn` configure option, thus you can `set rubydll=...` to use Ruby version you need.

**Comment by markwu** [comment]
I saw vim patch 8.0.0163 http://download.openpkg.org/components/cache/vim/8.0.0163 fix it, but it's in compile time, not in runtime. So I still need a way to build macvim against with my RVM ruby.

**Comment by eirnym** [comment]
Patch `8.0.0163` is already in MacVim. It seems, you need to open an issue with ViM itself as it looks like it needs to be fixed there.

**Comment by markwu** [comment]
I think the problem is Macvim's build formula, maybe need  a way to specify the ruby version.

**Comment by eirnym** [comment]
Does it well vim (not MacVim) from homebrew to blame MacVim?

**Comment by markwu** [comment]
I did not blame MacVim, I did say `Macvim's build formula, maybe need a way to specify the ruby version`.

I try to add the following code to the brew formula, it can compiled against with rvm ruby. Currently, there is no way to get the rvm ruby version information from environment. It is brew formula's restrictions.

``` ruby
    ENV.append 'vi_cv_path_ruby', "/Users/mark/.rvm/rubies/ruby-2.5.3/bin/ruby"
```

But, with wrong dll path.

`:set rubydll`, it shows `rubydll=libruby.2.5.dylib`

After set the dll path again, 

`set rubydll=/Users/mark/.rvm/rubies/ruby-2.5.3/lib/libruby.2.5.dylib`

The command `:ruby print RUBY_VERSION` works, it shows `2.5.3`.

**Comment by eirnym** [comment]
I compare formula from macvim-dev/macvim-homebrew and [this one](https://github.com/Homebrew/homebrew-core/blob/master/Formula/macvim.rb) and see that the first is quite outdated. Could you try formula from the homebrew-core repo?

**Comment by markwu** [comment]
No luck, the homebrew-core one still compiled against with system ruby 2.3.7, instead of rvm ruby 2.5.3.

**Comment by markwu** [comment]
Okay. I just come out my personal formula for this purpose.

https://github.com/markwu/homebrew-personal/blob/master/Formula/macvim.rb

You can use the following command to install RVM version.

```
brew tap markwu/personal
brew install --HEAD --with-rvm-ruby=$MY_RUBY_HOME markwu/personal/macvim
```

It will add `rubydll` to default vimrc to make rvm ruby works. 

The drawback of this method is no way to reinstall macvim, you have to `brew uninstall`/`brew install` again.

**Comment by ychin** [comment]
You may want to file an issue with homebrew/homebrew-core to see if they could add this. Your argument doesn't have to be `--with-rvm-ruby` though right? It could just be any Ruby binaries, not necessarily from RVM.

**Comment by markwu** [comment]
It is for RVM only, because I can guess ruby dll's location from ruby command. 

My formula fork from https://github.com/macvim-dev/homebrew-macvim made by macvim-dev team, I suppose this formula is more accurate than homebrew one.

**Comment by eirnym** [comment]
I suppose most people will install MacVim with formula from homebrew core, rather than from macvim-dev.

**Comment by ychin** [comment]
I do think most people use the Homebrew-core one which is quite actively maintained by the Homebrew team but it leaves a very good question why we maintain a mostly inactive MacVim Homebrew Tap.

The custom Homebrew Tap was before my time. Wonder if @splhack has input to why we added that in addition to the Homebrew Core formula?

**Comment by markwu** [comment]
Ok, I think I found the problem, `homebrew` use the `superenv` environment to compile all Formulas, it cause homebrew lose all environment  information include your custom ruby path and a lot of stuffs ... :(

The only way to add it back is to pass these information as `option arguments`, or put them in your system environment with `HOMEBREW_*` prefix, or get them from `pkg-config` if exists. they will keep inside  building process.

So, I come out a new `--with-custom-ruby` for this purpose, it combine homebrew-core/macvim and also fix a `homebrew python3 dynamic dll link problem` come with MacVim default `vimrc`.

https://github.com/markwu/homebrew-personal/blob/master/Formula/macvim.rb

**Comment by eirnym** [comment]
does modification of `/etc/paths` helps you? This file doesn't accept any environment variables during path building, but it's quite helpful for me.

**Comment by markwu** [comment]
@eirnym Thanks, I never know this. I'll try it.

**Comment by eirnym** [comment]
@markwu Does suggested solutions works for you? 

You have been suggested to set:
* correct paths
* setting parameters within configure script
* setting `rubydll` in your `vimrc`

All these options are not MacVim-specific and can be done with the original version of `vim`.

**Comment by markwu** [comment]
None of them working for me, I have to pass the correct RVM ruby path through HOMEBREW_* system variables.

**Comment by eirnym** [comment]
Did it solve your issue?

**Comment by eirnym** [comment]
Homebrew has it's own MacVim formula anyway and MacVim authors have no ability to fix it. If you blame the formula itself, you should write a ticket there.

**Comment by markwu** [comment]
OMG, again? I did not blame anything, I just ask how to resolve the issue. Anyway, I resolve by my personal formula.

**Comment by markwu** [comment]
I am happy with my modified formula. The issue solved.

**Comment by ychin** [comment]
Glad to see it resolved for you @markwu. There were a lot of back-and-forth here, so I just want to make sure I understand: You forked from https://github.com/macvim-dev/homebrew-macvim and did the modifications? Have you tried the latest official homebrew-core formula?

If homebrew-core's version is not working due to its usage of `superenv` and whatnot, have you filed an issue with them? If there are other users like you it may be a good idea to see if there's a common way to fix it for everyone.

The Macvim's own homebrew formula is quite outdated and since homebrew-core maintains an official MacVim formula I am not too inclined in keeping it up to date (more options to get MacVim = more complexities and more chances of things not working). I'll leave a note on the README there to make it clear it's no longer actively maintained.
