### ISSUE TITLE
CTRL-6 stopped working after #742

### ISSUE THREAD

**Issue by pavoljuhas** [macvim-dev/macvim#785]
I have noticed that the `CTRL-6` command to change buffer stopped working in the GUI mode.
After bisecting the repo I found this started as of d9c3c62ea which was introduced by #742.

Can this be corrected?

I am using OS X High Sierra 10.13.6.  I understand that when running in a Terminal it is necessary to press `CTRL-SHIFT-6` to switch buffers.  `CTRL-6` however used to work in the GUI.

cc: @ichizok

**Comment by ychin** [comment]
I was just wondering recently when that bug got introduced recently so thanks for bisecting it. I'll look into it.
