### ISSUE TITLE
Wide Character problem / Space Between Character problem 

### ISSUE THREAD

**Issue by ApolloTang** [macvim-dev/macvim#790]
## macvim version:

```
$ brew info macvim
macvim: stable 8.1-151 (bottled), HEAD
GUI for vim, made for macOS
https://github.com/macvim-dev/macvim
/usr/local/Cellar/macvim/8.1-151 (2,173 files, 34.9MB) *
  Poured from bottle on 2018-11-01 at 21:00:51
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/macvim.rb
```
I am running macvim on:

```
macOS Mojave version 10.14.1
```

## Issue: 
I updated macvim to 8.1-151 after Mojave, space in between wide character is not display properly.
For example, when I am trying to display this ascii diagram:

<pre>
┌───────────────┐              ┌──────────────┐
│               │              │              │
│               │              │              │
│               │              │              │
│               ├─────────────▶│              │
│               │              │              │
│               │              │              │
│               │              │              │
│               │              │              │
└───────────────┘              │              │
                               └──────────────┘
</pre>

where '┌' ,'└', ','┘', '┐', ' ─', and '▶' are wide character; while '│', and  ' ' (space) are normal character.

The rendering in MacVim shows:

![screen shot 2018-11-26 at 1 16 42 am](https://user-images.githubusercontent.com/1150961/48996165-1561af80-f119-11e8-81c2-cdf49f66e200.png)

my font setting are:
```
guifont=Inconsolata:h14
guifontwide=
encoding=utf-8
ambiwidth=single

```
Inconsolata is **fix width font** the width of charecter should be identical, but the rendering clearly shown otherwise.

## Expected correct behaviour

I am expected this to be displayed like:
![screen shot 2018-11-26 at 1 18 53 am](https://user-images.githubusercontent.com/1150961/48996550-7dfd5c00-f11a-11e8-8144-c30fc877b725.png)

The above is running vim in terminal that using the same font but different size:  *Inconsolata Regular 17pt*. 

I have tried:
```
set guifontwide=Menlo Regular:h14
```
Because `help: guifontwide` seem to indicates that macvim will use font specified in guifontwide when displaying wide character.  But setting this does not help either.

I don't think this has to do with guifontwide, it is more likely due to the how macvim render the space between character and I believe that the rendering behaviour has changed since Mojave update..

Here is another example of where wide character display that result in misalignment:

![screen shot 2018-11-26 at 11 42 18 am](https://user-images.githubusercontent.com/1150961/49028604-c47da580-f170-11e8-9bf0-35c585bff67d.png)

I am not using 'Core Text renderer', here is my preference for macvim:

![screen shot 2018-11-26 at 11 48 03 am](https://user-images.githubusercontent.com/1150961/49028807-4241b100-f171-11e8-823a-ebaf33c9a3b5.png)

![screen shot 2018-11-26 at 11 47 49 am](https://user-images.githubusercontent.com/1150961/49028844-54235400-f171-11e8-8c01-6cc2c75d1297.png)

**Comment by ApolloTang** [comment]
possibly relate to #455 ?

**Comment by ychin** [comment]
What's the actual text you tried to display? Can you paste it in a comment? It's a little hard to tell where the actual wide character is.

Also, are you using Core Text renderer?

**Comment by ApolloTang** [comment]
@ychin, I have update my description for the information you requested.

**Comment by ychin** [comment]
Thanks @ApolloTang. Did you turn off "Core Text renderer" to deal with the rendering issues in Mojave (#751)? Right now, the non-Core Text renderer doesn't deal with the CJK full-width characters in the exact same way as the Core Text renderer (which behaves more like how normal Vim) would.

In this case, I would recommend the following:

1. Use the default font in MacVim instead of Inconsolata. That should work out of the box and the text in your code block is rendered properly.
2. Wait for #751 to get fixed and then enable Core Text renderer.
3. Just enable Core Text renderer now and use a build of MacVim built using High Sierra SDKs. You can build it yourself or use our release (https://github.com/macvim-dev/macvim/releases).

For (2). I was hoping to get it fixed by last week but it slipped so we should really be pushing out the rendering fixes by the end of the week.

**Comment by ApolloTang** [comment]
Thank you so much for everyone who is working on #751 !

**Comment by ychin** [comment]
Please ping me if this doesn't get fixed by end of week.

**Comment by ychin** [comment]
#757 fixed Core Text renderer in Mojave. Please turn that on and try again. The non-Core Text renderer is mostly used as a backup and therefore not all text layout features and functionalities are as supported. If it fixed the issue please close the issue.

**Comment by ApolloTang** [comment]
This is indeed fixed, but has not added to brew yet. So
```
$ brew upgrade macvim
``` 
will not install the correct the latest fix version, you will need to install the HEAD  
```
$ brew install macvim --HEAD
```
However, this is a problem, because ruby/config.h is missing after Mojave update:

![screen shot 2018-12-04 at 11 57 06 pm](https://user-images.githubusercontent.com/1150961/49490995-7592d880-f820-11e8-85f8-2cd2cd7be966.png)
![screen shot 2018-12-04 at 11 56 41 pm](https://user-images.githubusercontent.com/1150961/49490998-7a578c80-f820-11e8-9703-f78949a814e9.png)

So for those of you like me, if you have the same problem you will have to download the correction version of Command Line Tool from [https://developer.apple.com/download/more/](https://developer.apple.com/download/more/) (for me this is ```Command_Line_Tools_macOS_10.14_for_Xcode_10.1```) and install it. 

But that does not give you ruby/config.h, you have to cd into 
```
cd /Library/Developer/CommandLineTools/Packages/
```
and execute macOS_SDK_headers_for_macOS_10.14.pkg:
```
$ open macOS_SDK_headers_for_macOS_10.14.pkg
``` 
Now you can run ```$ brew install macvim --HEAD```

Reference
https://stackoverflow.com/a/53194299/3136861
https://stackoverflow.com/a/53388305/3136861
https://github.com/flori/json/issues/255
https://github.com/macvim-dev/macvim/issues/751#issuecomment-444167716

**Comment by ApolloTang** [comment]
Please let me know when the HEAD is added to brew, and I will close this issue.

**Comment by ychin** [comment]
Yeah you are right it's not deployed yet. I'll let you know when the official formula is updated.

**Comment by ychin** [comment]
Homebrew should have been updated to snapshot 153. Feel free to verify.
