### ISSUE TITLE
All text invisible after update to 8.1.560 on Mojave

### ISSUE THREAD

**Issue by LukeOrgana** [macvim-dev/macvim#801]
I just upgraded to version 8.1.560 via an automatic update. Now when I launch MacVim I see the titlebar, menubar, and tab-bar, but the rest of the window is entirely blank - no text is displayed at all, anywhere so I cannot see the contents of my files. Nothing can be seen in the command line after pressing `:` either.

The attached screenshot shows what is displayed (i.e. nothing) after blindly typing `:help` 

<img width="1342" alt="screenshot 2018-12-06 at 22 35 46" src="https://user-images.githubusercontent.com/24378630/49616195-e3b5d780-f9a7-11e8-97cf-f2251f88f14a.png">

`

**Comment by ychin** [comment]
What's your macOS version? Do you have any custom preferences that you set (e.g. CGLayer)? Can you try launching it with `mvim -u NONE -U NONE`?

**Comment by LukeOrgana** [comment]
I'm running macOS Mojave 10.14.1. Yes, I had Core Text rendering turned on. Turning it off resolved the problem. Thank you.

**Comment by ychin** [comment]
@LukeOrgana hmm Core Text renderer is the default and should work. What color scheme were you using and do you have any transparency setting?

**Comment by LukeOrgana** [comment]
I don't think I have any transparency settings. Here is my vimrc and colour scheme (renamed with txt extension so they would upload).

[vimrc.txt](https://github.com/macvim-dev/macvim/files/2660030/vimrc.txt)

[valloric.vim.txt](https://github.com/macvim-dev/macvim/files/2660031/valloric.vim.txt)

**Comment by matsm** [comment]
I have the same problem with 8.1.560. Mojave 10.14.1

**Comment by matsm** [comment]
From system.log
MacVim[5213]: DEPRECATED USE in libdispatch client: dispatch source activated with no event handler set; set a breakpoint on _dispatch_bug_deprecated to debug

**Comment by ychin** [comment]
@LukeOrgana I couldn't reproduce the issue, but I'm suspecting it's happening due to your auto-load session script that's triggering some other behaviors. I suspect it's a similar issue as #804. Do you have non-native fullscreen set

**Comment by matsm** [comment]
> On 10 Dec 2018, at 00:40, Yee Cheng Chin <notifications@github.com> wrote:
> 
> @LukeOrgana I couldn't reproduce the issue, but I'm suspecting it's happening due to your auto-load session script that's triggering some other behaviors. I suspect it's a similar issue as #804. Do you have non-native fullscreen set

No

But de-select “Use Core Text renderer” resolves the problem.

**Comment by ychin** [comment]
I made pull request #811 which resolves this issue. I suspect both @matsm and @LukeOrgana  has the old deprecated `MMUseCGLayerAlways` set to `YES` which causes this problem. I fixed it to properly ignore this flag in Mojave. (It's unfortunate that we used to tell people to set `MMUseCGLayerAlways` as a clutch around misc rendering issues. Moving on, there should be no hidden setting that you need to set to make rendering work)

The [next release](
https://github.com/macvim-dev/macvim/milestone/1) will have this fix. Meanwhile, you should do `defaults delete org.vim.MacVim MMUseCGLayerAlways` in Terminal which *should* fix this issue for you. I suggest leaving Core Text renderer **on**. It's enabled by default because it's the most fully featured and the officially supported method.

**Comment by LukeOrgana** [comment]
> @LukeOrgana I couldn't reproduce the issue, but I'm suspecting it's happening due to your auto-load session script that's triggering some other behaviors. I suspect it's a similar issue as #804. Do you have non-native fullscreen set?

I have "Prefer native full-screen support" selected.

**Comment by matsm** [comment]
> On 10 Dec 2018, at 12:27, LukeOrgana <notifications@github.com> wrote:
> 
> I made pull request #811 which resolves this issue (I think). I suspect both @matsm and @LukeOrgana have the old deprecated MMUseCGLayerAlways set to YES which causes this problem. I fixed it to properly ignore this flag in Mojave. (It's unfortunate that we used to tell people to set MMUseCGLayerAlways as a clutch around misc rendering issues. Moving on, there should be no hidden setting that you need to set to make rendering work)
> 
> The next release will have this fix. Meanwhile, you should do defaults delete org.vim.MacVim MMUseCGLayerAlways in Terminal which should fix this issue for you. I suggest leaving Core Text renderer on. It's enabled by default because it's the most fully featured and the officially supported method.

Yes, it fixes the problem.

Thanks!

/mm
