### ISSUE TITLE
YouCompleteMe stopped working after update to 8.1.560

### ISSUE THREAD

**Issue by tupos** [macvim-dev/macvim#803]
Hello,

After I updated today to the latest version 8.1.560 YouCompleteMe stopped working. I guess it is related to the change in handling of python in macvim. 

When I install YouCompleteMe i usually install through python3. However, I think that due to the change in macvim 8.1.560, python2 is taken as default. Therefore, I have an error

```
YouCompleteMe unavailable: dlopen(/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Pytho
n.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyC
odecInfo_GetIncrementalDecoder
  Referenced from: /usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Ver
sions/2.7/lib/python2.7/lib-dynload/_io.so
  Expected in: flat namespace
 in /usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/p
ython2.7/lib-dynload/_io.so
```

Usually I install YouCompleteMe as

```
python3 install.py --clang-completer
```

Before the latest update everything was working fine.
Also everything is working fine with homebrew vim.

MacOS 10.13.6

P.S. I think it is related to lines 32-33 of this file #739, [here](https://github.com/macvim-dev/macvim/pull/739/files)

Thanks.

**Comment by zhipengyan** [comment]
Me too

**Comment by rseddon** [comment]
I downgraded to the previous version, and youcompleteme works again.  So this does seem to be a regression.

**Comment by bstaletic** [comment]
YouCompleteMe maintainer here. The error you see isn't YCM specific. Your vim can't do `:py import _io`, even though `_io` is part of the Python's standard library.

**Comment by ychin** [comment]
I cannot give too much insight into YCM since I don't use the plugin. Do you know how YCM selects python2 versus python3 in Vim? Is it by magic or manual configuration? That may shed some insight why it switched from Python3 in previous MacVim version to Python2.

Does Python3 still work for you in MacVim in general? You can type `:python3 print('testing')` to see if it does. It could be that it's now linking to a different version from what your machine has installed. Either way can you paste what you see when you do `:set pythondll?` and `set pythonthreedll?`

**Comment by tupos** [comment]
I think that the problem is there

> P.S. I think it is related to lines 32-33 of this file #739, [here](https://github.com/macvim-dev/macvim/pull/739/files)

There is a typo. insted ` set pythondll` it is written `set pythonthreedll` in the section about python.

Can you check this?

**Comment by ychin** [comment]
Yes I just saw that line after posting. I will fix that. Thanks.

**Comment by tupos** [comment]
I just looked at you commit [e92be4c](https://github.com/ychin/macvim/commit/e92be4c1ac524416fc28b4fbb9abbb2b58e19f35). But the lines 32 and 33 are still the same and it appears that `pythonthreedll` is set to python2. 
```
    set pythonthreedll=/Library/Frameworks/Python.framework/Versions/2.7/Python
    set pythonthreehome=/Library/Frameworks/Python.framework/Versions/2.7
```
Am I missing something?

**Comment by tupos** [comment]
Ahh sorry. Did not see your further commit.

**Comment by ychin** [comment]
There are two bugs in that original PR. I had to fix both :)
