### ISSUE TITLE
set fullscreen goes to black after update 8.1.560

### ISSUE THREAD

**Issue by dimitriacosta** [macvim-dev/macvim#804]
Before this update I used to have in my `~/.gvimrc` file the seting `set fullscreen` to start MacVim full screen when it starts, but after the update it goes all black.

If I remove this setting from my `~/.gvimrc` file and type `set fullscreen` within MacVim from the command bar it works fine, but not at start up.

**Comment by ychin** [comment]
I can repro. Will work on fixing that. I only saw this happening under non-native fullscreen. Just to confirm that's your setting as well?
