### ISSUE TITLE
binary release with wrong python3 path

### ISSUE THREAD

**Issue by fnino** [macvim-dev/macvim#818]
Until release snapshot-150 (included), the command ":py3 import sys" worked fine on my installation.  Henceforth, including the latest snapshot-153, the command fails with:

E370: Could not load library /usr/local/Frameworks/Python.framework/Versions/3.7/Python
E263: Sorry, this command is disabled, the Python library could not be loaded.

I do not use homebrew and so I don't have /usr/local/Frameworks,  so this fails.

Thanks,

**Comment by ychin** [comment]
Note that the release notes in snapshot 150 said "Python 3.7", so it's kind of a mistake to automatically link to 3.6, and subsequent release notes didn't make clear that was upgraded. I will try to make sure that's in sync and communicated in release notes in the future.

**Comment by fnino** [comment]
Yes, perfect.  That was it.  Thanks !

  Fernando

-- 
___________________________________________________________________________________________
Fernando NIÑO
LEGOS (UMR5566 CNES/CNRS/IRD/UPS)                                     18, Av. Edouard Belin
Tél: 05.61.33.47.38                                                  31401 Toulouse Cedex 9

**Comment by flniu** [comment]
set pythonthreedll is enough.

```
if exists('&pythonthreedll')
  set pythonthreedll=/usr/local/Frameworks/Python.framework/Versions/Current/Python
endif
```

**Comment by eirnym** [comment]
@fnino it could be dangerous :) Python ABI is not compatible between second version (e.g. 3.7 is not compatible with 3.8, but 3.7.1 is compatible with 3.7.5), so you can have weird problems out of the blue this way.
