### ISSUE TITLE
With the latest release, FPS scrolled down

### ISSUE THREAD

**Issue by nooks** [macvim-dev/macvim#819]
macOS 10.14.1
MacBook Pro (Retina, 15-inch, Mid 2014)
Intel Iris Pro 1536 МБ

**Comment by ychin** [comment]
Sorry I didn't quite understand from your descriptions. Are you saying the frame rate when scrolling down is slow? How slow? Are you using the GUI version? Are you using Mojave?

**Comment by ychin** [comment]
Closing as duplicate of #796
