### ISSUE TITLE
MacVim can't communicate via AppleEvents due to missing security declaration in manifest

### ISSUE THREAD

**Issue by shayneholmes** [macvim-dev/macvim#821]
Noticed an issue editing nvALT notes in MacVim (commented on https://github.com/ttscoff/nv/issues/496), but the root cause seems to MacVim's declared security permissions.

This issue should affect other interprocess communication via AppleEvents, but I don't know of any others to test it with.

## Preconditions:
* Using MacOS Mojave
* [nvALT](https://github.com/ttscoff/nv/) installed
* nvALT has MacVim set as its external editor
* nvALT is storing notes in a single database

## Steps:
1. Edit a note with external editor. (MacVim opens with the note's content.)
2. Change the note and save.

### Expected:
The note updates in nvALT.

### Actual:
No update. Console shows these logs:

```
error	11:25:39.605395 -0800	tccd	Refusing TCCAccessRequestIndirect for service kTCCServiceAppleEvents and client /Applications/MacVim.app[0] without NSAppleEventsUsageDescription key
default	11:25:39.605565 -0800	nvALT	TCCAccessRequestIndirect_block_invoke: access request result was 0, timeout was 0
error	11:25:39.605914 -0800	nvALT	Since sending application [sess=xxx pid=xxx uid:x,x,x g:20,20 pV:xxx] is not permitted to send this AppleEvent to this process, returning an errAEEventNotPermitted reply.
```

## Causes:
The error log mentions [NSAppleEventsUsageDescription](https://developer.apple.com/documentation/security/nsappleeventsusagedescription?language=objc), and running through the steps above after placing that key in `Info.plist` results in a new dialog being shown:

![image](https://user-images.githubusercontent.com/2735346/50112457-1eafda80-01f4-11e9-8f16-6ae5f6d1cd1c.png)

After the user clicks "OK", the note updates as it should.

**Comment by ychin** [comment]
The fix looks fine, but let me look up this Mojave security change and test it out first.

Also, how exactly does nvALT work? It's *MacVim* controlling nvALT using AppleScript? Is it just a series of `:!osascript` calls? I wasn't quite understanding how MacVim understands to send AppleScript calls to other applications.

**Comment by shayneholmes** [comment]
Good question! Did some digging and found this:

MacVim, when compiled with the `odbeditor` option (`:h odbeditor` has more), implements the [ODB Editor Suite](https://www.barebones.com/support/develop/odbsuite.html), which is a protocol for external editors based on Apple Events. nvALT uses that protocol to leverage MacVim as an external editor. After launch, MacVim uses Apple Events to notify nvALT when the file is modified or closed.
