### ISSUE TITLE
Investigate supporting App Notarization

### ISSUE THREAD

**Issue by ychin** [macvim-dev/macvim#825]
With the release of macOS 10.14 Mojave, Apple has introduced a concept called App Notarization. It allows developers to send a copy of the app to Apple for validation to make sure it has no malware, etc, before releasing. Investigate using it in addition to just code signing with an Apple Developer ID.

Reasons for investigation:
* In the future Apple will mandate using notarization for Gatekeeper (i.e. signed apps distributed outside app store) so may as well get ahead of it. The Mojave release breaking misc MacVim features has shown how falling behind in deprecated features to not be a good idea.
* First launch experience is better with the dialog box containing the app's logo (Apple's "carrot" for enticing developer adoption)
* Improve trust in MacVim.

Caveats:
* Notarization requires hardened runtime. Will need to see if it breaks certain usage of MacVim depending on what entitlement MacVim asks for.
* One extra step in releasing software. May not be supported by Travis CI so it could be a manual process per release.
* Requires Apple Developer account which costs an annual fee (but just signing the app already requires it).

This will come after #517 is done.

**Comment by eirnym** [comment]
#517 has been done

**Comment by ychin** [comment]
MacVim is now signed to use hardened runtime and notarized. The settings exists outside of the committed Xcode project and we choose to use the custom command line tools now (`codesign` and `xcrun altool`) which are much more flexible.
