### ISSUE TITLE
Allow curly single quote in contractions in spell check mode

### ISSUE THREAD

**Issue by tangentsoft** [macvim-dev/macvim#829]
I have a Unicode text file that uses curled single quotes in contractions, which causes a word like this:

     didn‘t

to be a spelling error, because "didn" is not a word in the default dictionary. 

(Incidentally, "`don‘t`" passes the spell checker, because "don" is an English word, so it succeeds for the wrong reason.)

After a lot of web searching and help file reading, I found that I can affect this by changing the `MIDWORD` setting in the spell checker's affix file. I then found these affix files in the MacVim distribution:

    /Applications/MacVim.app/Contents/Resources/vim/runtime/spell/check/check_aa.aff
    /Applications/MacVim.app/Contents/Resources/vim/runtime/spell/check/check_bb.aff

Unfortunately, changing these two lines

    SET utf-8
    MIDWORD '-‘

doesn't seem to have any effect. I first tried changing the "aa" file, then applied my changes to the "bb" file as well, restarting MacVim in between each attempt.

While I'd like to have a method to fix my local MacVim setup to work the way I like, if it involves editing these affix files, the proper fix should be to fix it in the distribution, else I'll have to update these files on every MacVim update. I think this change is safe to apply to everyone, at least for English language locales.

**Comment by ychin** [comment]
Please file this issue with Vim itself (https://github.com/vim/vim/issues), as this is not MacVim-specific.

Anyway, I think it's not working for you because you need to change the files in `$VIMRUNTIME/spell/en/` rather than `$VIMRUNTIME/spell/check/`.

Also, what do you use `don‘t` instead of `don’t`?

**Comment by tangentsoft** [comment]
[Done](/vim/vim/issues/3747).

As for the curl direction on that quote, I just didn't look closely enough at it when composing the message. My document does use the glyph you expect.
