### ISSUE TITLE
Command bar w/ increased size when in fullscreen and tabs

### ISSUE THREAD

**Issue by emaiax** [macvim-dev/macvim#833]
Using MacVim Snapshot >151 breaks the size of command bar when using tabs.

`Prefer native full-screen support`, makes no difference here, I tested w/ both options.
I'm using dark mode, but makes no difference either.

```
Mojave 10.14.2 (18C54)

:version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Dec 13 2018 08:58:43)
macOS version
Included patches: 1-577
Compiled by _datadetectors@Traviss-Mac-6.local
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl               +clipboard         +dnd               +fullscreen        +listcmds          -mouse_sysmouse    +postscript        +statusline        +title             +windows
+arabic            +cmdline_compl     -ebcdic            -gettext           +localmap          +mouse_urxvt       +printer           -sun_workshop      +toolbar           +writebackup
+autocmd           +cmdline_hist      +emacs_tags        -hangul_input      +lua/dyn           +mouse_xterm       +profile           +syntax            +transparency      -X11
+autochdir         +cmdline_info      +eval              +iconv             +menu              +multi_byte        +python/dyn        +tag_binary        +user_commands     -xfontset
-autoservername    +comments          +ex_extra          +insert_expand     +mksession         +multi_lang        +python3/dyn       +tag_old_static    +vartabs           +xim
+balloon_eval      +conceal           +extra_search      +job               +modify_fname      -mzscheme          +quickfix          -tag_any_white     +vertsplit         -xpm
+balloon_eval_term +cryptv            +farsi             +jumplist          +mouse             +netbeans_intg     +reltime           -tcl               +virtualedit       -xsmp
+browse            +cscope            +file_in_path      +keymap            +mouseshape        +num64             +rightleft         +termguicolors     +visual            -xterm_clipboard
++builtin_terms    +cursorbind        +find_in_path      +lambda            +mouse_dec         +odbeditor         +ruby/dyn          +terminal          +visualextra       -xterm_save
+byte_offset       +cursorshape       +float             +langmap           -mouse_gpm         +packages          +scrollbind        +terminfo          +viminfo
+channel           +dialog_con_gui    +folding           +libcall           -mouse_jsbterm     +path_extra        +signs             +termresponse      +vreplace
+cindent           +diff              -footer            +linebreak         +mouse_netterm     +perl/dyn          +smartindent       +textobjects       +wildignore
+clientserver      +digraphs          +fork()            +lispindent        +mouse_sgr         +persistent_undo   +startuptime       +timers            +wildmenu
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libya
ml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o Vim -framework Cocoa -framework Carbon       -lm  -lncurses -liconv -framework AppKit   -fstack-protector  -L/System/L
ibrary/Perl/5.18/darwin-thread-multi-2level/CORE 
```

### Snapshot 151

<img width="1440" alt="screenshot 2019-01-10 14 40 47" src="https://user-images.githubusercontent.com/1289661/50983072-c06dd300-14e5-11e9-8b2c-fbc075627729.png">

<img width="1440" alt="screenshot 2019-01-10 12 33 59" src="https://user-images.githubusercontent.com/1289661/50982560-9bc52b80-14e4-11e9-9d99-fc13087d09cc.png">

### Snapshot >152

<img width="1440" alt="screenshot 2019-01-10 12 39 50" src="https://user-images.githubusercontent.com/1289661/50982562-9bc52b80-14e4-11e9-8237-318f7ff827a7.png">

<img width="1440" alt="screenshot 2019-01-10 12 40 22" src="https://user-images.githubusercontent.com/1289661/50982563-9c5dc200-14e4-11e9-8a3d-59319a64e054.png">

**Comment by ychin** [comment]
That’s not really a bug per se.

When in full screen the screen size is usually not a precise fit for how many number of lines you want to fit (depending on font size). In the snapshot 151 screenshot above you can see that there are black bars and that the tabs are not top-aligned. In 152 it is fixed so that you don’t see black bars (read the release notes for it) and that MacVim is always top aligned so the tabs would look right. This does mean the command line is moved up a little bit.

If yoh open GVim on Windows or Linux (GTK) you would actually see similar results when you maximize the window.

**Comment by emaiax** [comment]
@ychin so, I'll close this issue since it isn't an exactly MacVim bug.

Thanks for your answer! ;)

**Comment by ychin** [comment]
Re-opening issue. With the recent stateful renderer change (#858), we could introduce a new setting to pin the command line to the bottom. I have some work-in-progress experiments on that but not ready for prime time yet, but using this issue to track.

**Comment by ychin** [comment]
There is now a pull request (#1280) up to fix this, sort of. A new setting will now allow you to pin the command line (this is the proper name for the "command bar" as mentioned in this issue) to the bottom of the window.  See the PR itself for screenshots and explanations.
