### ISSUE TITLE
Setting CC=clang prior to building?

### ISSUE THREAD

**Issue by jpetrie** [macvim-dev/macvim#84]
[This page](https://github.com/macvim-dev/macvim/wiki/Building) on the wiki notes that as of OS 10.8, one should set `CC=clang` prior to running `configure`. Does anybody know or recall why?

I am able to successfully build and run MacVim from a clean source checkout (10.11) without doing so, so it seems like perhaps we should remove this from the documentation, or point out which OS version you no longer needed to do this on (maybe it was OS versions during which Apple was transitioning off `gcc` to `clang`?)

**Comment by douglasdrumond** [comment]
This was during transition, maybe let it there with a warning. Like "in
some versions of Mac OS X you'll need to prepend the command line with
CC=clang"

2015年10月7日(水) 22:32 Josh Petrie <notifications@github.com>:

> This page <https://github.com/macvim-dev/macvim/wiki/Building> on the
> wiki notes that as of OS 10.8, one should set CC=clang prior to running
> configure. Does anybody know or recall why?
>
> I am able to successfully build and run MacVim from a clean source
> checkout (10.11) without doing so, so it seems like perhaps we should
> remove this from the documentation, or point out which OS version you no
> longer needed to do this on (maybe it was OS versions during which Apple
> was transitioning off gcc to clang?)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/macvim-dev/macvim/issues/84>.
>
-- 

Douglas Drumond

Androidから送信。

**Comment by chdiza** [comment]
As far as I recall, that was ONLY for 10.7 and 10.8, and might have only applied to when some new major revision to Xcode came out and goofed everything up.  The last I remember, I had to do that on my Lion machine but on no others.  I no longer have a Lion machine, so I can't test.

**Comment by jpetrie** [comment]
Seems reasonable; I updated the page to note that the `CC=clang` bit is only needed on certain older OS versions.
