### ISSUE TITLE
Could not install with lua

### ISSUE THREAD

**Issue by diegoryte** [macvim-dev/macvim#843]
On Mac Mojave I get  an error when running the command:
brew install macvim --with-lua

Error: invalid option: --with-lua

I remember It worked before. How should I solve it?

Thanks for your help.

**Comment by chdiza** [comment]
Homebrew removed all options from all their formulas.  Just do `brew install macvim`.

**Comment by diegoryte** [comment]
Hi @chdiza ,
thanks for your help. However, I need lua support for vim, that is why I was trying to use the options.
Running brew install macvim includes the lua support?

Thanks for your help.

**Comment by ychin** [comment]
That's what @chdiza is saying, yes.

**Comment by diegoryte** [comment]
Thanks for your help! I just installed with the command brew install macvim and it is compiled with lua.
