### ISSUE TITLE
MacVim ignores 'set noendofline' in ~/.vimrc

### ISSUE THREAD

**Issue by carlosfilhoadm** [macvim-dev/macvim#844]
Hi,

MacVim seems to ignore the command 'set noendofline' in ~/.vimrc.

Even after adding the command also to MacVim's own vimrc (/Applications/MacVim.app/Contents/Resources/vim/vimrc) and defaults.vim (/Applications/MacVim.app/Contents/Resources/vim/runtime/defaults.vim), the setting still has no effect at all.

I'm using MacVim 8.1.577 and macOS Mojave 10.14.3.

Please help.

**Comment by ychin** [comment]
What's the issue here? From the documentation (type `:help 'eol'`):

> This option is automatically set or reset when starting to edit a new file, depending on whether file has an <EOL> for the last line in the file.  Normally you don't have to set or reset this option.

**Comment by ychin** [comment]
Closing as this isn't really an issue.
