### ISSUE TITLE
runtime/autoload/matchit.vim is missing

### ISSUE THREAD

**Issue by showaltb** [macvim-dev/macvim#845]
Using 8.1-153 on MacOS installed via HomeBrew.

I have `matchit` plugin enabled via `packadd! matchit`. When I press `%` to move to a match, I receive an error:

    E117: Unknown function: matchit#Match_wrapper

It looks like commit 314dd79 updated `matchit.vim` under `runtime/pack/dist/opt/matchit/plugin`. But this update appears to have split the `matchit#Match_wrapper` function out to `runtime/autoload/matchit.vim`, and this file is not included in the distribution.

If I copy the autoload file from https://github.com/chrisbra/matchit/blob/0f654b2e0f0ee811da204bba44deaf278439bd1b/autoload/matchit.vim into `runtime/autoload`, then the error goes away and the plugin works properly.

**Comment by ychin** [comment]
I think you mean 8.1-154, not 153.

It's unfortunate but seems like it's a bug in Vim, and it just fixed the issue in 8.1.0875 in https://github.com/vim/vim/commit/94688b8a2a1fc3d6c8e49151b9533ec1c0a6757f (MacVim included only up to 8.1.0873). I will see if I can find other regressions in the latest snapshot 154 update, and then push a fix for this.

**Comment by showaltb** [comment]
> I think you mean 8.1-154, not 153.

Yes, sorry. I was getting the version from Homebrew, and it doesn't update when vim does an auto update. Also sorry if I reported this in the wrong project.

**Comment by showaltb** [comment]
> Hmm… did you manually enable auto-update?

No, I don't believe so. It was an auto update (to 154) today that introduced the problem for me. Thinking it might be something on my side, I did `brew update macvim`, which brought me to 153, and then did a "Check for Updates" within the app, which updated me to 154. The auto-updating has been working fine as far as I can tell, but I'm by no means an expert in any of this.

**Comment by ychin** [comment]
Ah ok. That will do it.

Yeah… I don't think the interaction there is well thought-out but you should probably rely on Homebrew to update MacVim instead of using the Check for Updates functionality. I may need to consider disabling that function completely when MacVim is managed through Homebrew.

**Comment by mechanicles** [comment]
@showaltb @ychin I am getting same error now. Could you tell me how did you add/copy the file in `runtime/autoload`? I don't know where this directory lives :(

**Comment by mechanicles** [comment]
Got it. I just added that file in my `~/.vim/autoload/matchit.vim` and it is working.

**Comment by dataf3l** [comment]
I have the same problem, I can't use % anymore, oh man....

**Comment by errantepiphany** [comment]
This is also a problem in version 8.1.873 on Fedora 29 linux (installed via dnf).

**Comment by ychin** [comment]
Sorry I have been busy and delayed in pushing out the fix. It should hopefully be out be this weekend.

**Comment by ychin** [comment]
Fixed in latest release https://github.com/macvim-dev/macvim/releases/tag/snapshot-155
