### ISSUE TITLE
Ctrl-C when in command-line mode doesn't work anymore

### ISSUE THREAD

**Issue by ychin** [macvim-dev/macvim#846]
Seems like snapshot 154 broke this functionality. Pressing Ctrl-C in command-line mode doesn't break out of it anymore, but a follow-on key press would.

**Comment by ychin** [comment]
Seems like https://github.com/vim/vim/commit/e40b9d47bf8f8f716d3ef5a95c8ecbbdc0a501f9 (v8.1.034) broke this. It could either be a bug in Vim or a merge error on MacVim's side.

**Comment by segeljakt** [comment]
Also, remapping `cnoremap <C-c> <Esc>` does not work. :/

**Comment by mathsaey** [comment]
I'm facing the same issue. Pressing `ctrl-c` in any mode causes a spike in CPU usage and a noticeable delay. The issue only seems to occur in when using the MacVim gui. (so it doesn't seem to be an issue on the vim side).

**Comment by ychin** [comment]
I'm still looking into this, but the CPU usage bit is interesting info. Just for context MacVim relies on the GUI codebase in Vim itself and presents itself as basically a special type of gVim. That's why when Vim's GUI code goes through refactor like this, sometimes bugs creep in despite a clean merge since we have to re-do some of the changes downstream to match the upstream changes.
