### ISSUE TITLE
Scrollbar redraw issue on resize with snapshot-154

### ISSUE THREAD

**Issue by jmknoble** [macvim-dev/macvim#848]
After upgrading from snapshot-153 (Vim-8.1.577) to snapshot-154 (Vim-8.1.873), an issue with scrollbar rendering has appeared when resizing a MacVim window to make it larger.

This seems to be related to #802, but the trigger is different.

- Mac OS X 10.11.6 (15G22010)
- MacBook Pro (Retina, 13-inch, Early 2015)
- External DisplayPort monitor (27-inch (2560 x 1440))

If resizing by mouse, dragging the right edge of the MacVim window to the right (bigger) leaves a ghosted scrollbar near the right edge; this happens whether the window contains a new, empty buffer or a buffer with text larger than the window, and it happens regardless of whether I drag fast or slow.

If I use [SizeUp](http://www.irradiatedsoftware.com/sizeup/) or [Spectacle](https://www.spectacleapp.com/) to resize to the left or right half of the display via a hotkey, the behavior is more pronounced -- the ghost scrollbar appears where it was before the resize, and only as tall as it was before the resize.

In both cases, redrawing the window via **Control+L** makes the ghosted scrollbar disappear.

**Comment by jmknoble** [comment]
Before resizing via SizeUp or Spectacle:

![screenshot_922](https://user-images.githubusercontent.com/678264/52373060-9e953c80-2a0e-11e9-9892-4df8e5b08cf6.png)

After resizing via SizeUp or Spectacle:

![screenshot_923](https://user-images.githubusercontent.com/678264/52373079-a94fd180-2a0e-11e9-95f8-13a5c55e4d7d.png)

**Comment by jmknoble** [comment]
MacVim => Preferences => Advanced:

![screenshot_927](https://user-images.githubusercontent.com/678264/52373187-e916b900-2a0e-11e9-931c-eb2bbb79e75b.png)

**Comment by ychin** [comment]
That’s odd. Snapshot 154 contains #827 which fixed existing scroll bar issues but maybe it didn’t fix everything. I will take a look.

**Comment by ychin** [comment]
This should be fixed in snapshot 155, which is scheduled to be released soon to fix some regressions. The issue currently only shows up in pre-Mojave CoreText renderers, which is why I didn't catch it.
