### ISSUE TITLE
menu bar not hide ']' prefix item

### ISSUE THREAD

**Issue by epheien** [macvim-dev/macvim#853]
```viml
:amenu ]Toolbar.Make	:make<CR>
:popup ]Toolbar
```
expect menu bar not show ]Toolbar, but I show

**Comment by eirnym** [comment]
@epheien Why do you need `]` character in menu title? I haven't found any documentation about processing this character in menu title by `vim` or `MacVim`

**Comment by epheien** [comment]
> @epheien Why do you need `]` character in menu title? I haven't found any documentation about processing this character in menu title by `vim` or `MacVim`

`:h popup`

**Comment by eirnym** [comment]
Thank you, I missed it

**Comment by eirnym** [comment]
Any other implementation of Vim GUI ignores `name` completely. Only this implementation uses it.

GTK formally have name for popup menu, but it is always `Input Methods`. 

So we can file an issue to the Vim repo that MacVim is the only implementation which shows title for popup menu :D
