### ISSUE TITLE
Unable to open files with dollar ($) character

### ISSUE THREAD

**Issue by daniele-orlando** [macvim-dev/macvim#863]
MacVim: **8.1.950 (155)**

MacVim is unable to open a file when it is invoked from Finder with a file name or a parent directory contains the character `$`.
Example: `project/$config/main.yml`

### Steps to reproduce
1. `mkdir -p 'test/$config'`
2. `echo "test" > 'test/$config/test.txt'`
3. `open -a Finder .`
3. From Finder, try to open the file with MacVim double clicking the file name (the file type must be associated with MacVim)

or download the [attached archive](https://github.com/macvim-dev/macvim/files/2893794/config.zip).

### Expected result
`test.txt` file should open inside MacVim displaying `test` content.

### Actual result
MacVim opens a not existing file `test//test.txt` displaying an empty content.

**Comment by ychin** [comment]
Hmm I'm having some issues reproducing this. It almost seems to me that someone is doing a variable substitution for `$config` here. What if you just name your file `test_$_file` and `test_$var_file`?

Also, what OS are you using? Does this not happen if you load the file from command line (i.e. `mvim <filename>`)? Do you have any plugins that you think could interfere with this?

**Comment by daniele-orlando** [comment]
@ychin The problem arises when the dollar is in the directory name.
To reproduce, please follow literally the _Steps to reproduce_.

**Comment by ychin** [comment]
Yes I did follow the steps literally which is why I asked the followup questions to help identify why I couldn't reproduce the issue. Did you have a chance to test whether file names with `$` work?

Also, what macOS version are you using? Did you only see this issue when you double click on the file or when you drag the file to the dock's icon too?

**Comment by daniele-orlando** [comment]
Yes, file names with `$` character work as expected, no problem with them.
