### ISSUE TITLE
variable name errors after 950 (155) update

### ISSUE THREAD

**Issue by rr0ss0rr** [macvim-dev/macvim#864]
I saw that macvim was updated last night on my Mac (using joshdick/onedark.vim). when I edit a file ... Can anyone shed some light?  Getting thousands of these .. not sure if they are coming from onedark or not.

VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb 19 2019 12:07:03)
macOS version
Included patches: 1-950

line   13:
E461: Illegal variable name: a:highlight
line   14:
E121: Undefined variable: a:highlight
line   18:
E121: Undefined variable: a:highlight
E116: Invalid arguments for function has_key(a:highlight, "cterm") && a:highlight["cterm"] == "italic"
line   21:
E121: Undefined variable: a:highlight
E116: Invalid arguments for function has_key(a:highlight, "gui") && a:highlight["gui"] == "italic"
line   30:
E121: Undefined variable: a:highlight
E116: Invalid arguments for function has_key(a:highlight, "fg") ? a:highlight.fg.cterm : "NONE")
line   31:
E121: Undefined variable: a:highlight
E116: Invalid arguments for function has_key(a:highlight, "bg") ? a:highlight.bg.cterm : "NONE")
line   34:
E121: Undefined variable: a:highlight
E116: Invalid arguments for function has_key(a:highlight, "fg")    ? a:highlight.fg.gui   : "NONE") "guibg="   (has_key(a:highlight, "bg")    ? a:highlight.bg.gui   : "NONE") "guisp="   (has_key(a:highlight, "sp")    ? a:highlight.sp.gui   : "NONE") "gui="     (has_key(a:highlight, "gui")   ? a:highlight.gui      : "NONE") "ctermfg=" . l:ctermfg "ctermbg=" . l:ctermbg "cterm="   (has_key(a:highlight, "cterm") ? a:highlight.cterm    : "NONE")

**Comment by michael-reeves** [comment]
Same issue.  But it affected VIM on the command line as well as the GUI version.  My command line VIM uses onedark, while the GUI uses liquidcarbon.

Had to uninstall MacVim to fix the issue.

**Comment by rr0ss0rr** [comment]
I confirmed that onedark was updated to fix the issue ... I also confirmed that I was not using the latest version ;-(

**Comment by michael-reeves** [comment]
> I confirmed that onedark was updated to fix the issue ... I also confirmed that I was not using the latest version ;-(

Thanks for the heads up.  I'll check it out

**Comment by ychin** [comment]
Closing this issue as it's fixed. Vim introduced a tightening on VimScript behaviors and disallow assigning to `a:` parameters which is why some old versions of plugins broke.
