### ISSUE TITLE
Code::Stats don't track

### ISSUE THREAD

**Issue by m8dotpie** [macvim-dev/macvim#872]
When I use terminal vim it updates stats without any problem, but MacVim just don't seem to do anything, panel just keeps XP and that is all

**Comment by ychin** [comment]
What's Code::Stats? Is that https://codestats.net (from casual online search)? What does it do?

**Comment by m8dotpie** [comment]
It is a plugin to track your coding stats in IDE's and editors. Separated by languages you use and experience you get by coding

**Comment by m8dotpie** [comment]
https://gitlab.com/code-stats/code-stats-vim/issues/10
Here is about the error

**Comment by m8dotpie** [comment]
![image](https://user-images.githubusercontent.com/44410570/53748162-d8464f80-3eb5-11e9-9b41-ae4a1072504f.png)
This is the error

**Comment by ychin** [comment]
Closing this because this is an issue with the plugin. Discussions should be done there instead.
