### ISSUE TITLE
fontSizeUp does not work well with guifontwide

### ISSUE THREAD

**Issue by adah1972** [macvim-dev/macvim#873]
Previously I can use `Cmd-=` and `Cmd--` to enlarge and shrink all fonts, including both `guifont` and `guifontwide`. It seems a recent version changed its behaviour—now the shortcut key only enlarges `guifont`, but not `guifontwide`. I have to change `guifontwide` manually (or in vim script).

Is there a way to change the behaviour, either in MacVim itself, or by some vim script? It seems I cannot simply remap `<D-=>`, and for some reason `:macm Edit.Font.Bigger key=<nop>` does not work either…

Currently I am on MacVim 8.1.950 (155), installed from Homebrew bottle.

**Comment by ychin** [comment]
I will need to look into this.

**Comment by adah1972** [comment]
For some reasons the issue is now gone in MacVim 8.1.1517 (156). So I am closing it.
