### ISSUE TITLE
Don't unfold when printing or print output will differ wildly from screen

### ISSUE THREAD

**Issue by jm3** [macvim-dev/macvim#874]
_version 8.1.577 (153)_

As per @masukomi's comment on [vim-markdown-folding's #23](https://github.com/masukomi/vim-markdown-folding/issues/23), 
> "MacVim seems to unfold everything for the printed form regardless of filetype."

When MacVim prints, following the UI principle of Least Surprise, it should not unfold content previously hidden by folding, correct? Otherwise, the screen and the print out would be wildly different, and certain forms of documents would be unprintable, e.g. a collapsed outline.

Currently, unless this is changed, a folded document on screen:

    1. Thing 1
    ...
    2. Thing 2
    ...

will print in a completely unexpected and different fashion, like this:

     1. Thing 1

      __        ___   ___   __  ___   __  __ _   _ ____ _____
      \ \      / / | | \ \ / / |_ _| |  \/  | | | / ___|_   _|
       \ \ /\ / /| |_| |\ V /   | |  | |\/| | | | \___ \ | |
        \ V  V / |  _  | | |    | |  | |  | | |_| |___) || |
         \_/\_/  |_| |_| |_|   |___| |_|  |_|\___/|____/ |_|

      __        ______  ___ _____ _____    ____ _   _ _   _
      \ \      / /  _ \|_ _|_   _| ____|  / ___| \ | | | | |
       \ \ /\ / /| |_) || |  | | |  _|   | |  _|  \| | | | |
        \ V  V / |  _ < | |  | | | |___  | |_| | |\  | |_| |
         \_/\_/  |_| \_\___| |_| |_____|  \____|_| \_|\___/

    I consider that the Golden Rule requires that if I like a program I
    must share it with other people who like it. Software sellers want
    to divide the users and conquer them, making each user agree not to
    share with others. I refuse to break solidarity with other users in
    this way. I cannot in good conscience sign a nondisclosure agreement
    or a software license agreement. For years I worked within the
    Artificial Intelligence Lab to resist such tendencies and other
    inhospitalities, but eventually they had gone too far: I could not
    remain in an institution where such things are done for me against
    my will.

    2. Thing 2

    So that I can continue to use computers without dishonor, I have
    decided to put together a sufficient body of free software so that I
    will be able to get along without any software that is not free. I
    have resigned from the AI Lab to deny MIT any legal excuse to
    prevent me from giving GNU away.(2)

    Once GNU is written, everyone will be able to obtain good system
    software free, just like air.(3)

    This means much more than just saving everyone the price of a Unix
    license. It means that much wasteful duplication of system
    programming effort will be avoided. This effort can go instead into
    advancing the state of the art.

    Complete system sources will be available to everyone. As a result,
    a user who needs changes in the system will always be free to make
    them himself, or hire any available programmer or company to make
    them for him. Users will no longer be at the mercy of one programmer
    or company which owns the sources and is in sole position to make
    changes.

    Schools will be able to provide a much more educational environment
    by encouraging all students to study and improve the system code.
    Harvard's computer lab used to have the policy that no program could
    be installed on the system if its sources were not on public
    display, and upheld it by actually refusing to install certain
    programs. I was very much inspired by this.

    Finally, the overhead of considering who owns the system software
    and what one is or is not entitled to do with it will be lifted.

    Arrangements to make people pay for using a program, including
    licensing of copies, always incur a tremendous cost to society
    through the cumbersome mechanisms necessary to figure out how much
    (that is, which programs) a person must pay for. And only a police
    state can force everyone to obey them. Consider a space station
    where air must be manufactured at great cost: charging each breather
    per liter of air may be fair, but wearing the metered gas mask all
    day and all night is intolerable even if everyone can afford to pay
    the air bill. And the TV cameras everywhere to see if you ever take
    the mask off are outrageous. It's better to support the air plant
    with a head tax and chuck the masks.

**Comment by ychin** [comment]
MacVim uses Vim’s “hardcopy” command (see `:help hardcopy`) to print and that command doesn’t support folds. I suggest following the recommendations here: https://stackoverflow.com/questions/27504394/how-to-print-hardcopy-with-folds-in-vim

Otherwise feel free to open an issue at https://github.com/vim/vim/issues

Since this is not MacVim-specific I will close this issue shortly.
