### ISSUE TITLE
MacVim changes default application on installation

### ISSUE THREAD

**Issue by kkew3** [macvim-dev/macvim#880]
Not sure whether it's caused by `MacVim`, but when I install it via `dmg` (copy the `app` folder within `dmg` to `/Applications/`) it changes the default application for shell, python, etc., all to MacVim. Before installation, I opened `shell` using `TextEdit` and opened `python` using `Sublime Text`. Thanks.

macOS version: `10.14.3`
MacVim version: `8.1.950 (155)`

**Comment by eirnym** [comment]
This looks like a standard way of OS X to handle default apps in general. I don't see any specific logic in `Info.plist` or anywhere else forcing it to be default editor.

Please, correct me  if I'm wrong.

**Comment by kkew3** [comment]
Thanks for your reply. I recently reinstalled MacVim and this time it did not change the default app. Thus I'm closing this issue.
