### ISSUE TITLE
-[MMCoreTextView initWithFrame:] doesn't initialize fontDescent

### ISSUE THREAD

**Issue by jjgod** [macvim-dev/macvim#883]
`-[MMCoreTextView initWithFrame:]` initializes `font` but not `fontDescent`:

    // NOTE!  It does not matter which font is set here, Vim will set its
    // own font on startup anyway.  Just set some bogus values.
    font = [[NSFont userFixedPitchFontOfSize:0] retain];

 so it defaults to 0. In the case of the later `-setFont:` is called with the same pointer as `font`, then other initialization related to the font won't happen.

    - (void)setFont:(NSFont *)newFont
    {
        if (!(newFont && font != newFont))
            return;

There are many ways to fix this, a simple way would be just to call `[self setFont:[NSFont userFixedPitchFontOfSize:0]]` at `-initWithFrame:`.

**Comment by jjgod** [comment]
Any update?

**Comment by ychin** [comment]
I can take a look. Do you have a concrete repro that I can use to validate this? As in what are the symtoms form this issue?

**Comment by jjgod** [comment]
Just launch MacVim without any .vimrc/.gvimrc on macOS 10.15 beta you will
see this, all the text will be clipped.

**Comment by eirnym** [comment]
> Just launch MacVim without any .vimrc/.gvimrc on macOS 10.15 beta you will see this, all the text will be clipped.
> […](#)

this depends on a font

**Comment by jjgod** [comment]
Nope, MacVim has a default GUI font when nothing is set.

**Comment by eirnym** [comment]
I mean the issue with clipping is font-specific. When I set to Menlo, the issue is clearly present, when I set it to Fira Code, clipping is not present. These conditions and outcomes are repeatable even you mix the order.

**Comment by jjgod** [comment]
This is describing the case when the guifont is not set.

**Comment by jjgod** [comment]
Most fonts will have a non-zero descender. When `fontDescent` is not initialized properly this will defintiely be a problem.

**Comment by eirnym** [comment]
So you want to say, that `guifont` setting sets  `fontDescent` to some meaningful value? If yes, why setting Menlo __after__ `Fira Code Light` I able to observe clipping?

**Comment by jjgod** [comment]
I'm sorry, exactly what you do to trigger this? Do you have steps to reproduce this behavior?

As far as I can tell,

https://github.com/macvim-dev/macvim/blob/master/src/MacVim/MMCoreTextView.m#L327

    fontDescent = ceil(CTFontGetDescent(fontRef));

Since it always assigns `fontDescent` here it shouldn't be a problem as long as `-setFont:` is being called properly every time a `guifont` changes.

**Comment by ychin** [comment]
If I'm guessing correctly, this happens in 10.15 because macOS is reusing and caching `NSFont` objects internally. Previously, we just naively assume `setFont` will always be called (which is true), and then the font will be different from the initial dummy font. However, it appears that macOS 10.15 will just pass the same `NSFont` to us, causing the first `setFont` (if your vimrc doesn't override the default font) to early-out and not set up `fontDescent` properly. I commented on your pull request for further improvements before I want to merge it in.

**Comment by jjgod** [comment]
Correct. PR updated.
