### ISSUE TITLE
Seamless title bar

### ISSUE THREAD

**Issue by nabsiddiqui** [macvim-dev/macvim#884]
**Describe the solution you'd like**

I have noticed that many applications are now utilizing a "seamless" title bar where the window decorations are embedded into the frame.  I know there are already implementations on changing the title bar and also hiding it, but is there any desire to create a similar title bar for MacVim.  I have provided an example from Typora below:

Seamless:

<img width="844" alt="Screen Shot 2019-04-23 at 10 20 09 AM" src="https://user-images.githubusercontent.com/11954508/56588655-c9c10e00-65b1-11e9-95b7-47fb1d269938.png">

Classic:
<img width="843" alt="Screen Shot 2019-04-23 at 10 20 20 AM" src="https://user-images.githubusercontent.com/11954508/56588656-c9c10e00-65b1-11e9-87b8-8dba6dd7c1e5.png">

**Comment by digicannon** [comment]
I'd like this.

**Comment by ychin** [comment]
Implemented in #888.
