### ISSUE TITLE
The URL at the top of our GitHub page points to GoogleCode

### ISSUE THREAD

**Issue by chdiza** [macvim-dev/macvim#89]
At the top of this repo's front page, it says: Vim - the text editor - for Mac OS X http://code.google.com/p/macvim/

But that GoogleCode URL just redirects back to here.  I'd fix it myself, but I don't see any way for me to touch that.

**Comment by splhack** [comment]
I can change it. Which URL is the best?

**Comment by chdiza** [comment]
Well, either no URL at all, or github.com/macvim-dev/macvim.  The Vim home page link is already in the README.

**Comment by splhack** [comment]
done

**Comment by chdiza** [comment]
Thanks!
