### ISSUE TITLE
Can't set guifont in .vimrc

### ISSUE THREAD

**Issue by nicolaimainiero** [macvim-dev/macvim#890]
**Describe the bug**
Can't set `guifont` in my `.vimrc`. It always defaults back to Menlo 11pt. 

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Open .vimrc and add `set guifont=Courier:h16`
2. restart mvim from terminal
3. Vim GUI should use Courier at 16pt but defaults back to Menlo 11pt

**Expected behavior**
I expect that MacVim uses the specified font from the `.vimrc`file

**Environment (please complete the following information):**
 - VIM - Vi IMproved 8.1 (2018 May 18 kompiliert am May  3 2019 21:30:35)
MacOS Version
Inklusive der Patches: 1-1222

**Additional context**
I installed mvim via brew.

**Comment by chdiza** [comment]
You need to set it in `~/.gvimrc`, not `~/.vimrc`.

**Comment by nicolaimainiero** [comment]
@chdiza Thanks, I realized also, that I do have a `~/.gvimrc` with an incorrect `guifont`definition.

**Comment by ychin** [comment]
I think the bug here is the incorrect `guifont` definition in the `.gvimrc`, since you can set it in a normal `.vimrc` and it will still work.

That said, it's still the recommended and documented way to put it in `gvimrc` instead.
