### ISSUE TITLE
MacVim crashes with EXC_CRASH (Code Signature Invalid)

### ISSUE THREAD

**Issue by jduan** [macvim-dev/macvim#892]
**Describe the bug**

My setup:
* macOS 10.14.5
* MacVim: Snapshot 155

MacVim crashes upon start with this error:
```
Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY
```
Note that this didn't happen the first time I installed MacVim. It only started happening after a few days/weeks. I've tried to reinstall MacVim and the same problem came back after a while.

**To Reproduce**

Install MacVim. Use it. After a few days/weeks, the problem starts happening.

**Expected behavior**

It never crashes.

**Comment by eirnym** [comment]
How did you install MacVim? Downloaded from GitHub, installed from MacPorts/Homebrew, installed manually?

**Comment by jduan** [comment]
Manually from this page: https://github.com/macvim-dev/macvim/releases

**Comment by eirnym** [comment]
Could you run `mvim -u NONE -U NONE` and see what's happening. It's possible, that some of your plugins doesn't work well and need to be updated/fixed.

**Comment by jduan** [comment]
Thanks for your quick response. Turns out that our IT department applies a "security patch". That's why the initial installment would work but it would stop working after the "security patch" is applied in the background. 

Sorry about the false alarm.

**Comment by ychin** [comment]
@jduan I'm still curious what the security patch did to MacVim to make the code signature no longer valid. Did you actually resolve it with your IT department?

**Comment by jduan** [comment]
I asked them and I'll circle back once I find out.
