### ISSUE TITLE
mapping 2-rightmouse doesn't seem to work

### ISSUE THREAD

**Issue by DervishD** [macvim-dev/macvim#894]
_Instructions: Replace the template text and remove irrelevant text (including this line)_

**Describe the bug**
In my `.vimrc` I have the following mapping:
>    nmap <silent> <2-RightMouse> :w<CR>

This mapping works perfectly in Windows (not MacVim there, of course) but doesn't work on macos Mojave with MacVim. I've tried with control+v in insert mode to see if the mouse works at all and I can generate <RightMouse>, <M-RightMouse>, <C-S-RightMouse>, etc. The only thing I can't generate are the double clicks.

**To Reproduce**
Add the previously indicated line to `.vimrc` or type it in normal mode, and then hit double right click on the touchpad.

**Expected behavior**
The current file should be saved because the normal mode command `:w` should be issued with the double-right-mouse-click mapping.

**Environment (please complete the following information):**
 - MacVim 8.1.950
 - OS: macOS 10.14.4
 - GUI

Thanks in advance, and feel free to ask for more information if needed.

**Comment by ychin** [comment]
It seems to work for me. Does `<RightMouse>` work for you at all?

I did this and I could alternate between "right click" and "right doubleclick":

````
noremap <2-RightMouse> :echo 'right doubleclick'<CR>
noremap <RightMouse> :echo 'right click'<CR>
````

Did you make sure to have a `<CR>` after `:w` in your mapping?

**Comment by DervishD** [comment]
First of all, thanks A LOT for your reply and your help.

> It seems to work for me. Does `<RightMouse>` work for you at all?

Yep, <RightMouse> works perfectly.

> I did this and I could alternate between "right click" and "right doubleclick"

I can't, only "right click" is shown. When I click twice on the touchpad with two fingers (the right click in my Mac), nothing is printed, not even "right click".

> Did you make sure to have a `<CR>` after `:w` in your mapping?

Of course, it was just an example of the mapping. That mapping works perfectly in Windows, so I knew it was not a syntax problem or a typo.

> Edit: Also, what does `set mouse?` show for you?

mouse=a

**Comment by ychin** [comment]
Yeah I don't think this is a MacVim problem. The thing is, very few programs use double-right-click anyway so it's not that easy to just find another program to test on. From the trackpad, try to actually press in to the track pad rather than doing a two-finger tap. I have found that two two-finger taps don't really register as a double-right-click.

Another way is to to Ctrl-Click twice to accomplish the same thing.

**Comment by eirnym** [comment]
It works for me as @ychin wrote. If rebind only `<2-RightClick>`, solution was `double ctrl-click`.

**Comment by DervishD** [comment]
Sorry for the delay, I've been horribly busy.

> Yeah I don't think this is a MacVim problem. The thing is, very few programs use double-right-click anyway so it's not that easy to just find another program to test on. From the trackpad, try to actually press in to the track pad rather than doing a two-finger tap. I have found that two two-finger taps don't really register as a double-right-click.

Yes, that seems to be the problem. MacOS bug, not MacVim's. Sorry for the noise.
> 
> Another way is to to Ctrl-Click twice to accomplish the same thing.

Duly noted 😉 Thanks a lot.
