### ISSUE TITLE
MacVim is vulnerable to arbitrary code execution via modelines (vim < 8.1.1365)

### ISSUE THREAD

**Issue by raimue** [macvim-dev/macvim#898]
Vim before 8.1.1365 is vulnerable to arbitrary code execution via modelines by opening a specially crafted text file.

A detailed description of the issue was published here:
https://github.com/numirias/security/blob/master/doc/2019-06-04_ace-vim-neovim.md

Although the original vulnerability was patched with 8.1.1365, I would suggest to update at least to vim 8.1.1368, as the follow-up patches add the new option `:set modelineexpr` as another mitigation for similar attacks.

* 8.1.1365: https://github.com/vim/vim/commit/53575521406739cf20bbe4e384d88e7dca11f040
* 8.1.1366: https://github.com/vim/vim/commit/110289e78195b6d01e1e6ad26ad450de476d41c1
* 8.1.1367: https://github.com/vim/vim/commit/7e800c6047c8a9cc3e5cbc019a4dc91ec36616b1
* 8.1.1368: https://github.com/vim/vim/commit/e09244ee3567d658c293fb1ae0d47a1a8be870ac

**Comment by ychin** [comment]
Thanks for pointing out. Will update.

**Comment by ychin** [comment]
Updated to latest and pushed a release out. Closing.

**Comment by lilyball** [comment]
The changelog for [snapshot-156](https://github.com/macvim-dev/macvim/releases/tag/snapshot-156) incorrectly claims the vulnerability was fixed in Vim 8.1.265.

**Comment by ychin** [comment]
@lilyball Thanks for pointing that out. I fixed the typo in release page and the auto-updater's message.
