### ISSUE TITLE
Failure running with mvim in OSX 10.10 (yosemite): missing Perl library

### ISSUE THREAD

**Issue by douglasdrumond** [macvim-dev/macvim#9]
_From @GoogleCodeExporter on March 16, 2015 9:25_

```
Pretty much the same as issue #484: 
https://code.google.com/p/macvim/issues/detail?id=484. The perl version was 
upgraded. Error is:

dyld: Library not loaded: 
/System/Library/Perl/5.12/darwin-thread-multi-2level/CORE/libperl.dylib
  Referenced from: /Applications/MacVim.app/Contents/MacOS/Vim
  Reason: image not found
Trace/BPT trap: 5

 I re-built and it works fine. Maybe just needs a new snapshot?
```

Original issue reported on code.google.com by `sande...@gmail.com` on 25 Jul 2014 at 11:13

_Copied from original issue: douglasdrumond/macvim#508_

**Comment by douglasdrumond** [comment]
_From @GoogleCodeExporter on March 16, 2015 9:25_

```
I could not open the old macvim window buffer for maverick too after I upgraded 
the os to yosemite beta. I downloaded a new snapshot and it works fine now.
```

Original comment by `Jason...@gmail.com` on 26 Jul 2014 at 11:04

**Comment by douglasdrumond** [comment]
_From @GoogleCodeExporter on March 16, 2015 9:25_

```
I had this issue with the current version of `brew cask install macvim`, but 
regular (non-cask) `macvim` worked (they both use snapshot 73).
```

Original comment by `priv.tom...@gmail.com` on 9 Aug 2014 at 2:21

**Comment by douglasdrumond** [comment]
_From @GoogleCodeExporter on March 16, 2015 9:25_

```
This affect me too
```

Original comment by `ryan.q...@gmail.com` on 4 Oct 2014 at 5:12

**Comment by douglasdrumond** [comment]
_From @GoogleCodeExporter on March 16, 2015 9:25_

```
I just hit this

```

Original comment by `Oscargod...@gmail.com` on 17 Oct 2014 at 7:25

**Comment by douglasdrumond** [comment]
_From @GoogleCodeExporter on March 16, 2015 9:25_

```
running into this after upgrading to yosemite osx. fixing everything in brew 
doctor doesn't fix this
```

Original comment by `Morenoh149@gmail.com` on 17 Oct 2014 at 9:52

**Comment by douglasdrumond** [comment]
_From @GoogleCodeExporter on March 16, 2015 9:25_

```
Until a new snapshot is released, an easy way to fix this is to build from 
source on a machine running Yosemite. There are no changes required, just a new 
build.
```

Original comment by `sande...@gmail.com` on 17 Oct 2014 at 10:08

**Comment by douglasdrumond** [comment]
_From @GoogleCodeExporter on March 16, 2015 9:25_

```
I compiled from source on a machine running Yosemite, and here's the build: 
http://ryat.la/Y5t1
```

Original comment by `m...@ryanatallah.com` on 17 Oct 2014 at 10:49

**Comment by douglasdrumond** [comment]
_From @GoogleCodeExporter on March 16, 2015 9:25_

```
I had this issue as well. I deleted my old Macvim install. Then, I followed 
these directions 
(http://vancelucas.com/blog/fixing-homebrew-on-osx-yosemite-10-10/) to make 
sure my homebrew was on par with Yosemite. Then I just did 'brew install 
macvim'. Works fine now.
```

Original comment by `helloger...@gmail.com` on 20 Oct 2014 at 3:12

**Comment by douglasdrumond** [comment]
_From @GoogleCodeExporter on March 16, 2015 9:25_

```
I just built from source. I received that error when using the downloadable 
snapshot.

Additionally, if you don't remove the old MacVim you get a cryptic error about 
missing iconv symbols if you try to build from source.
```

Original comment by `jarrett....@gmail.com` on 23 Oct 2014 at 4:06

**Comment by douglasdrumond** [comment]
_From @GoogleCodeExporter on March 16, 2015 9:25_

```
I solved this problem just like #9's way, brew uninstall macvim, then brew 
install macvim. done...
```

Original comment by `tblongg...@gmail.com` on 24 Oct 2014 at 2:55

**Comment by douglasdrumond** [comment]
_From @GoogleCodeExporter on March 16, 2015 9:25_

```
Please, a new snapshot!
```

Original comment by `eric...@gmail.com` on 2 Nov 2014 at 4:18

**Comment by douglasdrumond** [comment]
_From @GoogleCodeExporter on March 16, 2015 9:25_

```
New Yosemite snapshot is available, fixes issues for me:  
https://github.com/eee19/macvim/releases

```

Original comment by `eric...@gmail.com` on 11 Nov 2014 at 1:51

**Comment by douglasdrumond** [comment]
_From @GoogleCodeExporter on March 16, 2015 9:25_

```
brew uninstall macvim
brew install macvim

move the old application to trash or remove it, then run 

brew linkapps
```

Original comment by `lfender6...@gmail.com` on 10 Dec 2014 at 12:50

**Comment by jpetrie** [comment]
This appears to have been closed by the released on March 16.
