### ISSUE TITLE
Can/should we unfork ourselves from b4winckler/macvim?

### ISSUE THREAD

**Issue by chdiza** [macvim-dev/macvim#90]
At the top of our page it gives a count of how many commits ahead of b4winckler/macvim we are, as in: `This branch is 5539 commits ahead of b4winckler:master`.

It seems kind of pointless to just have that there growing and growing.  Is there a way to "unfork" ourselves from the b4winckler repo?  Is it a good idea to do so?

**Comment by splhack** [comment]
> Is there a way to "unfork" 

technically, maybe yes. http://stackoverflow.com/questions/29326767/unfork-a-github-fork-without-deleting#comment46845376_29326840 but I feel displaying "This branch is ..." is ok.

**Comment by jpetrie** [comment]
One reason to consider doing this I guess is that [forked repositories are not searchable](https://github.com/macvim-dev/macvim/search?q=MMBackend&type=Code&utf8=%E2%9C%93) which is a bit annoying.

**Comment by splhack** [comment]
@chdiza It's up to you. could you ask github.com/contact to unfork this repo or close this issue?

**Comment by chdiza** [comment]
Before I make a final call on this, I'd like to be sure that we've taken into consideration as many possible side-effects as we can.  Can anyone else think of any?

**Comment by splhack** [comment]
@chdiza It's totally up to you.

**Comment by tobireif** [comment]
Seems sensible.

**Comment by chdiza** [comment]
OK, I'll do this when I get a chance.  The gain in searchability would be nice.

**Comment by splhack** [comment]
no activities here. ok, we'll keep to be a fork of b4winckler/macvim.

**Comment by jpetrie** [comment]
FWIW, I am going to email GitHub and request that we unfork the repository today.

It's very annoying not being able to search it, especially as I do a lot of evaluation of issues and PRs that way when I don't have a Mac in front of me.

**Comment by jpetrie** [comment]
I haven't actually received a response from the GitHub support team, but they appear to have processed the ticket and disconnected MacVim from the old fork network, so there we go.

**Comment by seandenigris** [comment]
It might be good to explain the original source in the README/website (unless I missed it) because I found this repo and went on a 30 minute investigation to find the relationship between this project and the original MacVim. It also seems like good etiquette… Thanks for picking up this important project!

**Comment by jpetrie** [comment]
@seandenigris Good idea.
