### ISSUE TITLE
MacVim is lagging far behind again

### ISSUE THREAD

**Issue by chdiza** [macvim-dev/macvim#900]
How about a merge-in from upstream?  We're a whopping *two-hundred and thirteen* patches (and more than a month) behind.

Because of the lag MacVim is stuck with the annoying wraparound search delay bug that got fixed shortly after the last merge-in.

**Comment by mortonfox** [comment]
Also, merging from upstream would get us a mitigation for the modeline vulnerability mentioned in issue #898.

**Comment by mortonfox** [comment]
I submitted a pull request that gets us to the current patchlevel. Hope I merged all the changes correctly.

**Comment by chdiza** [comment]
Thanks @ychin!

**Comment by chdiza** [comment]
We are nearly 200 patches behind again.
