### ISSUE TITLE
Security vulnerability in VIM modelines

### ISSUE THREAD

**Issue by isaki** [macvim-dev/macvim#904]
Please refer to the following document for details:

https://github.com/numirias/security/blob/master/doc/2019-06-04_ace-vim-neovim.md

I see that newer versions of the VIM runtime have been integrated into this codebase; would it be possible to get a release that addresses this vulnerability?

Thanks!

**Comment by eirnym** [comment]
Thank you, #898 was already reported.

**Comment by isaki** [comment]
Ah, I missed it! Thank you for the heads up!
