### ISSUE TITLE
upgrade vim 

### ISSUE THREAD

**Issue by ApolloTang** [macvim-dev/macvim#906]
MacVim hasn't been updated since Feb 2019, and is lagging behind vim at v8.1.1517 (we are currently at v8.1.950). Because of this [bug](https://github.com/prabirshrestha/vim-lsp/issues/399), I am requesting for an new release build.

Thanks.

**Comment by eirnym** [comment]
Thank you for your interest, this request already has been addressed and in the process

**Comment by ychin** [comment]
Just released a new version. Sorry for the delays.
