### ISSUE TITLE
Some very recent commit broke building on Tiger PPC

### ISSUE THREAD

**Issue by chdiza** [macvim-dev/macvim#91]
The build made it to here:
```
CompileC build/MacVim.build/Release/MacVim.build/Objects-normal/ppc/MMWindowController.o /bld/macvim/src/MacVim/MMWindowController.m normal ppc objective-c com.apple.compilers.gcc.4_0
    cd /bld/macvim/src/MacVim
    /Developer/usr/bin/gcc-4.0 -x objective-c -arch ppc -pipe -Wno-trigraphs -fobjc-exceptions -fpascal-strings -fasm-blocks -Os -Wreturn-type -Wunused-variable -fmessage-length=0 -mtune=G5 -fvisibility=hidden -I/bld/macvim/src/MacVim/build/MacVim.build/Release/MacVim.build/MacVim.hmap -mdynamic-no-pic -F/bld/macvim/src/MacVim/build/Release -F/bld/macvim/src/MacVim -I/bld/macvim/src/MacVim/build/Release/include -I/bld/macvim/src/MacVim/build/MacVim.build/Release/MacVim.build/DerivedSources -c /bld/macvim/src/MacVim/MMWindowController.m -o /bld/macvim/src/MacVim/build/MacVim.build/Release/MacVim.build/Objects-normal/ppc/MMWindowController.o
/bld/macvim/src/MacVim/MMWindowController.m: In function ‘-[MMWindowController windowDidResize:]’:
/bld/macvim/src/MacVim/MMWindowController.m:1035: error: ‘NSAppKitVersionNumber10_10_Max’ undeclared (first use in this function)
/bld/macvim/src/MacVim/MMWindowController.m:1035: error: (Each undeclared identifier is reported only once
/bld/macvim/src/MacVim/MMWindowController.m:1035: error: for each function it appears in.)
** BUILD FAILED **
Makefile:2930: recipe for target 'macvim' failed
make[1]: *** [macvim] Error 1
make[1]: Leaving directory '/bld/macvim/src'
Makefile:26: recipe for target 'first' failed
make: *** [first] Error 2
```

I haven't tested on Leopard yet; will wait until this is fixed first since it seems likely to break in the same place on Leopard too.

**Comment by splhack** [comment]
Could you try https://github.com/macvim-dev/macvim/pull/92?

**Comment by jpetrie** [comment]
Travis CI supports VMs for older SDK versions, but only down to OS X 10.9 (afaik). I wonder if there is some other service or some other way for us to more easily test whether or not we're still building on older SDKs than making @chdiza suffer through it every time?

**Comment by chdiza** [comment]
> some other way for us to more easily test whether or not we're still building on older SDKs than making @chdiza suffer through it every time?

It's not too big a deal.  Changes to `src/macvim` or other Mac-specific tweaks are usually spaced far apart enough that I'm not glued to by Powerbook G4 doing testing.

**Comment by chdiza** [comment]
Good news.  This patch fixes building on Tiger PPC.  Also, with this patch applied, Leopard PPC builds and passes the "will it open up and go in and out of fullscreen" test.

Thanks, @splhack!
