### ISSUE TITLE
Mouse cursor in insert mode is almost invisible on dark background on Mac not retina

### ISSUE THREAD

**Issue by nfuria** [macvim-dev/macvim#910]
With the last update - 8.1.1517, the I-beam cursor lost the white border that allowed it to be visible on dark backgrounds.
Workaround: Reinstall the previous version ....

**Comment by ychin** [comment]
Do you have a screenshot or can you tell me what color scheme you are using? The old white cursor was not designed for retina hence it was changed to use the system I beam but if it’s causing real readability issues we should revert it and just add a HD cursor instead (that’s actually what Xcode does)

**Comment by nfuria** [comment]
I am using the darkblue scheme on a Mac running High Sierra OS.

Thanks

Newton

**Comment by eirnym** [comment]
@nfuria Could you check the snapshot 159 and tell if it still an an issue for you?

**Comment by nfuria** [comment]
Now it’s better, but still does not have a good visibility.

Newton Furia

**Comment by eirnym** [comment]
I see it white on black background

This is a screenshot from `mvim --clean`:

<img width="852" alt="Zrzut ekranu 2019-10-22 o 21 10 39" src="https://user-images.githubusercontent.com/485399/67328751-39409780-f51a-11e9-9eed-bdbb7e248a39.png">

**Comment by nfuria** [comment]
The problem is with the I beam cursor. The left screenshot is from version 8.1.950, the other is from the new version.

**Comment by eirnym** [comment]
You can see on my second screenshot this I-beam cursor above "It was created by" words.

**Comment by nfuria** [comment]
There are no I-beam cursor in your screenshot; look the email.
For some strange reason, the native capture tools does not register the I-beam cursor. I used Snagit to capture my screenshot.

**Comment by nfuria** [comment]
Follows a screenrecord showing the I-beam cursor, almost invisible in this color scheme.

**Comment by eirnym** [comment]
@nfuria I'm sorry, I don't see screenshots within GitHub interface. Could you check them there and re-attach if missing?

**Comment by nfuria** [comment]
The screen recording show the I-beam in the two versions. In the new version it is almost invisible.

![macvim](https://user-images.githubusercontent.com/2140247/67439460-a44aa680-f5cc-11e9-95d3-16b17dfd35f7.png)

**Comment by eirnym** [comment]
I've run `mvim --clean` and then `:colo darkblue` to see the theme.It's bright yellow and bold which has very good visibility on a navy blue background as per me. I attached the screenshot done right away.

<img width="733" alt="Zrzut ekranu 2019-10-24 o 08 39 29" src="https://user-images.githubusercontent.com/485399/67459854-ccbcba00-f639-11e9-9f31-c96e596613ff.png">

**Comment by eirnym** [comment]
ah, you meant _mouse_ I-beam cursor. I thought all the time you're talking about text cursor. I'm sorry for the misunderstanding. It's better if you edit the issue to name it better.

Currently, I have MacVim 159, macOS 10.15 on MBP with Retina display and see mouse cursor better than you have on the second screenshot.

**Comment by nfuria** [comment]
Sorry for the confusion. As the insert cursor in Vim is always a  vertical bar and not a I-beam as it occur in almost all other applications, I didn't explain that the problem was with the mouse cursor.

**Comment by nfuria** [comment]
I use the GitHub MacVim 159 and the mouse cursor problem occurs on an iMac midi 2010 without a retina display. On a MPB midi 2012 without a retina display the cursor becomes more visible. Both machines run macOS 10.13.6. As they are very old systems, I think it is not worth trying to improve cursor visibility as it is a cosmetic problem that does not affect the use of MacVim. 
What would be worth improving are my machines but both meet my needs.

**Comment by ychin** [comment]
Let me look more into this. Non-retina displays are definitely supported features. I could always just use the old cursor for non-retina displays.

**Comment by ychin** [comment]
Ok, so basically #859 changed MacVim to use the system native I-beam cursor.

I think Mojave (10.14) and above have a new set of I-beam cursors that have the strong white border, which I think were designed to work well on dark mode. That's why I couldn't quite see what the issue is. Since you are using 10.13 I think the system cursors are less designed for dark backgrounds and hard to see in those situations. I have made it so that on 10.13 or below, MacVim will use the old custom cursor with the contrasty cursor which should work for you. It will make 10.13 retina users see a blurry cursor, but for those people they should be able to upgrade to Mojave at least.

**Comment by nfuria** [comment]
Hi Yee

It is working perfectly.

Thanks

Furia
