### ISSUE TITLE
New Window/Drag-Drop currently open file fails

### ISSUE THREAD

**Issue by Paulv445** [macvim-dev/macvim#913]
Custom Version 8.1.1517 (156)
macOX Mojave Version 10.14.5 (18F132)
File opened by drag-drop to MacVim App.
MacVim/right-mouse, New Window
Drag-Drop same file to the new window.
Until this release it opened read only.
With this release hangs, with MacVim quit required to kill window.

**Comment by eirnym** [comment]
I have macOS Mojave Version 10.14.6 (18G48f)

the same workflow makes the second window unusable, but if close the opened file and/or open, it could be opened again. Looks like dialog window should be shown, but it either invisible or hidden by a window

**Comment by Paulv445** [comment]
Thanks for confirmation. I agree with you situation analysis. Instead of expected Open Read-only ... dialog just showing an unusable window. 

----- Original Message -----

**Comment by ychin** [comment]
I can reproduce this. This is happening due to #895, and only happens when swap files are enabled. This should be fixed next release.

**Comment by Paulv445** [comment]
Confirmed -- Custom Version 8.1.1722 (157) resolves this issue -- Thanks, Yee Cheng Chin . Paul 

----- Original Message -----
