### ISSUE TITLE
How to disable launch animation (scale up)

### ISSUE THREAD

**Issue by ooopscc** [macvim-dev/macvim#915]
**Is your feature request related something that is currently hard to do? Please describe.**
It launchs slow. The animation also increase startup time and not so good (scale from 0 to 1?), hurt eyes.

**Describe the solution you'd like**
disable, or change scale effect?

**Describe alternatives you've considered**
None.

**Additional context**
VSCode slows too. But show windows immediately no animation. I want to have an option to disable it. Thanks.

**Comment by ychin** [comment]
Wait, how long is "slow"? It shouldn't take more than half a second or so to launch. I'm wondering if it's misc plugins and vimrc settings making the launch slow. If you launch vim in terminal does it come up immediately? What happens if you launch MacVim GUI with no plugins (do `mvim -u NONE -U NONE` in terminal)?

**Comment by eirnym** [comment]
I see the same even I have no configuration at all (`-u NONE -U  NONE`). This is how MacVim GUI creates a new window. I'd also prefer to have no such animation at all. 

The half of a second is enough to be noticeable and it may be bad for some people. Most applications on macOS doesn't include open animation (e.g. Safari, Terminal, Mail). It's better to add a `defaults` option to change this behaviour.

**Comment by ooopscc** [comment]
@ychin As @eirnym said, the slow may caused by plugins. It doesn't matter in this case, I will optimize it latter. Even when plugins are all disabled, the animation is also annoying.

**Comment by ychin** [comment]
I guess I'm ok with adding an option to turn it off. The animation is the default if you use the ["document window"](https://developer.apple.com/documentation/appkit/nswindowanimationbehavior/nswindowanimationbehaviordocumentwindow?language=objc) style, and you can see that in default apps like TextEdit and Apple Maps, so I'm going to leave the current behavior as default. The new option will be a command-line-only toggle.
