### ISSUE TITLE
WinBar adds another MacVim menu in the menu bar

### ISSUE THREAD

**Issue by lifepillar** [macvim-dev/macvim#918]
If a window toolbar (`:help WinBar`) is added to a window, an additional MacVim menu appears in the app's menu bar (see screenshot below).

Detailed steps to reproduce the behavior:
1. `gvim --clean`
2. `:nnoremenu 1.10 WinBar.Foo :Bar<cr>`

I would expect that the window toolbar does not affect the app's menu bar. Alternatively, if a window toolbar is supposed to be replicated in the menu bar, it should be on the far right with a proper name (WinBar?) and its menu entries should be working.

<img width="325" alt="macvim-toolbar-menu" src="https://user-images.githubusercontent.com/1193314/60390057-1f43fa80-9ace-11e9-8adf-5f0f6beb9e6a.png">

 - Vim 8.1.1517
 - macOS 10.14.5

**Comment by eirnym** [comment]
Where have you got `gvim` from MacVim distribution?

**Comment by eirnym** [comment]
Btw, the step 2 is reproducable.

**Comment by lifepillar** [comment]
>Where have you got gvim from MacVim distribution?

I install MacVim with `brew install macvim`. The Homebrew formula creates that symlink:

```ruby
# Create MacVim vimdiff, view, ex equivalents
executables = %w[mvimdiff mview mvimex gvim gvimdiff gview gvimex]
executables += %w[vi vim vimdiff view vimex]
executables.each { |e| bin.install_symlink "mvim" => e }
```

So, it's just a symlink to `mvim`:

```sh
ls -l `which gvim`
lrwxr-xr-x  1 me  admin  42 Jun 11 20:51 /usr/local/bin/gvim -> /Applications/MacVim.app/Contents/bin/mvim
```

**Comment by eirnym** [comment]
I think it's a bad idea as gvim and mvim are different by nature. People expect to see GTK Vim instead of MacVim. I'd filed an issue to that formula on this.

**Comment by lifepillar** [comment]
I don't know, MacVim is the only GUI Vim I use. I'd just note that in MacVim's app bundle, under `Contents/bin` one finds `gview`, `gvim` and `gvimdiff` as well.

**Comment by eirnym** [comment]
My bad, I see symlinks. Didn't know that they appeared. a while ago there were no such symlinks. Thank you for an issue

**Comment by ychin** [comment]
I think it's fine to map `gvim` to `mvim` personally. The command line flags should mostly work. But yes this is a bug that should be fixed.
