### ISSUE TITLE
macvim not working with lftp "edit" command

### ISSUE THREAD

**Issue by guillaume-smo** [macvim-dev/macvim#923]
Hello,

I try to edit remote files with lftp "edit" command and my local macvim editor.
With the classic vim, everything works well: lftp create a local copy of my file in ~/.cache/lftp/edit/ which I can edit and sync it with the remote version), but it does not work with macvim (there is only an empty hidden swap file in ~/.cache/lftp/edit/).
I tried to remove my vimrc to check my options, but i didn't change anythinh.

Thanks for your help,

Guillaume

**Comment by eirnym** [comment]
Hi @guillaumesamson 
if this works with any editor, than it should work with MacVim as well.
All you need to do is to add a `-f` flag to the editor command. This will tell MacVim to keep the terminal.

**Comment by guillaumesamson** [comment]
The `-f`flag works perfectly, thanks !

Guillaume


Le 21/07/2019 à 16:55, Arseny Nasokin a écrit :

**Comment by eirnym** [comment]
You're welcome

**Comment by eirnym** [comment]
@guillaume-smo is it still an issue, please, close the issue if not.
