### ISSUE TITLE
MacVim resizes itself repeatedly in split view

### ISSUE THREAD

**Issue by kamitchell** [macvim-dev/macvim#93]
To reproduce:

1. Create a split view with MacVim and another app.
2. Do anything that causes a screen redraw in MacVim, like editing a file.
3. MacVim pushes the split over to the right.
4. Try to adjust the split to where you want it.
5. As soon as you let go of the drag, MacVim resizes itself and pushes the split to the right.
6. ``:set columns=40`` MacVim sizes to 40 columns...
7. ...but then goes back to taking over most of the screen after certain refresh operations.

My theory is that MacVim is trying to make the view fit the size of the screen; I don't think it understands fully the difference between full screen mode, and split-view mode.

Recording this in case somebody else wants to get to it first.

Before:

![screen shot 2015-10-11 at 2 29 11 pm](https://cloud.githubusercontent.com/assets/45672/10418590/e8076700-7024-11e5-9526-ef31202a80a2.png)

After:

![screen shot 2015-10-11 at 2 30 44 pm](https://cloud.githubusercontent.com/assets/45672/10418593/f6507c20-7024-11e5-867c-ae51886c7ff6.png)

**Comment by splhack** [comment]
Could you test https://github.com/macvim-dev/macvim/pull/103 ?
You can use the test binary https://github.com/macvim-dev/macvim/releases/tag/snapshot-test .

**Comment by robacarp** [comment]
@splhack I pulled down that binary and didn't experience any issues. I've had a little unpredictability with this specific bug, but I was able to reliably reproduce it this morning on master and following the same procedures it didn't present on the test build.

**Comment by datalogics-kam** [comment]
Thanks!

MacVim is no longer fighting over where the split is, at least. It still acts funny when trying to, say, use CTRL-P to open a file after resizing the split. Second time trying CTRL-P works.

I also have a programming question that I'll make on the pull request itself.

**Comment by splhack** [comment]
> CTRL-P to open a file after resizing the split. Second time trying CTRL-P works.

It seems Vim redraw issue. Could you create new issue?
