### ISSUE TITLE
Can't install macvim with brew: source checksum mismatch

### ISSUE THREAD

**Issue by vaga** [macvim-dev/macvim#934]
**Describe the bug**
When I install `macvim` from source, I have a checksum error.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `brew install -s macvim` 

**Expected behavior**
Compile and install macvim snapshot 157.

**Screenshots**
```
$ brew install -s macvim

==> Downloading https://github.com/macvim-dev/macvim/archive/snapshot-157.tar.gz
Already downloaded: /Users/vaga/Library/Caches/Homebrew/downloads/a2bf89c012fe784b3fbbe52088edf84d635cf9d0f81126ded4d56e27cb72429f--macvim-snapshot-157.tar.gz
Error: An exception occurred within a child process:
  ChecksumMismatchError: SHA256 mismatch
Expected: dbe7f4b19231989bb24f1e3e42f1372451974d8a224ba17498a103c325635e0a
  Actual: 6447bce4ec7b7f67327da8f7b2e9d4f4b748c1afb90f781fecb6b4a3f54cf0a0
 Archive: /Users/vaga/Library/Caches/Homebrew/downloads/a2bf89c012fe784b3fbbe52088edf84d635cf9d0f81126ded4d56e27cb72429f--macvim-snapshot-157.tar.gz
To retry an incomplete download, remove the file above.
```

**Environment (please complete the following information):**
 - Vim version 8.1-157
 - OS: MacOS Mojave

**Additional context**

An issue is already open in homebrew repo https://github.com/Homebrew/homebrew-core/issues/42304
> You should ask the macvim developers if the change was intentional. If it was you can make the change in homebrew using this guide: https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request

**Comment by eirnym** [comment]
Thanks for your report, @vaga 

MacVim build 157 was a pre-release for a while and maintainers of the formula in Homebrew didn't release that. 

The best way it to contact with maintainers of formula as it supported by other people.

**Comment by ychin** [comment]
I do wonder if the pre-release status broke something. I random into some Travis issues that I had to resolve and released a new binary to fix the issue, so maybe Homebrew caught the old one. I can post on the other issue in Homebrew.

**Comment by eirnym** [comment]
@ychin 

There's a live checking for unupgraded packages in package distributing systems like Homebrew and MacPort. This live check is based on regex and if version looks like a next major version, people tend to upgrade a package version semi-automatically. I've tried to catch the "pre-release" status for some app and regex became very complex to avoid such situations.

**Comment by 9mm** [comment]
This is now a problem for me on catalina. not quite sure what to do

**Comment by ychin** [comment]
I will push out a new version soon to address this (seems easier than the alternative). Apologies for the previous pre-release status as I ran into some build issues. It should have been smoothed out now.

**Comment by SMillerDev** [comment]
The alternative is just changing the checksum and refering to this thread in the pull request. Which seems a lot easier.

**Comment by 9mm** [comment]
Hey @ychin totally no rush, just curious when you planned to do that? I tried using `--HEAD` and it works, but it introduces a lot of other changes to fonts that I don't want.

**Comment by eirnym** [comment]
@ychin Could you mark beta releases as `158-b1` or something like this to eliminate this issue in the future?

**Comment by ychin** [comment]
@9mm snapshot 159 is released now. Homebrew should be updated shortly.

**Comment by 9mm** [comment]
awesome!

**Comment by ychin** [comment]
> @ychin Could you mark beta releases something like `158-b1` or something like this to eliminate this issue in the future? Automatic verifier lists versions by regex, totally ignoring "pre-release" label

Just to respond to this it was a mistake of mine to have rebased while using the same tag. I intended to release it but had to make a change. In the future I would just increment the snapshot number.

**Comment by mvcouwen** [comment]
Homebrew version got updated. Could you check if the problem got fixed?

**Comment by 9mm** [comment]
it works!

**Comment by eirnym** [comment]
@vaga Could you check if you're still experiencing the issue? If not, please, close the issue
