### ISSUE TITLE
gx stop open link in browser

### ISSUE THREAD

**Issue by ApolloTang** [macvim-dev/macvim#935]
**Describe the bug**
The normal mode keystroke `gx` suppose to open the link under cursor in browser. Below is the animated gif of expected behaviour executed on vim:

![2019-08-15 01 45 56](https://user-images.githubusercontent.com/1150961/63075282-1df45300-beff-11e9-8078-dbcd6bb5d664.gif)

This function is broken in macvim.
Below is the animated gif of broken behaviour executed on macvim:

![2019-08-15 01 46 52](https://user-images.githubusercontent.com/1150961/63075323-4b410100-beff-11e9-96cb-280a2e2bd5ed.gif)

Notice in above, broken behaviour for macvim:  
when typing `gx` while the cursor is on  a http link, it executes curl command to download the request into a temp buffer and open it in a new macvim window.

**To Reproduce on macvim**
1. place cursor over any valid http link 
2. escape to normal mode
3. press `gx`
4. you will see it does not open the link in browser

**Expected behavior**
it should open the link in default browser

**Environment**
 - Bug screenshot was taken on MacVim version 8.1.1722(157)
 - macOS 10.14.8
 - Expected behaviour screenshot was taken on vim 8.1.1700 running in iterm 3.3.2beta2

**Comment by ychin** [comment]
Dup of #925. It's a bug in Vim.
