### ISSUE TITLE
Get MacVim to build in Xcode 11

### ISSUE THREAD

**Issue by ychin** [macvim-dev/macvim#936]
Currently MacVim doesn't build under Xcode 11 beta. Get it to build.

**Comment by eirnym** [comment]
Does it mean we'll have a separate xcodeproject or we'll cut off some old macOS versions?

**Comment by lilyball** [comment]
Xcode 11 is now GM and this still fails to build. It looks like PSMTabBarControl is accessing a system-supplied ivar that no longer exists in the MacOSX10.15 SDK (`NSActionCell` no longer declares its ivars).

**Comment by lilyball** [comment]
Also this isn't a 10.15 issue. Xcode 11 runs on macOS 10.14.

**Comment by lilyball** [comment]
After applying a temporary patch (just declaring an `id _controlView` ivar, since I don't actually use the GUI tabs myself so I don't care if they work), I get another build failure ad code signing:

```
CodeSign /Users/lily/Dev/Scratch/macvim/src/MacVim/build/Debug/MacVim.app (in target 'MacVim' from project 'MacVim')
    cd /Users/lily/Dev/Scratch/macvim/src/MacVim
    export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
    
Signing Identity:     "-"

    /usr/bin/codesign --force --sign - --entitlements /Users/lily/Dev/Scratch/macvim/src/MacVim/build/MacVim.build/Debug/MacVim.build/MacVim.app.xcent --timestamp=none /Users/lily/Dev/Scratch/macvim/src/MacVim/build/Debug/MacVim.app

/Users/lily/Dev/Scratch/macvim/src/MacVim/build/Debug/MacVim.app: code object is not signed at all
In subcomponent: /Users/lily/Dev/Scratch/macvim/src/MacVim/build/Debug/MacVim.app/Contents/MacOS/macvim-askpass
```

I'm not sure what's going on here.

**Comment by lilyball** [comment]
If I temporarily get rid of `macvim-askpass` (mark it as copy only on installing) then I can build. Something about having it there is confusing Xcode. Even if I mark it to code sign on copy it doesn't work, probably because it's just a shell script.

**Comment by lilyball** [comment]
The code signing issue can be worked around by disabling code signing entirely with `CODE_SIGN_IDENTITY = ""`. Of course, your distributions are signed.

**Comment by lilyball** [comment]
Another issue: Xcode 11 seems to set `LSMinimumSystemVersion` to the deployment target, which I don't think Xcode 10 did. If I configure with `MACOSX_DEPLOYMENT_TARGET` in my environment, the configure script omits that from the `XCODEFLAGS` setting, but if the env var is missing then the configure script sets it to the current OS version. But since `xcodebuild` doesn't inherit environment anymore (that changed a few years ago), setting `MACOSX_DEPLOYMENT_TARGET` in the environment of the config script actually *breaks* the deployment target and causes Xcode to default to the SDK version.

As a result, building MacVim right now with Xcode 11 installed and `MACOSX_DEPLOYMENT_TARGET` set produces an app where the minimum version is set to 10.15, which won't run on the current (10.14) machine.

**Comment by lilyball** [comment]
Finally got it built and running. The following patch works around the `_controlView` issue; in a very quick test it seems GUI tabs still work just fine, but since I don't use them I don't know if there are any subtle differences:

```diff
--- a/src/MacVim/PSMTabBarControl/source/PSMTabBarCell.m
+++ b/src/MacVim/PSMTabBarControl/source/PSMTabBarCell.m
@@ -13,7 +13,9 @@
 #import "PSMTabDragAssistant.h"
 
 
-@implementation PSMTabBarCell
+@implementation PSMTabBarCell {
+    id _controlView;
+}
 
 #pragma mark -
 #pragma mark Creation/Destruction
```

**Comment by lilyball** [comment]
Looking again, the `_controlView` ivar in the 10.14 SDK is explicitly documented as saying it's not actually used for anything anymore and that we should be using the `-controlView` and `-setControlView:` accessors.

**Comment by markwu** [comment]
Apple already shipped Xcode 11 to Software update and I just found macvim build with Xcode 11 failed today.

**Comment by airblade** [comment]
I'm trying to `brew reinstall macvim` but it fails.  Xcode is at v11.0 and I'm on macOS 10.14.  I have opened Xcode and installed the additional components.

**Comment by markwu** [comment]
I fixed xcode11 build problem temporary in my formula according to @lilyball 's contribution. Jut for your reference.

https://github.com/markwu/homebrew-personal/blob/master/Formula/macvim.rb

**Comment by markwu** [comment]
I change my formula to use https://github.com/macvim-dev/macvim/pull/946, it works good.

**Comment by ychin** [comment]
Sorry for the delay but it should be fixed now.

> If I configure with MACOSX_DEPLOYMENT_TARGET in my environment, the configure script omits that from the XCODEFLAGS setting, but if the env var is missing then the configure script sets it to the current OS version. But since xcodebuild doesn't inherit environment anymore (that changed a few years ago), setting MACOSX_DEPLOYMENT_TARGET in the environment of the config script actually breaks the deployment target and causes Xcode to default to the SDK version.

@lilyball Yeah this seems like a bug in the configure script. Our `.travis.yaml` file kind of works around by manually setting `XCODEFLAGS` as well but seems convoluted. Will fix this later.
