### ISSUE TITLE
E363 when opening json file containing long base64 lines

### ISSUE THREAD

**Issue by kkew3** [macvim-dev/macvim#938]
**Describe the bug**
E363 error occurs when opening json file containing long lines.

**To Reproduce**
1. Download the attached example file (`base64.txt`: 128K), and rename it to `base64.json`)
2. Run `vim --clean base64.json`)
3. The error occurs (see below for complete error)

The error message:

```
E363: pattern uses more memory than 'maxmempattern'
Press ENTER or type command to continue
'redrawtime' exceeded, syntax highlighting disabled
Press ENTER or type command to continue
```

**Expected behavior**
No error, since 128K is not large memory consumption, and other text editor, say, Sublime text, has no problem with it.

**Environment (please complete the following information):**
 - Vim version: VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul 28 2019 01:07:30); Included patches: 1-1722
 - OS: macOS 10.14.6
 - Terminal: iTerm2

** Additional Context **
The attached `base64.txt` contains shuffled base64 image but it shouldn't affect the problem describe above.

[base64.txt](https://github.com/macvim-dev/macvim/files/3551177/base64.txt)

**Comment by eirnym** [comment]
Hi @kkew3, thank you for an issue

Have you tried to reproduce it without GUI?

**Comment by eirnym** [comment]
I've reproduced it without GUI, so please report the issue to https://github.com/vim/vim as the issue is there, not in GUI part implemented in this repository.

**Comment by kkew3** [comment]
Oh yes. I've also reproduced without GUI. Thanks for your suggestion.

**Comment by eirnym** [comment]
Back reference: https://github.com/vim/vim/issues/4885
