### ISSUE TITLE
mvim launches iTerm or Terminal window

### ISSUE THREAD

**Issue by jdeppe-pivotal** [macvim-dev/macvim#945]
**Describe the bug**
Running on Mac OS `10.14.6` and using Macvim `8.1.1722`.

When I run `mvim foo.txt` a new terminal window is launched that appears to be running the vim app. However it does not accept any input and anything I type appears in the original window.

I believe this may just be as a result of upgrading to `10.14.6` as everything was working until very recently. I cannot think of anything else that may have changed in my environment.

**Expected behavior**
Running `mvim` should launch the GUI version of Macvim.

**Comment by eirnym** [comment]
@jdeppe-pivotal Thank you for your issue

Please, tell how MacVim was installed (Homebrew, MacPorts, GitHub distribution, built manually, etc). 
Also I'd ask you to run `mvim --clean foo.txt` to eliminate your configuration changes and plugins used. This is required to understand if problem is in MacVim itself or in one of the plugins used in your configuration.
If it was the configuration problem, please, disable all the plugins, to check if any configuration option affects this issue.

**Comment by jdeppe-pivotal** [comment]
Seems like it was just environmental. I noticed a couple of these processes running:
```
/usr/local/Cellar/macvim/8.1-157/MacVim.app/Contents/MacOS/MacVim -MMNoWindow yes
```
Once I killed those everything worked again.

As you can probably tell, the app was installed via `brew`.
