### ISSUE TITLE
MacVim from brew crashes in MacOS Catalina 10.15

### ISSUE THREAD

**Issue by robjperez** [macvim-dev/macvim#947]
**Describe the bug**
Having installed MacVim from brew (`macvim: stable 8.1-157 (bottled), HEAD`)
It crashes because it looks for Ruby 2.3 and Catalina has Ruby 2.6

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `vim --clean` (or `gvim --clean`)
```
dyld: Library not loaded: /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/libruby.2.3.0.dylib
  Referenced from: /usr/local/Cellar/macvim/8.1-157/MacVim.app/Contents/MacOS/Vim
  Reason: image not found
fish: 'vim' terminated by signal SIGABRT (Abort)
```

In 10.15:

```
➜  ls /System/Library/Frameworks/Ruby.framework/Versions/
2.6     Current
```

**Environment:**
 - Vim version: from brew `macvim: stable 8.1-157 (bottled), HEAD`
 - OS: macOS 10.15
 - Terminal: iTerm2

**Comment by bmulholland** [comment]
And if you follow this answer (adapted for relevant versions): https://stackoverflow.com/a/49450569

```
% install_name_tool -change /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/libruby.2.3.0.dylib /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/libruby.2.6.dylib /usr/local/Cellar/macvim/8.1-157/MacVim.app/Contents/MacOS/Vim
```

Then:

```
% mvim                                                                        ~
dyld: Symbol not found: _rb_cFixnum
  Referenced from: /usr/local/Cellar/macvim/8.1-157/MacVim.app/Contents/MacOS/Vim
  Expected in: /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/libruby.2.6.dylib
 in /usr/local/Cellar/macvim/8.1-157/MacVim.app/Contents/MacOS/Vim
```

**Comment by samuelabreu** [comment]
Just uninstalled brew version and system version (8.1.1312) is working fine.

**Comment by nebiros** [comment]
> Just uninstalled brew version and system version (8.1.1312) is working fine. Maybe in a few days brew will update with a version compatible with Catalina.
> 
> Following https://github.com/macvim-dev/macvim/wiki/Building works just fine on Catalina

I remove the brew version, and then I re-install it with the --HEAD option: `brew install macvim --HEAD`, start working again, :D

**Comment by henryiii** [comment]
Should be fixed soon, either by fixing the hash, or a new MacVim release: https://github.com/Homebrew/homebrew-core/issues/44995

I *think* the current version is broken on Catalina, since I could not compile it but could compile master. So probably will have to wait for the new MacVim release.

**Comment by 9mm** [comment]
Now the fonts look all weird. So frustrating whatever Catalina did fucked up so many of my fonts. Everything looks like absolute trash now

**Comment by eirnym** [comment]
@henryiii  There was a problem with Xcode11 compatibility, this is why you can't compile it on Catalina. And with Xcode10 you can compile it. Temporarily, can apply the patch (#946) merged to master manually to make it buildable.

Official build (from GitHub) works fine on Catalina from the very beginning of Catalina public beta was out (I haven't tested it on Catalina Developer Betas).

**Comment by eirnym** [comment]
@9mm Not everything, but many things were broken, yes.

**Comment by 9mm** [comment]
@eirnym do you know where I might start tracking down the cause of the issue? For example the sidebar (nerdtree) looks very wack now .. i cant put my finger on why but its like the letter spacing has a full pixels in between each letter.

![image](https://user-images.githubusercontent.com/1386207/66426820-86bfef00-e9c7-11e9-9729-8afcf830f168.png)

**Comment by eirnym** [comment]
@9mm Please, create another issue for that.

**Comment by bmulholland** [comment]
@eirnym Do you know if a new version (with the xcode 11 fix and hopefully a catalina bottle) will be out soon?

**Comment by henryiii** [comment]
The brew bottle with patch applied is being worked on. Installing with `brew install macvim --HEAD` works fine for the moment as a workaround.

**Comment by lipeng1667** [comment]
> > Just uninstalled brew version and system version (8.1.1312) is working fine. Maybe in a few days brew will update with a version compatible with Catalina.
> > Following https://github.com/macvim-dev/macvim/wiki/Building works just fine on Catalina
> 
> I remove the brew version, and then I re-install it with the --HEAD option: `brew install macvim --HEAD`, start working again, :D

YES, `brew unlink macvim` and `brew install macvim --HEAD` works for me !

**Comment by ychin** [comment]
New release just came out (https://github.com/macvim-dev/macvim/releases/tag/snapshot-159). Let me know if it works. It may take a short while to have Homebrew update to 159 as well. You can use this badge to check: [![Homebrew package](https://repology.org/badge/version-for-repo/homebrew/macvim.svg)](https://repology.org/metapackage/macvim/versions) (Copied from README.md)

**Comment by henryiii** [comment]
Made the PR: https://github.com/Homebrew/homebrew-core/pull/45454

**Comment by mvcouwen** [comment]
New PR for snapshot 159 by @henryiii : Homebrew/homebrew-core#45455

**Comment by aaron-goshine** [comment]
Cantalina has broken vim;

**Comment by eirnym** [comment]
even their own build

**Comment by mvcouwen** [comment]
@eirnym @aaron-goshine The system version of vim should be working now. Could you check that? Also
`brew install macvim --HEAD`
should work for now (as suggested above).

Once the problem in Homebrew/homebrew-core#45455 gets fixed, the regular homebrew version should be working too.

**Comment by eirnym** [comment]
thank you for suggestion, it works!

**Comment by mvcouwen** [comment]
Should be solved by PR Homebrew/homebrew-core#45624.

**Comment by eirnym** [comment]
@robjperez Could I ask to install the fresh vim from Homebrew (not `HEAD`) and check if this still an issue?

**Comment by 9mm** [comment]
I'm using v159 (not `--HEAD`) on Catalina latest from Homebrew and it works great

➜  Desktop brew list macvim
/usr/local/Cellar/macvim/8.1-159/bin/gview
/usr/local/Cellar/macvim/8.1-159/bin/gvim
/usr/local/Cellar/macvim/8.1-159/bin/gvimdiff
/usr/local/Cellar/macvim/8.1-159/bin/gvimex
/usr/local/Cellar/macvim/8.1-159/bin/mview
/usr/local/Cellar/macvim/8.1-159/bin/mvim
/usr/local/Cellar/macvim/8.1-159/bin/mvimdiff
/usr/local/Cellar/macvim/8.1-159/bin/mvimex
/usr/local/Cellar/macvim/8.1-159/bin/vi
/usr/local/Cellar/macvim/8.1-159/bin/view
/usr/local/Cellar/macvim/8.1-159/bin/vim
/usr/local/Cellar/macvim/8.1-159/bin/vimdiff
/usr/local/Cellar/macvim/8.1-159/bin/vimex
/usr/local/Cellar/macvim/8.1-159/MacVim.app/Contents/ (2208 files)

**Comment by robjperez** [comment]
> @robjperez Could I ask to install the fresh vim from Homebrew (not `HEAD`) and check if this still an issue?

Just did it and it works ok, I think we can close this ticket already
