### ISSUE TITLE
MacVim + Catalina Font issues

### ISSUE THREAD

**Issue by 9mm** [macvim-dev/macvim#949]
**Describe the bug**

Before installing Catalina, MacVim font looked fantastic when paired with `Anonymous Pro` (https://www.marksimonson.com/fonts/view/anonymous-pro).

Now however, everything looks very weird, like it's spaced out with extra pixels between each letter.

Here is before installing (I believe this was Mojave when I took this screenshot):

![](https://camo.githubusercontent.com/94b1845976fae635016b6e0c5074524b7a02ea9e/68747470733a2f2f7261772e6769746875622e636f6d2f396d6d2f646f7466696c65732f6d61737465722f73637265656e73686f742e706e67)

and here is after

![image](https://user-images.githubusercontent.com/1386207/66428082-3e560080-e9ca-11e9-940d-0494309ef8c3.png)

**Environment (please complete the following information):**
 - Vim version [e.g. 8.1.1234] (Or paste the result of `vim --version`.) latest mvim from homebrew --HEAD
 - OS: [e.g. Ubuntu 18.04, Windows 10 1809, macOS 10.14] 10.15
 - Terminal: [e.g. GNOME Terminal, mintty, iTerm2, tmux, GNU screen] (Use GUI if you use the GUI.) iterm 3

**Comment by 9mm** [comment]
I actually booted up an old computer using Mojave just so I could make sure I wasn't crazy. Here's the exact same MacVim configuration using the same fonts. You can see from NerdTree listing that it's very different

<img width="1383" alt="Screen Shot 2019-10-08 at 1 04 44 PM" src="https://user-images.githubusercontent.com/1386207/66429591-30ee4580-e9cd-11e9-9979-a96456306a91.png">
<img width="271" alt="Screen Shot 2019-10-08 at 1 04 57 PM" src="https://user-images.githubusercontent.com/1386207/66429592-3186dc00-e9cd-11e9-87d2-8ee7fa0cea2b.png">

**Comment by 9mm** [comment]
I actually loaded it into Photoshop... the pixels actually line up perfectly but they are just a tiny bit less transparent. I assume this isn't a MacVim issue, but some way OSX changed how they render fonts. I really wish I knew what it was because I absolutely hate it. All the fonts look naked and weak

**Comment by 9mm** [comment]
Ah! The line-height most definitely DID change though, maybe that's what it is... there's so much space between the lines

**Comment by eirnym** [comment]
on different versions of macOS and in different apps I've used different fonts. This was also caused with different font versions. 

Currently I use `Fira Code` and previously I've used `Anonymous Pro` and `Roboto` and few others.

**Comment by 9mm** [comment]
I checked the version of Anonymous Pro but it seems to be the same for the last many years. It definitely changed though when upgrading to Catalina, and now I can't restore the old lineheight. :/

**Comment by eirnym** [comment]
Could you test the font in different applications to check if they process it differently?

Lastly MacVim started to honor more font properties on initialization, so it could affect as well.

**Comment by 9mm** [comment]
Oh wow... I just re-downloaded release 157 from the releases page and it was fixed (it was probably because i installed with --HEAD because of the other issue with homebrew hash not matching).

So the new changes are definitely crazy on my end. Is that something that is 100% going to be merged into 158 and onwards? If so I will basically stop updating because the font is sadly unusable because it is hideous haha

**Comment by 9mm** [comment]
or is there any way to use a new version but keep the old font settings?

**Comment by eirnym** [comment]
Could you explain the difference? Screenshot difference will be the best.

**Comment by 9mm** [comment]
You can see it very clearly in the sidebar, it adds so much whitespace between the lines

BEFORE (GOOD):

<img width="954" alt="Screen Shot 2019-10-10 at 4 19 39 PM" src="https://user-images.githubusercontent.com/1386207/66613296-d80fe000-eb79-11e9-8ada-c5caf30ffe04.png">

AFTER (BAD):

<img width="1210" alt="bad" src="https://user-images.githubusercontent.com/1386207/66613297-da723a00-eb79-11e9-8d9d-6806ec0ccc48.png">

**Comment by skyksandr** [comment]
As a workaround I `set linespace=-1`

**Comment by eirnym** [comment]
@9mm Thank you for sharing screenshots.

You use modified `Anonymous Pro` font, and I don't except the external modification will preserve same quality as `Anonymous Pro` itself.

I installed the font and tested it:
* Powerline/AirLine symbols are not provided by this font
* Linespace between size 12 (and below) and 13 (and above) is different.
* Japanese symbols are not shown with sizes below 12 (inclusive).

I'd select 13 which on my screen looks the best if I'd use this font. 

Anonymous Pro (original), size 12:
<img width="963" alt="Zrzut ekranu 2019-10-14 o 11 56 05" src="https://user-images.githubusercontent.com/485399/66743188-a8165480-ee79-11e9-89e4-84b3ca2f4a97.png">

Anonymous Pro (original), size 13:
<img width="963" alt="Zrzut ekranu 2019-10-14 o 11 56 55" src="https://user-images.githubusercontent.com/485399/66743217-b9f7f780-ee79-11e9-8f61-506c45624c5e.png">

Fira Code Light (original), size 12:
<img width="963" alt="Zrzut ekranu 2019-10-14 o 11 59 03" src="https://user-images.githubusercontent.com/485399/66743362-05aaa100-ee7a-11e9-9ea6-30df8db44bed.png">

**Comment by 9mm** [comment]
@eirnym the font itself shouldn't have changed with the added powerline symbols. I tested here with both fonts, and you can use photoshop to verify they're identical, so the difference came from macvim/vim (installing old macvim with same powerline font works how it should)

both fonts identical:
<img width="954" alt="Screen Shot 2019-10-14 at 8 03 41 AM" src="https://user-images.githubusercontent.com/1386207/66761923-cff5c000-ee59-11e9-8763-1b22f9f0d983.png">
<img width="954" alt="Screen Shot 2019-10-14 at 8 04 02 AM" src="https://user-images.githubusercontent.com/1386207/66761925-cff5c000-ee59-11e9-9bbc-f5e1ef2ca617.png">

here is how it used to be for reference:

![image](https://user-images.githubusercontent.com/1386207/66762093-27942b80-ee5a-11e9-8e09-5ba809531afc.png)

@skyksandr thanks... i messed around with linespace and nothing actually changed before, and I just tried again this morning and it works! I probably mixed up set/let. This fixed it, thanks! Crazily enough, I had to do `set linespace=-3` to get it back exactly how it was

**Comment by eirnym** [comment]
@9mm I've tried a few fonts from that repo (if we speak about the same mod repo), but fonts there in general seems to be very outdated for a few releases at least and some parameters were altered (like linespacing for some fonts). So yes, general symbols might not be changed, but other parameters and symbols might not be the same.

Thus I've found a font with these symbols and which support a few languages I type with support of airline symbols (you see my last screenshot above).

**Comment by 9mm** [comment]
Sorry, maybe were not talking about the same thing. I was basically wondering what in macvim/vim changed for my fonts to be so different (it's not related to the 'with powerline' modification of the font because i've used the same font for 5 years or so). You may be correct that it modifies/ruins the font, but I haven't noticed any changes besides what is caused by the `--HEAD` version of vim.

With all that said though, the `set linespace=-3` thing fixed the issue so I suppose I'm good as long as that continues to work :D I still out of curiosity would be curious to know what changed though, because I see the same linespace problem with the normal `Anonymous Pro` directly from the source: https://www.marksimonson.com/fonts/view/anonymous-pro

**Comment by eirnym** [comment]
I use the same build from GitHub (as I used on 10.14) and in my case nothing has been changed. For my font build from the `HEAD` changes nothing as well. 

Underneath MacVim uses `NSTextView` which may changed font processing somehow (e.g. use some font parameters not used before or use them differently).

**Comment by eirnym** [comment]
Your font looks better with `HEAD` and I hope these changes will be released as soon as possible (see #905 for details)

<img width="844" alt="Zrzut ekranu 2019-10-15 o 10 28 28" src="https://user-images.githubusercontent.com/485399/66814348-c1310b00-ef36-11e9-858d-a13403f38939.png">
<img width="963" alt="Zrzut ekranu 2019-10-15 o 10 28 40" src="https://user-images.githubusercontent.com/485399/66814349-c1310b00-ef36-11e9-9c0c-7b249e0987a4.png">
<img width="963" alt="Zrzut ekranu 2019-10-15 o 10 28 56" src="https://user-images.githubusercontent.com/485399/66814350-c1310b00-ef36-11e9-89d7-2795c7612f01.png">

**Comment by ychin** [comment]
The new release should have fixed it. Let me know if it doesn't work and I'll see if there are other reasons why it doesn't look right @9mm .

**Comment by 9mm** [comment]
Thanks it fixed it, and now I removed linespace=-3 👍

**Comment by eirnym** [comment]
Good to hear that!
