### ISSUE TITLE
If the MacVim window is closed in full screen split view on El Capitan, MacVim application would crash every time.

### ISSUE THREAD

**Issue by linse073** [macvim-dev/macvim#95]
2015-10-16 23:19:43.336 MacVim[1958:257935] *** Assertion failure in -[_NSWindowFullScreenTransition startExitFullScreenTransitionForCGWindow:targetFrame:duration:completionHandler:], /Library/Caches/com.apple.xbs/Sources/AppKit/AppKit-1404.11/AppKit.subproj/NSWindowFullScreenTransition.m:650
2015-10-16 23:19:43.340 MacVim[1958:257935] An uncaught exception was raised
2015-10-16 23:19:43.341 MacVim[1958:257935] Invalid parameter not satisfying: _fullScreenState == NSExitingFullScreen
2015-10-16 23:19:43.341 MacVim[1958:257935] (
	0   CoreFoundation                      0x00007fff81d56bd2 __exceptionPreprocess + 178
	1   libobjc.A.dylib                     0x00007fff8b1854fa objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff81d5b8aa +[NSException raise:format:arguments:] + 106
	3   Foundation                          0x00007fff847a4f46 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 198
	4   AppKit                              0x00007fff82b87e27 -[_NSFullScreenTransition startExitFullScreenTransitionForCGWindow:targetFrame:duration:completionHandler:] + 168
	5   AppKit                              0x00007fff82b87d74 -[_NSWindowFullScreenTransition _exitFullScreenModeForWindow:duration:completionHandler:] + 156
	6   AppKit                              0x00007fff829870a9 NSPerformVisuallyAtomicChange + 147
	7   AppKit                              0x00007fff8315a1b6 __106-[_NSWindowFullScreenTransition _performExitFullScreenModeForWindow:options:customWindows:doKitAnimation:]_block_invoke + 954
	8   AppKit                              0x00007fff83075be7 __177-[NSDockConnection(FullScreenMessages) sendFullScreenExitForTransition:synchronous:window:exitForClose:backgroundWindows:participatingWindows:customAnimation:completionHandler:]_block_invoke + 60
	9   libxpc.dylib                        0x00007fff8c18a74b _xpc_connection_reply_callout + 26
	10  libxpc.dylib                        0x00007fff8c18a6ec _xpc_connection_call_reply + 36
	11  libdispatch.dylib                   0x00007fff89685453 _dispatch_client_callout + 8
	12  libdispatch.dylib                   0x00007fff89698c1c _dispatch_main_queue_callback_4CF + 1685
	13  CoreFoundation                      0x00007fff81d0c789 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	14  CoreFoundation                      0x00007fff81ccb73d __CFRunLoopRun + 1949
	15  CoreFoundation                      0x00007fff81ccad38 CFRunLoopRunSpecific + 296
	16  HIToolbox                           0x00007fff8b5a1d55 RunCurrentEventLoopInMode + 235
	17  HIToolbox                           0x00007fff8b5a1b8f ReceiveNextEventCommon + 432
	18  HIToolbox                           0x00007fff8b5a19cf _BlockUntilNextEventMatchingListInModeWithFilter + 71
	19  AppKit                              0x00007fff8284cf3a _DPSNextEvent + 1067
	20  AppKit                              0x00007fff8284c369 -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 454
	21  AppKit                              0x00007fff82840ecc -[NSApplication run] + 682
	22  AppKit                              0x00007fff8280a162 NSApplicationMain + 1176
	23  libdyld.dylib                       0x00007fff86d4e5ad start + 1
	24  ???                                 0x0000000000000003 0x0 + 3
)
2015-10-16 23:19:43.342 MacVim[1958:257935] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: _fullScreenState == NSExitingFullScreen'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff81d56bd2 __exceptionPreprocess + 178
	1   libobjc.A.dylib                     0x00007fff8b1854fa objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff81d5b8aa +[NSException raise:format:arguments:] + 106
	3   Foundation                          0x00007fff847a4f46 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 198
	4   AppKit                              0x00007fff82b87e27 -[_NSFullScreenTransition startExitFullScreenTransitionForCGWindow:targetFrame:duration:completionHandler:] + 168
	5   AppKit                              0x00007fff82b87d74 -[_NSWindowFullScreenTransition _exitFullScreenModeForWindow:duration:completionHandler:] + 156
	6   AppKit                              0x00007fff829870a9 NSPerformVisuallyAtomicChange + 147
	7   AppKit                              0x00007fff8315a1b6 __106-[_NSWindowFullScreenTransition _performExitFullScreenModeForWindow:options:customWindows:doKitAnimation:]_block_invoke + 954
	8   AppKit                              0x00007fff83075be7 __177-[NSDockConnection(FullScreenMessages) sendFullScreenExitForTransition:synchronous:window:exitForClose:backgroundWindows:participatingWindows:customAnimation:completionHandler:]_block_invoke + 60
	9   libxpc.dylib                        0x00007fff8c18a74b _xpc_connection_reply_callout + 26
	10  libxpc.dylib                        0x00007fff8c18a6ec _xpc_connection_call_reply + 36
	11  libdispatch.dylib                   0x00007fff89685453 _dispatch_client_callout + 8
	12  libdispatch.dylib                   0x00007fff89698c1c _dispatch_main_queue_callback_4CF + 1685
	13  CoreFoundation                      0x00007fff81d0c789 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	14  CoreFoundation                      0x00007fff81ccb73d __CFRunLoopRun + 1949
	15  CoreFoundation                      0x00007fff81ccad38 CFRunLoopRunSpecific + 296
	16  HIToolbox                           0x00007fff8b5a1d55 RunCurrentEventLoopInMode + 235
	17  HIToolbox                           0x00007fff8b5a1b8f ReceiveNextEventCommon + 432
	18  HIToolbox                           0x00007fff8b5a19cf _BlockUntilNextEventMatchingListInModeWithFilter + 71
	19  AppKit                              0x00007fff8284cf3a _DPSNextEvent + 1067
	20  AppKit                              0x00007fff8284c369 -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 454
	21  AppKit                              0x00007fff82840ecc -[NSApplication run] + 682
	22  AppKit                              0x00007fff8280a162 NSApplicationMain + 1176
	23  libdyld.dylib                       0x00007fff86d4e5ad start + 1
	24  ???                                 0x0000000000000003 0x0 + 3
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by splhack** [comment]
the same as #62
