### ISSUE TITLE
Error while starting

### ISSUE THREAD

**Issue by rishabhdeepsingh** [macvim-dev/macvim#950]
```
mvim
dyld: Library not loaded: /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/libruby.2.3.0.dylib
  Referenced from: /usr/local/Cellar/macvim/8.1-157/MacVim.app/Contents/MacOS/Vim
  Reason: image not found
[1]    37367 abort      mvim
```
**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `mvim `

**Environment (please complete the following information):**
 - VIM - Vi IMproved 8.1 (2018 May 18, compiled Sep  5 2019 21:03:34)
 - OS: MacOS Cataline 10.15
 - Terminal: tmux

**Comment by eirnym** [comment]
@rishabhdeepsingh Thank you for an issue,

The reason is macOS Catalina deprecated scripting languages. It seems your issue is duplicated with #939.

**Comment by KISSMonX** [comment]
#947  same error
