### ISSUE TITLE
Vim fails to load Ruby dynamic library

### ISSUE THREAD

**Issue by definelicht** [macvim-dev/macvim#952]
**Describe the bug**
After upgrading to Catalina, macvim fails to open while trying to load the Ruby dynamic library:
```
% vim
dyld: Library not loaded: /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/libruby.2.3.0.dylib
  Referenced from: /usr/local/Cellar/macvim/8.1-157/MacVim.app/Contents/MacOS/Vim
  Reason: image not found
```
Catalina seems to ship with Ruby 2.6, not Ruby 2.3, so this path does not exist.

I have tried:
- `brew update && brew upgrade`
- `brew reinstall ruby && brew reinstall macvim`

**To Reproduce:**
`vim --clean` produces the error.

**Expected behavior:**
Vim should successfully open, using Ruby 2.6, either from macOS or from Homebrew.

**Screenshots:**
N/A

**Environment:**
 - Vim version 8.1-157
 - macOS 10.15 Catalina
 - iTerm2 3.3.5

**Additional context:**
N/A

**Comment by skyksandr** [comment]
`brew uninstall && brew install macvim --HEAD` fixed the issue for me

**Comment by EmpireJones** [comment]
Just to clarify the above suggestion:
`brew uninstall macvim && brew install macvim --HEAD`

**Comment by JezuzStardust** [comment]
Completely unrelated to the ruby thing, but the solution to install from head produces the following error when using the help command (:h) 

`E432: Tags file not sorted: /usr/local/Cellar/macvim/HEAD-dc07a14/MacVim.app/Contents/Resources/vim/runtime/doc/tags`

I actually get the same error many times when using help. One time for each plugin that I have.

**Comment by eirnym** [comment]
@JezuzStardust Please, create a new issue for this.

**Comment by definelicht** [comment]
An unfortunate consequence of this workaround:
```
macvim: A full installation of Xcode.app is required to compile
this software. Installing just the Command Line Tools is not sufficient.
```

**Comment by chdiza** [comment]
It has always been the case that a full installation of Xcode is needed to build MacVim.

**Comment by definelicht** [comment]
Yes, but it's not necessary to build MacVim when using the bottled version. So for those of us who don't have Xcode installed, we have to download and install this enormous thing for this workaround.

**Comment by eirnym** [comment]
@definelicht you still can download MacVim from GitHub and it's magically works on `Catalina 10.15` even it's not the latest commit.

**Comment by taiyangc** [comment]
`brew install macvim --HEAD` does not work for me:

```
==> Cloning https://github.com/macvim-dev/macvim.git
Updating /Users/eric/Library/Caches/Homebrew/macvim--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at dc07a14 Merge pull request #943 from ychin/macvim-tests
==> ./configure --with-features=huge --enable-multibyte --with-macarchs=x86_64 --enable-perlinterp --enable-rubyinterp
==> make
Last 15 lines from /Users/eric/Library/Logs/Homebrew/macvim/02.make:
	17  libdyld.dylib                       0x00007fff73a41405 start + 1
	18  ???                                 0x000000000000001d 0x0 + 29
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Command CompileAssetCatalog failed with a nonzero exit code

warning: Traditional headermap style is no longer supported; please migrate to using separate headermaps and set 'ALWAYS_SEARCH_USER_PATHS' to NO. (in target 'QuickLookStephen' from project 'QuickLookStephen')warning: Traditional headermap style is no longer supported; please migrate to using separate headermaps and set 'ALWAYS_SEARCH_USER_PATHS' to NO. (in target 'MacVim' from project 'MacVim')
** BUILD FAILED **


The following build commands failed:
	CompileAssetCatalog /tmp/macvim-20191013-29805-1oz8sa9/src/MacVim/build/Release/PSMTabBarControl.framework/Versions/A/Resources /tmp/macvim-20191013-29805-1oz8sa9/src/MacVim/PSMTabBarControl/Media.xcassets
(1 failure)
make[1]: *** [macvim] Error 65
make: *** [first] Error 2

READ THIS: https://docs.brew.sh/Troubleshooting

These open issues may also help:
macvim: upstream retagged https://github.com/Homebrew/homebrew-core/pull/45016
```

**Comment by rr0ss0rr** [comment]
Can someone place a working version in homebrew?

Thanks

**Comment by eirnym** [comment]
Looks like HB doesn't specify where to look ruby, so ViM's `configure` doesn't recognize ruby 2.3 and refuses to build.

Formula's maintainers test only if `Python 3` was taken from `Homebrew`, but not `Ruby`. Please, report them to fix the formula

**Comment by eirnym** [comment]
I have an idea: please, test `vim` from Homebrew and if there's no problems, just synchronize formulas

**Comment by rr0ss0rr** [comment]
vim install via brew works fine on catalina ... but I have no clue (at this moment) on creating or replacing a brew formula.

**Comment by eirnym** [comment]
@mvcouwen Thank you! 

@definelicht Could you check if it works in your environment?

**Comment by rr0ss0rr** [comment]
THANKS!  .. Works great in 10.15

**Comment by definelicht** [comment]
@eirnym I can confirm that this works for me as well. Thank you!

**Comment by TomasJavurek** [comment]
I can not confirm the solution, always end up with:
`Warning: Building python@3.9 from source:
  The bottle needs the Apple Command Line Tools to be installed.
  You can install them, if desired, with:
    xcode-select --install
`
although py3.9 is installed on my mac.

**Comment by TomasJavurek** [comment]
and the `xcode-select --install` is complaining about not finding a proper sources.
