### ISSUE TITLE
Graphical rendering issue on 10.15 (Catalina)

### ISSUE THREAD

**Issue by isaki** [macvim-dev/macvim#955]
**Describe the bug**
Characters such as 'j' and 'g' have their bottoms cut off on MacOS Catalina.

**To Reproduce**
1. Run gvim from the command line.
2. Start typing.

**Expected behavior**
I expect my fonts to be readable.

**Screenshots**
![image](https://user-images.githubusercontent.com/10616227/66761795-b7de6a80-ee72-11e9-9f00-12fe9fe30064.png)

**Environment (please complete the following information):**
 - Vim version: 8.1.1722 (157)
 - OS: MacOS 10.15
 - Terminal: Terminal.app

**Additional context**
N/A

**Comment by eirnym** [comment]
@isaki Thank you for an issue,

There's an [issue](#949) for this already, please, write your experience there

**Comment by isaki** [comment]
#949 does not appear to be directly related. #905 looks to be exactly this issue. I'll close this ticket and watch that ticket.
