### ISSUE TITLE
Cannot use vim-plug

### ISSUE THREAD

**Issue by zxdposter** [macvim-dev/macvim#958]
Macvim cannot use vim-plug

**Describe the bug**
line    1:
E117: Unknown function: plug#begin
line    4:
E492: Not an editor command: Plug 'bling/vim-airline'
line    5:
E492: Not an editor command: Plug 'vim-airline/vim-airline-themes'
line    9:
E117: Unknown function: plug#end

**Environment (please complete the following information):**
 - Vim version [e.g. 8.1.1234] (Or paste the result of `vim --version`.) 8.1
 - OS: [e.g. Ubuntu 18.04, Windows 10 1809, macOS 10.14] 10.15
 - Terminal: [e.g. GNOME Terminal, mintty, iTerm2, tmux, GNU screen] iTerm2

**Comment by eirnym** [comment]
@zxdposter thank you for an issue.

As per description I can't say that it is MacVim's fault or not. Could you share more information on the problem? 
* Which build do you use? from GitHub, from Homebrew, from MacPorts, etc
* Does it work on Terminal and GUI versions? 
* Could you share your `vimrc` or minimal example which doesn't work? 
* Could you please be sure that vim-plug has been installed properly? 

I personally can't reproduce your problem with `8.1.1722 (157)` from GitHub and `8.1.2102` from `HEAD`.

**Comment by zxdposter** [comment]
@eirnym 
My version is 8.1.2168
![image](https://user-images.githubusercontent.com/13846260/66990799-727f9e80-f0f9-11e9-8a6b-92f32d725fd9.png)


> Which build do you use? from GitHub, from Homebrew, from MacPorts, etc

Homebrew

> Does it work on Terminal and GUI versions?

It work in Terminal, not work on GUI version

> Could you share your vimrc or minimal example which doesn't work?

`ln -s ~/.config/nvim/init.vim ~/.vimrc`

~/.config/nvim/init.vim

```vim
for f in split(glob('~/.config/nvim/rc/*.vim'), '\n')
    exe 'source' f
endfor
```
~/.config/nvim/rc/1-plugins.vim
```vim
call plug#begin('~/.local/share/nvim/plugged')
Plug 'bling/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
call plug#end()
```

> Could you please be sure that vim-plug has been installed properly?

plug.vim path is ~/.local/share/nvim/site/autoload/plug.vim
Maybe plug.vim path is not correct.

**Comment by zxdposter** [comment]
Alreay known, I put plug.vim wrong path, sorry to bother you.

**Comment by eirnym** [comment]
BTW, I use auto install script for `vim-plug`:

```vim
function! s:InstallVimPlug()
    if empty(glob('~/.vim/autoload/plug.vim'))
      silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
      autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
    endif
endfunction

call s:InstallVimPlug()
```
