### ISSUE TITLE
Can't not open macvim in Catalina(10.15)

### ISSUE THREAD

**Issue by tracyone** [macvim-dev/macvim#959]
I just downloaded the latest release (MacVim.dmg)

https://github.com/macvim-dev/macvim/releases/tag/snapshot-159

<img width="532" alt="Screen Shot 2019-10-17 at 22 36 16" src="https://user-images.githubusercontent.com/4246425/67018946-898cb380-f12e-11e9-9f9a-b0df5cd8232f.png">

**Comment by tracyone** [comment]
Ok, I have found the solution:

https://www.reddit.com/r/MacOS/comments/cgj1qs/cant_be_opened_because_apple_cannot_check_it_for/

**Comment by ychin** [comment]
Will be fixed soon. The next release will be notarized. It was my mistake not catching that as I tested the release on Mojave.
