### ISSUE TITLE
Wrong highlighting in visual mode after latest update

### ISSUE THREAD

**Issue by antaed** [macvim-dev/macvim#960]
I have set guifg=NONE for the Visual highlighting group in my colorscheme but it gets overridden after the latest update:

![Screenshot 2019-10-18 at 11 10 40](https://user-images.githubusercontent.com/30736986/67077704-71517e80-f198-11e9-995a-13c7b1a64cf0.png)

**Comment by antaed** [comment]
Of course:
[antaed.vim.zip](https://github.com/macvim-dev/macvim/files/3744091/antaed.vim.zip)

**Comment by eirnym** [comment]
`guifg/guibg` is taken from `Normal` if it is `NONE` and visual `fg/bg` override syntax `fg/bg` respectively. 

Could you tell me what effect you want to achieve?

**Comment by antaed** [comment]
I would like to have only the background highlighted in visual mode and preserve the syntax highlighting on the foreground, like this:
![Annotation 2019-10-18 185908](https://user-images.githubusercontent.com/30736986/67109582-7be03800-f1d9-11e9-90c4-c549f5da8287.jpg)

(the screenshot above was taken on my Windows machine, the color scheme is exactly the same)

**Comment by eirnym** [comment]
ViM in Terminal has the same issue and MacVim only paints that Vim said to paint. 

You should report this issue to the upstream https://github.com/vim/vim as this issue definitely belongs there. 

Sorry for misunderstanding on the beginning.

**Comment by antaed** [comment]
All right, I'll report the issue there. Thank you very much for your support, closing this right now.

**Comment by eirnym** [comment]
Please, report here the ticket url for tracking

**Comment by antaed** [comment]
Ok, I'll be back with the url. Do you happen to know which patch created the issue? It must be a very recent one as it worked fine until today.

**Comment by eirnym** [comment]
I have snapshot `159`, and have the same problem as you. Thank you for reporting!

**Comment by eirnym** [comment]
@antaed the issue was fixed in the upstream, I hope it will be in snapshot 160

**Comment by antaed** [comment]
That was very quick, you're awesome. Thank you so much!

**Comment by ychin** [comment]
@eirnym What other issues are you looking to be fixed upstream?

**Comment by antaed** [comment]
Honestly, I haven't found any other issues besides this one. Thanks for asking

**Comment by eirnym** [comment]
@ychin as far as I see, other issues were fixed. It even could be built with Python 3.8.
