### ISSUE TITLE
Homebrew bottle fails to build on Mojave

### ISSUE THREAD

**Issue by mvcouwen** [macvim-dev/macvim#961]
When trying to update the homebrew version of Macvim to snapshot 159, the bottle fails to build on Mojave, see Homebrew/homebrew-core#45455. There seems to be a Ruby mismatch.

The problem becomes apparent when running `brew test macvim`. The output shows that `macvim --version` has no Ruby support (-ruby) although Mac OS X Mojave ships with Ruby 2.3: see https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/50000/version=mojave/testReport/brew-test-bot/mojave/test_macvim/

Most likely, there is a problem with the way Homebrew tries to build the bottle. So probably a Homebrew problem and no Macvim problem. However, I hope that some Macvim developers care about this problem as many users use Macvim through Homebrew. Hopefully, we could shed some light on the build failure.

It seems that there are two possible solutions to this problem.

Either we could ignore the problem and remove Ruby support from the Mojave bottle. I don't know how many users actually rely on Ruby support... On the other hand, I think that Apple plans to stop shipping Ruby with OS X so we might need to do this in the future anyway.

The other option would be to solve the Homebrew problem, which seems to be the superior solution at this point. However, I have no clue how to do this since the problem does not seem to occur on a local computer.

I am not a very experienced user but I love the work you guys have done with Macvim. Therefore, I would very much like to help to solve this problem. I might be interpreting this problem completely wrong, so don't hesitate to tell me and point me in the right direction. Basically, any help would very much be appreciated.

**Comment by eirnym** [comment]
@mvcouwen Thank you for an issue,  

Reading the log and formula, `configure` script of ViM (MacVim is only GUI) haven't found library or it was incompatible for some reason. Formula explicitly checks that ruby was included into the build.

You could try to build it manually by yourself and provide full build logs to discover what really happened.

**Comment by eirnym** [comment]
Returning to #952, it looks only for Ruby 2.6 shipped with Catalina. Alternatively, you could build with `ruby/dyn` (or download an official GitHub build), install Ruby 2.6 and try to use it.

**Comment by mvcouwen** [comment]
@eirnym Thanks for the help! Are you suggesting to make the Macvim formula dependent on ruby? And then use homebrew ruby to build Macvim?

On the other hand, I have read somewhere that deleting SDKROOT (as done in the formula for Sierra and Yosemite) might solve the mismatch. Is this worth trying?

**Comment by eirnym** [comment]
1) Could you try the build from GitHub if it works for you? 
2) please, try to build MacVim manually explicitly providing ruby paths for `configure` script, such as `--with-ruby-command` as per documentation for `configure` script. 

BTW, I don't know why the formula for `MacVim` is different with formula for [`vim`](https://github.com/Homebrew/homebrew-core/blob/f7a0810a4fccd31b6efe58928eaaddd93936fb99/Formula/vim.rb)

**Comment by mvcouwen** [comment]
Solved by PR Homebrew/homebrew-core#45624.
