### ISSUE TITLE
Precompiled Snapshot 159 fails to detect appearance change

### ISSUE THREAD

**Issue by L-TChen** [macvim-dev/macvim#973]
**Describe the bug**
The variable `v:os_appearance` always returns 0 for the compiled binary of Snapshot 159; it works as expected if compiled manually and changing the deployment target to macOS 10.14+ or above. 

**To Reproduce**
Run MacVim in the dark mode and `:echo v:os_appearance` always shows `0`.

**Expected behavior**
The variable `v:os_appearance` should be `1` in the dark mode.

**Proposed solution**
Another binary for macOS 10.14+. 

The API used to change the variable is only available on macOS 10.14+ ([here](https://developer.apple.com/documentation/appkit/nsappearancenamedarkaqua?language=objc)). Changing the deployment target to 10.14 is rather radical in my opinion. A temporary solution would be to provide another binary for macOS 10.14+.

**Comment by eirnym** [comment]
@L-TChen 
It's true. However, it peeks correct theme on restart (direct switch doesn't work well) which could be used to fix the problem
