### ISSUE TITLE
There is no commit for Snapshot 160

### ISSUE THREAD

**Issue by chdiza** [macvim-dev/macvim#976]
No commit was made for Snapshot 160, even though it's been released.

This means "About MacVim" still shows "159".

**Comment by ychin** [comment]
I just forgot to push to master (only pushed the tag). It won’t mess up the hash.

**Comment by eirnym** [comment]
I think it's enough to have a patch from Homebrew/MacPorts side to show appropriate value if needed

**Comment by ychin** [comment]
Fixed. There shouldn't be a need to rehash etc. It's the same commit.
