### ISSUE TITLE
Building on Yosemite with Xcode 7.1 only builds an ElCap version

### ISSUE THREAD

**Issue by chdiza** [macvim-dev/macvim#98]
On Yosemite, I installed Xcode 7.1 and the associated CLT for 10.10.

When I tried to build MacVim, just to test to see if the new things were working, it built successfully.  However, the resulting MacVim.app is ElCap-only.  If I try to open it, I get a dialog box saying:
```
You have OS X 10.10.5. The application requires OS X 10.11 or later.
```

Is anyone else seeing this?  I don't know if this is an Xcode bug, a CLT bug, a sign that MacVim's xcodeproj needs updating, or the result of some local weirdness like an old Xcode cache laying around somewhere.

Also worth noting: during this build, I saw clang warnings that I thought had been recently squelched:

```
gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/os_macosx.o os_macosx.m
MacVim/MacVim.m:315:13: warning:
      'propertyListFromData:mutabilityOption:format:errorDescription:' is
      deprecated: first deprecated in OS X 10.10 - Use
      propertyListWithData:options:format:error: instead.
      [-Wdeprecated-declarations]
            propertyListFromData:data
            ^
/System/Library/Frameworks/Foundation.framework/Headers/NSPropertyList.h:56:1: note:
      'propertyListFromData:mutabilityOption:format:errorDescription:' has been
      explicitly marked deprecated here
+ (id)propertyListFromData:(NSData *)data mutabilityOption:(NSPropertyLi...
^
MacVim/MacVim.m:330:41: warning:
      'dataFromPropertyList:format:errorDescription:' is deprecated: first
      deprecated in OS X 10.10 - Use dataWithPropertyList:format:options:error:
      instead. [-Wdeprecated-declarations]
    return [NSPropertyListSerialization dataFromPropertyList:self
                                        ^
/System/Library/Frameworks/Foundation.framework/Headers/NSPropertyList.h:52:1: note:
      'dataFromPropertyList:format:errorDescription:' has been explicitly marked
      deprecated here
+ (NSData *)dataFromPropertyList:(id)plist format:(NSPropertyListFormat)...
^
MacVim/MacVim.m:352:13: warning:
      'propertyListFromData:mutabilityOption:format:errorDescription:' is
      deprecated: first deprecated in OS X 10.10 - Use
      propertyListWithData:options:format:error: instead.
      [-Wdeprecated-declarations]
            propertyListFromData:data
            ^
/System/Library/Frameworks/Foundation.framework/Headers/NSPropertyList.h:56:1: note:
      'propertyListFromData:mutabilityOption:format:errorDescription:' has been
      explicitly marked deprecated here
+ (id)propertyListFromData:(NSData *)data mutabilityOption:(NSPropertyLi...
^
3 warnings generated.
```

**Comment by steeef** [comment]
I can confirm the same issue, yes.

**Comment by chdiza** [comment]
I wonder if this will affect building MacVim under Homebrew.  (I'm not in a position to test right now.)  If it does affect that, we're going to have Homebrew on our case to fix this.  If it does not affect that, perhaps `superenv` contains a clue as to how to fix it here.

**Comment by splhack** [comment]
On Travis-CI with Xcode 7.1, it seems ok
https://travis-ci.org/macvim-dev/macvim/builds/87139674

**Comment by chdiza** [comment]
A build log wouldn't show the problem, though, right?  The problem is once one tries to open MacVim.app after a normal-looking build completes.  The build process over here gives no indication that anything's wrong (at least, not that I can tell).

Make even `make test` wouldn't show it, because maybe the `Vim` binary inside of MacVim.app is not ElCap-only.

**Comment by splhack** [comment]
Sorry, what's the problem? MacVim.app doesn't work on before El Capitan?
Could you try https://github.com/macvim-dev/macvim/releases/download/snapshot-test/MacVim-7.4.dmg ?
It's compatible with 10.9 or later. https://github.com/macvim-dev/macvim/blob/30304bfbc0fdb7e4caad263f0cf85aa524467bad/.travis.yml#L12

**Comment by chdiza** [comment]
> Sorry, what's the problem?

The problem is that on a Yosemite machine, with Xcode 7.1 and the Yosemite CLT for 7.1, the result of going through the build process is an .app that only runs on El Cap.

**Comment by chdiza** [comment]
Building MacVim on an ElCap machine, with Xcode 7.1 and the ElCap CLT for 7.1, is fine with zero problems.

If that test snapshot was built on an ElCap machine, then even if it can run on a Yosemite machine, there is still a problem.

**Comment by splhack** [comment]
It sounds like you should submit a report to Apple
https://developer.apple.com/bug-reporting/using-bug-reporter/

**Comment by chdiza** [comment]
> It sounds like you should submit a report to Apple

I have no evidence that this issue extends beyond MacVim.  Also, in the event that they were to reply, I am not qualified to answer queries about our build system.

**Comment by splhack** [comment]
By the way, are you sure to set Deployment Target for your old OS X?

**Comment by chdiza** [comment]
> By the way, are you sure to set Deployment Target for your old OS X?

I did not, because I have never, ever had to do that before, even going back to 2007 and Tiger.  Thus it never occurred to me to do that.  I'll try it.

**Comment by splhack** [comment]
Xcode 7.1 includes only OS X 10.11 SDK. You should set Deployment Target if you want to build app for supporting OS X 10.10 or earlier.

**Comment by chdiza** [comment]
Since it appears that this is a general problem (not just me), whatever "set Deployment Target" means should be added to the wiki.  Do you mean the shell variable `MACOSX_DEPLOYMENT_TARGET`?  This is, of course, assuming that that actually fixes the problem.

I won't have access to a Yosemite machine for testing until tomorrow.

**Comment by chdiza** [comment]
I don't think this issue should be closed.  We have to decide on the appropriate fix, and then publicize it.  Anyone else having this problem should be able to see this issue in the list of open issues.

Turns out, I did have a 10.10 machine to test on.  Setting `export MACOSX_DEPLOYMENT_TARGET="10.10"` before the `configure` step worked for me.  @steeef Try that out and see if it works for you.

Setting such a variable has never been required before.  I think that the xcodeproj (or whatever) should be tweaked so that a user doesn't have to do that.

**Comment by jpetrie** [comment]
I do feel like this bears some investigation, although I'm not sure how to go about it as I don't have the capability to try to reproduce the scenario you're describing.

The MacVim project doesn't set the deployment target currently. That means Xcode should use the value of the base SDK (see [here](https://developer.apple.com/library/ios/documentation/DeveloperTools/Conceptual/cross_development/Configuring/configuring.html#//apple_ref/doc/uid/10000163i-CH1-SW1)). I *think* this is what we want: you specify which base SDK you want to use to build MacVim, and that controls which OS feature version is checked by the preprocessor stuff. I don't think we want to explicitly set a deployment target in the project file, because then you'll need to change it every time you want to build for older OS versions).

The Xcode environment variable for the base SDK is `SDKROOT`. It's possible you need to set that on the command line (via a flag or env var) prior to building?

(The .xcodeproj does need to be updated for other reasons, but I've been holding off because I don't know how they will impact the ability to build for and under old OS versions.)

**Comment by chdiza** [comment]
> It's possible you need to set that on the command line (via a flag or env var) prior to building?

It has never before been necessary for a user to *manually* do this, on any version of MacVim or any version of OS X.  Ideally, it would stay this way, and we will tweak some file instead.  I wasn't sure whether the xcodeproj was the appropriate place for making a tweak, and I also don't know what the tweak would even need to be.  Perhaps our `configure` or `Makefile` is the place; maybe we need `Makefile` to contain `xcodebuild --somethingnew the_usual_params ...`.

By the way, this problem exists even when building under Homebrew on a Yosemite machine.  I'm watching the Homebrew issues page like a hawk in case this problem gets reported there.

**Comment by jpetrie** [comment]
> It has never before been necessary for a user to manually do this

Right, this is something that changed slightly in Xcode 7.1 I believe.

Try setting the Deployment Target in the .xcodeproj to as old as you can, then (or at least as old as Tiger?). That might be an option; it doesn't *seem* to cause anything insurmountable for building on newer platforms, except for a few link warnings we'd need to address, although I haven't investigated thoroughly.

On the chance that it might matter (I suspect it will not), I pushed [a commit to a branch that upgrades the Xcode project](https://github.com/macvim-dev/macvim/tree/fix/xcodeproj-warnings) as recommended. Nothing that changed seemed relevant to this scenario though.

**Comment by chdiza** [comment]
There are two relevant instances of `MACOSX_DEPLOYMENT TARGET` in the xcodeproj, and both of them are set to the empty string.  I replaced the empty strings with "10.4", and this caused building to fail on both ElCap and Yosemite.

So I tried again with "10.6", and this time building was successful on Yosemite.  I'll now double-check that building will still work on ElCap.

But note that if building will succeed on ElCap, we will have the problem of what to do about Tiger and Leopard.  I have some thoughts about this, which I'll share soon.

**Comment by jpetrie** [comment]
I wonder if we should just bite the bullet and create distinct release branches for each major OS revision.

**Comment by chdiza** [comment]
OK, with the Deployment Target set to 10.6 inside the xcodeproj, building on ElCap succeeds.

So here are some questions:

1. Though this is a fix for the current issue (the one in the title of the thread), is this the RIGHT fix for it?

2. If the answer to (1) is "yes", what do we do about Tiger and Leopard?  Again, I have some thoughts on this, but they're probably better to put in their own issue.

**Comment by chdiza** [comment]
> I wonder if we should just bite the bullet and create distinct release branches for each major OS revision.

I was thinking that, under the macvim-dev organization, we can have a fork dedicated to Tiger/Leopard.  This fork would basically leave `src/macvim` untouched, but bring in Vim updates.  At first I thought, "why not just a separate git branch for Tiger/Leo?", but then it occurred to me that we don't want to in effect require `git` in order for someone on Tiger or Leo to build MacVim.

**Comment by chdiza** [comment]
> (The .xcodeproj does need to be updated for other reasons, but I've been holding off because I don't know how they will impact the ability to build for and under old OS versions.)

Out of curiosity, why does it need to be updated?  Obviously, it COULD be updated, but are we building a defective MacVim on newer OSes if we don't update it?  I don't think we are, but I could be wrong.

For the sake of knowledge, I will check out your xcodeproj-updating branch and check to see what happens on Tiger and Leopard.

**Comment by jpetrie** [comment]
> I was thinking that, under the macvim-dev organization, we can have a fork dedicated to Tiger/Leopard. This fork would basically leave src/macvim untouched, but bring in Vim updates. At first I thought, "why not just a separate git branch for Tiger/Leo?", but then it occurred to me that we don't want to in effect require git in order for someone on Tiger or Leo to build MacVim.

You need git to clone the repository, unless you download the `.zip` from GitHub. But if you do that, you can specifically download the `.zip` of a desired branch (for example a hypothetical `release-10.5` branch). 

You also can't fork the same project twice in the same organization (if you try to fork `macvim` under `macvim-dev`, GitHub will refuse), which means integration of bug fixes to common code would be more involved and the two repositories wouldn't really be connected in any way meaningfully visible to the source control system.

I feel like branches would be the better option, but you're right it's probably worth a more involved discussion of the pros and cons (and there are cons) in a separate issue.

> Out of curiosity, why does it need to be updated? Obviously, it COULD be updated, but are we building a defective MacVim on newer OSes if we don't update it? I don't think we are, but I could be wrong.

Strictly speaking we don't, which is why I haven't bothered until now to see if it might have any impact on this issue. But much of the changes it causes *today* are just useful conveniences or best-practice sort of things Apple wants to enforce.

However, until we do, we generate warnings during builds and warnings are usually bad. Just like the deprecation warnings, it's better to address them sooner, rather then when Apple finally pulls the trigger and *requires* you to make a change. For example, one day they finally *will* remove [NSCopyBits](https://github.com/macvim-dev/macvim/issues/88) and when they do, we won't be able to ship MacVim until we fix it because it's totally unusable without that function call. I'd rather deal with those kinds of things ahead of time.

**Comment by chdiza** [comment]
> But if you do that, you can specifically download the .zip of a desired branch

As long as there is a way to do that from the web (without using git at the CLI), that's OK with me, because we can always tell people in the wiki exactly how to do this.

**Comment by chdiza** [comment]
I had wrongly assumed there was no way to do that.

**Comment by chdiza** [comment]
> For the sake of knowledge, I will check out your xcodeproj-updating branch and check to see what happens on Tiger and Leopard.

Building on Tiger seemed to go off without a hitch.  Leopard is next.

**Comment by chdiza** [comment]
Worked on Leo too.

**Comment by splhack** [comment]
Setting Deployment Target to 10.8 or 10.9 in xcodeproj is the reasonable solution.

1. AFAIK, UNIX binary executable (for example, Vim executable) from, at least, 10.8 to 10.11 is completely binary compatible. No need to set Deployment Target. UNIX binary executable using 10.11 SDK does work well on 10.8 without Deployment Target. Thus, No-Deployment-Target for Vim executable, Deployment-Target=10.8or10.9 for MacVim app, is safe.

2. I think there are no reasons to support Tiger, Leopard, or the other old versions of OS X in this repository. Apple never release security patches for the old versions. It's extremely dangerous. And how many users use MacVim on 10.7 or earlier??

**Comment by chdiza** [comment]
> I think there are no reasons to support Tiger, Leopard, or the other old versions of OS X in this repository

MacVim is just a plain text editor.  There's no reason for those older systems to not be able to run a plain text editor, and no reason for a plain text editor that's really just Vim to acquire so many bells and whistles that it can't be built on older systems.  (Also, if we ever want to merge this into mainline Vim, they will surely want the oldest possible systems supported; they recognize, rightly, that older machines deserve good text editors.  Doesn't even gVim run on all manner of ancient machines?)

So if @jpetrie is right that we can't fork this repo under the macvim-dev organization, there is _a_ reason to support older versions in this repo (even if it's in a non-master branch, which I am totally fine with).

Perhaps another option (I don't know if it's available) would be to simply create a new empty repo and then have one of us push to it, creating a duplicate that's not a github-fork, into which non-GUI changes from master could be pulled.

> Apple never release security patches for the old versions

Just because older machines don't get security patches, and might thus be dangerous for SOME stuff, doesn't mean they aren't useful for coding or writing text.  I'm not doing my online banking on a Tiger/Leo machine's version of Safari, but I am writing academic papers, emailing with `mutt`, and trying to teach myself ruby, each with MacVim.

There has been a commitment to supporting old systems since the very inception of MacVim in 2007, and I hope we can continue it.  If I recall correctly (and I might not be), the only reason MacVim didn't support Panther at first is that Panther was irrevocably missing something crucial wrt CoreText or something like that, without which MacVim couldn't operate.

It would be especially tragic to lose such support just because Apple screwed up Xcode 7.1.

**Comment by chdiza** [comment]
Forgive my ignorance, but can't the `configure` script be made to check for what version of OS X we're on, and set `$MACOSX_DEPLOYMENT_TARGET` appropriately?

**Comment by splhack** [comment]
Could you try #104 ?

It is totally ok for me, I don't push people to remove code for older OS X if someone actively supports older OS X in this repository.

**Comment by chdiza** [comment]
Thanks, I'll try it when I have my Tiger machine at my disposal.

**Comment by chdiza** [comment]
Whoops, I meant when I have my Yosemite machine at my disposal.  (Though I will be testing this on Tiger too.)

**Comment by chdiza** [comment]
> Could you try #104 ?

It works on Yosemite under Xcode 7.1.
