### ISSUE TITLE
version 8.1.2234 no window

### ISSUE THREAD

**Issue by burakk** [macvim-dev/macvim#981]
After updating to version 8.1.2234, when opening any file macvim shows the initial opening screen for a very short period and dissapears. Program is not closing but no window is shown.

 - Vim version version 8.1.2234
 - macOS 10.14.6

**Comment by eirnym** [comment]
@burakk Thank you for an issue,

Could you, please, include a bit more information about your environment to help us with your issue?

* How do you run MacVim and how do you open a file?
* How did you installed MacVim? 
* Which snapshot do you use? (both 160 and 161 have the same ViM patch level)
* Could you try run MacVim without any plugins and settings and check if problem persists? (you could use `mvim --clean`/`gvim --clean`/`vim --clean` for it)
* Could you try vim in `Terminal.app`/`iTerm.app` by running `mvim -v --clean`?
* Please, run `defaults read org.vim.MacVim | grep 'MM\|SU'` in terminal and put there the output

**Comment by eirnym** [comment]
PS: I can't reproduce it with `build 161` on `macOS 10.15`

**Comment by eirnym** [comment]
It's great news that you have no problem now.

**Comment by ychin** [comment]
It could be related to the hardened runtime / app notarization issues that 8.1.2234 had. Your build should say 2334 now. Feel free to reopen if you have this issue. Also, if you are using Homebrew to install MacVim it's best if you don't use the auto-updater to update MacVim and use Homebrew's built-in update instead. The next update will disable the auto-updater to make sure that's the case.
