### ISSUE TITLE
--disable-sparkle doesn't work

### ISSUE THREAD

**Issue by chdiza** [macvim-dev/macvim#984]
I just tried out `--disable-sparkle`.

I still see "Check for updates" under the "MacVim" menubar menu.  I can even select it, and I will see "You're up to date".

There is also still stuff about checking for updates in the MacVim preferences, but that might be more complex to remove.

**Comment by ychin** [comment]
Seems to work for me. How exactly are you building it? You should be able to just pull to latest build, and build as follows:

    ./configure --disable-sparkle
    make
    open src/MacVim/build/Release/MacVim.app

If you want to you can even do `make distclean` before running those steps to make sure everything is cleaned, but I don't believe that's necessary.

You may also want to make sure the `configure` logs has this:

    checking --disable-sparkle argument... yes

**Comment by chdiza** [comment]
Sorry for the noise, I somehow wound up with two MacVims and was looking at the old one.
