### ISSUE TITLE
Bold Deactivate

### ISSUE THREAD

**Issue by marcelsby** [macvim-dev/macvim#988]
Hello, nice work! MacVim is awesome. I want deactivate all bold fonts, is there any way to do this?

**Comment by eirnym** [comment]
@marcel-yamamoto Thank you for an issue, 

Please, correct me if I understood you incorrectly, I think you could do this by changing a highlighting scheme you use. You can found about this information in `:help :hi`. 

MacVim uses bold font only when it is set in highlighting or you specified a bold font to use (`:guifont`).

**Comment by eirnym** [comment]
@marcel-yamamoto could you be more specific on your issue?
