### ISSUE TITLE
The latest icons don't show up properly on Leopard or Tiger

### ISSUE THREAD

**Issue by chdiza** [macvim-dev/macvim#99]
I'm passing on a report in the Tigerbrew repo: https://github.com/mistydemeo/tigerbrew/issues/354

I never noticed this because I immediately overwrite the icons with my own personal ones whenever a build completes.

This only affects the most recent update to the icons from a few months back, as far as I know.

**Comment by chdiza** [comment]
A little playing around reveals that the app icon is fine on Tiger/Leo at sizes 32x32 and below, but vanishes at anything bigger than that.

**Comment by chdiza** [comment]
I've created an `icns` file for the app icon, using IconComposer from 10.5.8, that seems to make the problem go away on Leopard and Tiger.

I'll see if it still works on newer systems, but I suspect that the hi-res portions got chopped out, and that those portions were what Leopard/Tiger couldn't handle.  (E.g., on Leopard, IconComposer claimed there was no 128x128 edition of the icon, even though ElCap's IconComposer says there is.)

If I'm right, then we'll have to figure out (a) how to ensure that Tiger/Leopard get the right `MacVim.icns`, and (b) whether Snow Leopard also exhibits this issue.  I have no Snow Leopard machine to test with.

(a) would be easy to fix if we end up making a separate git branch for Leo/Tig.

**Comment by splhack** [comment]
10.4 and 10.5 is no longer suppored.
