### ISSUE TITLE
[Feature Request] Disable scrollbars

### ISSUE THREAD

**Issue by ScrumpyJack** [macvim-dev/macvim#990]
I'm happy navigating vim from the keyboard, and with nerdtree active, we get one scrollbar each side of a macvim window.

Would be nice to have the option to disable scrollbars altogether.

**Comment by ScrumpyJack** [comment]
fixed with

set guioptions=

**Comment by ychin** [comment]
You don't want to do that. Using `set guioptions=` will unset *all* guioptions, including future additions to Vim meaning you will lose out on new features.

Instead, do this instead: `set guioptions-=lLrR`

**Comment by ScrumpyJack** [comment]
hmm

`set guioptions-=lLrR `

shows both scrollbars, and I can't find a combo that removes both

**Comment by chdiza** [comment]
I can confirm that e.g. `se go-=lLrRb` leaves a righthand scrollbar in place.  Seems like a bug.

**Comment by ychin** [comment]
It's not a bug. I just forgot how `set` works.  You have to remove them one by one by doing:

```
set go-=l
set go-=L
set go-=r
set go-=R
```

But yeah it's fair, you can always go for an additive approach by adding only the `guioptions` that you care about instead of subtracting from defaults.
