### ISSUE TITLE
Window Menu Bug on macOS 10.15.2

### ISSUE THREAD

**Issue by isaki** [macvim-dev/macvim#992]
**Describe the bug**
The Window menu has many repeated, duplicate entries. This is similar to #566 and #593.

**To Reproduce**
TBD

**Expected behavior**
The menu should not have so many duplicates.

**Screenshots**
![image](https://user-images.githubusercontent.com/10616227/70828592-a86b9700-1db9-11ea-8e92-77edba2bf101.png)

**Environment (please complete the following information):**
 - Vim version:
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct 30 2019 11:57:56)
macOS version
Included patches: 1-2234
Compiled by travis@Traviss-Mac.local
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl               +file_in_path      +mouse_urxvt       -tcl
+arabic            +find_in_path      +mouse_xterm       +termguicolors
+autocmd           +float             +multi_byte        +terminal
+autochdir         +folding           +multi_lang        +terminfo
-autoservername    -footer            -mzscheme          +termresponse
+balloon_eval      +fork()            +netbeans_intg     +textobjects
+balloon_eval_term +fullscreen        +num64             +textprop
+browse            -gettext           +odbeditor         +timers
++builtin_terms    -hangul_input      +packages          +title
+byte_offset       +iconv             +path_extra        +toolbar
+channel           +insert_expand     +perl/dyn          +transparency
+cindent           +job               +persistent_undo   +user_commands
+clientserver      +jumplist          +postscript        +vartabs
+clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +virtualedit
+cmdline_hist      +langmap           +python/dyn        +visual
+cmdline_info      +libcall           +python3/dyn       +visualextra
+comments          +linebreak         +quickfix          +viminfo
+conceal           +lispindent        +reltime           +vreplace
+cryptv            +listcmds          +rightleft         +wildignore
+cscope            +localmap          +ruby/dyn          +wildmenu
+cursorbind        +lua/dyn           +scrollbind        +windows
+cursorshape       +menu              +signs             +writebackup
+dialog_con_gui    +mksession         +smartindent       -X11
+diff              +modify_fname      -sound             -xfontset
+digraphs          +mouse             +spell             +xim
+dnd               +mouseshape        +startuptime       -xpm
-ebcdic            +mouse_dec         +statusline        -xsmp
+emacs_tags        -mouse_gpm         -sun_workshop      -xterm_clipboard
+eval              -mouse_jsbterm     +syntax            -xterm_save
+ex_extra          +mouse_netterm     +tag_binary        
+extra_search      +mouse_sgr         -tag_old_static    
-farsi             -mouse_sysmouse    -tag_any_white     
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: clang   -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/readline/lib -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o Vim -framework Cocoa -framework Carbon       -lm  -lncurses -liconv -framework AppKit   -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE 
```
 - OS: macOS 10.15.2
 - Terminal: GUI

**Additional context**
This is very reminiscent of a previous bug in this menu; however in this case I did not open windows that were already open (which is my reliable way of triggering the previous bug). I will update this thread once I find a way to reliably reproduce this.

**Comment by eirnym** [comment]
@isaki Thank you for an issue, 

This is a known bug (#566). The original issue was about the `Full Screen`, this is an additional menu which is broken. I bet the source and the way to reproduce is the same

**Comment by isaki** [comment]
I can reproduce it when no windows are open. Keep opening and closing the same file from the command line.

![image](https://user-images.githubusercontent.com/10616227/70935305-e4973580-200d-11ea-903c-25d138445ce4.png)

**Steps Taken:**

- touch a file (call it foo.txt)
- Repeatedly open and close foo.txt with /Applications/MacVim.app/Contents/bin/gvim
- See the above behavior when all windows are closed

I'm still working on reproducing the version with Windows open. Will update when I have more.

**Comment by isaki** [comment]
I've got it for windows open as well.

![image](https://user-images.githubusercontent.com/10616227/70935492-4192eb80-200e-11ea-82ea-1f6faf59641e.png)

**Steps Taken:**

- touch 2 files (foo1.txt, foo2.txt)
- Open both files with /Applications/MacVim.app/Contents/bin/gvim
- Repeatedly open and close foo2.txt
- See the above behavior

**Comment by eirnym** [comment]
@isaki It's true, this menu items are connected to the same source.

These additional menus are added and removed by macOS event handlers. The additional check should be done here. AFAIK, any other menus are not duplicated accidentally

**Comment by isaki** [comment]
@eirnym Please let me know if there is something you want me to test or if you need more information. I'm more than happy to help in any way I can!

**Comment by ychin** [comment]
This seems to be the same bug as the other listed ones (#566), except in Catalina it is worse. I actually haven't upgraded to Catalina yet, but I probably should, but it's really the same issue (I think).
