### ISSUE TITLE
Update to Vim 8.2

### ISSUE THREAD

**Issue by jlconlin** [macvim-dev/macvim#994]
I would like MacVim updated to Vim 8.2. I could do this on my own and submit a PR, but I don't know what it entails; i.e., I don't know where MacVim ends and where Vim begins.

**Comment by markwu** [comment]
Hi, 

Does there any schedules to patch macvim to vim 8.2? 

Mark

**Comment by ychin** [comment]
This is done. Apologies for the delays.

**Comment by ychin** [comment]
Commit is https://github.com/macvim-dev/macvim/commit/a1cb3f34bbd913a2e145f858041d9e7689d80a44.

Also made a page to describe the upstream merging process: https://github.com/macvim-dev/macvim/wiki/Merging-from-upstream-Vim

**Comment by eirnym** [comment]
@ychin Would you make a release with new ViM features or it's too early to speak about it?

**Comment by eirnym** [comment]
@ychin I'd happy to see a release just with ViM update, to be honest. I know there's a lot of issues in MacVim part, but ViM part is more important for me now

**Comment by ychin** [comment]
Yeah I'll work on it. Need to clean up the CI and make sure it builds on Travis first.

**Comment by jlconlin** [comment]
Thanks @ychin for merging in Vim 8.2. I cloned and downloaded this morning and was able to compile. However, when I tried to run vim I get this error:

```
Error detected while processing /Users/jlconlin/.vim/vimrc:
line    8:
E484: Can't open file /Users/jlconlin/local/bin/vim/runtime/syntax/syntax.vim
Press ENTER or type command to continue
```
When I try to open MacVim, I get an error that the application is damaged or incomplete.
![Screen Shot 2020-01-23 at 9 10 29 AM](https://user-images.githubusercontent.com/1275437/73001806-42166300-3dc0-11ea-97a1-465f8d69f039.png)

I'm compiling on MacOS Catalina 10.15.2. Here are the commands I used to build/install:
```
 1112  ./configure --prefix=$HOME/local --with-features=huge --enable-python3interp=dynamic --enable-macvim-check --enable-gui=macvim
 1113  make -j20
make install
```

**Comment by eirnym** [comment]
@jlconlin you don't need to set prefix as it's local to resulted `MacVim.app` and other flags except python3 are implied for MacVim repo
