### ISSUE TITLE
MacVim does not display Tibetan Text properly

### ISSUE THREAD

**Issue by madmansnest** [macvim-dev/macvim#995]
Even though in latest OS X versions there has been no problems with Tibetan text display, and even though MacVim uses the standard NSTextView, it still fails to display Tibetan text properly, just like Terminal.app used to many OS X versions ago.

To Reproduce: Open MacVim and input some relatively complex Tibetan text like ཧཱུྃ། or བསྒྲིགས་པ་. In order to see what it should look like, open TextEdit and input the same text.

This is current MacVim, unsatisfactory:
![image](https://user-images.githubusercontent.com/5081164/71302502-76c08480-23e6-11ea-8f37-7c86c832da07.png)

This is Terminal.app in OS X Mojave, bad kerning, but satisfactory:
![image](https://user-images.githubusercontent.com/5081164/71302532-e20a5680-23e6-11ea-8faa-f86319bb4a41.png)

This is what is should like, ideal:
![image](https://user-images.githubusercontent.com/5081164/71302544-023a1580-23e7-11ea-83d0-d42dd2246062.png)

**Comment by eirnym** [comment]
@madmansnest Thank you for an issue,

It's true, that some font parameters are not loaded from font correctly, but not many people was interested in it earlier. You can try to modify `linespace` manually to make things a bit smoother for now.

**Comment by eirnym** [comment]
Could you share with us a bit more information, such as some texts and the font you use (it's home page is preferable and tell if it's free-to-use (it'll be much harder to test the same over a paid one)

**Comment by madmansnest** [comment]
Text Example:
ཧཱུྃ༔ ཨོ་རྒྱན་ཡུལ་གྱི་ནུབ་བྱང་མཚམས༔
པདྨ་གེ་སར་སྡོང་པོ་ལ༔
ཡ་མཚན་མཆོག་གི་དངོས་གྲུབ་བརྙེས༔
པདྨ་འབྱུང་གནས་ཞེས་སུ་གྲགས༔
འཁོར་དུ་མཁའ་འགྲོ་མང་པོས་བསྐོར༔
ཁྱེད་ཀྱི་རྗེས་སུ་བདག་བསྒྲུབ་ཀྱི༔
བྱིན་གྱིས་བརླབ་ཕྱིར་གཤེགས་སུ་གསོལ༔
གུ་རུ་པདྨ་སིདྡྷི་ཧཱུྃ༔
Font download page:
https://collab.its.virginia.edu/wiki/tibetan-script/Jomolhari.html

**Comment by ychin** [comment]
MacVim actually doesn’t use NSTextView by default and uses CoreText renderer to get more flexibility in how it renders text. I will need to take a look but this is likely similar to other font issues we have had.
